import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = []

records.append({"id":"id_55751","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["조직개편","인사발령","징계아님","업무상필요성인정"],"legal_focus":["업무상필요성","인사재량권"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보정당","조직개편전보"],"exclude_for_queries":[],"summary_short":"조직개편에따른인사발령=징계아님+업무상필요성인정=TV정당","holding_summary":"조직개편에따른인사발령=취업규칙징계종류해당않음+과거비위제재목적아님=징계아님+업무상필요성인정=TV정당","retrieval_note":"조직개편인사발령이징계인지여부+TV정당성","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55761","issue_type_primary":"discrimination","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["육아휴직","승진차별주장","육아휴직자승진사례다수"],"legal_focus":["남녀고용평등법","승진차별"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["육아휴직승진차별","차별불인정"],"exclude_for_queries":[],"summary_short":"육아휴직후승진차별주장=육아휴직사용자승진사례다수=차별불인정","holding_summary":"육아휴직사용자74명중승진22명+과장→차장승진여성6명=육아휴직이승진불이익원인불인정=차별불인정","retrieval_note":"육아휴직승진차별주장남녀고용평등법","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55765","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["신규직원채용","이사장갈등","생활상불이익미입증","협의미준수"],"legal_focus":["업무상필요성","협의절차","당연무효아님"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보정당","협의미준수당연무효아님"],"exclude_for_queries":[],"summary_short":"신규채용+이사장갈등=TV업무상필요성인정+협의미준수=당연무효아님=TV정당","holding_summary":"신규직원채용에따른배치전환필요성+전임이사장업무갈등직장질서유지=업무상필요성인정+생활상불이익미입증+협의미준수=당연무효아님=TV정당","retrieval_note":"협의절차미준수당연무효아님TV정당누적패턴","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55769","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["화해조서복직조건","원직아닌신규업무배치","원부자재입출고"],"legal_focus":["화해조서이행","원직복직","업무상필요성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["화해조서후원직아닌배치","TV정당성"],"exclude_for_queries":[],"summary_short":"화해조서복직조건=원직아닌신규업무배치=TV정당성판단","holding_summary":"화해조서복직조건=복직명령이행했으나원직아닌원부자재입출고배치=TV정당성판단","retrieval_note":"화해조서이행후원직아닌업무배치전보정당성","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5577","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["복직후배치","업무환경변화","유사업무"],"legal_focus":["업무상필요성","인사재량권"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["복직후전보","전보정당"],"exclude_for_queries":[],"summary_short":"복직후적정인원배치=업무상필요성인정+유사업무=TV정당","holding_summary":"복직후업무환경변화=적정인원배치업무상필요성인정+시장관리→고객관리유사업무=TV정당","retrieval_note":"복직후전보TV정당성","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55771","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직책수당삭감","구제이익존재","업무상필요성"],"legal_focus":["구제이익","업무상필요성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직책수당삭감구제이익","전보구제이익"],"exclude_for_queries":[],"summary_short":"직책수당삭감=구제이익존재+업무상필요성인정=TV정당성","holding_summary":"인사발령으로직책수당삭감=금전적구제이익존재+인사규정근거=업무상필요성인정=TV정당성판단","retrieval_note":"전보후직책수당삭감구제이익존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55781","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["조직개편","질병으로인한업무공백","운전원수거원전보","김포시평가"],"legal_focus":["업무상필요성"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["조직개편전보","질병업무공백전보"],"exclude_for_queries":[],"summary_short":"조직개편+질병업무공백=운전원수거원전보=업무상필요성인정=TV정당","holding_summary":"김포시평가최하위쇄신목적조직개편+질병으로운전원공백=수거원전보=업무상필요성인정=TV정당","retrieval_note":"질병업무공백조직개편에따른전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55785","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["중대재해처벌법","직제개편","안전보건독립전문운영","생활상불이익없음"],"legal_focus":["업무상필요성","중대재해처벌법시행령"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["중대재해처벌법전보","법령에따른전보"],"exclude_for_queries":[],"summary_short":"중대재해처벌법시행령직제개편=안전보건독립전문운영=TV업무상필요성인정=TV정당","holding_summary":"중대재해처벌법시행령4조2호에따른안전보건독립전문적수행위한직제개편=전보=업무상필요성인정+생활상불이익없음=TV정당","retrieval_note":"중대재해처벌법에따른직제개편전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55789","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["복직명령수락","임금상당액수령","구제이익소멸"],"legal_focus":["구제이익소멸"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["복직명령구제이익소멸","임금수령구제이익소멸"],"exclude_for_queries":[],"summary_short":"복직명령수락+임금상당액수령=구제이익소멸","holding_summary":"사용자복직명령+근로자수락+해고기간임금상당액전액수령=구제신청목적달성=구제이익소멸","retrieval_note":"복직명령수락+임금수령구제이익소멸","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55797","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],"fact_markers":["수습기간","협박성문자","전보명령거부","관리자적대적태도"],"legal_focus":["수습기간본채용거부","정당한이유"],"industry_context":"unknown","exclusion_flags":["unrelated_to_probation"],"include_for_queries":["수습기간본채용거부정당","수습기간협박성문자"],"exclude_for_queries":[],"summary_short":"수습기간협박성문자+전보거부+적대적태도=본채용거부정당","holding_summary":"수습기간근로계약+관리자협박성문자+경찰대동면담+전보명령합리적사유없이거부=본채용거부=사회통념상부적절아님=정당","retrieval_note":"수습기간협박성문자전보명령거부본채용거부정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55801","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["보직해임","대기발령10일","징계사유인정","양정적정"],"legal_focus":["징계양정","사회통념상타당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계정당","보직해임대기발령양정적정"],"exclude_for_queries":[],"summary_short":"징계사유취업규칙해당+보직해임대기발령10일=양정적정=징계정당","holding_summary":"근로자행위=취업규칙41조8호9호+인사위규정12조3호징계사유인정+보직해임대기발령근무일10일=사회통념상타당성인정=징계정당","retrieval_note":"보직해임대기발령10일양정적정징계정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5581","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["공무직전보인사시행계획","동일직종간인사이동","취업장소계약당사자소속부서"],"legal_focus":["업무상필요성","인사재량권"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["공무직전보정당","인사시행계획준수전보"],"exclude_for_queries":[],"summary_short":"공무직전보인사시행계획+동일직종=TV정당","holding_summary":"공무직원전보인사시행계획수립+행정보조원동일직종간인사이동=전보원칙부합+근로계약취업장소=소속부서=전보대상=TV정당","retrieval_note":"공무직전보인사시행계획준수TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55813","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["금융실명법위반","채무과다","사고예방순환배치","인사규정65조"],"legal_focus":["업무상필요성","사고예방순환배치"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["사고예방순환배치전보","금융실명법위반전보"],"exclude_for_queries":[],"summary_short":"금융실명법위반+채무과다=인사규정사고예방순환배치=TV업무상필요성인정=TV정당","holding_summary":"금융실명법위반+확정가압류채무과다=인사규정65조사고예방순환배치대상=업무상필요성인정=TV정당","retrieval_note":"금융기관금융실명법위반사고예방순환배치TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55839","issue_type_primary":"union_activity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["공정대표의무","노동조합협의절차","근무형태변경","교섭대표노조"],"legal_focus":["공정대표의무","교섭대표노동조합"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["공정대표의무위반아님","근무형태변경노조협의"],"exclude_for_queries":[],"summary_short":"근무형태변경시노동조합협의절차거침=교섭대표노조차별없음=공정대표의무위반아님","holding_summary":"조합원4명근무형태변경시노조협의절차이행=교섭대표노조와차별없음=공정대표의무위반않음+노동조합간부인사발령협의=공정대표의무위반않음","retrieval_note":"공정대표의무위반여부노조협의절차","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55845","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["불법파견","직접고용간주","원직배치의무","이종업무배치"],"legal_focus":["파견법","전직재량권제한","원직배치원칙"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["불법파견직접고용전보부당","원직배치의무전보재량제한"],"exclude_for_queries":[],"summary_short":"불법파견직접고용간주=원직배치원칙=원직아닌이종업무배치=TV부당","holding_summary":"불법파견인정=직접고용간주=파견법취지상원직배치원칙=전직재량권상당히제한=원직아닌동종유사또는이종업무배치=TV부당","retrieval_note":"불법파견직접고용간주원직배치의무전직재량제한TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5585","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상신청","원직복직불가","구제이익존재"],"legal_focus":["구제이익","금전보상제도"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["금전보상구제이익","복직불가구제이익"],"exclude_for_queries":[],"summary_short":"금전보상명령신청=원직복직불가이더라도=구제이익존재","holding_summary":"해고기간임금상당액받을필요있으면본안판단필요=원직복직불가원하지않더라도금전보상구제이익포함=구제이익존재","retrieval_note":"금전보상구제이익원직복직불가무관","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55857","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["품질보증팀전보","업무상필요성없음","팀원없는팀","생산관리팀장직위박탈"],"legal_focus":["업무상필요성","생활상불이익"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["전보부당","팀원없는팀배치TV부당"],"exclude_for_queries":[],"summary_short":"객관적사유없는품질보증팀전보+팀원없는팀배치=업무상필요성없음=TV부당","holding_summary":"품질보증팀기존직원있음에도객관적사유없이근로자품질보증팀전보+수치상변화없음+팀원없는팀=업무상필요성불충분=TV부당","retrieval_note":"팀원없는팀단독배치업무상필요성없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55889","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["보직해임","업무권한대폭축소","직책급여삭감","구제신청대상"],"legal_focus":["근기법23조1항","징벌해당","구제신청적격"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["보직해임징벌해당구제대상","업무권한축소급여삭감구제신청"],"exclude_for_queries":[],"summary_short":"보직해임=제재목적+업무권한대폭축소+급여삭감=근기법23조1항징벌해당=구제신청대상","holding_summary":"보직해임=제재목적+업무범위권한대폭축소+직책관련급여삭감=신분상생활상불이익=근기법23조1항그밖의징벌해당=구제신청대상","retrieval_note":"보직해임근기법23조1항징벌해당구제신청적격","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55893","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근무장소특정아님","비연고지전보관행","규정위반업무촉구"],"legal_focus":["업무상필요성","근무장소특정여부"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보정당","근무장소비특정전보"],"exclude_for_queries":[],"summary_short":"근로계약근무장소특정아님+비연고지전보관행+규정위반업무촉구=TV정당","holding_summary":"근로계약근무장소특정아님+장기간비연고지전보관행=근무장소특정아님+규정위반업무촉구위한전보=업무상필요성인정=TV정당","retrieval_note":"근무장소비특정비연고지전보관행TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55919","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["전보명령","직장내괴롭힘신고","5개월무단결근","징계해고"],"legal_focus":["징계사유","무단결근","전보명령거부"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["무단결근5개월징계해고","전보후무단결근"],"exclude_for_queries":[],"summary_short":"전보명령후직장내괴롭힘신고이유5개월무단결근=징계사유인정=징계해고","holding_summary":"전보명령후직장내괴롭힘신고이유연차소진+5개월간사용자승인없이무단결근+출근거부=징계사유인정=징계해고","retrieval_note":"전보명령후직장내괴롭힘신고이유무단결근징계해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5593","issue_type_primary":"redundancy","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["긴박한경영상필요성없음","적자없음","흑자전환","기술연구소"],"legal_focus":["정리해고요건","긴박한경영상필요성"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["정리해고부당","긴박한경영상필요성없음"],"exclude_for_queries":[],"summary_short":"적자없음+흑자전환=긴박한경영상필요성불충분=정리해고부당","holding_summary":"한번도적자없음+2020년이후영업이익당기순이익흑자전환=긴박한경영상필요성객관적입증없음=정리해고부당","retrieval_note":"적자없음흑자전환정리해고긴박한경영상필요성불충분","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55951","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["연령건강이유전보","부현장대리인예비인력","객관적입증없음"],"legal_focus":["업무상필요성","객관적근거"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["연령건강이유전보부당","TV부당"],"exclude_for_queries":[],"summary_short":"연령건강이유부현장대리인→예비인력전보=객관적입증없음=TV부당","holding_summary":"연령에따른건강상이유교대근무지장=객관적입증없음+산업안전통계만으로산재직결불인정+불성실근무태도근거없음=업무상필요성불충분=TV부당","retrieval_note":"연령건강이유전보업무상필요성객관적입증없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55953","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["대기발령","평균임금70%","승진소요기간불산입","구제이익존재"],"legal_focus":["구제이익","대기발령정당성","인사규정"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["대기발령구제이익","평균임금70%구제이익"],"exclude_for_queries":[],"summary_short":"대기발령평균임금70%+승진소요기간불산입=구제이익존재+대기발령정당성판단","holding_summary":"대기발령제척기간미도과+평균임금70%지급+승진소요기간불산입=구제이익존재+인사규정3개월한도직권대기발령규정=정당성판단","retrieval_note":"대기발령구제이익평균임금70%승진소요기간","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55967","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["복직명령5회이상","임금상당액지급","고용보험피보험자격상실취득","구제이익소멸"],"legal_focus":["구제이익소멸","복직명령진정성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["복직명령5회이상구제이익소멸","구제이익소멸"],"exclude_for_queries":[],"summary_short":"내용증명+문자5회이상복직명령+임금상당액지급=구제이익소멸","holding_summary":"내용증명문자5회이상복직명령+임금상당액지급의사표시및지급+고용보험상실취득=구제이익소멸","retrieval_note":"복직명령5회이상임금지급구제이익소멸","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_55997","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["nonrenewal"],"fact_markers":["기간제직원운영지침","70세까지재계약조항","갱신기대권","단체협약"],"legal_focus":["갱신기대권","단체협약유효성"],"industry_context":"unknown","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["갱신기대권단체협약","70세재계약조항갱신기대권"],"exclude_for_queries":[],"summary_short":"기간제운영지침70세재계약조항+단체협약=갱신기대권판단","holding_summary":"기간제직원운영지침70세재계약조항명시+단체협약유효성=갱신기대에대한신뢰부여여부=갱신기대권판단","retrieval_note":"기간제운영지침70세재계약조항갱신기대권","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56011","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["입주자대표회의교체요구","상사동료갈등","취업규칙전보가능"],"legal_focus":["업무상필요성"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["입주자대표회의교체요구전보","경비원전보정당"],"exclude_for_queries":[],"summary_short":"입주자대표회의교체요구+상사동료입주민갈등=업무상필요성인정=TV정당","holding_summary":"입주자대표회의명시적교체요구+상사동료입주민다양한갈등=업무상필요성인정+취업규칙전보가능조항=TV정당","retrieval_note":"아파트경비원입주자대표회의교체요구전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56013","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상회피목적복직명령","서면통지없음","권고사직"],"legal_focus":["구제이익","해고존재","서면통지"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["금전보상회피복직명령구제이익","해고존재서면통지"],"exclude_for_queries":[],"summary_short":"금전보상회피목적추정복직명령=구제이익존재+서면통지없음=해고존재","holding_summary":"사용자금전보상신청인지후형식적복직명령=금전보상회피목적추정=구제이익존재+권고사직처리과정서면통지없음=해고존재","retrieval_note":"금전보상회피목적복직명령구제이익서면통지해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56015","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["부분인용","근로자1전보부당","근로자2전보정당","업무상필요성소명부족"],"legal_focus":["업무상필요성","부분인용"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보부분인용","조직개편업무상필요성소명부족"],"exclude_for_queries":[],"summary_short":"근로자1=조직개편업무상필요성소명부족=TV부당/근로자2=업무상필요성인정=TV정당(부분인용)","holding_summary":"근로자1=조직개편일반추상적필요성+전보대상객관적사유소명부족=TV부당/근로자2=업무상필요성인정+생활상불이익없음+절차하자없음=TV정당=부분인용","retrieval_note":"동일사건근로자전보부분인용TV부당TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5605","issue_type_primary":"redundancy","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["매출감소이나영업이익증가","적자없음","긴박한경영상필요성없음","무급휴직미검토"],"legal_focus":["정리해고요건","긴박한경영상필요성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["정리해고부당","긴박한경영상필요성없음"],"exclude_for_queries":[],"summary_short":"매출감소있으나영업이익증가+적자없음=긴박한경영상필요성불충분=정리해고부당","holding_summary":"2020년매출감소이나상반기전년대비증가+영업이익매년증가+적자없음+해고전무급휴직미검토=긴박한경영상필요성객관적입증불충분=정리해고부당","retrieval_note":"영업이익증가적자없음정리해고긴박한경영상필요성불충분","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56069","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],"fact_markers":["징계사유일부인정","직장질서문란","업무지시불이행","양정과도"],"legal_focus":["징계양정","최후수단성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["경미한비위징계해고양정과도","징계부당"],"exclude_for_queries":[],"summary_short":"징계사유일부인정+경미한비위에징계해고=최후수단불충족=양정과도=부당","holding_summary":"징계사유중직장질서문란업무지시불이행인정=나머지징계사유불인정+경미한비위에최후수단징계해고=양정과도=부당","retrieval_note":"징계사유일부인정경미한비위징계해고양정과도","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56071","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["버스운전원","노선2년단위재배치","기준인원변경","교대노조협의"],"legal_focus":["업무상필요성","협의절차"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["버스운전원노선재배치TV정당","순환전보TV정당"],"exclude_for_queries":[],"summary_short":"버스운전원노선2년단위재배치+기준인원변경=업무상필요성인정=TV정당","holding_summary":"버스운전원노선2년단위재배치+2022년기준인원변경=업무상필요성인정+생활상불이익크지않음+교대노조사전협의=TV정당","retrieval_note":"버스운전원노선재배치TV정당교대노조협의","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56075","issue_type_primary":"disciplinary_severity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["상시5인이상","학원","사용자자인"],"legal_focus":["상시근로자수","근기법적용","해고정당성"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["사용자자인5인이상근기법적용","해고정당성"],"exclude_for_queries":[],"summary_short":"사용자자인으로상시5인이상=근기법적용+해고정당성판단","holding_summary":"근로자주장5인이상+사용자심문회의자인상시5인이상+동업자공동운영인정=근기법적용+해고정당성판단","retrieval_note":"사용자자인상시5인이상근기법적용해고정당성","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56119","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["인사평가","성과급평가","특정근로자제재아님","광범위재량권"],"legal_focus":["근기법23조1항","징벌해당여부","구제신청적격"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사평가징벌아님각하","구제신청대상아님"],"exclude_for_queries":[],"summary_short":"전직원대상인사평가=특정제재아님=징벌해당않음=구제신청각하","holding_summary":"전직원대상인사평가성과급평가=특정근로자제재아님+평가재량권광범=명백한재량일탈남용없으면징벌해당않음=구제신청각하","retrieval_note":"인사평가성과급징벌해당않음구제신청각하","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56145","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["3급직제규정","등용팀장제","역장직무대리","객관적선발"],"legal_focus":["업무상필요성","인사재량권"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["직제규정전보","등용팀장제인사정당"],"exclude_for_queries":[],"summary_short":"3급직제규정상직무범위광범+등용팀장제객관적선발=TV정당","holding_summary":"3급직제규정부서장부터부서원보직가능+역장직무대리부센터장근무이력=업무역무매니저로한정아님+등용팀장제객관적투명선발=TV정당","retrieval_note":"직제규정상직무범위광범인사재량TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56157","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성인정","생활상불이익없음","절차하자없음","불이익취급부당노동행위불인정"],"legal_focus":["업무상필요성","부당노동행위","불이익취급"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV정당부당노동행위불인정","불이익취급부당노동행위불인정"],"exclude_for_queries":[],"summary_short":"업무상필요성인정+생활상불이익없음+절차하자없음=TV정당+불이익취급부당노동행위불인정","holding_summary":"인사발령업무상필요성인정+생활상불이익없음+절차상하자없음=TV정당+인사발령정당하면불이익취급부당노동행위불인정","retrieval_note":"TV정당판정후부당노동행위불이익취급불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56159","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"pre_hire","disposition_type":["dismissal"],"fact_markers":["채용내정성립","경영상위기지속","채용내정취소"],"legal_focus":["채용내정취소정당성","경영상이유"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["채용내정취소","채용내정취소정당성"],"exclude_for_queries":[],"summary_short":"채용내정성립+경영상위기2020이후지속=채용내정취소정당성판단","holding_summary":"입사안내메일+프로필사진제출=채용내정성립+경영상위기2020이후지속적발생=채용내정취소정당성불충분판단","retrieval_note":"채용내정성립후취소정당성경영상이유","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56165","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["업무지시거부해고","입증불충분","실질적손해없음"],"legal_focus":["징계사유","해고정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무지시거부해고부당","입증불충분해고부당"],"exclude_for_queries":[],"summary_short":"업무지시거부해고=사용자입증불충분+실질적손해없음=해고부당","holding_summary":"사용자업무지시이행거부주장=구체적입증불충분+설령거부하더라도실질적손해없음=해고부당","retrieval_note":"업무지시거부해고사용자입증불충분부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56203","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["점장해고통보","사용자대리인여부","출근명령진정성없음"],"legal_focus":["해고존재","구제이익","사용자대리인"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["점장해고통보해고존재","출근명령진정성없음구제이익"],"exclude_for_queries":[],"summary_short":"점장해고통보=해고존재확인+출근명령진정성없음=구제이익존재","holding_summary":"점장직원채용해고권한인정+근로자에게해고통보확인=해고존재여부판단+출근명령고용관계원상회복진정성불인정=구제이익존재","retrieval_note":"점장해고통보해고존재여부사용자대리인","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56205","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["contract_termination"],"fact_markers":["10년이상동일업무","동일근무장소","농협은행경비원","기간의정함없는근로자"],"legal_focus":["기간의정함없는근로자","갱신기대권"],"industry_context":"finance","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["10년이상동일업무기간의정함없는근로자","장기계속근무기간제"],"exclude_for_queries":[],"summary_short":"10년이상동일업무동일장소기간제=기간의정함없는근로자여부판단","holding_summary":"2012년입사이후10년이상매년기간제계약+동일업무동일장소한차례변경없음=기간의정함없는근로자해당여부판단","retrieval_note":"장기간동일업무기간제기간의정함없는근로자판단","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56231","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["부적절행위일부","직장위계질서문란아님","실질적피해없음","아파트경비원"],"legal_focus":["업무상필요성","권리남용"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["TV부당","업무상필요성불충분경비원"],"exclude_for_queries":[],"summary_short":"부적절행위일부이나직장위계질서문란아님+실질적피해없음=업무상필요성불충분=TV부당","holding_summary":"일부부적절행위있으나직장위계질서문란정도아님+타직원업무저해없음+입주민실질적피해없음=업무상필요성불충분=TV부당","retrieval_note":"아파트경비원부적절행위일부있어도업무상필요성없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56235","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["근로기준법상근로자인정","상시5인이상","연인원144명가동일수27일","식당"],"legal_focus":["상시근로자수","근기법적용","근로자성"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["연인원가동일수5인이상","식당근로자성인정"],"exclude_for_queries":[],"summary_short":"식당근로자=근기법상근로자인정+연인원144/가동27=5.3명=상시5인이상=근기법적용","holding_summary":"식당동일직원과동일근로제공=근기법상근로자인정+연인원144명가동일수27일=5.3명=상시5인이상=근기법적용","retrieval_note":"식당연인원가동일수계산상시5인이상근기법적용","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56287","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성없음","경영상위기인과관계불명","고과비일관","서울지부장이중관여"],"legal_focus":["업무상필요성","인사재량권남용"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV부당","업무상필요성인과관계불명"],"exclude_for_queries":[],"summary_short":"경영상위기와전보인과관계불명+고과비일관=업무상필요성불충분=TV부당","holding_summary":"경영상위기와인사발령인과관계불명+우수자표창시최하등수비일관+고과평가자와교체요청자모두서울지부장=업무상필요성불충분=TV부당","retrieval_note":"경영상위기인과관계불명고과비일관TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56325","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["인사발령예정만존재","실제발령없음","구제신청각하"],"legal_focus":["처분존재여부","구제신청적격"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사발령없음각하","처분존재여부각하"],"exclude_for_queries":[],"summary_short":"인사발령예정에불과=실제인사발령없음=구제신청각하","holding_summary":"사용자인사발령예정했을뿐실제인사발령없음=처분존재하지않음=구제신청각하","retrieval_note":"인사발령예정만존재실제발령없음구제신청각하","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56329","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사용자적격","법인","치과","급여지급주체","업무지시주체"],"legal_focus":["사용자적격","피신청인적격"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["사용자적격법인","급여지급주체사용자"],"exclude_for_queries":[],"summary_short":"법인이급여지급+업무지시=사용자적격인정+해고여부판단","holding_summary":"법인이치과급여지급+비용지출+대표이사채용관여업무지시=치과운영주체법인=사용자적격인정+해고여부판단","retrieval_note":"법인치과사용자적격급여지급업무지시기준","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5633","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["타회사취업","복직의사없음","금전보상신청","채용불가통보"],"legal_focus":["구제이익","해고존재","금전보상"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["타회사취업무관구제이익","금전보상구제이익"],"exclude_for_queries":[],"summary_short":"타회사취업+복직의사없음무관=금전보상구제이익존재+채용불가통보=해고존재","holding_summary":"타회사취업중복직의사없더라도금전보상명령신청=구제이익존재+채용불가통보=해고존재","retrieval_note":"타회사취업복직의사없어도금전보상구제이익","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56353","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["NCS채용","순환근무가능명시","공단형편전보가능","주차관리팀"],"legal_focus":["업무상필요성","근로계약"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["채용공고순환근무전보정당","근로계약전보가능TV정당"],"exclude_for_queries":[],"summary_short":"채용공고순환근무가능명시+근로계약전보가능조항=주차관리팀→전보=TV정당","holding_summary":"NCS채용공고순환근무가능자+임용후전보배치가능명시+근로계약전보가능조항=주차관리팀에서전보=TV정당","retrieval_note":"채용공고순환근무명시근로계약전보가능TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56369","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["대표도서관장","도서관건립자문","상주전담불필요","주무관청요청없음"],"legal_focus":["업무상필요성"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["TV부당","도서관자문전보업무상필요성없음"],"exclude_for_queries":[],"summary_short":"도서관건립자문병행지장없음+주무관청상주요청확인안됨=업무상필요성불충분=TV부당","holding_summary":"대표도서관장자문병행업무지장없음+주무관청상주전담요청사실확인안됨+매뉴얼상자문가이드라인존재=업무상필요성불충분=TV부당","retrieval_note":"도서관장자문전담배치업무상필요성없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56371","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["직권휴직","인사규정19조1항","불가피한특별한사정","휴일근무수당부정수급"],"legal_focus":["직권휴직요건","인사규정"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["직권휴직요건","무급직권휴직정당성"],"exclude_for_queries":[],"summary_short":"직권휴직근거규정존재+불가피한특별한사정요건=휴일수당부정수급형사고소=직권휴직정당성판단","holding_summary":"인사규정19조1항직권휴직규정존재+불가피한특별한사정요건충족여부=주된원인휴일근무수당부정수급형사고소=직권휴직정당성판단","retrieval_note":"직권휴직불가피한특별한사정요건충족여부","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56419","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"pre_hire","disposition_type":["dismissal"],"fact_markers":["채용내정성립","출근일자지정","현장교육","통근버스패스"],"legal_focus":["채용내정","해고존재"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["채용내정취소해고","채용내정성립기준"],"exclude_for_queries":[],"summary_short":"출근일자지정+현장교육실시+통근버스패스=채용내정성립+채용내정취소=해고존재","holding_summary":"별도면접없이출근일자지정+당일교육실시+통근버스패스지급=채용내정성립+채용내정취소=해고존재판단","retrieval_note":"채용내정성립기준출근일자교육통근버스","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_56429","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["부실대출감봉","30년전문성","총괄→여신팀","업무상필요성없음"],"legal_focus":["업무상필요성"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["TV부당","감봉후전보업무상필요성없음"],"exclude_for_queries":[],"summary_short":"부실대출감봉이후총괄→여신팀전보=업무상필요성없음+30년전문성차이=TV부당","holding_summary":"부실대출감봉=경미한지적사항외배치전환업무상필요성불충분+30년총괄전문성과대출영업상담차이=TV부당","retrieval_note":"감봉후전보업무상필요성없음30년전문성TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

output_path = r'C:\dev\labor-decisions-search\retagging\output\reviewed\transfer_batch_073_reviewed.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')
print(f'총 {len(records)}건 작성 완료')
