import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = []

# id_4733: 업무상필요성없음=TV부당
records.append({"id": "id_4733", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무상필요성없음", "객관적자료없음", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["업무상필요성없음TV부당", "사용자주장객관적자료없음전보부당"], "exclude_for_queries": [], "summary_short": "업무상필요성=객관적자료없음=TV부당", "holding_summary": "사용자가 주장하는 업무상 필요성을 확인할 객관적인 자료가 제출되지 않아 전보 부당", "retrieval_note": "업무상 필요성 입증책임 사용자에 있음. 객관적 자료 미제출로 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47335: 서울→제주=생활상불이익현저=TV부당
records.append({"id": "id_47335", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["서울제주전보", "생활상불이익현저", "구제이익인정", "TV부당"], "legal_focus": ["전보정당성3요건", "생활상불이익", "구제신청이익"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["서울제주전보생활상불이익현저TV부당", "원거리지역전보생활상불이익전보부당"], "exclude_for_queries": [], "summary_short": "서울→제주전보=업무상필요성인정이나생활상불이익현저=TV부당", "holding_summary": "OTA업무 이관에 따른 업무상 필요성은 인정되나 서울에서 제주로의 근무지 변경은 생활상 불이익이 현저하여 TV 부당", "retrieval_note": "서울→제주 원거리 전보에서 생활상 불이익 현저성 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47357: 복직+징계취소=구제이익소멸
records.append({"id": "id_47357", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal", "transfer"], "fact_markers": ["복직명령", "징계취소", "구제이익소멸"], "legal_focus": ["구제이익", "복직", "징계취소"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["복직명령징계취소구제이익소멸", "구제신청중복직명령징계취소구제이익없음"], "exclude_for_queries": [], "summary_short": "구제신청중복직명령+징계취소=구제이익소멸", "holding_summary": "구제신청 진행 중 사용자가 복직명령을 내리고 징계를 취소하여 구제신청의 목적이 달성되어 구제이익 소멸", "retrieval_note": "복직 + 징계취소 이중 조치로 구제이익 소멸 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47395: 근로자갈등분리=업무상필요성인정=TV정당
records.append({"id": "id_47395", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["갈등분리전보", "업무상필요성인정", "인근지역동일직급", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "갈등분리"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["근로자갈등분리전보업무상필요성인정TV정당", "직원간갈등분리배치전보정당"], "exclude_for_queries": [], "summary_short": "근로자간갈등반복=물리적분리필요=업무상필요성인정=TV정당", "holding_summary": "근로자와 상사 간 빈번한 다툼이 있어 물리적 거리 두기의 필요성이 인정되고 인근 지역에 동일 직급·업무 자리가 있어 TV 정당", "retrieval_note": "갈등 분리 목적 전보에서 업무상 필요성 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47401: 서면통지미이행=부당해고+금전보상
records.append({"id": "id_47401", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["서면통지미이행", "부당해고", "금전보상명령"], "legal_focus": ["서면해고통지", "금전보상명령"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["서면통지미이행부당해고", "해고서면통지위반부당금전보상"], "exclude_for_queries": [], "summary_short": "해고서면통지미이행=절차하자=부당해고+금전보상명령", "holding_summary": "해고사유와 시기를 서면으로 통지하지 않아 절차상 하자가 있는 부당해고에 해당하며, 신뢰관계 파탄으로 금전보상명령 적용", "retrieval_note": "서면 통지 위반 단독으로 부당해고 인정. 금전보상명령 병과", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4743: 업무상필요성없음(갈등주장입증안됨)=TV부당
records.append({"id": "id_4743", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무상필요성없음", "갈등주장미입증", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성입증"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["갈등주장미입증전보업무상필요성없음부당", "사용자주장입증실패전보부당"], "exclude_for_queries": [], "summary_short": "사용자갈등주장=보직미입증=업무상필요성없음=TV부당", "holding_summary": "사용자가 주장하는 팀장과 활동가들 간 갈등에 대한 구체적 입증이 부족하여 업무상 필요성이 인정되지 않아 TV 부당", "retrieval_note": "갈등 원인 입증 실패로 업무상 필요성 불인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47443: OJT교육훈련=전직아님=구제신청대상아님
records.append({"id": "id_47443", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["OJT교육훈련", "복귀예정", "전직아님", "구제신청대상아님"], "legal_focus": ["전직해당여부", "구제신청대상", "교육훈련"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["OJT교육훈련전직아님구제신청대상아님각하", "교육훈련목적배치전직해당안됨"], "exclude_for_queries": [], "summary_short": "OJT교육훈련목적인사명령=전직아님=구제신청대상아님", "holding_summary": "OJT 교육훈련 차원에서 이루어진 인사명령은 근로기준법 제23조의 전직에 해당하지 않아 구제신청 대상이 되지 않음", "retrieval_note": "교육훈련 목적 배치명령의 전직 해당 여부. 복귀 예정이므로 전직 아님", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47449: 근로계약변경가능+거래처요구=TV정당
records.append({"id": "id_47449", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["근로계약변경가능명시", "거래처요구", "TV정당"], "legal_focus": ["전보정당성3요건", "근로계약해석", "거래처관계유지"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["근로계약변경가능명시거래처요구전보정당", "거래처요구교체전보업무상필요성인정"], "exclude_for_queries": [], "summary_short": "근로계약변경가능명시+거래처교체요구=업무상필요성인정=TV정당", "holding_summary": "근로계약서에 근무장소 및 업무 변경 가능 조항이 있고 중요 거래처의 교체 요구가 있어 업무상 필요성이 인정되어 TV 정당", "retrieval_note": "근로계약 변경 가능 조항과 거래처 유지 필요성의 결합으로 전보 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47483: 위탁기간만료폐직=직권면직사유=정당
records.append({"id": "id_47483", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["위탁기간만료", "폐직", "직권면직사유", "정당"], "legal_focus": ["직권면직사유", "인사규정", "위탁사업종료"], "industry_context": "public", "exclusion_flags": [], "include_for_queries": ["위탁기간만료폐직직권면직정당", "정부위탁사업종료직권면직사유해당정당"], "exclude_for_queries": [], "summary_short": "위탁기간만료예산지원중단=폐직=인사규정직권면직사유=정당", "holding_summary": "서울시의 위탁기간 만료 및 예산지원 중단으로 사업이 종료되어 직제가 폐지된 경우 인사규정상 직권면직 사유에 해당하여 면직 정당", "retrieval_note": "정부 위탁사업 종료에 따른 직제 폐지→직권면직 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47487: TV+부당노동행위불인정
records.append({"id": "id_47487", "issue_type_primary": "union_activity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["전보", "부당노동행위불인정", "불이익취급불인정", "지배개입불인정"], "legal_focus": ["부당노동행위", "불이익취급", "지배개입"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["전보부당노동행위의사추정불가불인정", "노조활동이유전보부당노동행위불인정"], "exclude_for_queries": [], "summary_short": "전보=부당노동행위의사추정불가=불이익취급·지배개입불인정", "holding_summary": "근로자들에 대한 전보에서 사용자의 부당노동행위 의사를 추정할 수 없어 불이익취급 및 지배·개입의 부당노동행위 불인정", "retrieval_note": "전보의 부당노동행위 해당 여부: 사용자 의사 추정 불가 → 불인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47491: 전산실4년4개월경력→방재실=TV부당
records.append({"id": "id_47491", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["전산경력자", "4년4개월동일부서", "방재실전보", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "채용직무특정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["전산경력자방재실전보업무상필요성없음TV부당", "장기동일부서근무자타직무전보부당"], "exclude_for_queries": [], "summary_short": "전산경력자=4년4개월전산실근무→방재실전보=TV부당", "holding_summary": "전산 업무 경력자로 입사하여 4년 4개월간 전산실에서만 근무하다가 처음으로 방재실로 전보된 것은 업무상 필요성이 없어 TV 부당", "retrieval_note": "채용 직무·장기 동일 부서 근무 후 타 직무 전보 부당 패턴", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47505: 폐업이유근로계약종료통보=해고존재
records.append({"id": "id_47505", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["폐업이유근로계약종료통보", "해고존재", "자진퇴사주장불인정"], "legal_focus": ["해고존재여부", "폐업과해고", "근로관계자동소멸"], "industry_context": "education", "exclusion_flags": [], "include_for_queries": ["폐업이유근로계약종료통보해고존재", "폐업통보해고인정근로관계자동소멸아님"], "exclude_for_queries": [], "summary_short": "사용자폐업이유근로계약종료통보=해고존재+자진퇴사입증자료없음", "holding_summary": "사용자가 폐업을 이유로 근로계약이 종료된다고 통보한 것은 해고에 해당하며, 근로자들이 자진퇴사했다는 사용자 주장을 인정할 객관적 자료가 없음", "retrieval_note": "폐업 통보=해고 의사표시=해고 존재 패턴", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47539: 사직종용으로인한사직서=비진의=해고존재
records.append({"id": "id_47539", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["사직종용", "사직의사없음", "비진의사직서", "해고존재"], "legal_focus": ["해고존재여부", "사직서비진의", "강요사직"], "industry_context": "unknown", "exclusion_flags": ["resignation_dispute"], "include_for_queries": ["사직종용비진의사직서해고존재", "강요사직서제출해고인정"], "exclude_for_queries": [], "summary_short": "지속적사직종용→비진의사직서=사용자알았거나알수있었음=해고존재", "holding_summary": "사용자의 지속적인 사직 종용으로 인하여 사직 의사 없는 근로자가 어쩔 수 없이 제출한 사직서는 비진의 의사표시로 무효이므로 해고에 해당", "retrieval_note": "비진의 사직서=해고 의사표시 인정. 사용자 인식 가능성 기준", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47541: 조직개편전보TV정당
records.append({"id": "id_47541", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["조직개편", "업무효율성", "인사재량", "TV정당"], "legal_focus": ["전보정당성3요건", "인사재량", "조직개편필요성"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["조직개편전보인사재량TV정당", "조직개편효율성전보정당"], "exclude_for_queries": [], "summary_short": "조직개편효율성추구=인사재량범위내=TV정당", "holding_summary": "조직 개편에 따른 효율성 평가 및 적합한 체제 선택을 위한 전보는 사용자의 인사재량 범위 내에 있어 TV 정당", "retrieval_note": "조직개편에 따른 인사재량 전보 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47585: 복직명령진정성없음+해고존재
records.append({"id": "id_47585", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["복직명령진정성없음", "구제이익존재", "해고존재", "상무해고권한"], "legal_focus": ["구제이익", "복직명령진정성", "해고존재여부", "해고권한"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["복직명령진정성없음구제이익소멸않음해고존재", "대응방편복직명령구제이익유지"], "exclude_for_queries": [], "summary_short": "복직명령=대응방편=진정성없음=구제이익유지+해고존재", "holding_summary": "사용자의 복직명령은 부당해고를 다투자 이에 대응하는 방편에 불과하여 진정한 복직의사 없음=구제이익 유지. 해고도 존재하여 부당", "retrieval_note": "복직명령 진정성 없음=구제이익 소멸 않음 패턴(batch_063 id_46797, id_4693과 동일 법리)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47597: 정년후촉탁직재고용기대권+거절합리적이유있음=정당
records.append({"id": "id_47597", "issue_type_primary": "contract_expiry", "issue_type_secondary": [], "employment_stage": "renewal_stage", "disposition_type": ["nonrenewal"], "fact_markers": ["정년후촉탁직", "재고용기대권인정", "거절합리적이유있음", "정당"], "legal_focus": ["갱신기대권", "재고용기대권", "갱신거절합리적이유"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["정년후촉탁재고용기대권인정이나거절합리적이유정당", "정년후재고용기대권합리적거절정당"], "exclude_for_queries": [], "summary_short": "정년후촉탁직재고용기대권인정+근로시간준수불이행=거절합리적이유=정당", "holding_summary": "정년 후 촉탁직 재고용 기대권이 인정되나 근로시간 준수 불이행 등의 사유로 재고용 거절에 합리적 이유가 있어 정당", "retrieval_note": "정년 후 촉탁 재고용 기대권 + 합리적 거절사유로 정당 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4763: 업무상필요성인정이나다만조건=TV부당
records.append({"id": "id_4763", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무상필요성인정", "팀장폭언", "근로자요청전보", "협의절차미준수", "TV부당"], "legal_focus": ["전보정당성3요건", "협의절차", "전보경위"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["팀장폭언근로자요청전보이나협의미준수TV부당", "업무상필요성인정이나협의없음TV부당"], "exclude_for_queries": [], "summary_short": "업무상필요성인정이나팀장폭언상황협의절차미준수=TV부당", "holding_summary": "전보의 업무상 필요성은 인정되나, 팀장의 폭언으로 근로자가 전보를 요청한 상황임에도 사용자가 적절한 협의를 거치지 않아 TV 부당", "retrieval_note": "근로자 전보 요청 상황에서도 협의절차 미준수로 TV 부당 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47633: 보직해임=자료유출가능성=업무상필요성없음=TV부당
records.append({"id": "id_47633", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["보직해임", "자료유출가능성", "업무상필요성없음", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "보직해임"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["보직해임자료유출가능성업무상필요성없음TV부당", "자료유출우려보직해임업무상필요성기준불충족"], "exclude_for_queries": [], "summary_short": "보직해임=자료유출가능성=기업합리적운영기여아님=업무상필요성없음=TV부당", "holding_summary": "자료 유출 가능성에서 비롯된 보직해임은 노동력의 적정 배치로 업무능률 증진에 기여하는지 여부에 관한 객관적 기준에 부합하지 않아 업무상 필요성 없음=TV 부당", "retrieval_note": "업무상 필요성의 객관적 기준(업무능률 증진·기업 합리적 운영 기여) 적용. 자료유출 우려는 기준 불충족", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47637: 보육교사→업무보조원=근로계약서사인=TV정당+정직정당
records.append({"id": "id_47637", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["suspension", "transfer"], "fact_markers": ["보육교사업무보조원전직", "근로계약서자발서명", "정직정당", "TV정당"], "legal_focus": ["전보정당성", "근로계약서서명", "징계양정"], "industry_context": "education", "exclusion_flags": [], "include_for_queries": ["근로계약서자발서명업무보조원전직TV정당", "정직정당전직정당"], "exclude_for_queries": [], "summary_short": "보육교사→업무보조원근로계약서자발서명=TV정당+정직=징계사유인정=정당", "holding_summary": "보육교사에서 업무보조원으로 변경된 근로계약서에 자발적으로 서명하여 전직 정당하고, 정직 처분도 징계사유가 인정되어 정당", "retrieval_note": "근로계약서 자발적 서명으로 직종 변경 수용 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47647: 반장직인사발령업무상필요성없음=TV부당
records.append({"id": "id_47647", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["반장승진인사발령", "업무상필요성없음", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성"], "industry_context": "manufacturing", "exclusion_flags": [], "include_for_queries": ["반장직인사발령업무상필요성없음TV부당", "승진인사발령업무상필요성없음부당"], "exclude_for_queries": [], "summary_short": "반장직인사발령=업무상필요성사유불충분=TV부당", "holding_summary": "반장 직책 변경 인사발령의 이유로 주장된 사유(펄프 입고량 증가)가 직책 부여와 인과관계가 없고 인사발령 후에도 문제가 지속되어 업무상 필요성 불충분=TV 부당", "retrieval_note": "인사발령 이유와 실제 업무상 필요성의 인과관계 불충분으로 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47651: 해고존재+서면통지미이행=부당
records.append({"id": "id_47651", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["해고존재", "서면통지미이행", "부당해고", "금전보상"], "legal_focus": ["해고존재여부", "서면해고통지", "금전보상명령"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["해고존재서면통지미이행부당해고금전보상", "일방적근로관계종료통보해고존재서면미통지부당"], "exclude_for_queries": [], "summary_short": "다른보직거절=일방적근로관계종료통보=해고존재+서면통지미이행=부당+금전보상", "holding_summary": "사용자가 다른 보직을 제안하고 거절하자 일방적으로 근로관계 종료를 통보한 것은 해고에 해당하며, 서면 통지를 하지 않아 부당해고. 금전보상명령 적용", "retrieval_note": "일방적 종료 통보=해고 인정. 서면 통지 위반으로 절차 하자", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47661: 성비위전력+공공기관특성=인사발령TV정당
records.append({"id": "id_47661", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["성비위전력", "공공기관청렴성", "인사규정근거", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "공공기관인사", "성비위후속조치"], "industry_context": "public", "exclusion_flags": [], "include_for_queries": ["성비위전력공공기관전보TV정당", "성비위징계후속인사발령TV정당"], "exclude_for_queries": [], "summary_short": "성비위전력+공공기관청렴성추구+인사규정근거=인사발령TV정당", "holding_summary": "성비위 징계 전력이 있고 공공기관으로서 청렴성 추구의 필요성이 있으며 인사규정에 명문 근거가 있어 인사발령(직위 미부여)은 TV 정당", "retrieval_note": "성비위 전력자에 대한 공공기관 인사발령 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4769: 감봉=겸직금지위반인정이나양정과다+절차하자=부당+전보=징계후속=이중징계=부당
records.append({"id": "id_4769", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["pay_cut", "transfer"], "fact_markers": ["겸직금지위반", "양정과다", "절차하자", "이중징계", "감봉부당", "전보부당"], "legal_focus": ["징계양정", "징계절차", "이중징계", "전보징계성"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["감봉양정과다절차하자부당전보이중징계부당", "징계후속전보이중징계해당부당"], "exclude_for_queries": [], "summary_short": "겸직금지위반인정이나감봉양정과다+절차하자=부당+전보=징계후속이중징계=부당", "holding_summary": "겸직금지 위반 징계사유는 인정되나 감봉 양정이 과다하고 징계절차 하자가 있어 부당하며, 징계 후속 전보는 이중징계에 해당하여 부당", "retrieval_note": "징계 후속 전보의 이중징계 해당 여부. 이중징계=TV 부당 패턴", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4771: 법인사용자적격인정+경영난조직쇄신인사발령=TV정당
records.append({"id": "id_4771", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["법인사용자적격인정", "경영일체판단", "경영난조직쇄신", "TV정당"], "legal_focus": ["사용자적격", "전보정당성3요건", "경영난인사발령"], "industry_context": "retail", "exclusion_flags": [], "include_for_queries": ["법인사용자적격인정경영난조직쇄신TV정당", "경영상일체사용자적격인사발령정당"], "exclude_for_queries": [], "summary_short": "법인매장=경영상일체=법인사용자적격인정+경영난조직쇄신인사발령=TV정당", "holding_summary": "법인과 매장이 실질적으로 경영상 일체를 이루어 법인의 사용자 적격이 인정되며, 경영난 타개를 위한 조직쇄신 차원의 인사발령은 업무상 필요성이 인정되어 TV 정당", "retrieval_note": "법인-매장 경영상 일체 판단 후 사용자 적격 인정. TV 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47725: 직장내괴롭힘분리=TV정당+정직정당(일부사유)
records.append({"id": "id_47725", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["disciplinary_severity"], "employment_stage": "regular", "disposition_type": ["transfer", "suspension"], "fact_markers": ["직장내괴롭힘분리조치", "업무상필요성인정", "TV정당", "정직일부사유인정"], "legal_focus": ["전보정당성3요건", "직장내괴롭힘분리", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직장내괴롭힘분리조치TV정당정직정당", "괴롭힘가해자분리전보TV정당"], "exclude_for_queries": [], "summary_short": "직장내괴롭힘분리=업무상필요성인정=TV정당+정직=일부사유인정=정당", "holding_summary": "직장 내 괴롭힘 분리 조치를 위한 전직은 업무상 필요성이 인정되고 생활상 불이익도 과하지 않아 정당. 정직은 일부 징계사유가 인정되어 정당", "retrieval_note": "직장내괴롭힘 가해자 분리 전보 정당 패턴(batch_063 id_47063과 유사)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47745: 조직개편전보TV정당(재심번복)
records.append({"id": "id_47745", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["조직개편", "인력조정", "업무상필요성인정", "TV정당", "재심번복"], "legal_focus": ["전보정당성3요건", "업무상필요성", "조직개편"], "industry_context": "finance", "exclusion_flags": [], "include_for_queries": ["조직개편인력재배치전보TV정당재심번복", "초심부당재심번복TV정당"], "exclude_for_queries": [], "summary_short": "조직개편인력조정=업무상필요성인정=TV정당=재심번복(초심부당)", "holding_summary": "조직 개편으로 소속 부서 인원 조정 필요성 발생+인원 충원 요청 등 업무상 필요성이 인정되어 TV 정당. 초심의 TV 부당 판정을 재심에서 번복", "retrieval_note": "재심에서 초심 TV 부당을 번복하여 TV 정당으로 변경한 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47805: 보직해임=전보성격+징계사유불인정+양정과도=부당
records.append({"id": "id_47805", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["transfer", "demotion"], "fact_markers": ["보직해임=전보해당", "징계사유불인정", "양정과도", "부당"], "legal_focus": ["보직해임성격", "징계사유", "징계양정", "전보성격판단"], "industry_context": "healthcare", "exclusion_flags": [], "include_for_queries": ["보직해임전보성격징계사유불인정양정과도부당", "보직해임불인정사유전보부당"], "exclude_for_queries": [], "summary_short": "보직해임=전보성격+징계사유대부분불인정+최근상벌고려미흡=부당", "holding_summary": "보직해임은 실질적으로 전보의 인사명령에 해당하며, 징계사유 대부분이 불인정되고 양정이 과도하여 부당", "retrieval_note": "보직해임의 전보 성격 판단. 징계사유 불인정으로 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47811: 이사장규정해석+업무상필요성인정=TV정당
records.append({"id": "id_47811", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["이사회의결해석", "센터장겸직", "업무상필요성인정", "TV정당"], "legal_focus": ["전보정당성3요건", "이사회규정해석", "업무상필요성"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["이사회규정해석전보업무상필요성인정TV정당"], "exclude_for_queries": [], "summary_short": "이사회의결규정취지=의사에반한낮은직급복귀금지+센터장공백=업무상필요성인정=TV정당", "holding_summary": "이사회 의결 내용의 취지를 해석하면 직원의 의사에 반한 낮은 직급 복귀를 금지한 것이며, 센터장 공백에 따른 전보는 업무상 필요성이 인정되어 TV 정당", "retrieval_note": "이사회 의결 해석 + 인력 공백 충원 목적 전보 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47823: 이해관계충돌전보=업무상필요성없음=TV부당
records.append({"id": "id_47823", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["이해관계충돌전보", "업무상필요성없음", "대안방법존재", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "이해관계충돌"], "industry_context": "healthcare", "exclusion_flags": [], "include_for_queries": ["이해관계충돌이유전보업무상필요성없음부당", "인사팀장인권침해진정조사이해관계전보부당"], "exclude_for_queries": [], "summary_short": "인사팀장인권침해진정이해관계충돌=다른조사방법가능=업무상필요성없음=TV부당", "holding_summary": "인권침해 진정사건의 이해관계 충돌을 이유로 한 전보이나, 다른 방법(감사팀 또는 다른 인사팀 직원)으로 조사가 가능하여 업무상 필요성 없음=TV 부당", "retrieval_note": "이해관계 충돌 해소 전보이나 대안 존재로 업무상 필요성 불인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47851: 파산법인금전보상구제이익+해고존재+부당
records.append({"id": "id_47851", "issue_type_primary": "procedure", "issue_type_secondary": ["no_dismissal"], "employment_stage": "fixed_term", "disposition_type": ["dismissal"], "fact_markers": ["파산법인", "청산절차중법인격유지", "금전보상구제이익존재", "해고존재", "서면통지위반"], "legal_focus": ["구제이익", "파산법인", "금전보상", "해고존재여부"], "industry_context": "construction", "exclusion_flags": [], "include_for_queries": ["파산법인금전보상구제이익존재", "파산선고후청산중법인격존속구제이익인정"], "exclude_for_queries": [], "summary_short": "파산법인청산중=법인격소멸않음=금전보상구제이익존재+해고존재+부당", "holding_summary": "파산 선고 후 청산 절차 진행 중인 법인은 법인격이 소멸하지 않아 구제이익이 있으며, 해고가 존재하고 서면 통지도 위반하여 부당", "retrieval_note": "파산법인 청산 중 구제이익 존재 인정. 금전보상 신청 가능", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47853: 지회사용자=징계(일부사유)정당
records.append({"id": "id_47853", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["지회=사용자인정", "징계사유일부불인정", "여타사유인정", "징계정당"], "legal_focus": ["사용자적격", "징계사유", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["지회사용자적격인정징계정당", "인사발령거부징계사유아님이나여타사유인정징계정당"], "exclude_for_queries": [], "summary_short": "지회=사용자적격인정+인사발령거부=징계사유아니나겸직금지등인정=징계정당", "holding_summary": "지회가 근로자의 인사권을 가지므로 사용자 적격이 인정되며, 인사발령 거부는 징계사유로 인정 어려우나 암웨이 회원가입, 직장내 괴롭힘, 겸직금지 위반 등이 인정되어 징계 정당", "retrieval_note": "지회 사용자 적격 판단 + 복수 징계사유 중 일부 인정으로 징계 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47861: 자립지원팀충원=업무상필요성인정+생활상불이익통상범위=TV정당
records.append({"id": "id_47861", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["자립지원팀충원요청", "유사업무", "업무상필요성인정", "생활상불이익통상범위", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "생활상불이익"], "industry_context": "public", "exclusion_flags": [], "include_for_queries": ["자립지원팀인원충원전보TV정당", "공공기관부서충원전보업무상필요성인정TV정당"], "exclude_for_queries": [], "summary_short": "자립지원팀충원요청=업무상필요성인정+생활상불이익통상범위=TV정당", "holding_summary": "자립지원팀 강화를 위한 인원 충원의 업무상 필요성이 인정되고 전보로 인한 생활상 불이익이 통상 감수 범위 내에 있어 TV 정당", "retrieval_note": "부서 인원 충원 목적 전보의 TV 3요건 충족 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47873: 사직서제출+구제이익없음
records.append({"id": "id_47873", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["사직서제출", "구제이익없음", "각하"], "legal_focus": ["구제이익", "사직효력"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant", "resignation_dispute"], "include_for_queries": ["사직서제출근로관계종료구제이익없음각하"], "exclude_for_queries": [], "summary_short": "사직서제출로근로관계종료=구제이익없음", "holding_summary": "근로자의 사직서 제출로 근로관계가 종료되어 구제이익이 없어 각하", "retrieval_note": "사직으로 근로관계 종료 → 구제이익 없음 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47875: 금전보상신청후복직명령=구제이익소멸않음+해고없음
records.append({"id": "id_47875", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["no_formal_disposition"], "fact_markers": ["금전보상신청후복직명령", "구제이익소멸않음", "해고없음"], "legal_focus": ["구제이익", "금전보상신청", "해고존재여부"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["금전보상신청후복직명령구제이익소멸않음", "해고없음기각"], "exclude_for_queries": [], "summary_short": "금전보상신청후복직명령=구제이익유지+해고존재여부불인정=기각", "holding_summary": "금전보상 명령을 신청한 이후 복직명령이 있었더라도 구제이익이 소멸하지 않으나, 해고 자체가 존재하지 않아 기각", "retrieval_note": "금전보상신청 후 복직명령의 구제이익 소멸 않음 확인. 그러나 해고 없음으로 기각", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47881: 인사규정5년이상전보+생활상불이익없음=TV정당
records.append({"id": "id_47881", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["인사규정5년이상전보", "순환전보", "생활상불이익없음", "TV정당"], "legal_focus": ["전보정당성3요건", "인사규정", "순환전보주기"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["인사규정5년이상전보기준TV정당", "순환전보인사규정기준충족TV정당"], "exclude_for_queries": [], "summary_short": "인사규정5년이상근무전보기준+임금감소없음=TV정당", "holding_summary": "인사규정에 5년 이상 근무한 경우 전보조치 가능하다는 규정이 있어 업무상 필요성이 인정되고, 임금 감소 없이 월세보조 등이 제공되어 생활상 불이익도 없어 TV 정당", "retrieval_note": "인사규정상 전보 기간 기준 충족 + 생활상 불이익 없음으로 TV 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47895: 징계위원관련자포함=절차하자=부당
records.append({"id": "id_47895", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["징계위원관련자참여", "취업규칙위반", "절차하자", "부당"], "legal_focus": ["징계절차", "징계위원자격", "제척사유"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["징계위원관련자참여취업규칙위반절차하자부당", "징계사유관련자징계위원배제위반부당"], "exclude_for_queries": [], "summary_short": "징계사유관련이사가징계위원참여=취업규칙위반=절차하자=부당", "holding_summary": "취업규칙에서 징계사유와 관련된 위원은 징계의결에 관여하지 못한다고 규정하고 있음에도 관련 이사가 위원으로 의결권을 행사하여 징계절차 하자=부당해고", "retrieval_note": "징계위원 제척 규정 위반이 절차 하자로 부당해고 인정된 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4791: 긴박한경영상필요성불충분=정리해고부당(부분인용)
records.append({"id": "id_4791", "issue_type_primary": "redundancy", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["긴박한경영상필요성불충분", "재무지표검토", "정리해고부당", "부분인용"], "legal_focus": ["정리해고4요건", "긴박한경영상필요성", "회사전체경영사정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["긴박한경영상필요성불충분정리해고부당", "재무지표기준긴박성불인정정리해고부당"], "exclude_for_queries": [], "summary_short": "정리해고=회사전체재무지표기준긴박한경영상필요성불충분=부당", "holding_summary": "정리해고의 긴박한 경영상 필요성은 회사 전체 경영 사정을 종합 검토해야 하며, 자산총액·부채총액·당기순이익 등 재무지표를 보면 정리해고를 실시할 만큼의 긴박성이 없어 정리해고 부당", "retrieval_note": "일부 사업부문 기준이 아닌 회사 전체 재무지표로 긴박성 판단. 불충분으로 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47923: 다른직장알아보라=해고의사표시=해고존재+부당
records.append({"id": "id_47923", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["구두해고의사표시", "다른직장알아보라", "해고존재", "부당해고"], "legal_focus": ["해고존재여부", "해고의사표시", "구두해고"], "industry_context": "it", "exclusion_flags": [], "include_for_queries": ["다른직장알아보라해고의사표시해고존재", "구두로다른직장알아보라=해고인정부당"], "exclude_for_queries": [], "summary_short": "다른직장알아봐야할것같다구두발언=해고의사표시=해고존재+부당", "holding_summary": "사용자가 '다른 직장을 알아봐야 할 것 같다'고 말한 것은 해고 의사표시에 해당하여 해고가 존재하며, 서면 통지 없이 이루어진 부당해고", "retrieval_note": "구두 발언으로 해고 의사표시 인정 사례. 명시적 '해고한다' 표현 없어도 해고 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47935: TV정당+부당노동행위불인정(재심유지)
records.append({"id": "id_47935", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["union_activity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무상필요성인정", "생활상불이익통상범위", "협의절차준수", "TV정당", "부당노동행위불인정"], "legal_focus": ["전보정당성3요건", "부당노동행위", "인사권남용"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["TV3요건충족정당부당노동행위불인정재심유지", "전보정당부당노동행위거짓주장"], "exclude_for_queries": [], "summary_short": "TV3요건충족=TV정당+부당노동행위불인정=재심유지", "holding_summary": "전보의 업무상 필요성이 인정되고 생활상 불이익도 통상 감수 범위 내에 있으며 협의도 거쳐 TV 정당. 부당노동행위도 불인정. 재심에서도 유지", "retrieval_note": "TV 정당 + 부당노동행위 불인정이 재심에서도 유지된 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47953: 계약기간만료=원직복직구제이익없음
records.append({"id": "id_47953", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "fixed_term", "disposition_type": ["contract_termination"], "fact_markers": ["계약기간만료", "원직복직구제이익없음", "각하"], "legal_focus": ["구제이익", "계약기간만료", "원직복직불가"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["계약기간만료원직복직구제이익없음각하", "구제신청중계약기간만료구제이익소멸"], "exclude_for_queries": [], "summary_short": "구제신청당시계약기간만료=원직복직구제이익없음=각하", "holding_summary": "구제신청 당시 이미 근로계약 기간이 만료되어 원직복직에 대한 구제이익이 없어 각하", "retrieval_note": "구제신청 당시 기간 만료로 원직복직 불가능 = 구제이익 없음 각하", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_47957: 직제폐지인사발령=징계사유아님+겸직금지등인정=징계정당
records.append({"id": "id_47957", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["직제폐지인사발령", "징계사유아님", "겸직금지위반", "불법파견주장불인정", "징계정당"], "legal_focus": ["징계사유", "인사발령거부", "겸직금지"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직제폐지인사발령징계사유아님이나겸직금지등정당", "인사발령동의없다고징계사유아님여타사유정당"], "exclude_for_queries": [], "summary_short": "직제폐지인사발령=징계사유단정불가+겸직금지등여타사유인정=징계정당", "holding_summary": "직제 폐지에 따른 인사발령에 명시적 동의가 없었다는 사정만으로 근로계약 위반으로 단정할 수 없고, 겸직금지 규정 위반 등 여타 징계사유가 인정되어 징계 정당", "retrieval_note": "인사발령 거부/미동의를 단독 징계사유로 삼기 어려움. 여타 사유 인정으로 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48013: 전보=해고이외징벌=구제신청기간적용+도달주의기산
records.append({"id": "id_48013", "issue_type_primary": "procedure", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["전보=해고이외징벌", "구제신청기간적용", "도달주의기산점", "제척기간"], "legal_focus": ["제척기간", "도달주의", "전보구제신청기간", "해고이외징벌"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["전보해고이외징벌구제신청기간적용도달주의기산", "인사명령도달일부터구제신청기간기산"], "exclude_for_queries": [], "summary_short": "전보=해고이외징벌=구제신청기간적용+의사표시도달주의기산점", "holding_summary": "전보는 '해고 이외의 징벌'로서 구제신청 기간이 적용되며, 민법 제111조의 도달주의에 따라 인사발령이 근로자에게 도달한 날부터 기산", "retrieval_note": "전보의 해고이외징벌 해당 여부 + 도달주의 적용으로 기산점 확정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48015: 조합원배치전환차별불이익취급불인정
records.append({"id": "id_48015", "issue_type_primary": "union_activity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["조합원배치전환", "차별불이익취급불인정", "부당노동행위불인정"], "legal_focus": ["부당노동행위", "불이익취급", "조합원차별"], "industry_context": "transport", "exclusion_flags": [], "include_for_queries": ["조합원배치전환차별불이익취급불인정", "특정노조조합원배치전환부당노동행위불인정"], "exclude_for_queries": [], "summary_short": "신청노조조합원배치전환=타노조조합원과차별없음=불이익취급불인정", "holding_summary": "신청 노동조합 조합원의 지원근무 배치전환이 다른 노동조합 조합원과 달리 차별적 불이익 취급을 받았다고 보이지 않아 부당노동행위 불인정", "retrieval_note": "복수 노조 상황에서 조합원 배치전환 차별 주장 불인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48039: 보직변경과장→팀장=강등아님+업무상필요성인정=TV정당
records.append({"id": "id_48039", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["disciplinary_severity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["보직변경과장팀장", "강등아님", "직급임금유지", "업무상필요성인정", "TV정당"], "legal_focus": ["전보정당성3요건", "강등해당여부", "보직변경", "직급임금변화"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["보직변경강등아님직급임금유지TV정당", "과장팀장보직변경직급임금변화없음강등아님"], "exclude_for_queries": [], "summary_short": "과장→팀장보직변경=직급임금낮아지지않음=강등아님+조직간소화업무상필요성=TV정당", "holding_summary": "과장에서 팀장으로 보직이 변경되었으나 직급 및 임금이 낮아지지 않아 강등에 해당하지 않고, 조직 간소화를 위한 업무상 필요성이 인정되어 TV 정당", "retrieval_note": "보직 변경의 강등 해당 여부: 직급·임금 변화 없으면 강등 아님", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48055: 직무수행불이행=징계사유+양정적정
records.append({"id": "id_48055", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["직무수행불이행", "근로제공거부", "20일간", "서면경고2회", "징계양정적정"], "legal_focus": ["징계사유", "직무수행의무", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직무수행불이행20일근로제공거부징계정당", "서면경고후근로제공거부징계양정적정"], "exclude_for_queries": [], "summary_short": "직무수행불이행=근로제공거부20일+서면경고2회무시=징계사유인정+양정적정=정당", "holding_summary": "근로 제공을 정당한 이유 없이 20일간 거부하고 사용자의 2차례 서면 경고에도 불응한 것은 징계사유에 해당하며, 고직급자라는 점과 소규모 회사라는 점을 고려하면 양정도 적정", "retrieval_note": "장기 근로 제공 거부에 따른 징계 정당 사례. 소규모 회사 가중 요소", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48057: 직위해제+감봉+전보=모두정당
records.append({"id": "id_48057", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["suspension", "pay_cut", "transfer"], "fact_markers": ["직위해제정당", "감봉정당", "전보정당", "직장내괴롭힘내부비위인정"], "legal_focus": ["직위해제정당성", "징계양정", "전보정당성3요건"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직위해제감봉전보모두정당", "직장내괴롭힘내부비위복수처분모두정당"], "exclude_for_queries": [], "summary_short": "직위해제+감봉+전보=직장내괴롭힘내부비위인정=모두정당", "holding_summary": "직위해제는 업무상 필요성 및 절차 하자 없어 정당하고, 감봉은 직장내 괴롭힘 및 내부 비위가 인정되고 양정 적정하여 정당하며, 전보도 업무상 필요성 있어 정당", "retrieval_note": "직위해제, 징계, 전보 3종 동시 처분에서 모두 정당 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48119: 공금횡령불인정+인사발령거부+관리미흡=일부사유인정이나양정과도=부당
records.append({"id": "id_48119", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["공금횡령불인정", "인사발령거부인정", "관리미흡인정", "징계양정과도", "부당"], "legal_focus": ["징계사유", "주요사유불인정", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["주요징계사유불인정여타사유인정이나양정과도부당", "횡령불인정경미한사유로면직양정과도부당"], "exclude_for_queries": [], "summary_short": "주요사유공금횡령불인정+인사발령거부·관리미흡인정이나면직양정과도=부당", "holding_summary": "주된 징계사유인 공금횡령 가담은 불인정되고, 인사발령 거부와 가지급금 관리 미흡만 인정되는데 이에 대해 면직 양정은 과도하여 부당한 징계해고", "retrieval_note": "주요 사유 불인정 + 경미 사유만 인정 → 양정 과도 부당 패턴", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48129: 대법원판결후복직=원래업무불가능=다른업무부여=TV정당
records.append({"id": "id_48129", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["대법원판결원직복직", "원래업무불가", "하도급용역", "대체업무부여", "TV정당"], "legal_focus": ["전보정당성3요건", "원직복직후업무배치", "불가피한업무변경"], "industry_context": "service", "exclusion_flags": [], "include_for_queries": ["대법원판결복직후원업무불가대체업무부여TV정당", "원직복직원래업무불가피한변경정당"], "exclude_for_queries": [], "summary_short": "대법원판결원직복직=원래업무하도급용역전환불가능=대체업무부여=불가피=TV정당", "holding_summary": "대법원 판결로 원직 복직한 근로자의 원래 업무가 하도급 용역으로 전환되어 회사 직원이 수행하지 않아 원래 업무 부여 불가능=불가피한 업무 변경=TV 정당", "retrieval_note": "원직복직 후 원래 업무가 외주화된 경우 대체 업무 부여의 TV 정당 여부", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4813: 조직개편전보+근로계약유사업무명시=TV정당
records.append({"id": "id_4813", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["온라인사업부문강화조직개편", "근로계약유사업무명시", "일반직도발령", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "근로계약해석"], "industry_context": "retail", "exclusion_flags": [], "include_for_queries": ["조직개편본사지점전보근로계약유사업무명시TV정당", "인력재배치조직개편근로계약유사업무조항전보정당"], "exclude_for_queries": [], "summary_short": "온라인강화조직개편인력재배치+근로계약유사업무명시=TV정당", "holding_summary": "온라인 사업부문 강화를 위한 조직개편 계획이 합리적이고 근로계약서에 유사 업무를 명할 수 있다는 조항이 있어 본사→지점 전보의 업무상 필요성이 인정되어 TV 정당", "retrieval_note": "조직개편 + 근로계약 유사업무 조항으로 전보 정당 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48259: 징계사유불인정+단체협약징계절차위반=부당
records.append({"id": "id_48259", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["징계사유불인정", "단체협약징계절차위반", "입증책임사용자", "부당"], "legal_focus": ["징계사유입증책임", "징계절차", "단체협약준수"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["징계사유불인정입증책임사용자단체협약절차위반부당", "객관적입증자료없음징계사유불인정단체협약위반부당"], "exclude_for_queries": [], "summary_short": "징계사유=객관적입증자료없음=불인정+단체협약징계절차위반=부당", "holding_summary": "징계사실을 부인하는 근로자에 대한 입증책임은 사용자에 있는데 객관적 입증자료 미제출로 징계사유 불인정. 단체협약상 징계절차도 위반하여 부당해고", "retrieval_note": "징계 입증책임 사용자 원칙 + 단체협약 절차 위반 이중 하자 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

output_path = r'C:\dev\labor-decisions-search\retagging\output\reviewed\transfer_batch_064_reviewed.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')

print(f"총 {len(records)}건 작성 완료")
