import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')

records = [
    # ── transfer_validity TV정당 (15건) ──────────────────────────────────────────
    {
        "case_id": "id_413931",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["파견부서폐지", "야간→주간발령", "인력재배치필요"],
        "legal_focus": ["업무상필요성인정", "전직3요건"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["파견부서폐지로인한전배=업무상필요성인정=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "파견부서 폐지로 주간 현장 발령=업무상 필요성 인정=TV 정당",
        "holding_summary": "파견부서 폐지 및 공석 야간 현장 없음=주간 현장 발령의 업무상 필요성 인정=TV 정당",
        "retrieval_note": "파견부서 폐지에 따른 인력 재배치 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_413975",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["처무규정범위내전보", "2급→팀장급", "인사권재량"],
        "legal_focus": ["업무상필요성인정", "인사권재량범위"],
        "industry_context": "public",
        "exclusion_flags": [],
        "include_for_queries": ["처무규정상허용범위내전보=인사권재량=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "처무규정상 2급→팀장 전보 가능=인사권 재량=TV 정당",
        "holding_summary": "처무규정에 2급인 사무처장을 1~4급 팀장으로 전보 가능하도록 정함=인사권 재량 범위 내=TV 정당",
        "retrieval_note": "내부 규정에 근거한 직급 간 전보 재량 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_413979",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["반복업무지연누락", "조직개편B2C온라인영업강화", "거래내용변동"],
        "legal_focus": ["업무상필요성인정", "조직개편TV정당"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["반복업무지연+조직개편=업무상필요성인정=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "반복 업무 지연·누락+조직개편=업무상 필요성 인정=TV 정당",
        "holding_summary": "반복 업무 지연/누락 및 B2C 영업 조직개편 사정=업무상 필요성 인정=TV 정당",
        "retrieval_note": "업무 성과 문제+조직개편 병존 시 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414021",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["백화점입점계약종료", "매장철수", "근무지재배치", "근무시간변동없음"],
        "legal_focus": ["업무상필요성인정", "생활상불이익미미"],
        "industry_context": "retail",
        "exclusion_flags": [],
        "include_for_queries": ["백화점입점계약종료매장철수=근무지재배치업무상필요성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "백화점 입점 계약 종료→매장 철수→근무지 재배치=TV 정당",
        "holding_summary": "백화점 입점 계약 종료로 매장 철수 후 근무지 재배치 필요성 인정=근무시간 변동 없음=생활상 불이익 미미=TV 정당",
        "retrieval_note": "임차·입점 계약 종료에 따른 근무지 재배치 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414057",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": ["procedure"],
        "employment_stage": "fixed_term",
        "disposition_type": ["transfer"],
        "fact_markers": ["근로계약기간내구제신청", "구제이익인정", "TV정당성판단"],
        "legal_focus": ["구제이익존재", "전직정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["기간제계약기간내전보구제신청=구제이익존재+TV정당"],
        "exclude_for_queries": [],
        "summary_short": "계약기간 내 구제신청=구제이익 존재+TV 정당",
        "holding_summary": "근로계약기간 종료 전 구제신청=구제이익 인정+TV 업무상 필요성 판단 후 정당",
        "retrieval_note": "기간제 근로자의 TV 구제이익+TV 정당 병존",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414071",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["경영악화대응조직개편", "전시체험팀→마케팅팀통합", "인력재배치"],
        "legal_focus": ["업무상필요성인정", "조직개편TV정당"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["경영악화조직개편팀통합=인력재배치업무상필요성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "경영악화 대응 조직개편+팀 통합=업무상 필요성 인정=TV 정당",
        "holding_summary": "경영악화 대응 상시 조직개편+전시체험팀→마케팅팀 통합=인력 재배치 업무상 필요성 인정=TV 정당",
        "retrieval_note": "경영악화에 따른 팀 통합·인력 재배치 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_4143",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["부적절발언인정", "동료직원관계고려", "심문회의발언"],
        "legal_focus": ["업무상필요성인정", "인화목적TV정당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["부적절발언+동료관계고려=전보업무상필요성인정=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "부적절 발언+동료 관계 고려=전보 업무상 필요성 인정=TV 정당",
        "holding_summary": "근로자가 동료 직원에게 부적절한 발언 인정+지위 및 동료 관계 고려=전보 업무상 필요성 인정=TV 정당",
        "retrieval_note": "직장 내 갈등·부적절 발언 원인 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41473",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["보험업순환근무원칙", "부정방지목적", "보복인사주장불인정"],
        "legal_focus": ["업무상필요성인정", "순환근무원칙TV정당"],
        "industry_context": "finance",
        "exclusion_flags": [],
        "include_for_queries": ["보험업순환근무원칙=부정방지목적=보복인사주장불인정=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "보험업 순환근무 원칙=부정 방지 목적=보복인사 주장 불인정=TV 정당",
        "holding_summary": "보험업 특성상 부정 방지를 위한 순환근무 원칙+이에 따른 전보=업무상 필요성 인정=보복인사 주장 불인정=TV 정당",
        "retrieval_note": "보험업 순환근무제도 근거 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41485",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["교대승무원칙", "연차휴가연속사용후정상배차", "전환배치"],
        "legal_focus": ["업무상필요성인정", "전환배치정당성"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["교대승무원칙에따른전환배치=업무상필요성인정=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "교대 승무 원칙+연차 후 정상 배차=전환배치 정당",
        "holding_summary": "운전원 교대 승무 원칙+연차 후 정상배차된 점=전환배치 업무상 필요성 인정=TV 정당",
        "retrieval_note": "버스 운수업 교대 승무 원칙 근거 전환배치 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41567",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["보직해임+전보일련절차", "업무전환=징계아님", "인사권재량"],
        "legal_focus": ["전보=징계아님", "인사권재량"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["보직해임+전보=징계아닌인사발령업무전환=인사권재량=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "보직해임+전보=징계 아닌 업무전환=인사권 재량=TV 정당",
        "holding_summary": "보직해임+전보처분=인사발령에 따른 업무전환=징계 또는 징벌 아님=인사권 재량 범위 내=TV 정당",
        "retrieval_note": "보직해임+전보 병존 시 징계 아닌 인사발령 판단",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41579",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["근로계약서미작성", "근무장소미특정", "협의절차미준수=당연무효아님"],
        "legal_focus": ["협의절차미준수=당연무효아님", "전직정당성"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["근로계약서미작성=근무장소미특정+협의절차미준수=당연무효아님=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "근로계약서 미작성으로 근무장소 미특정+협의절차 미준수=당연 무효 아님=TV 정당",
        "holding_summary": "근로계약서 미작성=근무장소 미특정+협의절차 미준수해도 당연 무효 아님=TV 정당",
        "retrieval_note": "batch_055 id_413251과 동일 법리: 협의절차미준수=당연무효아님",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41585",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["인사재량권인정", "시말서제출전력", "전환배치"],
        "legal_focus": ["인사권재량", "업무상필요성인정"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["인사재량권+시말서제출전력=전환배치정당"],
        "exclude_for_queries": [],
        "summary_short": "인사 재량권+시말서 전력=전환배치 업무상 필요성 인정=TV 정당",
        "holding_summary": "전환배치=인사명령으로 상당한 인사 재량+근로자의 시말서 제출 전력=업무상 필요성 인정=TV 정당",
        "retrieval_note": "인사재량권+근로자 전력 고려 전환배치 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41655",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무상필요성인정", "임금감소원격지불가피", "생활상불이익<업무상필요성"],
        "legal_focus": ["생활상불이익vs업무상필요성비교형량"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["원격지임금감소불가피=생활상불이익<업무상필요성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "원격지+임금감소 불가피=생활상 불이익<업무상 필요성=TV 정당",
        "holding_summary": "업무상 필요성 인정+임금감소·원격지 전보 불가피한 사정=생활상 불이익이 업무상 필요성보다 크지 않음=TV 정당",
        "retrieval_note": "원격지·임금감소에도 업무상 필요성 우위로 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41847",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["물량감소인력재배치필요", "업무경력고려발령", "수처리사업부"],
        "legal_focus": ["업무상필요성인정", "인원선정합리성"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["물량감소인력재배치+업무경력고려=TV정당재심유지"],
        "exclude_for_queries": [],
        "summary_short": "물량 감소 인력 재배치+업무경력 고려 발령=TV 정당 유지",
        "holding_summary": "물량 감소로 인력 재배치 필요+근로자 업무경력 고려하여 수처리사업부 발령=비합리적이지 않음=TV 정당(재심 유지)",
        "retrieval_note": "물량 감소+업무경력 연계 인력 재배치 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41937",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["지각등다수문제", "민원최소화", "장거리노선배정"],
        "legal_focus": ["업무상필요성인정", "민원방지목적TV"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["지각등문제발생=민원최소화위한장거리배치=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "다수 문제 발생 근로자=민원 최소화 위한 노선 변경=TV 정당",
        "holding_summary": "지각 등 업무 문제 다수 발생=민원 최소화를 위한 기존 장거리 노선 배정=업무상 필요성 인정=TV 정당",
        "retrieval_note": "민원 방지 목적 운전원 노선 변경 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── transfer_validity TV부당 (10건) ─────────────────────────────────────────
    {
        "case_id": "id_413891",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무상필요성인정이나", "사무직→현장직직군변경", "공휴일포함근무변경", "대안배치미고려"],
        "legal_focus": ["생활상불이익막대", "업무상필요성인정이나생활상불이익>업무상필요성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["업무상필요성인정이나사무직→현장직+공휴일근무=생활상불이익막대=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "업무상 필요성 인정이나 사무직→현장직+공휴일 근무=생활상 불이익 막대=TV 부당",
        "holding_summary": "업무상 필요성 인정+사무직→현장직 직군 변경·공휴일 포함 근무 변경·본사 사무직 배치 미고려=생활상 불이익이 업무상 필요성에 비해 막대=TV 부당",
        "retrieval_note": "업무상 필요성 인정되어도 생활상 불이익 막대=TV 부당. batch_054 id_412049 유사 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_413907",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무상필요성소명불충분", "정신적손해인정"],
        "legal_focus": ["업무상필요성불충분=TV부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["전보업무상필요성소명불충분=정신적손해인정=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "전보 업무상 필요성 소명 불충분+정신적 손해 일부 인정=TV 부당",
        "holding_summary": "전보의 구체적 업무상 필요성 소명 어렵고, 보직 변경에 따른 정신적 손해 일부 인정=TV 부당",
        "retrieval_note": "업무상 필요성 소명 실패 및 정신적 손해 인정 TV 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_413909",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["본부장→비관리직매니저", "권고사직실패후전보", "보복적전보"],
        "legal_focus": ["업무상필요성불충분", "보복적TV부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["권고사직실패후전보=업무상필요성불충분=보복적TV부당"],
        "exclude_for_queries": [],
        "summary_short": "본부장→비관리직 매니저, 권고사직 실패 후 전보=업무상 필요성 불충분=TV 부당",
        "holding_summary": "전문성 인정 본부장으로 1년 근무 후 비관리직 매니저 전보+권고사직 합의 실패 직후=업무상 필요성 불충분=TV 부당",
        "retrieval_note": "권고사직 실패 직후 전보=보복적 TV 부당 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41499",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["별개법인인사발령=전적", "전적구제이익인정", "전적동의없음"],
        "legal_focus": ["전적구제이익", "전적=동의필요=TV부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["계열사별개법인인사발령=전적=동의없음=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "별개 법인 인사발령=전적=동의 없음=TV 부당",
        "holding_summary": "계열사 다른 법인으로 인사발령=전적에 해당하여 구제이익 존재+전적 동의 없음=TV 부당",
        "retrieval_note": "계열사 전적의 구제이익 인정 및 동의 없는 전적 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41667",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer", "demotion"],
        "fact_markers": ["팀장→팀원하향전보", "업무상필요성불확인", "객관적인사기준없음"],
        "legal_focus": ["업무상필요성불충분", "인원선정기준불합리"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["팀장→팀원하향전보=업무상필요성+인사기준미확인=TV부당재심유지"],
        "exclude_for_queries": [],
        "summary_short": "팀장→팀원 하향 전보=업무상 필요성+객관적 인사 기준 미확인=TV 부당(재심 유지)",
        "holding_summary": "팀장→팀원으로 하향 전보=업무상 필요성 및 객관적 인사 기준 미확인=TV 부당(재심에서도 초심 TV 부당 유지)",
        "retrieval_note": "하향 전보(팀장→팀원)에서 업무상 필요성+기준 필요",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41705",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": ["procedure"],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["퇴직처리와전보연관=구제이익존재", "업무상필요성문제"],
        "legal_focus": ["TV구제이익", "업무상필요성불충분"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["퇴직처리와전보정당성직접관련=구제이익존재+TV부당"],
        "exclude_for_queries": [],
        "summary_short": "퇴직처리와 전보 연관=구제이익 존재+TV 부당",
        "holding_summary": "사용자의 퇴직처리 사유와 전보 정당성 직접 관련=전보 구제이익 존재+업무상 필요성 불충분=TV 부당",
        "retrieval_note": "퇴직처리 연계 TV 구제이익 및 TV 부당 병존",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41823",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["희망전보신청", "희망과다른근무지발령", "사전협의없음"],
        "legal_focus": ["협의절차위반", "생활상불이익현저"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["희망전보신청에도희망과다른근무지발령+사전협의없음=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "희망전보 신청했으나 희망과 다른 근무지+협의 없음=TV 부당",
        "holding_summary": "근로자 희망에 의한 전보임에도 희망과 배치되는 생활상 불이익 큰 근무지 발령+사전 협의·동의 없음=TV 부당",
        "retrieval_note": "희망전보 신청과 다른 근무지 배정+협의 미준수=TV 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41855",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["소송제기=전보주된이유", "현장업무→본사사무직", "보복적전보"],
        "legal_focus": ["업무상필요성불충분", "보복적TV부당"],
        "industry_context": "construction",
        "exclusion_flags": [],
        "include_for_queries": ["소송제기가전보주된이유=보복적TV=업무상필요성없음=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "소송 제기가 전보의 주된 이유=보복적 TV=업무상 필요성 없음=TV 부당",
        "holding_summary": "근로자지위확인 소송 진행이 전보 발령의 가장 큰 이유+현장→본사 사무직=업무상 필요성 없음=보복적 TV 부당",
        "retrieval_note": "소송 제기 후 전보=보복적 TV 부당 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41945",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": ["procedure"],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["인사발령형식의실질징계", "징계절차미준수", "설령전보라도정당인사권범위초과"],
        "legal_focus": ["실질징계=징계절차필요", "전보부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["인사발령형식이나실질징계=징계절차미준수=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "인사발령 형식의 실질 징계=징계절차 미준수=TV 부당",
        "holding_summary": "인사발령 형식을 빌린 전보의 실질=징계+징계절차 미준수=부당. 설령 전보라 해도 정당한 인사권 범위 초과=TV 부당",
        "retrieval_note": "실질 징계인 전보=징계절차 필요. 전보·징계 이중 판단 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41949",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무순환제도폐지", "경영팀총무업무강제배치", "승무단복귀불가통보", "운수종사자변동통보"],
        "legal_focus": ["사실상강제전보=TV부당"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["업무순환제도폐지+승무단복귀불가통보=사실상강제전보=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "순환제도 폐지+경영팀 강제 배치+승무단 복귀 불가=사실상 강제 전보=TV 부당",
        "holding_summary": "업무순환제도 폐지+경영팀 총무업무 담당 지정+승무단 복귀 불가 통보+운수종사자 변동 통보=사실상 강제적 전보=TV 부당",
        "retrieval_note": "순환제도 폐지+원직 복귀 불가 선언=강제 전보 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── transfer_validity TV부분인용 (2건) ──────────────────────────────────────
    {
        "case_id": "id_413959",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["팀장지시무시=징계사유이지TV필요성아님", "번역TF기존없음", "업무상필요성불충분"],
        "legal_focus": ["업무상필요성불충분", "전직필요성근거불충분"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["팀장지시무시=징계사유이지TV필요성근거아님+TF신설미명확=TV부당=부분인용"],
        "exclude_for_queries": [],
        "summary_short": "팀장 지시 무시=징계사유이지 TV 필요성 아님+번역TF 기존 미존재=TV 부당=부분인용",
        "holding_summary": "팀장 지시 무시는 징계사유에 해당할지언정 TV 필요성 근거 불충분+번역TF 기존에 없었음=업무상 필요성 불충분=TV 부당=부분인용",
        "retrieval_note": "징계사유 ≠ TV 업무상 필요성 근거. TV 부당 부분인용 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41433",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": ["disciplinary_severity"],
        "employment_stage": "regular",
        "disposition_type": ["transfer", "reprimand"],
        "fact_markers": ["견책정당(사유인정+절차적법)", "전보=동료불화=업무상필요성인정", "생활상불이익현저+협의미준수=전보부당"],
        "legal_focus": ["견책정당+TV부당=부분인용", "전직3요건중생활상불이익+협의절차"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["견책정당+전보부당=부분인용", "동료불화TV=생활상불이익현저+협의미준수=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "견책 정당+전보 부당(생활상 불이익 현저+협의 미준수)=부분인용",
        "holding_summary": "견책: 사유 인정+절차 적법=정당. 전보: 업무상 필요성 인정이나 생활상 불이익 현저+협의절차 미준수=부당. 부분인용",
        "retrieval_note": "견책 정당 + TV 부당 동일 사건 부분인용 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── disciplinary_severity (11건) ─────────────────────────────────────────────
    {
        "case_id": "id_413933",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["reprimand"],
        "fact_markers": ["부임지연=징계사유불해당", "품위손상=징계사유불해당", "인사발령불복=일부해당", "폭언위협=해당"],
        "legal_focus": ["징계사유일부불인정", "징계양정"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["발령지부임지연+품위손상=징계사유불해당+폭언위협=해당=징계양정과도=부당"],
        "exclude_for_queries": [],
        "summary_short": "부임 지연·품위 손상=징계사유 불해당+폭언·위협=해당=징계양정 과도=징계 부당",
        "holding_summary": "발령지 부임 지연·회사 품위 손상=징계사유 불해당, 폭언·위협=일부 해당이나 전체 양정 과도=징계 부당",
        "retrieval_note": "징계사유 일부 불인정+양정 과도=징계 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_413999",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "probation",
        "disposition_type": ["probation_termination"],
        "fact_markers": ["근로계약서수습3개월명시", "수습기간중해고", "해고부당"],
        "legal_focus": ["수습기간중해고정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["근로계약서수습3개월명시+수습기간중해고=해고부당"],
        "exclude_for_queries": [],
        "summary_short": "수습기간 3개월 명시+수습 중 해고=해고 부당",
        "holding_summary": "근로계약서에 수습기간 3개월 및 불량 시 해고 가능 규정+수습기간 중 해고=정당한 이유 불충분=해고 부당",
        "retrieval_note": "수습기간 중 해고 부당 판정 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414053",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": ["procedure"],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["징계위원회7일전서면통보미실시", "진술권포기서미수령", "소명기회불충분"],
        "legal_focus": ["징계절차하자=징계부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["징계위원회서면출석통보미실시+진술권포기서미수령=절차하자=징계부당"],
        "exclude_for_queries": [],
        "summary_short": "징계위원회 서면 통보 미실시+진술권 포기서 미수령=절차 하자=징계 부당",
        "holding_summary": "징계위원회 개최 7일 전 서면 통보 미실시+진술권 포기서 미수령으로 충분한 소명기회 미부여=절차 하자=징계 부당",
        "retrieval_note": "징계위원회 사전 서면 통보+진술권 보장 절차 하자=징계 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41577",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["외부공문발송입증자료없음", "허위보고징계사유주장", "사유입증실패"],
        "legal_focus": ["징계사유불인정"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["외부공문발송입증자료없음+허위보고사유입증실패=징계부당"],
        "exclude_for_queries": [],
        "summary_short": "외부 공문 발송 입증 자료 없음+허위보고 사유 입증 실패=정직 부당",
        "holding_summary": "①외부 공문 발송 입증 자료 없음, ②허위보고 징계사유 입증 실패=정직처분 사유 불충분=정직 부당",
        "retrieval_note": "징계사유 입증 실패=징계 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_4163",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["demotion", "transfer"],
        "fact_markers": ["취업규칙강등정의=직급내림+3개월직무종사불가", "직급직위변동없음", "3개월직무제한없음", "팀장→팀원보직변경"],
        "legal_focus": ["강등vs보직변경구별", "취업규칙강등정의기준"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["취업규칙강등=직급내림+3개월직무제한인데직급변동없고제한없음=강등아닌보직변경=부당"],
        "exclude_for_queries": [],
        "summary_short": "취업규칙상 강등 정의 미충족=보직만 팀장→팀원 변경=강등 아닌 보직변경=부당",
        "holding_summary": "취업규칙상 강등=직급 내리고 3개월 직무 종사 불가, 그런데 직급/직위 변동 없고 직무 제한도 없이 팀장→팀원 보직만 변경=취업규칙상 강등 정의 미충족=부당",
        "retrieval_note": "취업규칙 강등 정의 vs 실제 처분 괴리=강등/보직변경 구별 기준",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41615",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["정당한이유필요", "서면통지필요", "해고사유객관적확인불가"],
        "legal_focus": ["해고정당성요건미충족"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["해고사유객관적확인불가+서면통지요건=해고부당"],
        "exclude_for_queries": [],
        "summary_short": "해고 사유 객관적 확인 불가+서면통지 미비=해고 부당",
        "holding_summary": "근로기준법 제23조 정당한 이유+제27조 서면통지 요건 중 해고사유 객관적 확인 불가=해고 부당",
        "retrieval_note": "해고사유 입증 실패+서면통지 요건=해고 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41621",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["취업규칙무단반출+지시불응=질서문란", "운송수입금미납=의무위반"],
        "legal_focus": ["징계사유인정=징계정당"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["취업규칙무단반출+운송수입금미납=징계사유=징계정당"],
        "exclude_for_queries": [],
        "summary_short": "취업규칙 무단 반출+지시 불응+운송수입금 미납=징계 정당",
        "holding_summary": "취업규칙 무단 반출·반납 지시 불응=질서 문란, 운송수입금 미납=의무 위반=취업규칙 징계사유 해당=징계 정당",
        "retrieval_note": "운수업 취업규칙 위반 징계 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41729",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["총괄관리이사소극적업무처리", "안전사고2건안전보건관리책임", "징계사유주장"],
        "legal_focus": ["징계사유정당성"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["총괄관리이사소극적업무+안전사고2건=징계부당(사유입증불충분)"],
        "exclude_for_queries": [],
        "summary_short": "총괄관리이사 소극적 업무+안전사고 2건=징계사유 주장 입증 불충분=징계 부당",
        "holding_summary": "울산공장 총괄관리이사의 소극적 업무처리 및 안전사고 2건 관련 징계사유 주장=입증 불충분=징계 부당",
        "retrieval_note": "관리이사 직책 관련 징계사유 입증 실패=징계 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41779",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["사업장무단이탈", "작업지시불응", "상급자업무명령거부", "연락두절"],
        "legal_focus": ["징계사유인정=징계정당"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["무단이탈+업무명령거부+연락두절=취업규칙위반=징계정당"],
        "exclude_for_queries": [],
        "summary_short": "무단이탈+업무명령 거부+연락 두절=취업규칙 위반=징계 정당",
        "holding_summary": "사업장 무단이탈·작업지시·상급자 업무명령 거부·연락 두절=취업규칙 위반 행위=징계 정당",
        "retrieval_note": "복합 취업규칙 위반(이탈+명령거부+연락두절) 징계 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41853",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": ["redundancy"],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["원청도급계약해지", "창원전보+희망퇴직등구제방안제시", "무단결근후직권해고", "서면통지있음"],
        "legal_focus": ["무단결근직권해고정당", "해고요건충족"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["원청도급계약해지=구제방안제시했으나무단결근=직권해고정당"],
        "exclude_for_queries": [],
        "summary_short": "원청 도급 해지→전보 등 구제방안 제시했으나 출근 거부+무단결근=직권해고 정당",
        "holding_summary": "원청 도급계약 해지+창원 전보 등 구제방안 제시→근로자 출근 거부·무단결근=직권해고=인사권 남용 아님=근기법 23조 위반 아님=해고 정당",
        "retrieval_note": "구제방안 제시 후 무단결근=직권해고 정당. 정리해고 주장이나 실질은 무단결근 해고",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41959",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["인사규정무단결근15일이상=면직사유", "연속10일이상직무이탈=면직사유"],
        "legal_focus": ["면직사유해당=징계정당"],
        "industry_context": "public",
        "exclusion_flags": [],
        "include_for_queries": ["인사규정15일이상무단결근=면직사유해당=면직정당"],
        "exclude_for_queries": [],
        "summary_short": "인사규정 무단결근 15일 이상=면직 사유 해당=면직 정당(재심 유지)",
        "holding_summary": "인사규정상 15일 이상 무단결근 또는 10일 이상 직무이탈=면직 사유=근로자 해당=면직 정당(재심 유지)",
        "retrieval_note": "인사규정 면직 사유(무단결근 기준) 해당=면직 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── procedure (4건) ──────────────────────────────────────────────────────────
    {
        "case_id": "id_414043",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["전직발령2025.1.2+2025.8.1", "인사발령일기준3개월도과", "2025.12.8구제신청"],
        "legal_focus": ["제척기간3개월초과=각하"],
        "industry_context": "unknown",
        "exclusion_flags": ["procedure_dominant"],
        "include_for_queries": ["복수전직발령=각발령일기준3개월도과=각하"],
        "exclude_for_queries": [],
        "summary_short": "2건 전직 발령일 기준 각각 3개월 도과=각하",
        "holding_summary": "전직발령 2건(2025.1.2 및 2025.8.1) 기준으로 각 인사발령일로부터 3개월을 도과한 2025.12.8 구제신청=제척기간 초과=각하",
        "retrieval_note": "복수 발령 시 각 발령일 기준 제척기간 산정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414095",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["금전보상명령신청", "사용자복직명령+임금지급", "구제이익소멸않음"],
        "legal_focus": ["금전보상구제이익=복직+임금지급무관"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["금전보상명령신청자=복직명령+임금지급에도구제이익소멸않음"],
        "exclude_for_queries": [],
        "summary_short": "금전보상 신청자=복직명령+임금지급에도 구제이익 소멸하지 않음",
        "holding_summary": "근로자가 원직복직이 아닌 금전보상명령 구하는 중 사용자가 복직명령+임금지급 해도 구제이익 소멸하지 않음",
        "retrieval_note": "금전보상 구제이익=복직+임금지급 무관. batch_053 id_411481, batch_054 id_412295, batch_056 id_413577에 이어 4회 누적",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41443",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer", "pay_cut", "dismissal"],
        "fact_markers": ["감봉+보직해임+전보구제이익없음", "해고사유와직접관련없음", "해고외나머지각하"],
        "legal_focus": ["구제이익각하", "해고와전보연관성"],
        "industry_context": "unknown",
        "exclusion_flags": ["procedure_dominant"],
        "include_for_queries": ["감봉+보직해임+전보=해고사유와직접관련없음=구제이익없음=각하"],
        "exclude_for_queries": [],
        "summary_short": "감봉·보직해임·전보=해고와 직접 관련 없음=구제이익 없음=각하",
        "holding_summary": "감봉 3개월, 감봉 5개월, 보직해임, 전보의 구제이익=해고사유와 직접 관련 없음=구제이익 없음=각하. 해고만 본안 판단",
        "retrieval_note": "해고와 무관한 선행 징계·전보=구제이익 소멸 각하",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41981",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무내용변동없음", "근무장소만변경=전보아님", "취업규칙강등규정없음"],
        "legal_focus": ["전보해당않음=구제신청대상아님"],
        "industry_context": "unknown",
        "exclusion_flags": ["procedure_dominant"],
        "include_for_queries": ["업무내용변동없이근무장소만변경=전보아님=구제신청대상아님"],
        "exclude_for_queries": [],
        "summary_short": "업무내용 변동 없이 근무장소만 변경=전보 아님=구제신청 대상 아님",
        "holding_summary": "업무내용 변동 없이 같은 공간 내 다른 부서로 근무장소만 변경=전보로 볼 수 없음+취업규칙에 강등 규정 없음=구제신청 대상 아님",
        "retrieval_note": "부서 내 근무장소 변경=전보 미해당=각하. 근기법23조 열거사유 비해당 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── no_dismissal (5건) ───────────────────────────────────────────────────────
    {
        "case_id": "id_414023",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": ["contract_expiry"],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["근로계약서종료일미작성", "무기계약인정", "기간제주장반박"],
        "legal_focus": ["처분문서효력", "기간제vs무기계약"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["근로계약서종료일미작성=무기계약=기간만료주장불인정=해고존재"],
        "exclude_for_queries": [],
        "summary_short": "근로계약서 종료일 미작성=무기계약=기간만료 주장 불인정=해고 존재",
        "holding_summary": "근로계약서에 계약기간 종료일 미작성=처분문서 효력 부인 어려움=무기계약=기간만료 주장 불인정=해고 존재+부당",
        "retrieval_note": "근로계약서 종료일 미기재=무기계약 인정 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414033",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["사직서3회요구", "근로자제출거부", "관리자이렇게는같이일못한다발언=해고의사표시", "고용보험상실신고일방"],
        "legal_focus": ["해고의사표시인정", "사직서강요=자발적사직아님"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["사직서3회요구거부+관리자발언=해고의사표시+고용보험일방상실신고=해고존재"],
        "exclude_for_queries": [],
        "summary_short": "사직서 3회 요구+관리자 '같이 일 못 한다' 발언+고용보험 일방 상실신고=해고 존재",
        "holding_summary": "횡령 의심 사직서 3회 요구, 근로자 거부, 관리자의 '이렇게는 같이 일 못 한다' 발언=해고 의사표시+고용보험 피보험자격 상실신고 일방 처리=해고 존재. 서면통지 없음=절차 하자=부당",
        "retrieval_note": "사직서 강요 거부+관리자 구두 발언+일방 상실신고=해고 존재 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414061",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "fixed_term",
        "disposition_type": ["dismissal"],
        "fact_markers": ["기간제계약기간내", "인원충원필요성부족발언", "해고의사표시인정"],
        "legal_focus": ["해고의사표시인정"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["기간제계약기간내인원충원필요성부족발언=해고의사표시=해고존재=부당"],
        "exclude_for_queries": [],
        "summary_short": "계약기간 내 '인원 충원 필요성 부족' 발언=해고 의사표시=해고 존재=부당해고",
        "holding_summary": "기간제 근로자에게 계약 종료일 전 '인원 충원의 필요성이 부족함으로' 발언=해고 의사표시=해고 존재=부당해고",
        "retrieval_note": "계약기간 내 사용자 발언=해고 의사표시 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_414099",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["no_formal_disposition"],
        "fact_markers": ["결정권한없는직원발언", "출근하지말라취지", "해고의사표시불인정"],
        "legal_focus": ["해고의사표시권한", "해고없음"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["결정권한없는직원의출근하지말라발언=해고의사표시불인정=해고없음"],
        "exclude_for_queries": [],
        "summary_short": "결정권한 없는 직원 발언=해고 의사표시 불인정=해고 없음",
        "holding_summary": "회사 직원이 근로자에게 출근하지 말라 했어도 그 직원이 근로관계 종료 결정 권한 없음=사용자 지위 아님=해고 의사표시 불인정=해고 없음",
        "retrieval_note": "해고 의사표시=결정권한 있는 자의 표시여야 함. 권한 없는 직원 발언=해고 불인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_4193",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": ["procedure"],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["근로관계이미종료", "제척기간내신청=구제이익인정", "사직서합의주장증거없음=해고존재", "서면통지없음"],
        "legal_focus": ["구제이익=원직복직불가에도임금지급구제이익", "해고존재인정"],
        "industry_context": "education",
        "exclusion_flags": [],
        "include_for_queries": ["근로관계종료후구제신청=제척기간내=구제이익인정+합의입증실패=해고존재=부당"],
        "exclude_for_queries": [],
        "summary_short": "근로관계 종료 후 구제신청=제척기간 내=구제이익+합의 증거 없음=해고 존재=부당",
        "holding_summary": "근로관계 이미 종료되었으나 제척기간 내 신청=원직복직 불가해도 임금 지급 구제이익 존재+합의 주장 증거 없음=해고 존재+서면통지 없음=부당(재심에서 초심 번복)",
        "retrieval_note": "근로관계 종료 후 구제이익=임금지급 청구 가능 확인. 합의 입증 실패=해고 존재",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── discrimination (2건) ─────────────────────────────────────────────────────
    {
        "case_id": "id_41411",
        "issue_type_primary": "discrimination",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["other"],
        "fact_markers": ["비교대상근로자선정", "근무기간5년미만=8급동일호봉상임단원", "국악단조례시행규칙"],
        "legal_focus": ["비교대상근로자선정기준", "기간제차별"],
        "industry_context": "public",
        "exclusion_flags": [],
        "include_for_queries": ["국악단기간제=조례시행규칙기준비교대상상임단원선정=차별인정"],
        "exclude_for_queries": [],
        "summary_short": "국악단 기간제=조례 시행규칙 기준 비교대상 상임단원 선정=차별 인정(재심에서 초심 번복)",
        "holding_summary": "국악단 기간제 근로자의 비교대상=근무기간 5년 미만에 따라 8급 동일 호봉의 상임단원=조례 시행규칙 기준 적용=차별 인정(재심 번복)",
        "retrieval_note": "공공기관 기간제 비교대상근로자 선정 기준=조례 시행규칙",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_41851",
        "issue_type_primary": "discrimination",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["other"],
        "fact_markers": ["단시간근로자차별", "비교대상상임단원", "기본급예능수당맞춤형복지비정근수당명절휴가비=차별금지영역"],
        "legal_focus": ["차별금지영역판단", "단시간근로자차별"],
        "industry_context": "public",
        "exclusion_flags": [],
        "include_for_queries": ["단시간근로자=기본급예능수당정근수당명절휴가비=차별금지영역=차별인정=부분인용"],
        "exclude_for_queries": [],
        "summary_short": "단시간 근로자=기본급·예능수당·정근수당·명절휴가비=차별금지 영역=차별 인정=부분인용",
        "holding_summary": "단시간근로자 비교대상=상임단원. 기본급, 예능수당, 맞춤형복지비, 정근수당, 명절휴가비=차별금지영역 해당=부분인용",
        "retrieval_note": "공공기관 단시간 근로자 차별금지 영역 판단 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── redundancy (1건) ─────────────────────────────────────────────────────────
    {
        "case_id": "id_41595",
        "issue_type_primary": "redundancy",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["부산분원독립분사무소", "수행업무다른사업장없음", "전환배치사실상불가"],
        "legal_focus": ["전환배치불가=정리해고정당", "구제이익현실적제약"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["독립분사무소폐쇄=해당업무다른사업장없음=전환배치불가=해고정당"],
        "exclude_for_queries": [],
        "summary_short": "독립 분사무소 폐쇄=해당 업무 다른 사업장 없음=전환배치 사실상 불가=해고 정당",
        "holding_summary": "부산분원=목적사업만 수행하는 독립 분사무소+수행 업무 다른 사업장에서 미수행=전환배치 사실상 어려움=구제명령 실효성 없음=해고 정당(재심 유지)",
        "retrieval_note": "독립 분사무소 폐쇄+업무 전환 불가=정리해고 유사 법리",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
]

out_path = "retagging/output/reviewed/transfer_batch_057_reviewed.jsonl"
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print(f"Written {len(records)} records")
