import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = []

records.append({"id":"id_52927","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["고객대면영업=주요직무","주된부분배제=전직해당","영업실적미비","과도한접대비","보고미흡"],"legal_focus":["고객대면영업배제=전직해당","업무상필요성검토"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["고객대면영업=주요직무=주된부분배제=전직해당","영업실적미비+접대비과다+보고미흡=TV정당성검토"],"exclude_for_queries":[],"summary_short":"고객 대면 영업=주요 직무=주된 부분 배제=전직 해당, TV 정당성 검토","holding_summary":"외환 영업 중 고객 대면 업무 제한=채용 광고·직무기술서상 주요 직무=주된 부분 배제=근로 내용 중대 변경=전직 해당. 영업실적 미비·과도한 접대비·보고 미흡=업무상 필요성 검토.","retrieval_note":"고객대면영업 주요직무 주된부분배제 전직해당 영업실적미비 접대비","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_52937","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer","suspension"],"fact_markers":["국립학교=대한민국교육부사용자적격","센터장기공사","업무상필요성인정","희망직종조사협의","징계사유인정"],"legal_focus":["사용자적격=대한민국교육부","센터공사=업무상필요성인정+협의절차=TV정당","징계정당"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["국립학교=대한민국교육부사용자적격","센터장기공사=업무상필요성인정+희망직종조사=협의=TV정당"],"exclude_for_queries":[],"summary_short":"국립학교=대한민국교육부 사용자적격+센터 공사=업무상필요성+협의=TV정당, 징계 정당","holding_summary":"국립학교=교육부장관 관할=사용자 적격 대한민국(교육부). 센터 장기 공사=업무상 필요성. 생활상 불이익 감수 범위. 희망 직종 조사=협의=TV 정당. 징계사유·양정·절차 정당.","retrieval_note":"국립학교 교육부사용자적격 센터공사 업무상필요성 희망직종조사 협의 TV정당 징계정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_52953","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["dismissal"],"fact_markers":["1개월단위계속근로예정","계속근로1년미달2명","퇴직금회피목적","현장소장해고지시","해고존재"],"legal_focus":["사실상계속근로예정=자동종료아님","퇴직금발생회피목적해고=해고존재"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["1개월계약계속근로예정=기간만료자동종료아님+퇴직금회피목적해고=해고존재","퇴직금발생1일2일전해고=퇴직금회피목적=해고존재"],"exclude_for_queries":[],"summary_short":"1개월 계약 계속 근로 예정+계속근로 1년 미달 2명=퇴직금 회피 목적=해고 존재","holding_summary":"1개월 단위 계약으로 사실상 계속 근로 예정=기간 만료 자동 종료 아님. 계속근로 1년에서 각 1일·2일 부족한 근로자들에게 해고 지시=퇴직금 발생 회피 목적=해고 존재.","retrieval_note":"1개월계약계속근로예정 기간만료자동종료아님 퇴직금회피목적해고 해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_52971","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["5가지해고사유","낙마사고1가지만인정","나머지증거불충분","낙마징계전례없음","양정과도"],"legal_focus":["1가지사유만인정","낙마전례없음=양정과도=부당해고"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["5가지해고사유중낙마사고1가지만인정+낙마징계전례없음=양정과도=부당해고","해고사유증명책임미이행=대부분불인정=양정과도=부당"],"exclude_for_queries":[],"summary_short":"5가지 해고 사유 중 낙마 사고 1건만 인정+낙마 징계 전례 없음=양정 과도=부당","holding_summary":"5가지 해고 사유 중 낙마 사고만 인정(나머지 사용자 증명 실패). 낙마 사고로 징계한 전례 없음=1가지 사유만으로 고용 계속 불가 수준 아님=양정 과도=부당해고.","retrieval_note":"5가지해고사유 낙마사고1건만인정 낙마징계전례없음 양정과도 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_52973","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["무인주차시스템설치","업무필요성충분","근무장소변경없음","임금감소없음","취업규칙별도기준없음"],"legal_focus":["업무상필요성인정","생활상불이익없음","무인주차관리운영과정협의=절차준수","TV정당"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["무인주차시스템설치=업무필요성+근무장소임금변동없음=TV정당","무인주차운영과정협의=절차준수=TV정당"],"exclude_for_queries":[],"summary_short":"무인주차 시스템=업무 필요성+근무장소·임금 변동 없음+과정 협의=TV정당","holding_summary":"병원 무인 주차 시스템 설치+외래 환자 특성=업무 필요성 충분. 근무 장소 변경 없음+통근·임금 변동 없음=생활상 불이익 없음. 무인 주차관리 운영 과정 통해 협의=절차 준수=TV 정당.","retrieval_note":"무인주차시스템 업무필요성 근무장소변동없음 임금감소없음 협의 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53027","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사용자일방의사표시","해고존재","서면통지없음","금전보상"],"legal_focus":["해고존재","서면통지없음=부당해고","금전보상"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사용자일방의사=해고존재+서면통지없음=부당해고+금전보상"],"exclude_for_queries":[],"summary_short":"사용자 일방 의사=해고 존재+서면통지 없음=부당해고+금전보상","holding_summary":"사용자의 일방적 의사에 의한 근로관계 종료=해고 존재. 해고 서면 통지 없음=절차 하자=부당해고. 원직복직 갈음 금전보상명령 수용.","retrieval_note":"사용자일방의사 해고존재 서면통지없음 부당해고 금전보상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5303","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약근무장소불특정","기존본사업무겸행","부산지점업무종료","대구본사배치","출퇴근증가감수범위"],"legal_focus":["근무장소불특정=동의불필요","부산지점업무종료=업무상필요성인정","출퇴근증가=감수범위=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약근무장소불특정+부산지점업무종료=대구본사배치=TV정당","부산지점업무종료+기존본사업무겸행=업무내용본질변경없음=TV정당"],"exclude_for_queries":[],"summary_short":"근무장소 불특정+부산지점 업무 종료=대구 본사 배치=업무상필요성+출퇴근 증가 감수범위=TV정당","holding_summary":"근로계약서에 근무장소·업무내용 미특정=동의 불필요. 기존 본사 업무 겸행=본질적 변경 없음. 부산지점 업무 종료=대구 본사 배치 업무상 필요성. 출퇴근 증가=불가피+감수 범위=TV 정당.","retrieval_note":"근로계약근무장소불특정 부산지점업무종료 대구본사배치 출퇴근증가감수범위 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53035","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["직장내성희롱","언어적성희롱","징계사유인정","양정적정","절차정당","TV정당","부당노동행위불인정"],"legal_focus":["언어적성희롱=징계사유","양정적정","절차정당=징계정당","성희롱이유전보=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직장내성희롱언어적=징계사유인정+양정적정+절차정당+TV정당","성희롱징계정당+TV정당+부당노동행위불인정"],"exclude_for_queries":[],"summary_short":"직장내 성희롱=징계 정당+TV정당+부당노동행위 불인정","holding_summary":"언어적 성희롱=징계사유 인정. 양정 과도 없음+절차 준수=징계 정당. 성희롱 이유 전보=업무상 필요성 인정=TV 정당. 부당노동행위 불인정.","retrieval_note":"직장내성희롱언어적 징계사유인정 양정적정 절차정당 TV정당 부당노동행위불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53093","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["전보철회취소논란","구제이익소멸단정불가","임금차액구제가능성","전보정당성"],"legal_focus":["전보철회미인정+임금차액구제이익=구제이익소멸단정불가"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보철회취소여부불분명+임금차액구제이익=구제이익소멸단정불가"],"exclude_for_queries":[],"summary_short":"전보 철회·취소 논란+임금 차액 구제이익=구제이익 소멸 단정 불가","holding_summary":"전보 철회·취소 종국적 이루어졌다고 볼 수 없음. 설령 철회 가정해도 전보 기간 임금 차액 구제이익 유지될 여지=구제이익 소멸 단정 불가.","retrieval_note":"전보철회취소논란 임금차액구제이익 구제이익소멸단정불가","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53103","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직장내괴롭힘조사없이근무지변경","업무미부여","전직해당=대상적격","10.27자택대기와달리부당"],"legal_focus":["직장내괴롭힘조사없이근무지변경=전직=대상적격","전직정당성검토"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["직장내괴롭힘조사없이근무지변경+업무미부여=전직=구제신청대상적격","괴롭힘진정인지못한상태조사없이전직=대상적격"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘 조사 없이 근무지 변경+업무 미부여=전직=구제신청 대상적격","holding_summary":"직장내 괴롭힘 진정 제기 사실 미인지+피해 사실 조사·확인 없이 근로자만 근무지 변경+업무 미부여=전직 처분=구제신청 대상 적격.","retrieval_note":"직장내괴롭힘조사없이근무지변경 업무미부여 전직해당 구제신청대상적격","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53155","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["사무총장중앙교육연수원장","근로계약서작성","급여기재","4대보험가입","직위해제대기발령","임금감액","승진재직기간불산입"],"legal_focus":["사무총장연수원장=근로자성인정","직위해제=임금감액+승진불산입=구제이익있음"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["사무총장연수원장=근로계약+급여+4대보험=근로자성인정","직위해제=임금감액+승진재직기간불산입=구제이익"],"exclude_for_queries":[],"summary_short":"사무총장·연수원장=근로자성 인정+직위해제=임금감액+승진재직기간 불산입=구제이익","holding_summary":"사무총장·중앙교육연수원장=근로계약서+급여 기재+4대보험+지시에 따른 근무=근로자성 인정. 직위해제=임금 감액+승진 재직기간 불산입=구제이익 존재.","retrieval_note":"사무총장연수원장 근로자성인정 직위해제 임금감액 승진재직기간불산입 구제이익","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53171","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["입주자대표회의교체요청","업무상필요성인정","급여변동없음","차량유지보조비지급","사전설명이해구함"],"legal_focus":["업무상필요성인정","생활상불이익없음","사전설명협의=TV정당"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["입주자대표회의교체요청=업무상필요성인정+급여변동없음+사전설명=TV정당"],"exclude_for_queries":[],"summary_short":"입주자대표회의 교체 요청=업무상필요성+급여 변동 없음+사전 설명=TV정당","holding_summary":"입주자대표회의 교체 요청 등 업무상 필요성 없다고 단정 어려움. 급여 변동 없음+차량유지보조비 지급=생활상 불이익 없음. 전직 전 근로자에게 설명·이해=TV 정당.","retrieval_note":"입주자대표회의교체요청 업무상필요성 급여변동없음 사전설명 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53177","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"pre_hire","disposition_type":["dismissal"],"fact_markers":["근로계약서작성=채용내정성립","채용내정취소","해고해당","서면통지없음"],"legal_focus":["근로계약서작성=채용내정성립","채용내정취소=해고해당","서면통지없음=부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약서작성=채용내정성립+채용내정취소=해고해당+서면통지없음=부당"],"exclude_for_queries":[],"summary_short":"근로계약서 작성=채용내정 성립, 취소=해고 해당+서면통지 없음=부당","holding_summary":"2022.10.27 근로계약서 작성=채용내정 성립. 2022.11.9 취소=근기법상 해고 해당=서면으로 취소 사유 통보 의무. 서면 통지 없음=부당.","retrieval_note":"근로계약서작성 채용내정성립 채용내정취소 해고해당 서면통지없음 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53179","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["상시5인미만주장","입증자료없음","현장조사","5인미만인정=각하"],"legal_focus":["상시5인미만=근기법적용제외=각하"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["상시5인미만=근기법적용제외=각하","5인이상입증실패=각하"],"exclude_for_queries":[],"summary_short":"상시 5인 미만=근기법 적용 제외=각하","holding_summary":"근로자 상시 5인 이상 주장이나 입증 자료 없음+현장조사 결과 5인 이상 사용 불확인=근기법 적용 사업장 해당 않음=각하.","retrieval_note":"상시5인미만 근기법적용제외 각하 5인이상입증실패","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53189","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["기간제한없는근로계약","고용미승계조항없음","고용미승계통보서=해고예고명시","근로자의사반한종료=해고"],"legal_focus":["기간제한없는계약+고용미승계=해고예고명시=해고존재"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["고용미승계통보=해고예고명시+근로자의사반한=해고존재","기간제한없는계약+고용미승계결정=해고"],"exclude_for_queries":[],"summary_short":"기간 제한 없는 계약+고용 미승계 통보서=해고예고 명시=해고 존재","holding_summary":"기간 정함 없는 근로계약+취업규칙에 고용 미승계 해고 조항 없음. 고용 미승계 통보서에 \"근기법에 의거한 해고예고\" 명시=해고 존재.","retrieval_note":"기간제한없는계약 고용미승계통보 해고예고명시 해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53193","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["SP2→SP3진급누락","그밖의징벌여부","성과조건3년근무+최소AP+사고미발생","4명진급누락"],"legal_focus":["진급누락=그밖의징벌아님=구제신청대상아님"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["진급누락=그밖의징벌아님=사용자제재아님=구제신청대상아님","진급조건미충족=제재성불이익아님=각하"],"exclude_for_queries":[],"summary_short":"진급 누락=그밖의 징벌 아님=구제신청 대상 아님","holding_summary":"그밖의 징벌=사용자가 제재로서 가하는 불이익한 처분. SP2→SP3 진급 누락=진급 조건(근무기간+성과+사고미발생) 미충족에 따른 결과=제재로서의 불이익한 처분 아님=구제신청 대상 아님.","retrieval_note":"진급누락 그밖의징벌아님 사용자제재불이익아님 구제신청대상아님","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53201","issue_type_primary":"redundancy","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상신청후복직명령","임금미지급","구제이익존재","코로나19백신계약해지","경영상이유해고","절차미준수"],"legal_focus":["금전보상신청후복직명령=진정성없음=구제이익존재","코로나19백신계약해지=경영상해고+절차미준수=부당"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["금전보상신청후복직명령+임금미지급=구제이익존재","코로나19백신계약해지=경영상해고+절차미준수=부당"],"exclude_for_queries":[],"summary_short":"금전보상 신청 후 복직명령=구제이익 존재, 코로나19 계약 해지=경영상 해고+절차 미준수=부당","holding_summary":"금전보상명령 신청 후 복직명령=임금 미지급=진정성 없음=구제이익 존재. 코로나19 백신 유통 계약 해지=경영상 이유 해고=근기법 제24조 적용. 절차 미준수=부당.","retrieval_note":"금전보상신청후복직명령 구제이익존재 코로나19백신계약해지 경영상해고 절차미준수 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53217","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"unknown","disposition_type":["transfer"],"fact_markers":["별지참조"],"legal_focus":["전보정당성"],"industry_context":"unknown","exclusion_flags":["evidence_too_thin"],"include_for_queries":[],"exclude_for_queries":[],"summary_short":"전보 정당성 판단 사례 (원문 별지 참조)","holding_summary":"원문이 별지 참조로만 기재된 사례로 구체적 내용 확인 불가.","retrieval_note":"전보정당성 별지참조 원문미수록","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53237","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["전보희망자","인천지사인원충원급박","직급체계적합","업무상필요성인원선택합리성인정"],"legal_focus":["전보희망+인천충원필요+직급적합=업무상필요성인정=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로자전보희망+인천지사인원충원급박+직급적합=업무상필요성인원선택합리성인정=TV정당"],"exclude_for_queries":[],"summary_short":"전보 희망+인천지사 인원 충원 급박+직급 적합=업무상필요성·인원선택 합리성=TV정당","holding_summary":"근로자 전보 희망(경기지사 불화). 2022.7 인천지사 업무 과다+직원 퇴사=시급한 충원 필요. 수도권 지사 대리 직급 적합=업무상 필요성·인원 선택 합리성 인정=TV 정당.","retrieval_note":"전보희망 인천지사인원충원급박 직급적합 업무상필요성 인원선택합리성 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53315","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["연차유급휴가=무단결근주장","무단결근1일=해고사유아님","근로계약5일이상조항","해고사유불충분"],"legal_focus":["연차유급휴가=무단결근아님","무단결근1일=해고사유아님","근로계약5일이상조항=1일미충족=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["연차유급휴가=무단결근주장=사실아님=부당","무단결근1일=근로계약5일이상조항미충족=해고사유없음=부당해고"],"exclude_for_queries":[],"summary_short":"연차유급휴가=무단결근 주장+무단결근 1일=계약 5일 이상 조항 미충족=부당해고","holding_summary":"근로자 연차 유급휴가 정당 사용 주장. 설령 인정해도 무단결근 1일=근로관계 종료 수준 중대 사유 아님. 근로계약서에 무단결근 계속 5일 이상=해고 사유 명시=1일 해당 않음=부당해고.","retrieval_note":"연차유급휴가 무단결근주장 무단결근1일 근로계약5일이상조항 해고사유없음 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53317","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["dismissal"],"fact_markers":["기간제계약기간만료전해고","해고존재","서면통지없음","금전보상"],"legal_focus":["계약기간만료전해고=해고존재","서면통지없음=부당해고","금전보상=해고일~계약종료일"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["기간제계약기간만료전해고=해고존재+서면통지없음=부당해고+금전보상","계약기간만료전일방종료=해고존재+서면통지없음=부당"],"exclude_for_queries":[],"summary_short":"기간제 계약기간 만료 전 해고=해고 존재+서면통지 없음=부당해고+금전보상","holding_summary":"기간제 계약기간 만료 전 사용자 일방 근로관계 종료=해고 존재. 해고 사유·시기 서면 통지 없음=부당해고. 금전보상=해고일~계약 종료일까지 정상 근로 시 수령 금액.","retrieval_note":"기간제 계약기간만료전해고 해고존재 서면통지없음 부당해고 금전보상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53349","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["대표도서관장","도서관자문역전담","44개월완공","개관전2~6개월전문가필요","긴급업무없음"],"legal_focus":["도서관완공3년남음+자문전담필요성입증불충분+긴급업무없음=업무상필요성없음=TV부당"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["도서관완공3년남음+자문전담필요성미입증=업무상필요성없음=TV부당","대표도서관장→자문역전담=시기부적절=TV부당"],"exclude_for_queries":[],"summary_short":"도서관 완공 3년 남음+자문 전담 필요성 미입증=업무상필요성 없음=TV부당","holding_summary":"도서관 건립까지 3년 남음. 개관 전 2~6개월이 전문가 전담 필요 시기. 완공 3년 전 자문역 전담 필요성 입증 불충분+전직 후 긴급 처리 업무 없음=업무상 필요성 없음=TV 부당.","retrieval_note":"대표도서관장 도서관완공3년 자문역전담 필요성미입증 업무상필요성없음 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53355","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["보직변경통보사직서제출","계속근무권유","무단결근","타회사면접취업","사직의사에의한종료"],"legal_focus":["사직서제출+계속근무권유무시+무단결근+타회사취업=자발적사직=해고없음"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["보직변경후사직서제출+계속근무권유거부+타회사취업=자발적사직=해고없음"],"exclude_for_queries":[],"summary_short":"보직변경 후 사직서+계속 근무 권유 거부+타회사 취업=자발적 사직=해고 없음","holding_summary":"인원 증원·보직 변경 통보 이유 사직서 제출. 행정부장 계속 근무 권유. 근로자 명시적 출근 의사 없이 무단결근+2022.12.9 타 회사 면접+12.19 취업=사직 의사에 의한 종료=해고 없음.","retrieval_note":"보직변경후사직서 계속근무권유거부 무단결근 타회사취업 자발적사직 해고없음","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53371","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["준수사항위반업무지시불이행","서면통지시위반규정나열만","구체적비위행위미특정","서면통지하자"],"legal_focus":["서면통지시구체적특정없음=서면통지하자=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["서면통지=위반규정나열+구체적비위행위미특정=서면통지하자=부당해고","징계해고=서면통지구체적특정없음=절차하자=부당"],"exclude_for_queries":[],"summary_short":"서면통지 시 위반 규정 나열만+구체적 비위행위 미특정=서면통지 하자=부당해고","holding_summary":"징계해고 서면통지 시 징계 원인된 구체적 행위 특정 없이 위반 규정 나열만+행위 형태 외 구체적 위반 사실 미특정=서면통지 하자=부당해고. 징계사유·양정 판단 불필요.","retrieval_note":"징계해고 서면통지 위반규정나열 구체적비위행위미특정 서면통지하자 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53387","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["PP센터폐점","업무상필요성인정","출퇴근증가감수범위","임금변동없음","2차례면담"],"legal_focus":["폐점=업무상필요성인정","생활상불이익없음","2차례면담=협의=TV정당"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["PP센터폐점=업무상필요성인정+출퇴근증가감수범위+2차례면담=TV정당"],"exclude_for_queries":[],"summary_short":"PP센터 폐점=업무상필요성+출퇴근 증가 감수범위+2차례 면담=TV정당","holding_summary":"PP센터 폐점=직원 인사발령 업무상 필요성. 출퇴근 증가이나 임금 변동 없음=감수 범위. 2차례 면담=협의=TV 정당.","retrieval_note":"PP센터폐점 업무상필요성 출퇴근증가감수범위 임금변동없음 2차례면담 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53405","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["취업규칙직무변경재량","징계종류없음","담당고객사변경","업무본질내용종류임금변동없음","인센티브유지"],"legal_focus":["담당고객사변경=본질변경없음+징계아님=TV정당"],"industry_context":"sales","exclusion_flags":[],"include_for_queries":["담당고객사변경=업무본질내용종류임금변동없음=TV정당","인센티브유지+사용자재량=담당고객사변경=TV정당"],"exclude_for_queries":[],"summary_short":"담당 고객사 변경=업무 본질·내용·임금 변동 없음+인센티브 유지=TV정당","holding_summary":"취업규칙 직무 변경 재량 조항+징계 종류 해당 않음. 담당 고객사 변경=업무의 본질적 내용·종류·소속부서·임금 변동 없음+인센티브 기존 플랜 유지=사용자 재량=TV 정당.","retrieval_note":"담당고객사변경 업무본질변동없음 임금변동없음 인센티브유지 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53441","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["복직명령","금전보상별도신청없음","임금지급","구제이익소멸"],"legal_focus":["복직명령+임금지급+금전보상별도신청없음=구제이익소멸"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["해고인정후복직명령+임금지급+금전보상별도신청없음=구제이익소멸"],"exclude_for_queries":[],"summary_short":"해고 인정 후 복직명령+임금 지급+금전보상 별도 미신청=구제이익 소멸","holding_summary":"사용자 해고 인정+구제신청 후 복직명령(2023.1.2). 근로자 복직 의사 없다고 재차 표명+금전보상명령 별도 신청 없음+임금 지급=구제이익 소멸.","retrieval_note":"해고인정 복직명령 임금지급 금전보상별도신청없음 구제이익소멸","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5345","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["nonrenewal"],"fact_markers":["1차계약후퇴직금정산","인사위원회계약종료결정","2차재계약기간제계약직","3차6개월특수계약형태","갱신기대권없음"],"legal_focus":["1차종료후퇴직금정산+계약종료결정=갱신기대권없음"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["1차계약종료퇴직금정산+인사위원회계약종료결정=갱신기대권없음","6개월특수계약형태=갱신기대권인정안됨"],"exclude_for_queries":[],"summary_short":"1차 계약 종료 퇴직금 정산+인사위원회 종료 결정+6개월 특수계약=갱신기대권 없음","holding_summary":"1차 계약 종료 후 퇴직금 정산+인사위원회 계약 종료 결정 후 재계약+기간제 계약직 발령+3차 6개월 특수 계약 형태=일반 미화근로자와 다른 특수 계약=갱신기대권 없음.","retrieval_note":"1차계약종료 퇴직금정산 인사위원회계약종료결정 6개월특수계약 갱신기대권없음","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53469","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["인사규정직권휴직","형사고소장기지연","무급휴직=정직유사중징계","정직유사"],"legal_focus":["무급휴직=인사명령","형사고소지연합리성없음","정직유사무급휴직=부당"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["무급휴직=직권휴직+형사고소장기지연합리성없음+정직유사=무급휴직부당","인사규정직권휴직=형사고소장기지연=부당"],"exclude_for_queries":[],"summary_short":"무급 직권휴직=형사고소 장기 지연 합리성 없음+정직 유사=부당","holding_summary":"체육회 인사규정 제19조제1항 직권휴직 규정 존재. 그러나 해고 시부터 알았던 사유로 복직 후에야 형사고소(장기 지연=합리적 이유 없음)+무급휴직=정직의 중징계와 유사한 불이익=무급 직권휴직 부당.","retrieval_note":"무급직권휴직 형사고소장기지연 정직유사 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53485","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["1년주기정기인사","차량반정원감소지원자증가","노선청소인원증원필요","거주지인근전보","출퇴근거리감소"],"legal_focus":["업무상필요성인정","출퇴근거리감소=생활상불이익없음","TV정당"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["1년주기정기인사+차량반정원감소+노선청소인원충원=업무상필요성인정+거주지인근=TV정당"],"exclude_for_queries":[],"summary_short":"정기인사+차량반 정원 감소+노선청소 인원 필요=업무상필요성+거주지 인근=TV정당","holding_summary":"1년 주기 정기 인사. 차량반 정원 감소+지원자 증가+노선청소 인원 증원 필요=업무상 필요성 인정. 거주지 인근 전보=출퇴근 감소=생활상 불이익 없음=TV 정당.","retrieval_note":"정기인사 차량반정원감소 노선청소인원증원 업무상필요성 거주지인근 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53499","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["dismissal"],"fact_markers":["1개월단위계약","공정종료일종료조항","용접공정미종료","12.11인원감축퇴사통보","해고존재"],"legal_focus":["공정미종료+인원감축퇴사통보=해고존재"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["용접공정미종료+인원감축퇴사통보=해고존재","계약종료일이전공정미종료상태퇴사통보=해고"],"exclude_for_queries":[],"summary_short":"용접 공정 미종료+인원 감축 퇴사 통보=해고 존재","holding_summary":"1개월 단위 계약, 계약서에 공정 종료일=근로관계 종료일 조항. 용접 공정 종료일(12.23) 이전인 12.11에 인원 감축 이유 퇴사 처리 통보=해고 존재.","retrieval_note":"용접공정미종료 인원감축퇴사통보 공정종료일전 해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53533","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["구두계약=근로자","급여합의결렬=근로계약지속","12.18해고존재","서면통지없음","부당해고"],"legal_focus":["구두계약근로자성인정","급여합의결렬=근로계약지속","12.18해고+서면통지없음=부당해고"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["구두계약=근로자성인정+급여합의결렬=계약지속+해고서면통지없음=부당","12.14급여산정의견불일치=계약지속+이후해고=서면통지없음=부당해고"],"exclude_for_queries":[],"summary_short":"구두 계약=근로자성+급여 합의 결렬=계약 지속+해고 서면통지 없음=부당","holding_summary":"구두 계약(주5일, 09~18시, 기본급+연장수당)=근로자. 2022.12.14까지 급여 산정 방식 의견 불일치=기존 계약 지속. 2022.12.18 해고+서면 통지 없음=부당해고.","retrieval_note":"구두계약 근로자성인정 급여합의결렬 계약지속 해고서면통지없음 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5357","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["시설관리팀장→영선관리담당","직무내용변경=전직","업무해태미입증","업무상필요성없음","급여15%삭감"],"legal_focus":["직무내용변경=전직=구제신청대상","업무해태미입증=업무상필요성없음","급여15%삭감=생활상불이익현저","TV부당"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["시설관리팀장→영선관리담당=직무내용변경=전직=구제신청대상","업무해태미입증+급여15%삭감=TV부당"],"exclude_for_queries":[],"summary_short":"시설관리팀장→영선관리 담당=직무 변경=전직+업무해태 미입증+급여 15% 삭감=TV부당","holding_summary":"시설관리팀장→영선관리 담당자=직무 내용 변경=전직=구제신청 대상. 업무 해태 미입증+조직쇄신 필요성에 귀책사유 없음=업무상 필요성 없음. 급여 15% 삭감=생활상 불이익 현저=TV 부당.","retrieval_note":"시설관리팀장 영선관리담당 직무내용변경 전직 업무해태미입증 급여15%삭감 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53573","issue_type_primary":"union_activity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["지방자치단체장사용자적격","정기인사전보","노조간부전보유예관행없음","부당노동행위의사추정없음"],"legal_focus":["사용자적격=지방자치단체장","정기인사+유예관행없음+추정근거없음=부당노동행위불인정"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["소방공무원정기인사전보+노조간부유예관행없음+부당노동행위의사없음=부당노동행위불인정","정기인사전보=노조간부유예관행없음=부당노동행위불인정"],"exclude_for_queries":[],"summary_short":"지방자치단체장 사용자적격+정기인사 전보=노조간부 유예 관행 없음=부당노동행위 불인정","holding_summary":"임용권 위임받은 지방자치단체장=사용자 적격. 정기 인사에 따른 전보+노조 간부 전보 유예 관행 없음+부당노동행위 의사 추정 근거 없음=부당노동행위 불인정.","retrieval_note":"지방자치단체장 사용자적격 정기인사 노조간부전보유예관행없음 부당노동행위불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53577","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["nonrenewal"],"fact_markers":["1개월단위4~11차갱신","도급만료일미도래","관행적갱신","팀장통화=데리고가려했는데","갱신기대권인정","갱신거절합리적이유없음"],"legal_focus":["1개월단위반복갱신+도급미만료+관행=갱신기대권","회원민원불확인+동료불화일방잘못아님=갱신거절합리적이유없음=부당"],"industry_context":"construction","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["1개월단위4~11차갱신+도급만료미도래+관행=갱신기대권인정+갱신거절합리적이유없음=부당"],"exclude_for_queries":[],"summary_short":"1개월 단위 4~11차 갱신+도급 미만료+관행=갱신기대권+갱신거절 합리적 이유 없음=부당","holding_summary":"1개월 단위 4~11차 반복 갱신+원청 도급 만료 미도래+관행적 갱신+팀장 통화('데리고 가려 했는데')=갱신기대권 인정. 회원 민원 불확인+동료 불화 일방 잘못 아님+상해 인과관계 없음=갱신거절 합리적 이유 없음=부당.","retrieval_note":"1개월단위반복갱신 도급만료미도래 관행 갱신기대권 갱신거절합리적이유없음 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53607","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약인사규정변경가능","파견직퇴사","기관장수행기사경력","업무상필요성인정","TV정당"],"legal_focus":["근로계약인사규정변경가능+파견직퇴사=업무상필요성인정=TV정당"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["파견직퇴사+기관장수행기사경력=업무상필요성인정=TV정당","인사규정변경가능+합리적대상선정=TV정당"],"exclude_for_queries":[],"summary_short":"파견직 퇴사+기관장 수행기사 경력=업무상필요성+인사규정 변경 조항=TV정당","holding_summary":"근로계약서·인사규정에 보직 변경 가능 규정. 기관장 수행기사 파견직 퇴사=충원 필요. 입사 후 징계 전까지 기관장 수행기사 근무=대상자 선정 합리성=업무상 필요성 인정=TV 정당.","retrieval_note":"파견직퇴사 기관장수행기사경력 근로계약인사규정변경가능 업무상필요성 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53611","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["nonrenewal"],"fact_markers":["9년위수탁계약","5차갱신","동일업무","사직서진의아님","회원민원불확인","동료불화일방잘못아님","상해인과관계없음"],"legal_focus":["9년위수탁+5차갱신+동일업무+사직서진의아님=갱신기대권","갱신거절합리적이유없음=부당"],"industry_context":"service","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["9년위수탁+5차갱신+동일업무=갱신기대권+갱신거절합리적이유없음=부당","회원민원불확인+동료불화일방아님+상해인과없음=갱신거절합리적이유없음"],"exclude_for_queries":[],"summary_short":"9년 위수탁+5차 갱신+동일업무=갱신기대권, 갱신 거절 합리적 이유 없음=부당","holding_summary":"사용자-위탁사 9년 위수탁+5차 갱신+동일 업무+사직서 진의 아님=갱신기대권 인정. 회원 민원 객관적 미확인+동료 불화 일방 잘못 아님+상해 인과관계 미확인=갱신거절 합리적 이유 없음=부당.","retrieval_note":"9년위수탁 5차갱신 동일업무 사직서진의아님 갱신기대권 갱신거절합리적이유없음 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53673","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["reprimand","transfer"],"fact_markers":["부하직원유류비거부","퇴사권유","직장내괴롭힘","경고처분전력","견책","TV정당"],"legal_focus":["유류비거부+퇴사권유=직장내괴롭힘=징계사유인정","경고처분전력+견책=양정적정","TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["유류비거부+퇴사권유=직장내괴롭힘=징계사유인정+경고처분전력=견책양정적정","직장내괴롭힘징계정당+TV정당"],"exclude_for_queries":[],"summary_short":"유류비 거부+퇴사 권유=직장내괴롭힘=징계 정당, TV정당","holding_summary":"부하 직원 유류비 지급 거부+퇴사 권유=직장내괴롭힘=징계사유 인정. 2022.2.24 경고 처분 전력=견책 양정 적정. 절차 하자 없음=징계 정당. 전보발령=TV 정당.","retrieval_note":"유류비거부 퇴사권유 직장내괴롭힘 경고처분전력 견책양정적정 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53683","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["취업규칙보직해제징계없음","인사명령","충분한유예없음","근무성적대응기회없음","관리수당감소"],"legal_focus":["보직해제=징계아님=인사명령","유예없음+대응기회없음=업무상필요성인정어려움","관리수당감소=생활상불이익","TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["취업규칙보직해제징계없음=인사명령+충분한유예없음+근무성적대응기회없음=TV부당","보직해제=인사명령+유예없음=TV부당"],"exclude_for_queries":[],"summary_short":"보직해제=징계 아님+인사명령+충분한 유예 없음+대응 기회 없음=TV부당","holding_summary":"취업규칙에 보직해제 징계 종류 없음=인사명령. 그러나 충분한 유예기간 없음+근무성적 대응 기회 미제공=업무상 필요성 인정 어려움. 관리수당 감소=생활상 불이익=TV 부당.","retrieval_note":"보직해제징계없음 인사명령 충분한유예없음 근무성적대응기회없음 관리수당감소 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5369","issue_type_primary":"union_activity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["콜센터=센터소속=5인이상","인사혁신=구체적해고사유아님","서면통지하자","노조가입5일후해고","부당노동행위"],"legal_focus":["콜센터=센터소속=5인이상사업장","인사혁신=구체적사유아님+서면통지하자=부당해고","노조가입5일후해고=부당노동행위"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["노조가입5일후해고=부당노동행위","인사혁신=구체적해고사유아님+서면통지하자=부당해고"],"exclude_for_queries":[],"summary_short":"노조 가입 5일 후 해고=부당노동행위, 인사혁신=구체적 사유 아님=부당해고","holding_summary":"콜센터=센터 소속=5인 이상 사업장. 인사혁신=구체적 해고사유 아님+서면통지 해고시기 미명시=부당해고. 노조 가입 통보 5일 후 해고+조합원만 해고=불이익 취급 부당노동행위.","retrieval_note":"콜센터센터소속5인이상 인사혁신구체적사유아님 서면통지하자 부당해고 노조가입5일후해고 부당노동행위","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53697","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로자피해자갈등","직장내괴롭힘여부별론","다른근로자인지","노조업무과정필연적접촉","업무상필요성인정","임금변동없음"],"legal_focus":["갈등분리필요성=업무상필요성인정","임금변동없음=TV정당"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["직장내괴롭힘여부별론+갈등있고타인인지+노조업무접촉필연=분리필요성=TV정당","갈등분리필요+임금변동없음=TV정당"],"exclude_for_queries":[],"summary_short":"갈등+다른 근로자 인지+노조 업무 필연적 접촉=분리 필요성=업무상필요성+임금 변동 없음=TV정당","holding_summary":"직장내괴롭힘 여부 별론으로 갈등 명백+조직 업무능률·원활한 운영 위한 분리 필요. 노조 업무 과정 필연적 접촉 차단 필요=업무상 필요성. 임금 변동 없음=생활상 불이익 없음=TV 정당.","retrieval_note":"직장내괴롭힘여부별론 갈등분리필요 노조업무필연적접촉 업무상필요성 임금변동없음 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53703","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer","demotion"],"fact_markers":["직제개편이사회승인없음","직제규정변경없음","마케팅팀장→대외협력팀원","관리수당감소"],"legal_focus":["이사회승인없음+직제규정변경없음=업무상필요성불충분","관리수당감소=생활상불이익","TV부당"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["직제개편이사회승인없음+직제규정변경없음=업무상필요성불충분=TV부당","마케팅팀장→대외협력팀원+관리수당감소=TV부당"],"exclude_for_queries":[],"summary_short":"직제개편 이사회 승인 없음+직제규정 변경 없음=업무상필요성 불충분+관리수당 감소=TV부당","holding_summary":"직제개편·인사발령에 필요한 이사회 승인+직제규정 변경 절차 미이행=업무상 필요성 불충분. 마케팅팀 팀장→대외협력팀 팀원=관리업무 수당 감소=생활상 불이익=TV 부당.","retrieval_note":"직제개편이사회승인없음 직제규정변경없음 업무상필요성불충분 관리수당감소 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53753","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["이사회의결조직개편","사내게시판사용자비판게시물","간부자질부족","급여직책변동없음","출퇴근증가감수범위"],"legal_focus":["이사회의결조직개편+간부자질부족=업무상필요성인정","급여직책변동없음+출퇴근증가감수=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["이사회의결조직개편+사내게시판비판게시물+간부자질부족=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"이사회 의결 조직개편+사내게시판 비판 게시물+간부 자질 부족=업무상필요성=TV정당","holding_summary":"이사회 의결 조직개편. 공개 사내게시판 사용자 비판 게시물 반복+간부 자질·소양 부족=정기 인사 발령 업무상 필요성 인정. 급여·직책 변동 없음+출퇴근 증가=감수 범위=TV 정당.","retrieval_note":"이사회의결조직개편 사내게시판비판게시물 간부자질부족 업무상필요성 급여직책변동없음 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53755","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["채용방식주체하자","정당해고사유아님","서면통지없음","내용절차하자","금전보상"],"legal_focus":["채용방식주체하자=정당해고사유아님","서면통지없음=절차하자=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["채용방식주체하자=정당해고사유아님+서면통지없음=내용절차하자=부당해고"],"exclude_for_queries":[],"summary_short":"채용방식·주체 하자=정당 해고 사유 아님+서면통지 없음=내용·절차 하자=부당해고","holding_summary":"채용방식·주체 하자=근로계약 취소 사유로 주장이나 정당한 해고 사유 해당 않음. 서면 통지 없음=절차 하자. 내용+절차 모두 하자=부당해고. 금전보상 수용.","retrieval_note":"채용방식주체하자 정당해고사유아님 서면통지없음 내용절차하자 부당해고 금전보상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53757","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["other","transfer"],"fact_markers":["대기발령=인사규정요건미해당","이사회전해제","전보=인사규정위반","업무상필요성없음","징계목적전보"],"legal_focus":["대기발령=인사규정요건미해당+이사회전해제=부당","전보=인사규정위반+업무상필요성없음+징계목적=TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["대기발령인사규정요건미해당+이사회전해제=부당+전보인사규정위반+징계목적=TV부당","대기발령부당+전보인사규정위반=TV부당"],"exclude_for_queries":[],"summary_short":"대기발령=인사규정 요건 미해당+이사회 전 해제=부당, 전보=인사규정 위반+징계목적=TV부당","holding_summary":"대기발령=인사규정상 \"징계에 부의한 때\" 해당 않음+사회통념상 합리성 없음+이사회 전 해제=부당. 전보=인사규정 위반+업무상 필요성 없음+징계 목적=TV 부당.","retrieval_note":"대기발령 인사규정요건미해당 이사회전해제 부당 전보 인사규정위반 징계목적 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53817","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약취업규칙전보조항","개원초기개선","초음파경험팀장경력","급여직급변동없음","거주지인근"],"legal_focus":["업무상필요성인정","생활상불이익없음","TV정당"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["개원초기개선+초음파경험팀장경력=업무상필요성인정+급여직급변동없음+거주지인근=TV정당","근로계약전보조항+초음파경험=인력배치요건=TV정당"],"exclude_for_queries":[],"summary_short":"개원 초기 개선+초음파 경험·팀장 경력=업무상필요성+급여직급 변동 없음+거주지 인근=TV정당","holding_summary":"근로계약·취업규칙 전보 가능 조항. 개원 초기 검진시스템 개선+전문인력 양성 필요. 초음파 경험+팀장 경력=인력배치 요건 부합. 급여·직급 변동 없음+거주지 오히려 가까워짐=TV 정당.","retrieval_note":"개원초기개선 초음파경험팀장경력 업무상필요성 급여직급변동없음 거주지인근 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53823","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],"fact_markers":["수습기간해당","취업규칙수습기간3개월","부적합해지가능","근무성적평가"],"legal_focus":["수습기간해당","근무성적평가기반본채용거부"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["수습기간=취업규칙부적합해지가능+근무성적평가=본채용거부"],"exclude_for_queries":[],"summary_short":"수습기간=취업규칙 3개월+부적합 해지 가능+근무성적 평가=본채용 거부","holding_summary":"근로계약서 수습기간 기재+취업규칙 제9조 3개월 수습기간+부적합 시 해지 가능+인사관리규정 제9조=시용 근로계약 해당. 근무성적 평가 기반 본채용 거부 정당성 검토.","retrieval_note":"수습기간 취업규칙3개월 부적합해지가능 근무성적평가 본채용거부","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53825","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["두학원=동일건물동일층","인사노무재무일괄관리","카드기혼용","홍보공동","동일사업장=5인이상"],"legal_focus":["두학원=동일사업장","5인이상=근기법적용"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["두학원동일건물동일층+인사노무일괄관리+카드기혼용=동일사업장=5인이상","별도사업장주장+실질동일운영=동일사업장인정=5인이상"],"exclude_for_queries":[],"summary_short":"두 학원=동일 건물·층+일괄 관리+카드기 혼용+공동 홍보=동일 사업장=5인 이상","holding_summary":"두 학원 동일 건물 동일 층+인사·노무·재무 일괄 관리+카드기 혼용+공동 홍보=외관상 하나의 학원=동일 사업장=5인 이상=근기법 적용.","retrieval_note":"두학원 동일건물동일층 인사노무일괄관리 카드기혼용 공동홍보 동일사업장 5인이상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53833","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["reprimand","transfer"],"fact_markers":["미개발업소소명불이행","면담거부","징계사유인정","불화인원충원요청","TV정당","배우자망막색소변성증","생활상불이익현저여부"],"legal_focus":["징계사유인정+양정적정","불화인원충원=TV정당","배우자장애=생활상불이익검토"],"industry_context":"sales","exclusion_flags":[],"include_for_queries":["미개발업소소명불이행+면담거부=징계사유인정+불화인원충원=TV정당","배우자망막색소변성증=생활상불이익검토"],"exclude_for_queries":[],"summary_short":"미개발업소 소명 불이행+면담 거부=징계 정당, 불화+인원충원=TV정당, 배우자 장애=생활상불이익 검토","holding_summary":"미개발업소 소명 불이행+면담 거부=징계사유 인정+양정 적정+절차 적법=징계 정당. 소속 센터장 불화+호남센터 인원충원 요청=업무상 필요성=TV 정당. 배우자 망막색소변성증=생활상 불이익 현저 여부 검토.","retrieval_note":"미개발업소소명불이행 면담거부 징계사유인정 불화인원충원 TV정당 배우자망막색소변성증 생활상불이익","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_53847","issue_type_primary":"redundancy","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["ABM업무수행장소무관","국내ABM사업부폐지","사업전체폐지아님","경영상이유해고","긴박한경영상필요성"],"legal_focus":["국내ABM사업부폐지=사업전체폐지아님=경영상이유해고","긴박한경영상필요성검토"],"industry_context":"it","exclusion_flags":[],"include_for_queries":["국내ABM사업부폐지=사업전체폐지아님=경영상해고+긴박성검토"],"exclude_for_queries":[],"summary_short":"국내 ABM 사업부 폐지=사업 전체 폐지 아님=경영상 해고+긴박한 필요성 검토","holding_summary":"ABM 업무 수행장소 중요 아님+국내·일본 구분 없음+취업규칙 해고 조항=경영상 이유 해고 해당. 국내 ABM 사업부 폐지=사업 축소=전체 폐지 아님. 긴박한 경영상 필요성 판단.","retrieval_note":"국내ABM사업부폐지 사업전체폐지아님 경영상해고 긴박한경영상필요성","confidence":"high","review_status":"approved","tag_version":"v3"})

output_path = r'C:\dev\labor-decisions-search\retagging\output\reviewed\transfer_batch_070_reviewed.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')
print(f'총 {len(records)}건 작성 완료')
