"""
transfer_batch_061 tagging script
Distribution: TV22(정당17/부당5) / procedure9 / disciplinary8 / no_dismissal3 / union_activity5 / redundancy1 / contract_expiry1 / discrimination1 = 50건
"""
import json, pathlib

OUTPUT = pathlib.Path("retagging/output/reviewed/transfer_batch_061_reviewed.jsonl")
OUTPUT.parent.mkdir(parents=True, exist_ok=True)

records = [

# ── procedure ──

{"case_id":"id_44895","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["다른사업장노무제공금지","취업규칙적용","사용자직접임금지급","기본급위주"],
"legal_focus":["근로자성판단","전속성","임금구조"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["다른사업장금지+취업규칙적용+직접임금+기본급위주=근로자성인정"],
"exclude_for_queries":[],
"summary_short":"타사업장 금지+취업규칙+직접임금+기본급 위주=근로자성 인정",
"holding_summary":"다른사업장노무제공금지+취업규칙적용+사용자직접임금지급+기본급위주=근기법상근로자성인정",
"retrieval_note":"batch_060 id_44855와 동일 패턴. 근로자성 판단 3요소(전속성+직접임금+기본급구조) 반복 확인",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44979","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["경영독립의견없음","대표이사지휘명령","연차휴가사용보고"],
"legal_focus":["근로자성판단","사용종속관계"],
"industry_context":"it","exclusion_flags":["procedure_dominant"],
"include_for_queries":["경영독립의견없음+대표이사지휘명령=근로자성인정"],
"exclude_for_queries":[],
"summary_short":"경영 독립 의견 없음+대표이사 지휘명령=근로자성 인정",
"holding_summary":"경영에독립적의견제시없음+대표이사수주계약따른개발자+연차휴가보고=사용종속관계=근로자성인정",
"retrieval_note":"개발자라도 수주 계약 따른 작업+연차 보고 의무=사용종속관계=근로자성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44989","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["용역계약서에기재","고정급여","출근부업무보고반복","장기간","전속성"],
"legal_focus":["근로자성판단","형식용역이나실질근로"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["용역계약서기재+고정급+출근부+장기간+전속성=근로자성인정"],
"exclude_for_queries":[],
"summary_short":"용역계약서이나 고정급+출근부+장기간+전속성=근로자성 인정",
"holding_summary":"용역계약서에기재+고정급여+출근부업무보고반복+장기간+고용전속성=근기법상근로자성인정",
"retrieval_note":"용역계약 형식이더라도 고정급+출근부+장기간+전속성 모두 충족=근로자성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44995","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전보취소","원직복직명령","임금상당액지급"],
"legal_focus":["구제이익소멸","복직명령","임금지급"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["전보취소원직복직+임금상당액지급=구제이익소멸"],
"exclude_for_queries":[],
"summary_short":"전보 취소+원직복직+임금상당액 지급=구제이익 소멸",
"holding_summary":"전보발령취소+원직복직명령+임금상당액지급=구제이익소멸",
"retrieval_note":"전보 취소+원직복직+임금상당액까지 지급된 경우 구제이익 완전 소멸",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45029","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["복무규정적용","4대보험가입","일정임금","시간장소지정"],
"legal_focus":["근로자성판단","당사자적격"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["복무규정+4대보험+일정임금+시간장소지정=근로자성인정=당사자적격"],
"exclude_for_queries":[],
"summary_short":"복무규정+4대보험+일정임금+시간장소 지정=근로자성 인정",
"holding_summary":"복무규정적용+4대보험가입+일정임금+시간장소지정=근기법상근로자=당사자적격인정",
"retrieval_note":"4대보험+복무규정+임금+시간장소 지정이 복합적으로 충족되면 근로자성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45187","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["손해배상청구신청","노동위구제대상아님"],
"legal_focus":["노동위원회구제범위","손해배상청구"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant","unrelated_to_dismissal"],
"include_for_queries":["인사발령관련손해배상청구=노동위구제대상아님=각하"],
"exclude_for_queries":[],
"summary_short":"인사발령 관련 손해배상청구=노동위원회 구제 대상 아님=각하",
"holding_summary":"인사발령전제손해배상청구=근로조건위반손해배상청구대상해당않음=노동위구제대상아님=각하",
"retrieval_note":"근로계약 후 상당 기간 근무 후 인사발령 관련 손해배상청구=노동위원회 구제 범위 밖",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45487","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity","union_activity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전보통지일=기산일","효력발생일=집행일","3개월경과","제척기간도과"],
"legal_focus":["제척기간기산일","전보통지일vs효력발생일"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["전보통지일=기산일(효력발생일집행일에불과)=제척기간도과각하"],
"exclude_for_queries":[],
"summary_short":"전보 통지일이 기산일(효력발생일은 집행일)=3개월 경과=제척기간 도과=각하",
"holding_summary":"전보통지일2021.11.12=기산일+전보효력일2022.1.1=집행일에불과=제척기간3개월도과=각하",
"retrieval_note":"전보 구제신청 제척기간 기산일=전보통지일(근로자 인지일). 효력발생일(시행일)은 집행일에 불과하여 기산일 아님",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45715","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["other"],
"fact_markers":["업무직일반직전환배제","근기법23조비해당"],
"legal_focus":["근기법23조구제신청대상","전직여부"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant","unrelated_to_dismissal"],
"include_for_queries":["업무직일반직전환배제=근기법23조열거사유비해당=구제신청각하"],
"exclude_for_queries":[],
"summary_short":"업무직→일반직 전환 배제=근기법 23조 열거사유 해당 않음=각하",
"holding_summary":"업무직근로자일반직전환배제=근기법23조1항해고휴직정직전직감봉그밖의징벌비해당=각하",
"retrieval_note":"근기법 23조 구제신청 대상: 전직, 감봉 등 열거된 사유만 해당. 일반직 전환 배제는 열거 사유에 포함 안 됨",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45729","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity","disciplinary_severity"],
"employment_stage":"regular","disposition_type":["transfer","pay_cut","demotion"],
"fact_markers":["전직취소","감봉강등취소","소급임금지급","구제이익소멸"],
"legal_focus":["구제이익소멸","취소+소급지급"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["전직감봉강등취소+소급임금지급=구제이익소멸"],
"exclude_for_queries":[],
"summary_short":"전직·감봉·강등 취소+소급 임금 지급=구제이익 소멸",
"holding_summary":"전직감봉강등취소+소급임금지급=구제이익소멸",
"retrieval_note":"복수의 불이익 처분(전직+감봉+강등)을 모두 취소하고 소급 임금까지 지급=구제이익 완전 소멸",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── transfer_validity ──

{"case_id":"id_44925","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["인사규정순환보직가능","공석사무국장직위","직장질서유지"],
"legal_focus":["인사규정순환보직","공석직위전보","업무상필요성"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["인사규정순환보직+공석사무국장전보+직장질서=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"인사규정 순환보직+공석 사무국장 전보+직장질서=TV 정당",
"holding_summary":"인사규정및근로계약순환보직가능+공석사무국장직위전보+직장질서유지근로자간인화=업무상필요성=TV정당",
"retrieval_note":"인사규정에 순환보직 가능 규정+공석 직위 충원=업무상 필요성 자동 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44955","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로계약장애인주간보호센터특정","다년간동일업무","원직배치어려움주장"],
"legal_focus":["근로계약근무부서특정","TV동의필요"],
"industry_context":"service","exclusion_flags":[],
"include_for_queries":["근로계약근무부서장애인주간보호센터특정+다년간동일업무=동의없이변경=TV부당"],
"exclude_for_queries":[],
"summary_short":"근로계약 근무부서 장애인주간보호센터로 한정+다년간 동일 업무=TV 부당",
"holding_summary":"근로계약서근무부서장애인주간보호센터한정+다년간동일업무=동의없는변경=TV부당",
"retrieval_note":"batch_058 id_42357, batch_059 id_43223에 이어 근로계약 근무부서 특정+다년간 동일 업무=TV 부당 법리 3회 누적",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44963","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["transfer","suspension"],
"fact_markers":["모바일팀폐지","디지털뉴스편집팀신설","직무변경(직종변경아님)","협의절차미적용"],
"legal_focus":["업무상필요성","직무변경vs직종변경","단협협의절차적용범위"],
"industry_context":"it","exclusion_flags":[],
"include_for_queries":["모바일팀폐지디지털뉴스팀신설=TV업무상필요성","직무변경=직종변경아님=단협협의절차불필요=TV정당"],
"exclude_for_queries":[],
"summary_short":"모바일팀 폐지+디지털뉴스팀 신설=TV 정당, 직무변경=직종변경 아님=협의 불필요",
"holding_summary":"모바일팀폐지디지털뉴스편집팀신설=업무상필요성+직위임금변동없음+직무변경=직종변경아님=단협35조3항협의절차미적용=TV정당",
"retrieval_note":"직종 변경이 아닌 직무 변경은 단체협약 협의절차 조항 적용 대상 아님. 팀 폐지에 따른 신설 팀 전보=업무상 필요성",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44967","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로계약서업무변경가능규정","코로나19이용객감소","공무직전환경영환경변화"],
"legal_focus":["업무상필요성","근로계약서규정"],
"industry_context":"service","exclusion_flags":[],
"include_for_queries":["근로계약서업무변경가능+코로나이용객감소+공무직전환=TV정당"],
"exclude_for_queries":[],
"summary_short":"근로계약서 업무변경 가능 규정+코로나 이용객 감소=TV 정당",
"holding_summary":"근로계약서무기계약직관리규정업무변경가능+코로나19이용객감소+공무직전환경영환경변화=TV정당",
"retrieval_note":"batch_060 id_44383과 동일 사실관계 유형(근로계약서 업무변경 가능+코로나 이용객 감소=TV 정당) 반복",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45043","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["실질조직개편없음","인원재배치수준","생활상불이익","협의미준수"],
"legal_focus":["업무상필요성","실질조직개편여부","생활상불이익"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["실질조직개편없음인원재배치수준+생활상불이익+협의미준수=TV부당"],
"exclude_for_queries":[],
"summary_short":"실질 조직개편 없음(인원재배치 수준)+생활상 불이익+협의 미준수=TV 부당",
"holding_summary":"조직도일부변경이나근본적조직개편없음+근로자업무능력주장사용자측증언다름+생활상불이익+협의미준수=TV부당",
"retrieval_note":"조직개편 주장이더라도 실질적 근본적 변화가 없으면 업무상 필요성 불인정. 생활상 불이익+협의 미준수로 TV 부당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45053","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전국체전인사요인","부서별근로조건유사","출퇴근거리업무강도차이없음"],
"legal_focus":["인사요인TV업무상필요성","생활상불이익"],
"industry_context":"public","exclusion_flags":[],
"include_for_queries":["전국체전인사요인=TV업무상필요성+근로조건유사=TV정당"],
"exclude_for_queries":[],
"summary_short":"전국체전 인사요인=업무상 필요성+부서별 근로조건 유사=TV 정당",
"holding_summary":"전국체전등인사요인=TV업무상필요성+부서별근로조건유사+출퇴근거리업무강도차이없음=TV정당",
"retrieval_note":"국내 스포츠 행사 등 인사요인에 의한 전보=업무상 필요성 인정. 부서별 유사 근로조건=생활상 불이익 없음",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45057","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["3년이상동일직무동일장소","정기전보대상","업무상필요성"],
"legal_focus":["정기전보업무상필요성","장기근무순환"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["3년이상동일직무장소=정기전보대상=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"3년 이상 동일 직무·장소=정기전보 대상=업무상 필요성=TV 정당",
"holding_summary":"인사발령기준안3년이상동일직무동일장소=2022년정기전보대상=업무상필요성=TV정당",
"retrieval_note":"3년 이상 동일 직무·장소 근무자를 정기전보 대상으로 규정+적용=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45145","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["2명업무→1명경영상이유","업무상필요성","생활상불이익없음"],
"legal_focus":["경영효율화TV업무상필요성"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["2명업무1명경영상이유=TV업무상필요성+생활상불이익없음=TV정당"],
"exclude_for_queries":[],
"summary_short":"2명 업무→1명으로 경영상 이유 인력 재배치=TV 정당",
"holding_summary":"2명근로자업무를경영상이유1명으로운영필요성+TV생활상불이익감수범위+협의미준수=당연무효아님=TV정당",
"retrieval_note":"경영상 이유로 인력을 줄이면서 남은 근로자의 부서 재배치=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45179","issue_type_primary":"redundancy","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["방송외주화","긴박성불충분","방송효율성전문성"],
"legal_focus":["정리해고긴박한경영상필요성","외주화"],
"industry_context":"it","exclusion_flags":[],
"include_for_queries":["방송외주화만으로긴박한경영상필요성불충분=정리해고부당"],
"exclude_for_queries":[],
"summary_short":"방송 외주화=긴박한 경영상 필요성 불충분=정리해고 부당",
"holding_summary":"방송효율성전문성향상위한외주화만으로=근기법24조1항긴박한경영상필요성인정어려움=정리해고부당",
"retrieval_note":"외주화(아웃소싱)만으로는 정리해고의 긴박한 경영상 필요성 불충분",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45241","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["소통불화","업무량감소","추가업무거부","협업피드백문제","생활상불이익없음"],
"legal_focus":["소통문제TV업무상필요성","업무량감소"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["소통불화+업무량감소+추가업무거부+협업문제=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"소통 불화+업무량 감소+추가업무 거부+협업 문제=업무상 필요성=TV 정당",
"holding_summary":"마케팅매니저소통불화+리콜사태업무감소+추가업무거부+협업커뮤니케이션피드백문제=업무상필요성+임금수당복리후생변동없음=생활상불이익없음=TV정당",
"retrieval_note":"소통 불화+업무량 감소+추가 업무 거부 등 복합 사유=업무상 필요성 인정. 처우 변동 없으면 생활상 불이익 없음",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45251","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["현장직안전위협행동","내근직전보","안전목적"],
"legal_focus":["안전목적TV업무상필요성"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["현장직안전위협행동=안전목적내근직전보=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"현장직 안전 위협 행동=안전 목적 내근직 전보=업무상 필요성=TV 정당",
"holding_summary":"근로자안전위협행동인정+안전최우선고려=현장직→내근직전보=안전목적업무상필요성=TV정당",
"retrieval_note":"안전 위협 행동을 한 현장직 근로자를 내근직으로 전보=안전 목적 업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45263","issue_type_primary":"disciplinary_severity","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["해고서면통지위반","금전보상","신뢰관계훼손"],
"legal_focus":["해고서면통지","금전보상"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["해고서면통지의무위반=절차부당해고+금전보상"],
"exclude_for_queries":[],
"summary_short":"서면통지 의무 위반=절차상 부당해고+금전보상",
"holding_summary":"해고서면통지의무위반=절차상하자=부당+신뢰관계훼손=금전보상",
"retrieval_note":"해고 서면통지 의무(근기법 27조) 위반=절차적 부당해고. 신뢰 훼손으로 금전보상",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45297","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["폐업진행중","관리직→생산직","신분사회적불이익인정","업무상필요성>불이익"],
"legal_focus":["폐업진행TV업무상필요성","사회적불이익vs업무상필요성"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["폐업진행중인사발령=업무상필요성+사회적불이익인정이나업무상필요성초과=TV정당"],
"exclude_for_queries":[],
"summary_short":"폐업 진행 중 인사발령=업무상 필요성+사회적 불이익 인정이나 필요성>불이익=TV 정당",
"holding_summary":"폐업진행=관리업무감소=업무상필요성+분쟁근로자→폐업수행효율적인원선택합리적이유+관리직→생산직사회적불이익인정이나업무상필요성이초과=TV정당",
"retrieval_note":"폐업 진행 중 TV는 업무상 필요성 충분. 관리직→생산직 사회적 불이익 있더라도 업무상 필요성이 더 큰 경우 TV 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45317","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["연2회정기전보","노조협의전보기준","4급이하5년이상"],
"legal_focus":["정기전보업무상필요성","노조협의"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["연2회정기전보+노조협의전보기준결정+5년이상=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"연 2회 정기전보+노조 협의로 전보기준 결정+5년 이상=TV 정당",
"holding_summary":"연2회정기전보+노조협의전보기준결정+전보관리규칙5년이상근무전보대상=업무상필요성=TV정당",
"retrieval_note":"노조와 협의로 정한 전보기준(5년 이상 근무자)에 따른 정기전보=업무상 필요성 당연 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45331","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["통상근무인력배치","생활상불이익없음","협의준수"],
"legal_focus":["전보3요소"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["통상근무인력배치+생활상불이익없음+협의준수=TV정당"],
"exclude_for_queries":[],
"summary_short":"통상 근무 인력 배치+생활상 불이익 없음+협의 준수=TV 정당",
"holding_summary":"통상적근무인력배치+생활상불이익없음+협의절차준수=TV정당",
"retrieval_note":"TV 3요소 기본 충족 사례",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45395","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["업무상필요성","근로계약부합","신의칙위반아님","생활상불이익없음"],
"legal_focus":["전보정당성","근로계약부합"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["업무상필요성+근로계약부합+신의칙위반않음+생활상불이익없음=TV정당"],
"exclude_for_queries":[],
"summary_short":"업무상 필요성+근로계약 부합+신의칙 위반 아님+생활상 불이익 없음=TV 정당",
"holding_summary":"TV업무상필요성인정+근로계약부합신의칙반하지않음+생활상불이익감수범위=TV정당",
"retrieval_note":"TV 정당성 판단에서 근로계약과의 부합성도 별도 검토 항목",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4541","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["소장직책부적절업무수행","조직인화저해","업무상필요성>생활상불이익"],
"legal_focus":["직무부적절TV업무상필요성","필요성vs불이익비교형량"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["소장직책부적절업무+조직인화저해=TV업무상필요성>생활상불이익=TV정당"],
"exclude_for_queries":[],
"summary_short":"소장 직책 부적절 업무+조직 인화 저해=업무상 필요성>생활상 불이익=TV 정당",
"holding_summary":"소장직책부적절업무수행+조직인화저해=업무상필요성인정+생활상불이익<업무상필요성=TV정당",
"retrieval_note":"직책 부적절 수행+조직 인화 저해=TV 업무상 필요성 인정. 필요성이 생활상 불이익보다 크면 TV 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45425","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["코로나업무량감소","미결률증가","근무분위기쇄신","손해보험교차점검"],
"legal_focus":["업무분위기쇄신TV업무상필요성","손해보험특성"],
"industry_context":"finance","exclusion_flags":[],
"include_for_queries":["코로나업무량감소+미결률증가+근무분위기쇄신+교차점검=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"코로나 업무량 감소+미결률 증가+근무분위기 쇄신+교차점검=TV 정당",
"holding_summary":"코로나19업무량감소+미결률증가+근무분위기쇄신필요+본지부인원과부족조절+손해보험교차점검=업무상필요성=TV정당",
"retrieval_note":"손해보험 업무 특성(미결사항 교차점검 필요)이 TV 업무상 필요성 판단에 반영",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45447","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],
"fact_markers":["시용계약명시","본채용거부합리성없음","사무국장지시방식차이","객관적증거없음"],
"legal_focus":["시용기간본채용거부합리성","보복성추정"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["시용계약본채용거부합리성없음=부당+금전보상"],
"exclude_for_queries":[],
"summary_short":"시용계약 본채용 거부 합리성 없음=부당+금전보상",
"holding_summary":"시용계약인정+사무국장지시방식차이있으나객관적증거없음+지시거부동료갈등확인불가=본채용거부합리성인정어려움=부당+금전보상",
"retrieval_note":"시용계약 본채용 거부의 합리성: 주관적 지시방식 차이만으로 불충분. 객관적 증거 필요",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45457","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["파견사유종료복귀필요","교대근무인력적정배치","통상근무자선정"],
"legal_focus":["파견복귀TV업무상필요성","교대근무배치"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["파견사유종료복귀+교대근무인력배치=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"파견 사유 종료에 따른 복귀+교대근무 인력 배치=TV 정당",
"holding_summary":"파견사유종료복귀필요+교대근무운영인력적정배치=업무상필요성=TV정당",
"retrieval_note":"파견 종료 후 원소속 복귀 전보=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45467","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["pay_cut","transfer","no_formal_disposition"],
"fact_markers":["휴대폰사용무단이탈불인정","상사무시욕설모욕인정","감봉3월양정과도","TV정당"],
"legal_focus":["징계사유개별심사","양정형평원칙","전보정당성"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["일부징계사유인정이나감봉3월양정과도형평위반=징계부당+TV정당"],
"exclude_for_queries":[],
"summary_short":"상사 욕설모욕=징계사유 인정이나 감봉 3월 양정 과도=형평 위반=부당, TV는 정당",
"holding_summary":"징계사유4가지중1가지인정이나감봉3월=실정법위반동료감봉3월비교형평위반=징계재량남용=부당+TV업무상필요성+생활상불이익감수=TV정당",
"retrieval_note":"징계 양정은 형평의 원칙 적용. 더 중한 위반 동료와 동일 감봉=형평 위반=양정 과도=부당. 동일 사건 TV는 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45473","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전보와징계처분별도판단","소속기관복귀","인사권재량"],
"legal_focus":["전보와징계독립성","소속기관복귀TV"],
"industry_context":"public","exclusion_flags":[],
"include_for_queries":["전보징계처분별도판단+소속기관복귀=인사재량=TV정당"],
"exclude_for_queries":[],
"summary_short":"전보와 징계처분은 별도 판단, 소속기관 복귀=인사권 재량=TV 정당",
"holding_summary":"전보와징계처분정당성별도판단+소속기관복귀인사권재량범위내=TV업무상필요성=TV정당",
"retrieval_note":"선행 징계 처분이 부당하더라도 전보의 정당성은 별도 판단. 소속기관 복귀는 인사권 재량 범위 내",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45493","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전보사유합리성결여","출퇴근시간증가","가족부양곤란","협의미준수"],
"legal_focus":["업무상필요성합리성","생활상불이익현저","협의절차"],
"industry_context":"finance","exclusion_flags":[],
"include_for_queries":["전보사유합리성결여+출퇴근증가+가족부양곤란=TV부당"],
"exclude_for_queries":[],
"summary_short":"전보 사유 합리성 결여+출퇴근 증가+가족 부양 곤란=TV 부당",
"holding_summary":"전보사유타당성합리성결여+출퇴근시간비용증가+가족부양고충가중+협의미준수=TV부당",
"retrieval_note":"TV 사유의 합리성 결여+원거리 전보의 생활상 불이익(출퇴근+가족부양) 복합=TV 부당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45521","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["광주손해사정→부산본사","직원갈등전보업무상필요성낮음","생활상불이익현저","가족부양고충"],
"legal_focus":["업무상필요성낮음","생활상불이익현저","협의미준수"],
"industry_context":"finance","exclusion_flags":[],
"include_for_queries":["광주지역손해사정→부산본사=업무상필요성낮음+원거리생활상불이익현저+협의미준수=TV부당"],
"exclude_for_queries":[],
"summary_short":"광주 손해사정→부산 본사=업무상 필요성 낮음+생활상 불이익 현저+협의 미준수=TV 부당",
"holding_summary":"광주손해사정조사직→부산본사근무지변경+직원갈등전보업무상필요성낮음+원거리근무생활상불이익현저+가족부양고충+협의미준수=TV부당",
"retrieval_note":"지역 이동 TV에서 업무상 필요성 낮음+원거리 생활상 불이익(가족 부양)+협의 불충분 3요소 모두 실패=TV 부당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45539","issue_type_primary":"union_activity","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전환배치거부부당노동행위주장","제척기간미도과","부당노동행위의사입증부족"],
"legal_focus":["부당노동행위","제척기간","전환배치거부"],
"industry_context":"transport","exclusion_flags":[],
"include_for_queries":["전환배치거부부당노동행위=제척기간미도과이나의사입증부족=불인정"],
"exclude_for_queries":[],
"summary_short":"전환배치 거부 부당노동행위=제척기간 미도과이나 의사 입증 부족=불인정",
"holding_summary":"용인노선지원근무+전환배치미실시=제척기간미도과=본안판단+부당노동행위의사객관적입증부족=불인정",
"retrieval_note":"부당노동행위 제척기간은 미도과이나 반조합적 의사 객관적 입증자료 부족=불인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4533","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"probation","disposition_type":["probation_termination"],
"fact_markers":["수습기간부적합","인사위원회결정","직권면직"],
"legal_focus":["수습기간직권면직","인사규정"],
"industry_context":"public","exclusion_flags":[],
"include_for_queries":["수습기간부적합인사위원회결정직권면직정당"],
"exclude_for_queries":[],
"summary_short":"수습기간 부적합 인사위원회 결정=직권면직 정당",
"holding_summary":"인사규정수습기간부적합직권면직가능+채용공고수습평가후적격자임용고지=인사위원회결정직권면직정당",
"retrieval_note":"수습기간 직권면직의 정당성: 인사규정 근거+채용 공고에 사전 고지+인사위원회 결정 절차 준수",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45569","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["리스차량명의변경승인","대표이사결정","법무담당자위법인지어려움","선량한관리자주의의무"],
"legal_focus":["징계사유입증","선량한관리자주의의무"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["대표이사결정리스차량승인=법무담당자위법인지어려움=징계사유불인정=징계부당"],
"exclude_for_queries":[],
"summary_short":"대표이사 결정 리스차량 승인=법무담당자 위법 인지 어려움=징계사유 불인정=부당",
"holding_summary":"리스차량명의변경및비용지급=대표이사결정+법무담당자단순결재대행+위법성인지어려움+주의의무이행확인=징계사유불인정=부당",
"retrieval_note":"대표이사가 결정한 사항을 법무담당자가 결재만 대행한 경우=위법성 인지 기대 어려움=징계사유 불인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45609","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["펌프장관리공백","부서간업무갈등","대체직원없음","직급직책유지"],
"legal_focus":["업무공백TV업무상필요성","생활상불이익"],
"industry_context":"service","exclusion_flags":[],
"include_for_queries":["펌프장관리공백+대체직원없음=시설관리TV업무상필요성+직급유지=TV정당"],
"exclude_for_queries":[],
"summary_short":"펌프장 관리 업무 공백+대체 직원 없음=TV 업무상 필요성+직급 유지=TV 정당",
"holding_summary":"펌프장관리퇴사후업무공백+부서간갈등+대체직원없는상황=외부시설관리가능근로자전보=업무상필요성+직급직책유지=TV정당",
"retrieval_note":"특정 업무 공백이 발생하고 대체 직원이 없는 경우 해당 업무 수행 가능한 근로자 전보=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45613","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],
"fact_markers":["시용계약3개월","본채용거부","무단결근","현장소장의혹제기보복추정"],
"legal_focus":["시용기간본채용거부합리성","보복성추정"],
"industry_context":"construction","exclusion_flags":[],
"include_for_queries":["시용계약본채용거부=현장소장의혹제기보복추정=합리적이유없음=부당"],
"exclude_for_queries":[],
"summary_short":"시용계약 본채용 거부=현장소장 의혹 제기 보복 추정=합리적 이유 없음=부당",
"holding_summary":"시용계약인정+무단결근취업규칙요건미충족+현장소장의혹제기→인사발령→인사위원회→무단결근종료=보복추정=본채용거부합리적이유없음=부당",
"retrieval_note":"시용 근로자가 문제를 제기한 다음 날 계약이 종료된 경우 보복적 본채용 거부 추정=합리적 이유 없음",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45629","issue_type_primary":"discrimination","issue_type_secondary":[],
"employment_stage":"fixed_term","disposition_type":["no_formal_disposition"],
"fact_markers":["기간제vs정규직","비교대상근로자인정","정액급식비시간외식대차별"],
"legal_focus":["기간제차별금지","비교대상근로자","차별금지영역"],
"industry_context":"public","exclusion_flags":[],
"include_for_queries":["기간제청소년지도사vs정규직=비교대상인정+정액급식비시간외식대차별인정"],
"exclude_for_queries":[],
"summary_short":"기간제 청소년지도사=정규직 비교대상 인정+식비류 차별 인정",
"holding_summary":"기간제청소년지도사=주된업무동일+대체가능성인정=정규직비교대상근로자+정액급식비시간외식대=차별금지영역해당=차별인정",
"retrieval_note":"기간제 근로자 비교대상 근로자 선정기준: 주된 업무 동일+업무 대체 가능성. 식비류(정액급식비, 식대)는 차별금지 영역",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45663","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["사직원제출이나자발적의사없음","연차휴가처리요구","퇴직금포기이유없음"],
"legal_focus":["사직서자발성","해고의사표시","서면통지위반"],
"industry_context":"service","exclusion_flags":["resignation_dispute"],
"include_for_queries":["연차처리요구후사직원제출=자발적의사없음=해고존재+서면통지위반=부당"],
"exclude_for_queries":[],
"summary_short":"연차처리 요구 후 사직원 제출=자발적 의사 없음=해고 존재+서면통지 위반=부당",
"holding_summary":"연차처리요구+사직원퇴직일단기+퇴직금포기이유없음=자발적사직의사없음=해고존재+서면통지위반=부당+금전보상",
"retrieval_note":"사직서가 있더라도 퇴직금 포기 이유 없음+연차처리 요구 맥락=자발적 사직 의사 부정=해고 존재",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45667","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["진단서만으로상차업무불가명백않음","발판제거작업난이도","생활상불이익현저"],
"legal_focus":["업무상필요성불충분","근로자능력검증"],
"industry_context":"transport","exclusion_flags":[],
"include_for_queries":["진단서만으로상차업무불가명백않음+발판제거작업난이도높지않음=TV부당"],
"exclude_for_queries":[],
"summary_short":"진단서만으로 상차 업무 불가 명백하지 않음+발판 제거 작업난이도 감당 가능=TV 부당",
"holding_summary":"진단서내용만으로상차업무계속수행불가명백않음+발판제거작업난이도감당불가수준아님=업무상필요성불충분=TV부당",
"retrieval_note":"TV의 업무상 필요성은 업무 수행 불가 여부를 객관적으로 입증해야 함. 진단서 하나만으로는 불충분",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45691","issue_type_primary":"contract_expiry","issue_type_secondary":[],
"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],
"fact_markers":["관행적촉탁직계약갱신","다수고령근로자재계약","갱신기대권인정","합리적이유없는갱신거절"],
"legal_focus":["갱신기대권","촉탁직계약","갱신거절합리성"],
"industry_context":"unknown","exclusion_flags":["renewal_expectation_dominant"],
"include_for_queries":["관행적촉탁직계약갱신+다수고령재계약=갱신기대권인정+객관적검증없는갱신거절=부당해고"],
"exclude_for_queries":[],
"summary_short":"관행적 촉탁직 갱신+다수 고령 재계약=갱신기대권 인정+합리적 이유 없는 거절=부당",
"holding_summary":"매년관행적촉탁직계약갱신+다수고령근로자재계약=갱신기대권인정+객관적검증없는갱신거절합리적이유없음=부당해고",
"retrieval_note":"관행적 매년 갱신+다수 고령자 재계약=갱신기대권 성립. 객관적 검증 없는 갱신 거절=합리적 이유 없음=부당해고",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45715","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["other"],
"fact_markers":["업무직일반직전환배제","근기법23조비해당","임금근로조건변동없음"],
"legal_focus":["근기법23조구제범위","전직열거사유"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant","unrelated_to_dismissal"],
"include_for_queries":["업무직일반직전환배제=근기법23조1항열거사유비해당=구제신청대상아님=각하"],
"exclude_for_queries":[],
"summary_short":"업무직→일반직 전환 배제=근기법 23조 열거사유 해당 않음=각하",
"holding_summary":"업무직일반직미전환=근기법23조1항해고휴직정직전직감봉징벌열거사유비해당=임금근로조건변동없음=구제신청대상아님=각하",
"retrieval_note":"일반직 전환 배제는 근기법 23조 1항의 열거 사유에 해당하지 않아 노동위원회 구제신청 대상 아님",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45729","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity","disciplinary_severity"],
"employment_stage":"regular","disposition_type":["transfer","pay_cut","demotion"],
"fact_markers":["전직취소","감봉강등취소","소급임금지급"],
"legal_focus":["구제이익소멸","취소및소급지급"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["전직감봉강등취소+소급임금지급=구제이익소멸"],
"exclude_for_queries":[],
"summary_short":"전직·감봉·강등 취소+소급 임금 지급=구제이익 소멸",
"holding_summary":"전직취소+감봉강등취소+소급임금지급=구제이익소멸",
"retrieval_note":"복수 불이익처분(전직+감봉+강등) 모두 취소+소급 임금 지급=구제이익 완전 소멸",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45733","issue_type_primary":"no_dismissal","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["no_formal_disposition"],
"fact_markers":["사직서자발적제출","강요증거불충분","구직활동중","퇴직일임의기재"],
"legal_focus":["사직서자발성","해고없음"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["사직서강요증거불충분+구직활동중=자발적사직=해고없음"],
"exclude_for_queries":[],
"summary_short":"사직서 강요 증거 불충분+구직활동 중=자발적 사직=해고 없음",
"holding_summary":"퇴직일조율소통2회+이사건근로자구직활동중언급+퇴직일임의기재+전직취업=강요에의한하자의사표시보기어려움=자발적사직=해고없음",
"retrieval_note":"퇴직일 조율 소통 2회+근로자의 구직 활동 병행+퇴직 후 즉시 전직=자발적 사직으로 판단. 강요 증거 부족=해고 없음",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45751","issue_type_primary":"union_activity","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["contract_termination","no_formal_disposition","transfer"],
"fact_markers":["시간적단절행위","계속행위아님","부분제척기간도과","나머지행위부당노동행위불인정"],
"legal_focus":["부당노동행위계속행위","제척기간","대기발령전보CCTV"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["시간적단절행위=계속행위아님=부분제척기간도과+나머지행위부당노동행위불인정"],
"exclude_for_queries":[],
"summary_short":"시간적 단절 행위=계속 행위 아님=부분 제척기간 도과+나머지 부당노동행위 불인정",
"holding_summary":"시간적단절행위간객관적관련성없음=계속행위아님=일부행위제척기간도과각하+기간제계약종료대기발령전보CCTV설치=부당노동행위의사입증불충분=불인정",
"retrieval_note":"부당노동행위 복수 행위의 제척기간: 시간적 단절+객관적 관련성 없으면 계속 행위 아님=개별 기산. 제척기간 내 행위도 실질 부당노동행위 입증 필요",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45753","issue_type_primary":"union_activity","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["행정기관점검결과","생활재활교사전체적용","노조활동인과관계없음"],
"legal_focus":["부당노동행위","행정기관점검결과","전체적용평등"],
"industry_context":"service","exclusion_flags":[],
"include_for_queries":["행정기관점검결과근무형태개선+전체근로자적용=노조활동인과관계없음=부당노동행위불인정"],
"exclude_for_queries":[],
"summary_short":"행정기관 점검 결과 근무형태 개선+전체 적용=노조 활동 인과관계 없음=부당노동행위 불인정",
"holding_summary":"행정기관지도점검결과근무형태개선불가피+생활재활교사전체대상+노조활동인과관계없음=부당노동행위불인정",
"retrieval_note":"행정기관 지도 결과에 따른 근무형태 변경+전체 근로자 동일 적용=특정 노조원 차별 없음=부당노동행위 불인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── no_dismissal ──

{"case_id":"id_44911","issue_type_primary":"no_dismissal","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["카카오톡퇴직의사진의아님","사회적약자","수동적대응"],
"legal_focus":["퇴직의사표시진의","사회적약자"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["카카오톡퇴직의사표시진의아님+사회적약자수동적대응=해고존재"],
"exclude_for_queries":[],
"summary_short":"카카오톡 퇴직 의사=진의 아님+사회적 약자=해고 존재",
"holding_summary":"카카오톡퇴직의사표시내용=진의아님사용자인지가능+사회적약자수동적대응=해고존재",
"retrieval_note":"SNS를 통한 퇴직 의사표시도 진의 아닌 경우 해고 인정. 사회적 약자로 수동적 대응한 경우 특히 진의 여부 면밀 검토",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── union_activity ──

{"case_id":"id_44991","issue_type_primary":"union_activity","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["suspension"],
"fact_markers":["휴업명령경영상필요성인정","대상자선정기준합리성불입증","노조협의불충분","부당노동행위의사불인정"],
"legal_focus":["휴업명령정당성","대상자선정기준","노조협의"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["휴업명령대상자선정기준합리성불입증+노조협의불충분=부당+부당노동행위불인정"],
"exclude_for_queries":[],
"summary_short":"휴업명령 대상자 선정기준 합리성 불입증+노조 협의 불충분=부당, 부당노동행위 불인정",
"holding_summary":"휴업명령경영상필요성인정+대상자선정기준합리성객관적불입증+9차례교섭중노조협의미확인=부당+반조합적의사입증없음=부당노동행위불인정",
"retrieval_note":"휴업명령 부당 이유: 경영상 필요성 있어도 대상자 선정기준 합리성 객관적 입증 필요+노조 협의 의무. 단 반조합적 의사 별도 입증 필요",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45027","issue_type_primary":"union_activity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["no_formal_disposition"],
"fact_markers":["고정배차조정","근무평가표노사협의","조합원점수낮음","반조합적의사불인정"],
"legal_focus":["불이익취급부당노동행위","주관적평가요소","반조합적의사입증"],
"industry_context":"transport","exclusion_flags":[],
"include_for_queries":["근무평가고정배차조정=노사협의기준적용+반조합적의사입증불충분=부당노동행위불인정"],
"exclude_for_queries":[],
"summary_short":"노사협의 근무평가 기준 적용 고정배차 조정=반조합적 의사 입증 불충분=부당노동행위 불인정",
"holding_summary":"노사협의정한근무평가표기준고정배차조정+조합원점수낮음인정이나반조합적의사객관적입증자료없음=불이익취급부당노동행위불인정",
"retrieval_note":"노사 합의 기준에 따른 근무평가 결과 차이만으로는 부당노동행위 의사 추단 불충분",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45201","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],
"fact_markers":["보육교사","업무태도불량원운영방해","징계사유인정","양정적정","절차적법"],
"legal_focus":["징계사유","양정재량권","징계절차"],
"industry_context":"education","exclusion_flags":[],
"include_for_queries":["보육교사징계사유인정+징계해고양정적정+절차적법=징계정당"],
"exclude_for_queries":[],
"summary_short":"보육교사 징계사유 인정+징계해고 양정 적정+절차 적법=정당",
"holding_summary":"보육교사업무방관업무태도불량원운영방해징계사유인정+직분고려양정재량남용아님+절차적법=징계정당",
"retrieval_note":"보육교사의 직분(유아보육 담당)을 고려한 징계해고 양정 판단",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_45205","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["suspension"],
"fact_markers":["직무수행불이행20일","2차서면경고","기업질서훼손","정직정당"],
"legal_focus":["징계사유","양정정당성","기업질서"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["직무수행불이행20일=징계사유+고직급+서면경고후재위반=정직정당"],
"exclude_for_queries":[],
"summary_short":"직무수행 불이행 20일+서면경고 후 재위반+고직급=정직 정당",
"holding_summary":"직무수행불이행=근로제공거부=징계사유+높은직급+2차서면경고후20일근로거부=기업질서심각훼손=정직양정재량범위내=정당",
"retrieval_note":"직위가 높은 근로자가 반복 경고에도 장기간(20일) 근로 거부=기업질서 심각 훼손=정직 양정 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

]

with open(OUTPUT, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Written {len(records)} records")
