"""
write_batch047.py — transfer_batch_047 tagging
Distribution: TV13, procedure13, no_dismissal7, disciplinary8, redundancy4, contract_expiry3, union_activity2
"""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = [
{
  "case_id": "id_405791",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["demotion"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range", "relief_interest_exists"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["보직해임구제이익있음+업무상필요성O+불이익통상범위=정당"],
  "exclude_for_queries": [],
  "summary_short": "보직해임 구제이익+TV 정당",
  "holding_summary": "보직해임 구제이익 있음+업무상 필요성 인정+불이익 통상 감수 범위=정당",
  "retrieval_note": "보직해임 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40581",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["relief_interest_extinguished", "business_closed"],
  "legal_focus": ["relief_interest", "reinstatement_impossibility"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["사업장폐업=원직복직불가=구제이익없음"],
  "exclude_for_queries": [],
  "summary_short": "사업장 폐업=원직복직 불가=구제이익 없음",
  "holding_summary": "사용자 폐업=복귀 사업장 없음=원직복직 불가능=구제이익 없음=각하",
  "retrieval_note": "폐업 후 원직복직 불가=구제이익소멸 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405831",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성O+불이익통상범위=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성+불이익 통상 범위=정당",
  "holding_summary": "전보 업무상 필요성 인정+생활상 불이익 통상 감수 범위=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405867",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+서면통지 없음=부당",
  "holding_summary": "해고 존재+서면통지 절차 미준수=부당해고",
  "retrieval_note": "서면통지결여 부당해고 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405869",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["urgent_necessity_insufficient", "dismissal_avoidance_insufficient", "selection_criteria_unjust", "consultation_insufficient"],
  "legal_focus": ["managerial_dismissal_requirements"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영상긴박한필요없음+절차미충족=부당정리해고"],
  "exclude_for_queries": [],
  "summary_short": "긴박한 필요 없음+절차 미충족=부당 정리해고",
  "holding_summary": "긴박한 경영상 필요 인정 어려움+해고회피노력·합리적선정·협의 미충족=부당",
  "retrieval_note": "경영상해고 1+3요건 미충족 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405885",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["worker_status_confirmed", "dismissal_exists", "no_written_notice", "unilateral_termination"],
  "legal_focus": ["written_notice_requirement", "worker_status"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로자성인정+일방적종료=해고+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "근로자성+일방적 종료=해고+서면통지 없음=부당",
  "holding_summary": "근기법상 근로자+사용자 일방적 의사로 종료=해고+서면통지 의무 위반=부당해고",
  "retrieval_note": "근로자성+일방적종료=해고+서면통지결여 복합 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405913",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["no_formal_disposition"],
  "fact_markers": ["relief_interest_extinguished", "resignation_during_relief_proceedings"],
  "legal_focus": ["relief_interest"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["구제신청중사직=근로관계종료=구제이익소멸"],
  "exclude_for_queries": [],
  "summary_short": "구제신청 중 사직=구제이익 소멸",
  "holding_summary": "구제신청 계류 중 사직서 제출→근로관계 종료=구제이익 소멸",
  "retrieval_note": "구제신청 중 사직=구제이익 소멸 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405927",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["dismissal", "transfer"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed", "business_necessity_recognized"],
  "legal_focus": ["disciplinary_validity", "transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계정당+전보정당"],
  "exclude_for_queries": [],
  "summary_short": "징계·전보 모두 정당",
  "holding_summary": "징계와 전보 모두 정당",
  "retrieval_note": "징계+TV 정당 병합 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405931",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["relief_interest_extinguished", "reinstatement_ordered", "back_pay_paid"],
  "legal_focus": ["relief_interest", "monetary_compensation"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["복직명령+임금상당액지급=금전보상구제이익없음"],
  "exclude_for_queries": [],
  "summary_short": "복직+임금 지급=금전보상 구제이익 없음",
  "holding_summary": "원직복직 명령+해고기간 임금상당액 지급=금전보상 구제이익 소멸",
  "retrieval_note": "원직복직+임금지급 후 금전보상 불가 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405935",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["demotion"],
  "fact_markers": ["disciplinary_grounds_found", "procedure_followed", "excessive_sanction"],
  "legal_focus": ["proportionality_review"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계사유일부인정+절차적법+양정과다=부당"],
  "exclude_for_queries": [],
  "summary_short": "징계사유 일부 인정+절차 적법+양정 과다=부당",
  "holding_summary": "징계사유 일부 인정+절차 적법+인정 비위 대비 양정 과도=부당",
  "retrieval_note": "양정 과다 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405973",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["five_or_more_workers_confirmed", "no_written_notice"],
  "legal_focus": ["written_notice_requirement", "worker_count_threshold"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["상시5인이상+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "상시 5인 이상+서면통지 없음=부당",
  "holding_summary": "상시근로자 5인 이상+서면통지 의무 위반=부당해고",
  "retrieval_note": "5인 이상+서면통지결여 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406005",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["redundancy_requirements_met", "consultation_defect_insufficient_alone"],
  "legal_focus": ["managerial_dismissal_requirements", "consultation_defect_effect"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로자대표협의절차흠결만으로경영상해고무효아님=정당", "협의절차흠결=당연무효아님"],
  "exclude_for_queries": [],
  "summary_short": "근로자대표 협의 흠결만으로 경영상 해고 무효 아님=정당",
  "holding_summary": "근로자대표 협의절차 흠결 있으나 이것만으로 경영상 해고 무효라고 볼 수 없어=정당",
  "retrieval_note": "협의절차 흠결만으로 경영상 해고 당연무효 아님 — 다른 요건 충족 시. batch_045 id_405197(절차미충족=부당)과 비교",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406013",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "renewal_stage",
  "disposition_type": ["nonrenewal"],
  "fact_markers": ["renewal_expectation_recognized", "rational_reason_for_refusal_found"],
  "legal_focus": ["renewal_expectation_right"],
  "industry_context": "unknown",
  "exclusion_flags": ["renewal_expectation_dominant"],
  "include_for_queries": ["갱신기대권인정이나갱신거절합리적이유있음=부당아님"],
  "exclude_for_queries": [],
  "summary_short": "갱신기대권 인정이나 합리적 이유 있어 갱신거절 정당",
  "holding_summary": "갱신기대권 인정되나 갱신거절에 합리적 이유 있음=부당 아님",
  "retrieval_note": "갱신기대권O이나 합리적 이유있어 거절 정당 패턴 — 기대권 인정=자동 부당 아님",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406019",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["적정인력운영=업무상필요성O+불이익통상범위=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "적정인력 운영=업무상 필요성+불이익 통상 범위=정당",
  "holding_summary": "적정 인력 운영을 위한 전보=업무상 필요성 인정+불이익 통상 범위=정당",
  "retrieval_note": "인력운영 목적 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406021",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "pre_hire",
  "disposition_type": ["dismissal"],
  "fact_markers": ["job_offer_accepted", "no_written_notice", "cancellation_constitutes_dismissal"],
  "legal_focus": ["employment_offer_cancellation", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["채용내정취소=근기법상해고+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "채용내정 취소=해고+서면통지 없음=부당",
  "holding_summary": "채용내정 취소=근기법상 해고+사유·시기 서면통지 없음=부당해고",
  "retrieval_note": "채용내정취소=근기법상 해고+서면통지결여 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406045",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전직업무상필요성>불이익=정당인사재량"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성>불이익=인사 재량 일탈 없음=정당",
  "holding_summary": "전직 업무상 필요성에 비해 생활상 불이익 크지 않음=인사 재량권 일탈·남용 아님=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406093",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["demotion", "transfer"],
  "fact_markers": ["demotion_disguised_as_reassignment", "supreme_court_ruling_violated", "collective_agreement_violated", "ulp_recognized"],
  "legal_focus": ["unfair_labor_practice", "demotion_disguise", "collective_agreement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무분장형식빌린강등=대법원판결단협위반=효력없음+ULP인정"],
  "exclude_for_queries": [],
  "summary_short": "업무분장 형식 강등=대법원판결·단협 위반+ULP 인정",
  "holding_summary": "업무분장 형식의 강등=구제신청 대상+대법원 판결·단협 위반=효력없음+조합원 불이익취급 ULP 인정; 지배·개입 ULP는 해당 아님",
  "retrieval_note": "업무분장 형식 실질 강등+대법원판결위반+ULP 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406109",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["suspension", "transfer"],
  "fact_markers": ["disciplinary_grounds_found", "procedure_followed", "excessive_sanction", "business_necessity_recognized"],
  "legal_focus": ["proportionality_review", "transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계=양정과다=부당+인사발령=TV정당(부분인용)"],
  "exclude_for_queries": [],
  "summary_short": "징계 양정 과다=부당, 인사발령 TV 정당(부분인용)",
  "holding_summary": "징계=사유 인정+절차 하자 없으나 양정 과다=부당; 인사발령=업무상 필요성 인정+불이익 크지 않음=정당",
  "retrieval_note": "징계 부당+TV 정당 부분인용 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40613",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["ulp_allegation_rejected", "union_membership_not_confirmed"],
  "legal_focus": ["unfair_labor_practice"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["조합원아님+노조관련없음=ULP아님"],
  "exclude_for_queries": [],
  "summary_short": "노조 미가입+노조 관련성 없음=ULP 아님",
  "holding_summary": "근로자 노동조합 미가입+노조와 관련 없음=불이익취급 ULP 불성립",
  "retrieval_note": "ULP 주장 기각 — 조합원 미가입 사실 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406203",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range", "consultation_held"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성O+생활상불이익과도하지않음+협의O=정당"],
  "exclude_for_queries": [],
  "summary_short": "TV 3요건 충족=정당",
  "holding_summary": "업무상 필요성 인정+생활상 불이익 과도하지 않음+협의 거침=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406213",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["disciplinary_grounds_rejected", "insufficient_evidence"],
  "legal_focus": ["disciplinary_grounds_validity"],
  "industry_context": "healthcare",
  "exclusion_flags": [],
  "include_for_queries": ["무면허진료횡령환자민원=징계사유불인정=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "무면허진료·횡령·민원 등 징계사유 불인정=부당해고",
  "holding_summary": "무면허진료·자금횡령·환자민원유발=비위 없거나 구체적 입증 없음=징계사유 불인정=부당해고",
  "retrieval_note": "의료기관 징계사유(무면허진료, 횡령, 민원) 불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406217",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+서면통지없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+서면통지 없음=부당",
  "holding_summary": "해고 존재+서면통지 의무 위반=부당해고",
  "retrieval_note": "서면통지결여 부당해고 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406223",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "no_living_disadvantage", "consultation_not_required_for_validity"],
  "legal_focus": ["transfer_3prong_test", "consultation_requirement_source"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전직업무상필요성O+불이익크지않음+협의없어도당연무효아님=정당"],
  "exclude_for_queries": [],
  "summary_short": "TV 정당+협의 없어도 인사발령 당연무효 아님",
  "holding_summary": "전직 업무상 필요성O+불이익 크지 않음+협의절차 미이행만으로 인사발령 당연무효 아님=정당",
  "retrieval_note": "협의절차 미이행=당연무효 아님 패턴. id_405027, id_40545 계열",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406233",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range", "procedure_followed", "standby_order_valid"],
  "legal_focus": ["transfer_3prong_test", "standby_order_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["대기발령업무상필요성O+불이익크지않음+절차정상=정당"],
  "exclude_for_queries": [],
  "summary_short": "대기발령 업무상 필요성+불이익 크지 않음+절차 정상=정당",
  "holding_summary": "대기발령 업무상 필요성 인정+불이익 크지 않음+절차 하자 없음=정당",
  "retrieval_note": "대기발령 TV 3요건 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406243",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["demotion", "transfer"],
  "fact_markers": ["business_necessity_recognized", "demotion_not_disciplinary", "personnel_authority_not_abused"],
  "legal_focus": ["transfer_3prong_test", "demotion_as_personnel_action"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사발령TV정당+강등=징계아님+인사권내=정당"],
  "exclude_for_queries": [],
  "summary_short": "TV 정당+강등=징계 아님+인사권 내=정당",
  "holding_summary": "인사발령 TV 정당+강등=징계 해당 아님+전직명령권 범위 내=정당",
  "retrieval_note": "TV+강등=징계아님 병합 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406245",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "renewal_stage",
  "disposition_type": ["nonrenewal"],
  "fact_markers": ["renewal_expectation_recognized", "no_rational_reason_for_refusal"],
  "legal_focus": ["renewal_expectation_right"],
  "industry_context": "unknown",
  "exclusion_flags": ["renewal_expectation_dominant"],
  "include_for_queries": ["갱신기대권인정+합리적이유없는거절=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "갱신기대권+합리적 이유 없는 거절=부당",
  "holding_summary": "갱신기대권 인정+갱신거절 합리적 이유 없음=부당해고",
  "retrieval_note": "갱신기대권 인정 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406249",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["indefinite_term_worker_confirmed", "no_written_notice"],
  "legal_focus": ["written_notice_requirement", "contract_classification"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["기간정함없는근로자+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "기간정함없는 근로자+서면통지 없음=부당",
  "holding_summary": "기간의 정함이 없는 근로자+서면통지 의무 위반=부당해고",
  "retrieval_note": "근로계약 분류(기간정함없음)+서면통지결여 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406263",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+서면통지없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+서면통지 없음=부당",
  "holding_summary": "해고 존재+서면통지 절차 미준수=부당해고",
  "retrieval_note": "서면통지결여 부당해고 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406267",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "renewal_stage",
  "disposition_type": ["nonrenewal"],
  "fact_markers": ["renewal_expectation_recognized", "no_rational_reason_for_refusal"],
  "legal_focus": ["renewal_expectation_right"],
  "industry_context": "unknown",
  "exclusion_flags": ["renewal_expectation_dominant"],
  "include_for_queries": ["갱신기대권+합리적이유없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "갱신기대권+합리적 이유 없음=부당",
  "holding_summary": "갱신기대권 인정+갱신거절 합리적 이유 없음=부당",
  "retrieval_note": "갱신기대권 인정 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406293",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_dismissal_grounds", "procedure_violated"],
  "legal_focus": ["dismissal_grounds", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+사유없음+절차부적법=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+사유없음+절차 부적법=부당",
  "holding_summary": "해고 존재+사유·절차 적법하지 않음=부당해고",
  "retrieval_note": "사유+절차 이중 위반 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406321",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["five_or_fewer_workers", "labor_act_inapplicable"],
  "legal_focus": ["worker_count_threshold", "statute_applicability"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["상시5인미만=근기법부당해고규정미적용=각하"],
  "exclude_for_queries": [],
  "summary_short": "상시 5인 미만=부당해고 규정 미적용=각하",
  "holding_summary": "상시근로자 5인 미만=부당해고 관련 규정 미적용 사업장=각하",
  "retrieval_note": "5인 미만 사업장 각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406335",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["no_business_necessity", "insufficient_consultation"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성없음+협의불충분=부당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성 없음+협의 불충분=부당",
  "holding_summary": "업무상 필요성 없음+신의칙상 협의절차 불충분=부당 전보",
  "retrieval_note": "TV 1+3요건 불충족 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406367",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["redundancy_requirements_met"],
  "legal_focus": ["managerial_dismissal_requirements"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영상해고요건충족=정당정리해고"],
  "exclude_for_queries": [],
  "summary_short": "경영상 해고 요건 충족=정당",
  "holding_summary": "긴박한 경영상 필요 등 근기법 제24조 요건 갖춰=정당 경영상 해고",
  "retrieval_note": "경영상해고 요건 충족 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406371",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["disciplinary_dismissal"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed", "long_term_unauthorized_absence"],
  "legal_focus": ["disciplinary_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["장기무단결근징계사유O+양정적정+절차O=해고정당"],
  "exclude_for_queries": [],
  "summary_short": "장기 무단결근=징계사유+양정 적정+절차 정당",
  "holding_summary": "장기간 무단결근=징계사유 인정+양정 적정+절차 하자 없음=정당 해고",
  "retrieval_note": "장기무단결근 징계해고 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406415",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "pre_hire",
  "disposition_type": ["dismissal"],
  "fact_markers": ["job_offer_accepted", "no_written_notice"],
  "legal_focus": ["employment_offer_cancellation", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["채용내정취소존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "채용내정 취소+서면통지 없음=부당",
  "holding_summary": "채용내정 취소 존재+사유·시기 서면통지 없음=부당해고",
  "retrieval_note": "채용내정취소+서면통지결여 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406421",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": ["union_activity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "ulp_allegation_rejected"],
  "legal_focus": ["transfer_3prong_test", "unfair_labor_practice"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["제강공장연주반인사발령정당+ULP아님"],
  "exclude_for_queries": [],
  "summary_short": "인사발령 정당+노조활동 이유 ULP 아님",
  "holding_summary": "인사발령 정당+노동조합 활동을 이유로 한 불이익취급 ULP 해당 아님",
  "retrieval_note": "TV 정당+ULP 기각 병합 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40643",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["health_based_dismissal_valid", "long_term_sick_leave", "medical_certification_limits_return"],
  "legal_focus": ["dismissal_grounds", "inability_to_work"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["장기병가+의사소견업무복귀제한=해고정당"],
  "exclude_for_queries": [],
  "summary_short": "장기 병가+의사소견 업무복귀 제한=해고 정당",
  "holding_summary": "장기 병가에도 건강 미회복+의사소견서상 업무복귀 제한=해고 정당",
  "retrieval_note": "건강상 업무불능=해고 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40645",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": ["union_activity"],
  "employment_stage": "regular",
  "disposition_type": ["demotion", "transfer"],
  "fact_markers": ["business_necessity_recognized", "selection_criteria_rational", "living_disadvantage_within_normal_range", "ulp_allegation_rejected"],
  "legal_focus": ["transfer_3prong_test", "unfair_labor_practice"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["보직해제+전보=업무상필요성O+선정합리성O+불이익수인범위=정당+ULP아님"],
  "exclude_for_queries": [],
  "summary_short": "보직해제+전보 정당+ULP 아님",
  "holding_summary": "업무상 필요성·선정합리성 인정+불이익 수인 범위=보직해제·전보 정당+ULP 아님",
  "retrieval_note": "TV+ULP 병합 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406471",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["relief_interest_extinguished", "transfer_cancelled_reinstatement"],
  "legal_focus": ["relief_interest"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["전보발령취소+복직=구제이익없음"],
  "exclude_for_queries": [],
  "summary_short": "전보 취소+복직=구제이익 없음",
  "holding_summary": "사용자 전보 발령 취소→복직=구제이익 없음",
  "retrieval_note": "전보 취소 복직=구제이익 소멸 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406525",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "unknown",
  "disposition_type": ["no_formal_disposition"],
  "fact_markers": ["worker_status_rejected"],
  "legal_focus": ["worker_status"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근기법상근로자아님=각하"],
  "exclude_for_queries": [],
  "summary_short": "근기법상 근로자 해당 안됨=각하",
  "holding_summary": "근기법상 근로자에 해당하지 않음=각하",
  "retrieval_note": "근로자성 부정 각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406535",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["no_business_necessity", "living_disadvantage_significant", "no_consultation", "occupational_change"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성없음+직종변경불이익크+협의불충분=부당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성 없음+직종변경 불이익+협의 불충분=부당",
  "holding_summary": "업무상 필요성 없음+직종변경 생활상 불이익 크고+사전협의 불충분=부당",
  "retrieval_note": "TV 3요건 모두 불충족 + 직종변경 불이익 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406539",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "pre_hire",
  "disposition_type": ["dismissal"],
  "fact_markers": ["job_offer_accepted", "no_written_notice"],
  "legal_focus": ["employment_offer_cancellation", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["채용내정성립+서면통지없이취소=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "채용내정 성립+서면통지 없이 취소=부당",
  "holding_summary": "채용내정 성립+사유·시기 서면통지 없이 취소=부당해고",
  "retrieval_note": "채용내정취소+서면통지결여 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406587",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성O+불이익통상범위=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성+불이익 통상 범위=정당",
  "holding_summary": "업무상 필요성 인정+생활상 불이익 통상 감수 범위=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406595",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["filing_period_expired"],
  "legal_focus": ["statute_of_limitations"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": [],
  "exclude_for_queries": [],
  "summary_short": "전보일 기준 3개월 제척기간 도과=각하",
  "holding_summary": "전보일로부터 3개월 제척기간 도과=각하",
  "retrieval_note": "제척기간 도과 각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406625",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["redundancy_requirements_unmet"],
  "legal_focus": ["managerial_dismissal_requirements"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영상해고정당성없음=부당해고+금전보상"],
  "exclude_for_queries": [],
  "summary_short": "경영상 해고 정당성 없음=부당+금전보상",
  "holding_summary": "경영상 해고 정당성 없음=부당해고, 금전보상명령 수용",
  "retrieval_note": "경영상해고 요건 미충족 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406637",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+서면통지 없음=부당",
  "holding_summary": "해고 존재+사유·시기 서면통지 없음=부당해고",
  "retrieval_note": "서면통지결여 부당해고 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406653",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "probation",
  "disposition_type": ["disciplinary_dismissal"],
  "fact_markers": ["disciplinary_grounds_partially_rejected", "excessive_sanction"],
  "legal_focus": ["disciplinary_grounds_validity", "proportionality_review"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계사유일부부존재+인정사유대비양정과도=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "징계사유 일부 부존재+인정 사유 대비 양정 과도=부당",
  "holding_summary": "징계사유 일부 부존재+인정 사유 기준으로도 해고 양정 과도=부당",
  "retrieval_note": "징계사유 일부 부존재+양정과다 이중 하자 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406703",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["disciplinary_grounds_found", "excessive_sanction"],
  "legal_focus": ["proportionality_review"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계사유인정이나정직=목적대비양정과다=부당정직"],
  "exclude_for_queries": [],
  "summary_short": "징계사유 인정이나 정직=목적 대비 양정 과다=부당",
  "holding_summary": "물품 무단매각 승인·허위 임차계약 징계사유 인정+정직=달성 목적 대비 양정 과다=부당정직",
  "retrieval_note": "징계사유O이나 목적 대비 양정과다 부당정직 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40671",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["union_activity"],
  "employment_stage": "regular",
  "disposition_type": ["suspension", "transfer"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed", "ulp_allegation_rejected", "re_disciplinary_valid"],
  "legal_focus": ["disciplinary_validity", "unfair_labor_practice", "re_discipline"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["정직+인사발령+재징계=모두정당+배차등지배개입ULP아님"],
  "exclude_for_queries": [],
  "summary_short": "정직·인사발령·재징계 모두 정당+배차 등 ULP 아님",
  "holding_summary": "정직·예비기사 인사발령·재징계=모두 정당; 배차·근로시간면제자 지정=지배·개입 ULP 아님",
  "retrieval_note": "징계+인사발령+재징계 모두 정당+ULP 기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406717",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "fixed_term",
  "disposition_type": ["dismissal"],
  "fact_markers": ["coerced_resignation_as_dismissal", "no_written_notice", "monetary_compensation_ordered"],
  "legal_focus": ["dismissal_existence", "written_notice_requirement", "coerced_resignation"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["사용자강요압박퇴직원=사실상해고+서면통지없음=부당해고", "강요된사직=해고"],
  "exclude_for_queries": [],
  "summary_short": "강요·압박으로 제출된 퇴직원=사실상 해고+서면통지 없음=부당",
  "holding_summary": "퇴직원이 사용자 강요·압박에 의한 것=사실상 해고+서면통지 의무 미이행=부당; 기간 만료=금전보상명령",
  "retrieval_note": "강요된 사직=사실상 해고+서면통지결여+기간만료=금전보상 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
}
]

out_path = "retagging/output/reviewed/transfer_batch_047_reviewed.jsonl"
with open(out_path, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print(f"Written {len(records)} records")
