import json, pathlib, sys
sys.stdout.reconfigure(encoding='utf-8')

OUT = pathlib.Path("retagging/output/reviewed/transfer_batch_054_reviewed.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)

records = [

# ── TV 부당 (10건) ──────────────────────────────────────────────────

{"case_id":"id_411747","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["발령부서미설치=업무상필요성없음","재심심문회의시까지부서미존재","근로자기존업무존재"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["전보발령부서미설치=업무상필요성없음=TV부당"],"exclude_for_queries":[],"summary_short":"발령 부서가 심문회의 시까지 설치되지 않음+기존 업무 존재=업무상 필요성 없음=TV 부당","holding_summary":"인사발령 부서가 재심 심문회의 시까지도 실제 설치되지 않았을 뿐만 아니라 언제 설치될지 불명확하고, 근로자가 담당하고 있는 인터넷 마케팅 업무가 현재 근무하는 곳에 존재하므로 업무상 필요성을 인정하기 어려워 TV 부당","retrieval_note":"TV 부당=부서미설치 패턴","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411791","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성객관적구체적증거부족","생활상불이익현저"],"legal_focus":["TV3요건_업무상필요성","TV3요건_생활상불이익"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["업무상필요성객관적증거부족+생활상불이익현저=TV부당","TV3요건2개불충족=TV부당"],"exclude_for_queries":[],"summary_short":"업무상 필요성 객관적·구체적 증거 부족+생활상 불이익 현저=TV 부당","holding_summary":"사용자의 업무와 관련하여 전보의 필요성이 존재한다고 단정할 수 있는 객관적·구체적 증거가 부족하고, 전보에 따른 근로자의 생활상 불이익이 현저하여 통상적으로 감수할 수 있는 정도를 벗어나므로 TV 부당","retrieval_note":"TV 3요건 중 2개 불충족 패턴","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411845","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["동료충돌+고객불편이유주장이나징계사유부존재","업무상필요성부족","협의없음"],"legal_focus":["TV3요건_업무상필요성","TV3요건_협의절차"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["징계사유부존재=TV사유도불충분+협의없음=TV부당"],"exclude_for_queries":[],"summary_short":"사용자 주장 TV 사유(동료충돌·고객불편) 객관적 근거 부족+협의 없음=TV 부당","holding_summary":"사용자는 전보 필요성으로 동료 직원들과의 충돌, 고객사 불편 사항 접수 및 인사규정상 기구 개편을 주장하나, 징계 절차 없이 이루어진 점 등 업무상 필요성에 대한 객관적 근거가 부족하고 협의도 없어 TV 부당","retrieval_note":"TV 사유 주장 있으나 객관적 근거 부족+협의 없음","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411949","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["경영악화인정이나이자비용증가=물류직접하기비용절감효과불충분","업무상필요성불충분"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["경영악화인정이나업무상필요성(물류직접하기)불충분=TV부당"],"exclude_for_queries":[],"summary_short":"경영악화 인정이나 이자비용 증가가 주원인=물류 직접 전환 업무상 필요성 불충분=TV 부당","holding_summary":"사용자가 경영악화 상황을 겪고 있다는 사실은 인정되나, 경영악화의 주된 이유가 이자비용 증가에 기인한 것으로 보이고 물류 업무 직접하기가 비용 절감에 일부 효과가 있다 하더라도 그로 인하여 발생하는 업무상 필요성이 충분하지 않아 TV 부당","retrieval_note":"경영악화 인정에도 업무상 필요성 불충분 TV 부당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411991","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["채용당시승강기보수기능사자격증직무한정","체험관시설관리=기계기능사전기기능사요구=다른직무","근로계약직무한정TV부당"],"legal_focus":["TV3요건_업무상필요성","근로계약상직무한정"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["채용당시자격증직무한정=다른직무TV=업무상필요성없음=TV부당","근로계약직무한정TV부당"],"exclude_for_queries":[],"summary_short":"채용 당시 승강기보수기능사 자격증 소지자로 선발=체험관 시설관리(다른 자격 요구 직무) TV=업무상 필요성 없음=TV 부당","holding_summary":"채용될 당시 승강기보수기능사 자격증 소지자로서 선발된 근로자를 체험관 시설관리(기계기능사·전기기능사 자격소지자 채용조건) 직무로 전보하는 것은 채용 당시 직무와 다른 직무로의 이동으로 업무상 필요성이 인정되지 않아 TV 부당","retrieval_note":"채용 자격증 직무 한정 TV 부당 패턴","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411993","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["감리단교체요구=부당업무지시거부기인","연고지없음+본사근무경험거의없음","경제적정신적불이익큼"],"legal_focus":["TV3요건_업무상필요성","TV3요건_생활상불이익"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["부당업무지시거부에서기인한감리단교체전보+연고지없음+불이익큼=TV부당"],"exclude_for_queries":[],"summary_short":"감리단 교체요구=부당업무지시 거부에서 기인+연고지 없고 본사 근무 경험 거의 없음=생활상 불이익 큼=TV 부당","holding_summary":"사용자에게 인사권의 폭넓은 재량을 인정하더라도 감리단의 교체요구가 부당한 업무지시에 대한 거부에서 기인한 사실과 연고지가 없고 본사 근무 경험이 거의 없는 근로자에게 경제적·정신적 불이익이 크다고 인정되므로 TV 부당","retrieval_note":"부당업무지시 거부 기인 전보+생활상 불이익 TV 부당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412049","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["저성과자교육목적TV=업무상필요성인정","기한없음+종전업무무관교육만=생활상불이익"],"legal_focus":["TV3요건_업무상필요성","TV3요건_생활상불이익"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["저성과자교육TV=업무상필요성인정이나무기한+종전업무무관교육=생활상불이익=TV부당"],"exclude_for_queries":[],"summary_short":"저성과자 재교육 TV=업무상 필요성 인정이나 기한 없음+종전 업무와 무관한 교육만=생활상 불이익=TV 부당","holding_summary":"인사평가 결과 업무 저성과자에 대해 재교육을 실시하기 위한 전보로 업무상 필요성이 인정되나, 정해진 기한도 없이 종전 업무와 직접적 관련이 없는 교육만을 받으며 근로를 지속하게 하는 것은 생활상 불이익으로 TV 부당","retrieval_note":"교육목적 TV 업무상필요성 인정이나 생활상불이익으로 부당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412227","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["ICT벤처센터장=직제에없는직책","결재권한책임없는유명무실직책","원심TV정당→재심취소"],"legal_focus":["TV3요건_업무상필요성","유명무실직책전직"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["직제없는유명무실직책전직=결재권한없음=TV부당=원심취소","ICT벤처센터장=직제없음+결재권없는직책=TV부당"],"exclude_for_queries":[],"summary_short":"ICT벤처센터장 직책=직제에도 없고 결재권·권한·책임 없는 유명무실 직책=TV 부당=원심 취소","holding_summary":"사용자는 근로자를 ICT벤처센터장 직책으로 전직 발령했으나, 해당 직책은 직제에도 없고 결재권, 권한, 책임이 없는 유명무실한 직책으로 초심 TV 정당 판정 이후 이 사건 초심 판정을 취소하여 TV 부당으로 전환","retrieval_note":"유명무실직책 전직 TV 부당 원심취소 패턴","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412259","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["설비직→행정직=이질적직무전환","설비직업무특수성(냉난방유지관리배관보수등)","업무상필요성부족"],"legal_focus":["TV3요건_업무상필요성","이질적직무전환"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["설비직→행정직이질적직무TV=업무상필요성부족=TV부당"],"exclude_for_queries":[],"summary_short":"설비직→행정직 이질적 직무 전보=사용자 주장 업무상 필요성 객관적 근거 부족=TV 부당","holding_summary":"사용자는 설비직→행정직 전보의 업무상 필요성이 있다고 주장하나, 설비직 업무는 냉난방 유지관리, 배관보수, 위생, 설비보수, 도색, 건물공사 감독관 등 특수성이 있어 행정직과 이질적 직무 전환으로 업무상 필요성이 인정되지 않아 TV 부당","retrieval_note":"이질적 직무 전환 TV 부당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412323","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["성과개선프로그램운영중성과향상이유전직=타당않음","초심에서전직이유불일치","원심TV정당→재심취소"],"legal_focus":["TV3요건_업무상필요성","성과개선절차와전직모순"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["성과개선프로그램대상자에게성과향상이유전직=타당않음+이유불일치=TV부당=원심취소"],"exclude_for_queries":[],"summary_short":"성과개선프로그램 운영 중인데 성과 향상을 이유로 전직=타당하지 않음+초심에서 전직이유 불일치=TV 부당=원심 취소","holding_summary":"공식적인 성과 개선프로그램을 운영하고 있음에도 사전성과 개선프로그램 대상자인 근로자에 대해 성과 향상을 이유로 전직한 행위는 타당하지 않고, 사용자는 초심에서 전직의 주된 이유를 근로자의 성과 개선을 위한 것이라고 하여 이유 불일치=TV 부당=원심 취소","retrieval_note":"성과개선프로그램과 모순된 전직=TV 부당 원심취소","confidence":"high","review_status":"approved","tag_version":"v3"},

# ── TV 정당 (13건) ──────────────────────────────────────────────────

{"case_id":"id_411753","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영종차고지=프리랜서적정","인스파이어리조트=정규직스케줄적정","효율적인력관리"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["정규직-프리랜서인력배치효율화TV=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"영종 차고지=프리랜서 적정, 인스파이어리조트=정규직 스케줄=효율적 인력관리=TV 정당","holding_summary":"영종 차고지는 비정기적인 스케줄로 프리랜서 기사들이 근무하기에 적정하고, 인스파이어리조트는 일정한 스케줄 근무로 정규직 근로자들이 근무하기에 적정하여 효율적 인력관리를 위한 업무상 필요성이 인정되어 TV 정당","retrieval_note":"효율적 인력관리 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411783","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["스토킹예방지침제8조피해자보호조치","스토킹행위인정아님이나피해자보호목적","피해자진술구체적"],"legal_focus":["TV3요건_업무상필요성","스토킹피해자보호조치TV"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["스토킹예방지침피해자보호조치TV=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"스토킹예방지침 제8조 피해자 보호조치 전보=근로자 행위를 스토킹으로 인정한 결과물 아님+업무상 필요성 인정=TV 정당","holding_summary":"인사발령이 근로자의 행위를 스토킹으로 인정한 결과물이 아니라 공사 스토킹 예방 지침 제8조에 따라 피해자 보호조치의 일환으로 취해진 조치이며, 근로자의 언행에 대한 피해근로자의 진술이 구체적으로 업무상 필요성이 인정되어 TV 정당","retrieval_note":"스토킹 예방지침 피해자 보호조치 TV 정당 (batch_051 id_409701과 동일 패턴)","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411829","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["동일평가방식+결과토대전보","외부환경불리상황평가=인사권재량내","업무상필요성인정"],"legal_focus":["TV3요건_업무상필요성","인사권재량"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["동일평가방식+인사권재량내전보=이례적외부환경주장불인정=TV정당"],"exclude_for_queries":[],"summary_short":"기존과 동일한 평가방식+결과 기반 전보=이례적 외부환경 평가 불리 주장 불인정=인사권 재량 내=TV 정당","holding_summary":"회사가 기존과 동일한 평가방식과 그 결과의 토대 위에 기존의 같은 방법으로 행한 전보는 이례적인 외부환경으로 인한 불리한 상황에서의 평가라는 근로자의 주장을 고려하더라도 인사권 재량 범위 내로 업무상 필요성이 인정되어 TV 정당","retrieval_note":"동일 평가방식 기반 TV 인사권 재량 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411861","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["발주처관계회복+용역계약이행업무상필요성","임금등근로조건변동없음","출퇴근30분단축"],"legal_focus":["TV3요건_업무상필요성","TV3요건_생활상불이익"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["발주처관계회복용역계약이행TV=임금변동없음+출퇴근단축=TV정당"],"exclude_for_queries":[],"summary_short":"발주처 관계 회복+용역계약 이행=업무상 필요성 인정+임금 등 근로조건 변동 없음+출퇴근 30분 단축=TV 정당","holding_summary":"전보는 발주처와의 관계 회복과 용역계약을 원활히 이행하기 위한 업무상 필요성이 인정되고, 근로자의 임금 등 근로조건에 변동이 없고 오히려 출퇴근 시간이 30분 단축된 것이 확인되므로 TV 정당","retrieval_note":"발주처 관계 회복 TV 정당 패턴","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412037","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["경영기획팀장-재무회계팀장업무갈등","업무효율화보고체계단순화","인사발령=전직=구제신청대상"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["팀장간업무갈등=업무효율화보고체계단순화TV=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"경영기획팀장-재무회계팀장 업무 갈등=업무 효율화·보고체계 단순화 TV=업무상 필요성 인정=TV 정당","holding_summary":"경영기획팀장과 근로자인 재무회계팀장 간의 업무 갈등으로 인해 업무 효율화와 보고체계 단순화를 위한 TV로 업무상 필요성이 인정되어 TV 정당 (인사발령은 보직 해임 및 변경에 해당하여 구제신청 대상인 전직임이 먼저 확인됨)","retrieval_note":"팀장 간 갈등 업무효율화 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412125","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["인사발령=징계아님(회사규정상)","해설강화업무상필요성존재","징계효력미적용"],"legal_focus":["TV3요건_업무상필요성","TV_징계아님구별"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["인사발령=징계아님확인+해설강화업무상필요성=TV정당"],"exclude_for_queries":[],"summary_short":"인사발령=회사규정상 징계 해당 않음+징계 효력 미적용+해설 강화 업무상 필요성 존재=TV 정당","holding_summary":"인사발령은 회사 규정상 징계에 해당하지 않으며 징계의 효력도 적용받지 않았으므로 징계가 아니고, 해설을 강화해야 하는 업무상 필요성이 존재하는 이상 직제 개편에 따른 TV는 정당","retrieval_note":"TV 징계 아님 확인+업무상 필요성 인정 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412201","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["의왕지점직영차량없어져배치전환필요","근로자도인정취지진술","업무상필요성있음"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["직영차량없어진지점=배치전환불가피=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"의왕지점에 더 이상 운행 가능한 직영 차량 없어 배치전환 필요=근로자도 인정=업무상 필요성 인정=TV 정당","holding_summary":"의왕지점에 더 이상 운행 가능한 직영 차량이 존재하지 않게 되어 근로자에 대한 배치전환이 필요하게 되었고, 이러한 사실에 대하여는 근로자도 심문회의에서 인정하는 취지로 진술한 바 업무상 필요성이 인정되어 TV 정당","retrieval_note":"직영차량 소멸로 인한 배치전환 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412211","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["전직후해임으로근로관계종료","해고다툼중전직구제이익존재","TV정당"],"legal_focus":["TV3요건_업무상필요성","구제이익_전직후해임"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["전직이후해임으로근로관계종료=해고다툼중전직구제이익존재+TV정당"],"exclude_for_queries":[],"summary_short":"전직 이후 해임으로 근로관계 종료=해고 효력 다툼 중 전직 구제이익 존재+전직 업무상 필요성 인정=TV 정당","holding_summary":"근로자가 전직 이후 해임으로 근로관계가 종료되었다고 하더라도 해고의 효력을 둘러싸고 법률적인 다툼이 계속되는 이상 전직에 대한 구제이익이 존재하고, 전직의 업무상 필요성이 인정되어 TV 정당","retrieval_note":"전직 후 해임으로 관계 종료되어도 전직 구제이익 존재 + TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412225","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직책해임=인사권자재량","업무역량리더십사업상필요고려","조직개편"],"legal_focus":["TV3요건_업무상필요성","인사권재량"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["직책해임=인사권자재량+업무역량리더십사업상필요=TV정당"],"exclude_for_queries":[],"summary_short":"직책해임=인사권자 재량 범위+업무역량·리더십·사업상 필요 고려=TV 정당","holding_summary":"회사의 조직 구성 및 개편, 전보나 전직은 원칙적으로 인사권자인 사용자의 권한에 속하고, 회사는 사업의 원활한 경영을 위하여 근로자들의 업무역량, 리더십 역량, 사업상 필요 등을 고려한 직책해임으로 TV 정당","retrieval_note":"인사권 재량 내 직책해임 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412237","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["다이렉트부서최대근무기간초과","해지방어부서업무전환불가피","생활상불이익없음"],"legal_focus":["TV3요건_업무상필요성","TV3요건_생활상불이익"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["최대근무기간초과=해지방어부서업무전환불가피=업무상필요성인정+생활상불이익없음=TV정당"],"exclude_for_queries":[],"summary_short":"다이렉트 부서 최대 근무기간 초과=해지방어 부서 업무 전환 불가피=업무상 필요성 인정+근로시간 등 생활상 불이익 없음=TV 정당","holding_summary":"다이렉트 부서 근무자가 최대 근무기간을 초과하여 해지방어 부서 근로자의 업무 전환이 불가피한 상황에서 이루어진 것으로 업무상 필요성이 인정되고, 인사발령 전후 전체 근로시간 등 생활상 불이익이 없어 TV 정당","retrieval_note":"최대 근무기간 초과로 인한 의무적 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412359","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["적자해소지방영업점인력축소","퇴직연금사업확대=종사자선정","권한남용없음"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["적자해소지방영업점인력축소+퇴직연금사업확대TV=권한남용없음=TV정당"],"exclude_for_queries":[],"summary_short":"적자해소 지방영업점 인력축소+퇴직연금 사업 확대 종사자 선정 TV=권한 남용 없음=TV 정당","holding_summary":"적자해소를 위한 지방영업점 인력축소 및 퇴직연금 사업의 확대에 따른 퇴직연금 사업 종사자 선정을 목적으로 인사발령이 시행되었고, 인사발령 대상자 선정 및 인사발령 검토과정에서 권한을 남용하지 않아 TV 정당","retrieval_note":"경영합리화 퇴직연금 사업 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412385","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["열차승무원이례적다수민원","근무불성실자전보규정적용","업무상필요성인정"],"legal_focus":["TV3요건_업무상필요성"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["열차승무원이례적다수민원=전보규정적용=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"열차 승무원 이례적으로 다수 민원 발생=근무 불성실자 전보 규정 적용=업무상 필요성 인정=TV 정당","holding_summary":"열차 승무원인 근로자에 대하여 이례적으로 다수의 민원이 발생하였고, 근무 불성실자 등에 대한 전보 관련 규정에 따라 전보 발령이 이루어졌으므로 업무상 필요성이 인정되어 TV 정당","retrieval_note":"민원 발생 전보 규정 적용 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412419","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["공단인력재배치필요=업무상필요성인정","생활상불이익감수가능정도","전직정당"],"legal_focus":["TV3요건_업무상필요성","TV3요건_생활상불이익"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["공단인력재배치필요=업무상필요성인정+생활상불이익감수가능정도=TV정당"],"exclude_for_queries":[],"summary_short":"공단 인력 재배치 필요=업무상 필요성 인정+생활상 불이익이 근로자가 통상 감수하여야 할 정도를 현저히 벗어나지 않음=TV 정당","holding_summary":"사용자에게는 공단의 인력 재배치가 필요한 상황에서 업무상 필요성이 인정되고, 근로자가 전직으로 인해 업무강도 차이 외에는 생활상 불이익이 통상 감수하여야 할 정도를 현저하게 벗어나지 않아 TV 정당","retrieval_note":"공공기관 인력 재배치 TV 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

# ── TV 각하 (2건) ──────────────────────────────────────────────────

{"case_id":"id_411843","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["인사발령사내공지일1.12","구제신청일4.13=91일","제척기간3개월초과"],"legal_focus":["제척기간","구제신청요건"],"industry_context":"office","exclusion_flags":["procedure_dominant"],"include_for_queries":["인사발령공지일기산제척기간3개월초과=각하","사내공지일기준제척기간=개별통지일주장불인정"],"exclude_for_queries":[],"summary_short":"인사발령 사내 공지일(1.12)부터 기산=구제신청일(4.13)=91일=제척기간 3개월 초과=각하","holding_summary":"근로자는 인사발령 통지를 받은 2024.1.15.부터 기산하여 제척기간이 경과되지 않았다고 주장하나, 2024.1.12. 사용자가 인사발령을 사내에 공지하였으며 그로부터 구제신청일(4.13.)까지 3개월을 초과하여 제척기간 경과로 각하","retrieval_note":"사내 공지일 기준 제척기간 기산 각하","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411953","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["전보발령일=사직서제출","사직서수리=근로관계종료","TV구제이익소멸"],"legal_focus":["구제이익","TV_사직수리_구제이익소멸"],"industry_context":"office","exclusion_flags":["procedure_dominant"],"include_for_queries":["전보발령일사직서제출수리=TV구제이익소멸=각하"],"exclude_for_queries":[],"summary_short":"전보 발령일에 사직서 제출하여 수리됨=TV 구제이익 소멸=각하","holding_summary":"근로자는 전보 발령이 부당하다며 구제신청을 하였으나, 근로자가 전보 발령일인 2025.6.30. 사용자에게 사직서를 제출하여 수리되었으므로 전보에 대한 구제이익이 없어 각하","retrieval_note":"전보발령일 사직=구제이익 소멸 각하","confidence":"high","review_status":"approved","tag_version":"v3"},

# ── no_dismissal (9건) ──────────────────────────────────────────────────

{"case_id":"id_411793","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal","disciplinary_dismissal"],"fact_markers":["근로자의사반한일방적근로관계종료=해고","사직서제출당시징계해고에대한의사반한종료"],"legal_focus":["해고존재여부","일방적근로관계종료"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["사직서제출당시징계해고에의한일방적근로관계종료=해고존재=부당해고"],"exclude_for_queries":[],"summary_short":"근로자 의사에 반하여 사용자 일방적 의사에 의해 근로관계 종료=해고 해당=부당해고","holding_summary":"근로자의 의사에 반하여 사용자의 일방적 의사에 의해 근로관계 종료가 이루어진 것으로 보이므로 해고에 해당하고, 사직서를 제출할 당시 사용자의 징계해고에 대한 의사반한 근로관계 종료가 인정되어 부당해고","retrieval_note":"일방적 근로관계 종료=해고 존재=부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411853","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["1년근로계약서명시","기간전사퇴사직서등입증자료없음","해고존재인정"],"legal_focus":["해고존재여부","자발적사퇴입증책임"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["1년계약기간전사퇴입증자료없음=사용자입증실패=해고존재인정=부당해고"],"exclude_for_queries":[],"summary_short":"1년 근로계약 명시+계약기간 전 사퇴 사직서 등 사용자 입증 자료 없음=해고 존재 인정=부당해고","holding_summary":"근로자와 사용자 간에 1년간의 근로계약기간이 명시된 근로계약서가 체결된 상황에서 계약기간 종료 이전에 근로자가 스스로 사퇴하였다는 사직서 등 사용자측 입증 자료가 없어 해고 존재가 인정되어 부당해고","retrieval_note":"사용자의 자발적 사퇴 입증 실패=해고 존재 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411863","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["해고통보자-실경영자관계","해고통보자에게인사권위임","실경영자해고의사표시"],"legal_focus":["해고존재여부","인사권위임범위","해고의사표시주체"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["해고통보자인사권위임+실경영자해고의사표시=해고존재=부당해고"],"exclude_for_queries":[],"summary_short":"해고 통보자에게 인사권 위임 인정+실경영자의 해고 의사표시 해당=해고 존재=부당해고","holding_summary":"해고 통보자와 실경영자의 관계와 현장의 상황, 근로관계 종료 이후의 사정 등을 고려할 때 해고 통보자에게 근로자의 인사권이 위임되어 있다고 보아야 하며, 그렇지 않더라도 실경영자의 해고 의사표시에 해당하여 해고 존재=부당해고","retrieval_note":"인사권 위임 범위 판단+실경영자 해고 의사표시 해고 존재","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411929","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["권고사직수용의사표시없음","사직서작성제출등수용취지의사표시확인안됨","해고존재인정"],"legal_focus":["해고존재여부","권고사직_합의해지구별"],"industry_context":"office","exclusion_flags":["settlement_or_mutual_termination"],"include_for_queries":["권고사직수용의사표시확인안됨=사용자주장합의해지불인정=해고존재=부당해고"],"exclude_for_queries":[],"summary_short":"권고사직 수용 의사표시 확인 안 됨=사용자 합의해지 주장 불인정=해고 존재=부당해고","holding_summary":"사용자는 근로자와 권고사직으로 근로관계가 종료되었다고 주장하나, 근로자가 스스로 사직서를 작성·제출하는 등 사용자의 권고사직 제안을 수용한다는 취지의 의사표시가 확인되지 않아 해고 존재가 인정되어 부당해고","retrieval_note":"권고사직 수용 의사표시 부존재=해고 존재 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411961","issue_type_primary":"no_dismissal","issue_type_secondary":["discrimination"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["육아휴직후신입직원채용","복직거부=부당해고","긴급인력충원주장불인정"],"legal_focus":["육아휴직복직권","남녀고용평등법","해고존재여부"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["육아휴직후신입채용+긴급충원주장불인정=복직거부=부당해고","남녀고용평등법육아휴직복직거부=부당해고"],"exclude_for_queries":[],"summary_short":"육아휴직 후 신입직원 채용=긴급 충원 필요성 주장 불인정=복직 거부=부당해고","holding_summary":"사용자가 근로자의 육아휴직 후 신입직원을 채용한 사실과 수습·적응 기간을 고려할 때 긴급한 인력 충원이 필요했다는 주장을 받아들이기 어렵고, 사용자는 조직 내 복직 조치 없이 복직을 거부하여 부당해고","retrieval_note":"육아휴직 복직 거부 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412043","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"probation","disposition_type":["probation_termination","dismissal"],"fact_markers":["채용당시근로조건서면미명시","기간의정함있는근로계약입증실패","기간의정함없는근로계약=해고=부당해고"],"legal_focus":["해고존재여부","기간의정함없는근로계약","시용기간포함계약기간"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["근로계약서근로조건서면미명시+기간정함입증실패=기간의정함없는근로계약=해고=부당해고"],"exclude_for_queries":[],"summary_short":"채용 당시 근로조건 서면 미명시+사용자 기간의 정함 입증 실패=기간의 정함 없는 근로계약=해고=부당해고","holding_summary":"채용 당시 근로조건을 서면으로 명시하지 않았고, 사용자가 달리 기간의 정함이 있는 근로계약임을 입증하지 못하였으므로 사실상 기간의 정함이 없는 근로계약으로 보아야 하며 해지 통보는 해고=부당해고","retrieval_note":"근로조건 서면 미명시+기간 정함 입증 실패=기간의 정함 없는 계약=해고 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412267","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사직의사표시없음","합의해지주장이나부인","해고존재인정"],"legal_focus":["해고존재여부","합의해지_해고구별"],"industry_context":"office","exclusion_flags":["settlement_or_mutual_termination"],"include_for_queries":["사직의사없음+합의해지부인=합의해지불인정=해고존재=부당해고"],"exclude_for_queries":[],"summary_short":"사직 의사 표시 없음+합의해지 부인=사용자 합의해지 주장 불인정=해고 존재=부당해고","holding_summary":"사용자는 근로자의 사직 의사를 확인하고 퇴직일에 합의하였다고 주장하나, 근로자는 사직의사를 표시한 사실이 없고 합의 사실을 부인하고 있어 합의해지 불인정=해고 존재=부당해고","retrieval_note":"합의해지 주장 불인정 해고 존재 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412315","issue_type_primary":"no_dismissal","issue_type_secondary":["contract_expiry"],"employment_stage":"renewal_stage","disposition_type":["rejection_of_regular_employment","dismissal"],"fact_markers":["무기계약전환기대권(취업규칙+채용공고)","인사위원회심사통한전환가능기재","전환거부=부당해고"],"legal_focus":["무기계약전환기대권","고용기대권"],"industry_context":"public","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["취업규칙+채용공고무기계약전환가능=전환기대권성립=전환거부=부당해고"],"exclude_for_queries":[],"summary_short":"무기계약 근로자 취업규칙+채용공고 '심사를 거쳐 무기계약 전환 가능'=전환기대권 성립=전환 거부=부당해고","holding_summary":"무기계약 근로자 취업규칙 제13조 및 2023.6.14. 채용공고문상에 '근무태도, 근무성적 평정 등에 따라 심사를 거쳐 무기계약 전환 가능'이라고 기재되어 무기계약직 전환 기대권이 있고, 전환 거부는 부당해고","retrieval_note":"취업규칙+채용공고 무기계약 전환 기대권 성립 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412457","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["메시지=근로관계종료의사해석불가","해고존재인정","근로자부인"],"legal_focus":["해고존재여부","근로관계종료의사표시해석"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["근로자메시지=근로관계종료의사해석불가=사직아님=해고존재=부당해고"],"exclude_for_queries":[],"summary_short":"근로자가 남긴 메시지=근로관계 종료 의사로 해석하기에 무리=해고 존재=부당해고","holding_summary":"근로자가 2025.7.15. 남긴 메시지는 사용자와 근로관계를 종료하겠다는 의미로 해석하기에는 무리가 있으며, 근로자가 사직 의사를 표시하지 않아 해고 존재=부당해고","retrieval_note":"메시지 근로관계 종료 의사 해석 불가 해고 존재","confidence":"high","review_status":"approved","tag_version":"v3"},

# ── disciplinary_severity (8건) ──────────────────────────────────────────────────

{"case_id":"id_411823","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["근로시간임의변경권한없음에도변경","원상회복지시불응","징계사유인정=징계정당"],"legal_focus":["징계사유정당성","업무지시위반"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["근로시간임의변경+원상회복지시불응=징계사유인정=징계정당"],"exclude_for_queries":[],"summary_short":"근로시간 임의 변경 권한 없음에도 변경+원상회복 지시 불응=징계사유 인정=징계 정당","holding_summary":"센터 직원들의 근로시간을 변경할 권한이 없음에도 이를 임의로 변경하고 사용자의 정당한 근로시간 원상회복 지시에 불응한 행위는 취업규칙에서 정한 징계사유에 해당하여 징계 정당","retrieval_note":"권한없는근로시간변경+지시불응 징계 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_41193","issue_type_primary":"disciplinary_severity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["비방이메일=징계사유인정","대기발령보직변경선행","원심기각→재심취소=징계부당"],"legal_focus":["징계양정적정성","선행처분고려","징계양정과다"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["비방이메일=징계사유인정이나선행대기발령보직변경고려=징계양정과다=원심취소"],"exclude_for_queries":[],"summary_short":"비방 이메일=징계사유 인정이나 선행 대기발령·보직변경 고려=징계 양정 과다=원심 취소","holding_summary":"근로자가 동료들에게 특정인과 인사팀을 비방하는 이메일을 보내 명예를 훼손한 행위는 징계사유에 해당하나, 징계 이전에 있었던 대기발령·보직변경 등 선행 처분을 고려하면 징계 양정이 과다하여 원심 기각을 취소하고 징계 부당 인정","retrieval_note":"선행처분(대기발령·보직변경) 고려 징계양정과다 원심취소","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_411977","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사전보고누락+지시불이행","회사경제손실야기","취업규칙제30조4호해당=징계양정적정=기각"],"legal_focus":["징계사유정당성","징계양정적정성"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["사전보고누락+지시불이행+경제손실야기=징계사유인정+양정적정=기각"],"exclude_for_queries":[],"summary_short":"사전보고 누락·지시 불이행·경제손실 야기=취업규칙 징계사유 해당=양정 적정=기각","holding_summary":"근로자의 사전보고 누락, 지시 불이행, 회사의 경제적 손실 야기는 취업규칙 제30조 징계사유에 해당하고, 징계양정도 적정하여 기각","retrieval_note":"3개 징계사유 인정+양정 적정 기각","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_41199","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["부당전보노동위승소후에도","5차업무복귀명령불응","77일무단결근=징계사유인정=징계정당"],"legal_focus":["징계사유정당성","업무복귀명령불응","무단결근"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["부당전보승소에도5차업무복귀명령불응+77일무단결근=징계사유인정=징계정당"],"exclude_for_queries":[],"summary_short":"부당전보 노동위 승소에도 불구 5차례 업무복귀 명령 불응+77일 무단결근=징계사유 인정=징계 정당","holding_summary":"근로자들이 부당전보에 대하여 지방노동위원회에서 승소하였다고 하더라도 사용자의 5차례에 걸친 업무복귀 명령에 불응하며 77일 동안 무단결근한 행위는 징계 사유에 해당하고 양정도 적정하여 징계 정당","retrieval_note":"전보승소 후에도 복귀명령 불응 무단결근 징계 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4121","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["pay_cut"],"fact_markers":["지각=징계사유인정","동일비위다른근로자미징계","감봉5월=해고다음중한징계=양정과다=부분인용"],"legal_focus":["징계양정적정성","형평성","비교대상근로자"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["지각징계사유인정이나동일비위자미징계=감봉5월양정과다=부분인용"],"exclude_for_queries":[],"summary_short":"지각=징계사유 인정+동일 비위 다른 근로자 미징계=감봉 5월 양정 과다=부분인용","holding_summary":"지각에 대한 징계사유가 인정되기는 하나, 동일한 비위행위를 행한 다른 근로자는 징계를 하지 않았으며, 감봉은 해고 다음으로 중한 징계인 점을 고려하면 감봉 5월의 징계는 양정이 과다하여 부분인용","retrieval_note":"형평성 위반 징계양정 과다 부분인용","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412015","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["업무태만+부정행위미보고+장비유출주장","사용자주장관계자진술입증불충분","징계사유불인정=해고부당"],"legal_focus":["징계사유정당성","입증책임"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["업무태만+부정행위미보고+장비유출=사용자진술입증불충분=징계사유불인정=해고부당"],"exclude_for_queries":[],"summary_short":"업무태만·부정행위 미보고·장비 유출=사용자 주장·관계자 진술 입증 불충분=징계사유 불인정=해고 부당","holding_summary":"근로자가 업무시간 중 경쟁업체 가맹점 관리 업무태만, 직원 부정행위 미보고, 회사 장비 유출 등에 대한 사용자의 주장과 관계자 진술이 불충분하여 징계사유를 인정하기 어려워 해고 부당","retrieval_note":"징계사유 입증 불충분=해고 부당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412233","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["성희롱비위행위=정직정당","피해자와동일처지평균인기준","정직처분적정=기각"],"legal_focus":["징계사유정당성","성희롱징계","징계양정적정성"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["성희롱비위행위=평균인기준성적굴욕감=정직징계정당=기각"],"exclude_for_queries":[],"summary_short":"성희롱 비위행위=평균적인 사람 기준 성적 굴욕감·혐오감=정직 처분 정당=기각","holding_summary":"근로자의 비위행위들은 피해자와 같은 처지에 있는 일반적이고도 평균적인 사람으로 하여금 성적 굴욕감이나 혐오감을 느끼게 할 수 있는 행위이고, 그로 인해 행위의 상대방이 성적 굴욕감이나 혐오감을 느꼈으므로 정직 처분 정당","retrieval_note":"성희롱 평균인 기준 정직 정당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412335","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["판매용고기가져간행위=일부사유인정","판매용음료수임의음용=일부사유인정","나머지사유불인정=양정과다=인용"],"legal_focus":["징계사유정당성","징계양정적정성","일부사유인정"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["일부징계사유인정+나머지불인정=전체양정과다=징계부당=인용"],"exclude_for_queries":[],"summary_short":"판매용 고기·음료수 무단 취식=일부 사유 인정+나머지 사유 불인정=양정 과다=징계 부당=인용","holding_summary":"근로자들이 판매용 고기를 가지고 간 행위, 판매용 음료수를 임의로 마신 행위는 징계사유로 인정되나 나머지 사유는 징계사유로 보기 어렵고, 전체 양정이 과다하여 징계 부당=인용","retrieval_note":"일부 사유 인정+나머지 불인정 양정과다 부분인용","confidence":"high","review_status":"approved","tag_version":"v3"},

# ── procedure (7건) ──────────────────────────────────────────────────

{"case_id":"id_411797","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["봄내스튜디오+봄내대가+봄내안전보건=실질하나의사업장","인사회계관리독립성없음","상시근로자수합산=5인이상인정"],"legal_focus":["상시근로자수5인이상","개별사업장합산","근로기준법적용"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["별개법인명의이나실질하나의사업장=상시근로자수합산=5인이상인정=근로기준법적용=부당해고인용"],"exclude_for_queries":[],"summary_short":"봄내스튜디오·봄내대가·봄내안전보건=실질 하나의 사업장=인사·회계관리 독립성 없음=상시근로자 수 합산 5인 이상=근로기준법 적용","holding_summary":"봄내스튜디오, 봄내대가, 봄내안전보건은 실질적으로 인사·회계관리의 독립성이 없고 하나의 사업장으로 운영되므로 상시근로자 수를 합산하여 5인 이상이 인정되어 근로기준법이 적용되고 부당해고 구제신청 인용","retrieval_note":"별개 법인 실질 하나 사업장 상시근로자 합산 5인 이상 인정","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_41201","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["인사기록부2018.7이후대기발령없음","업무계획서제출지시=대기발령아님","구제신청대상아님=각하"],"legal_focus":["구제신청대상","대기발령존재여부"],"industry_context":"office","exclusion_flags":["procedure_dominant"],"include_for_queries":["인사기록부대기발령인사명령없음=대기발령아님=구제신청대상아님=각하"],"exclude_for_queries":[],"summary_short":"인사기록부상 대기발령 형식 인사명령 없음+업무계획서 제출 지시=대기발령 아님=구제신청 대상 아님=각하","holding_summary":"근로자의 인사기록부상에 2018.7. 이후 대기발령 형식의 인사명령이 존재하지 않는 점, 신사업1팀장이 근로자에게 업무계획서 제출을 지시한 행위는 대기발령에 해당하지 않으므로 구제신청 대상이 아니어서 각하","retrieval_note":"인사기록부 대기발령 없음=구제신청 대상 아님 각하","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_41211","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["pay_cut"],"fact_markers":["인사위원회5명구성재적3분의2이상출석요건","1차부터재심까지3명만출석","의사정족수미달=절차하자=감봉부당"],"legal_focus":["인사위원회정족수","징계절차"],"industry_context":"office","exclusion_flags":["procedure_dominant"],"include_for_queries":["인사위원회재적위원3분의2이상출석요건미달=의사정족수미달=절차하자=감봉부당"],"exclude_for_queries":[],"summary_short":"인사위원회 재적위원 3분의 2 이상 출석 규정에도 1차부터 재심까지 3명만 출석=의사정족수 미달=절차 하자=감봉 부당","holding_summary":"인사위원회는 5명으로 구성되고 재적위원 3분의 2 이상의 출석과 출석위원 과반수의 찬성으로 의결하도록 규정하고 있음에도 1차부터 재심까지 각 인사위원회에 3명의 인사위원만이 출석한 것은 의사정족수 미달=절차 하자=감봉 부당","retrieval_note":"인사위원회 의사정족수 미달 절차 하자 징계 부당","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412063","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["직위해제사전서면통지없음","인사위원회정상실시안됨","직위해제부당=대기발령부분인용"],"legal_focus":["직위해제절차","사전통지","인사위원회"],"industry_context":"office","exclusion_flags":["procedure_dominant"],"include_for_queries":["직위해제사전서면통지없음=인사위원회정상미실시=절차하자=직위해제부당=부분인용"],"exclude_for_queries":[],"summary_short":"직위해제 사전 서면 통지 절차 없음+인사위원회 정상 미실시=절차 하자=직위해제 부당=부분인용","holding_summary":"직위해제에 대해 인사 규정상 사전 서면 통지 절차가 이루어지지 않는 등 인사위원회가 정상적으로 실시되었다고 볼 수 없는 절차상 하자가 있어 직위해제 부당, 직위해제가 무효인 이상 후속 대기발령도 부당하여 부분인용","retrieval_note":"직위해제 사전 서면 통지 없음 절차 하자 부분인용","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412079","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["법인=당사자적격있음","본사지점동일법인격=하나의사업","상시근로자수법인전체합산=5인이상"],"legal_focus":["당사자적격","상시근로자수5인이상","본지점합산"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["본사-지점동일법인=상시근로자수전체합산=5인이상인정=구제신청인용"],"exclude_for_queries":[],"summary_short":"본사와 지점이 동일 법인격=하나의 사업=상시근로자 수 법인 전체 합산 5인 이상=구제신청 인용","holding_summary":"사용자는 법인에 해당하므로 당사자 적격이 있고, 본사와 지점이 동일한 법인격을 가진 하나의 사업으로 보아 법인 전체의 근로자로 상시근로자 수를 산정해야 하며 5인 이상이 인정되어 구제신청 인용","retrieval_note":"본지점 동일 법인 상시근로자 합산 5인 이상 인정","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412263","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사용자2=근로자와근로계약관계없음","피신청인적격=근로관계사업주","사용자2당사자적격없음=각하"],"legal_focus":["당사자적격","사용자범위"],"industry_context":"office","exclusion_flags":["procedure_dominant"],"include_for_queries":["근로계약관계없는사용자2=피신청인적격없음=각하"],"exclude_for_queries":[],"summary_short":"사용자2=근로자와 명시적·묵시적 근로계약 관계 없음=피신청인 적격 없음=각하","holding_summary":"노동위원회 구제신청에 있어 피신청인 적격은 근로관계를 형성하고 있는 사업주에게 있는 바, 사용자2는 근로자와 명시적이거나 묵시적인 근로계약 관계를 맺고 있는 자에 해당하지 않아 당사자 적격 없음=각하","retrieval_note":"근로계약관계 없는 자 피신청인 적격 없음 각하","confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_412295","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["corrective_order_related"],"fact_markers":["금전보상명령신청","복직+임금지급에도구제이익소멸않음","금전보상신청=구제이익있음"],"legal_focus":["구제이익","금전보상신청","복직명령후구제이익"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["금전보상명령신청=복직+임금지급에도구제이익소멸않음=정당한금전보상액판정받을이익있음"],"exclude_for_queries":[],"summary_short":"금전보상명령 신청=복직명령과 임금 상당액 지급과 관계없이 정당한 금전보상액 판정 받을 구제이익 있음","holding_summary":"근로자가 금전보상명령을 신청했다면, 금전보상명령 신청과 복직명령의 선후관계, 복직명령 이후 임금 상당액의 지급과 관계없이 정당한 임금 상당액 이상의 금전보상액을 판정받을 구제이익이 있어 각하 불가","retrieval_note":"금전보상 신청=복직+임금지급에도 구제이익 소멸 않음 (batch_053 id_411481과 동일 법리)","confidence":"high","review_status":"approved","tag_version":"v3"},

# ── discrimination (1건) ──────────────────────────────────────────────────

{"case_id":"id_412331","issue_type_primary":"discrimination","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["성희롱피해신고2022.2.3","신고후3년4개월경과후전보","업무역량부족원인=불리한처우불인정=기각"],"legal_focus":["성희롱피해신고자불리한처우","남녀고용평등법","인과관계"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["성희롱피해신고자전보=신고후3년4개월경과+업무역량부족원인=불리한처우인과관계불인정=기각"],"exclude_for_queries":[],"summary_short":"성희롱 피해 신고 후 3년 4개월 경과 전보+업무역량 부족이 원인=불리한 처우 인과관계 불인정=기각","holding_summary":"전보는 직장 내 성희롱 피해 사실을 신고한 2022.2.3.부터 약 3년 4개월이 지나 이루어졌고, 근로자의 업무 역량 부족 등이 원인이었던 점을 감안하면 직장 내 성희롱 피해근로자에 대한 불리한 처우로서의 인과관계가 인정되지 않아 기각","retrieval_note":"성희롱 신고자 전보=시간적 간격+업무역량부족=불리한처우 인과관계 불인정 기각","confidence":"high","review_status":"approved","tag_version":"v3"},

]

with open(OUT, 'w', encoding='utf-8') as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')

print(f"Written {len(records)} records")
