import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = []

records.append({"id":"id_49355","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["성희롱신고후피해자분리전보","업무상필요성인정","생활상불이익감수범위","협의절차준수","TV3대요건충족"],"legal_focus":["TV정당성3요건","남녀고용평등법제14조"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["성희롱피해자분리조치=TV정당","TV3대요건충족=정당"],"exclude_for_queries":[],"summary_short":"성희롱 피해자 분리조치 전보 정당","holding_summary":"성희롱 신고에 따른 피해자 분리 전보=업무상 필요성+생활상 불이익 감수범위+협의절차 준수=TV정당","retrieval_note":"성희롱 분리 전보 TV정당 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49365","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직장내괴롭힘분리조치전보","업무상필요성인정","생활상불이익현저","권리남용","TV부당"],"legal_focus":["TV정당성3요건","생활상불이익형량"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요성인정이나생활상불이익현저=권리남용=TV부당"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘 분리 전보 생활상 불이익 현저=TV부당","holding_summary":"직장내괴롭힘 분리조치 전보=업무상 필요성 인정이나 동일 사무소 내 대안 부서 존재+생활상 불이익 현저=권리남용=TV부당","retrieval_note":"업무상 필요성 인정에도 생활상 불이익 형량 실패 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49371","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["교통사고다발민원운전기사","예비기사발령","단협상징계미규정","징계아님","업무상필요성인정","생활상불이익경미"],"legal_focus":["TV정당성3요건","징계해당여부"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["교통사고다발운전기사예비기사발령=TV정당","예비기사발령=단협상징계아님"],"exclude_for_queries":[],"summary_short":"교통사고 다발 운전기사 예비기사 발령 TV정당","holding_summary":"다수 교통사고·민원 운전기사 예비기사 발령=단협상 징계 아님+업무상 필요성+생활상 불이익 경미=TV정당","retrieval_note":"예비기사 발령 징계 해당 여부+TV 정당성 복합 판단","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49387","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["contract_termination"],"fact_markers":["수탁업체위수탁계약","사용자1적격없음","배치전환거부","위수탁계약해지","근로계약종료","해고없음"],"legal_focus":["사용자적격","근로관계종료원인"],"industry_context":"unknown","exclusion_flags":["fact_specific_low_reusability"],"include_for_queries":["위수탁계약해지=배치전환거부=근로계약종료=해고없음"],"exclude_for_queries":[],"summary_short":"위수탁계약해지 배치전환거부 근로계약 종료 해고없음","holding_summary":"사용자1=당사자 적격 없음+사용자2=배치전환 거부+위수탁계약 해지=정당한 근로계약 종료=해고 없음","retrieval_note":"위수탁계약 해지+배치전환 거부 근로계약 종료 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49403","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer","suspension"],"fact_markers":["근무형태변경야간주간","취업규칙근거","업무상필요성","지시불이행징계","출근정지정당"],"legal_focus":["TV정당성3요건","취업규칙근무형태","복무규정위반"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["취업규칙근거근무형태변경=TV정당","지시불이행=출근정지정당"],"exclude_for_queries":[],"summary_short":"취업규칙 근거 근무형태 변경 TV정당+지시불이행 징계 정당","holding_summary":"취업규칙 근거 주간근무 지시=정당한 인사명령(TV정당)+지시불이행=복무규정 위반=출근정지 정당","retrieval_note":"근무형태 변경 인사명령+지시불이행 징계 복합 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49421","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사직의사표시전퇴사통보","서면통지없음","해고존재","부당해고","금전보상명령"],"legal_focus":["해고서면통지의무","해고존재여부","금전보상명령"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사직의사전일방퇴사통보=해고존재=서면통지없음=부당해고"],"exclude_for_queries":[],"summary_short":"사직 의사 전 일방 퇴사 통보=해고존재+서면통지없음=부당해고","holding_summary":"사직 의사 표시 전에 일방적 퇴사 통보=해고 존재+서면 통지 없음=부당해고+금전보상","retrieval_note":"해고 존재 + 서면통지 없음 병합 부당해고 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49425","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["임금미지급대기발령","해고존재","서면통지없음","해고예고수당지급","사용자해고인정"],"legal_focus":["해고서면통지의무","해고존재여부"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사용자해고인정+서면통지없음=부당해고"],"exclude_for_queries":[],"summary_short":"임금 미지급 대기발령+서면통지없음=부당해고","holding_summary":"임금 미지급+사용자 해고 인정(근로감독관 조사)+서면 통지 없음=부당해고","retrieval_note":"사용자 스스로 해고 인정한 서면통지 없음 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49449","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["pay_cut","transfer"],"fact_markers":["직장내괴롭힘휴게실방해","관계우위이용","감봉1개월정당","분리전보정당","근기법76조3항5항"],"legal_focus":["직장내괴롭힘징계","분리조치TV정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직장내괴롭힘가해자=감봉+분리전보=모두정당"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘 감봉+분리 전보 모두 정당","holding_summary":"직장내괴롭힘(휴게실 사용 방해)+감봉1개월=징계정당+피해자 분리 전보=업무상 필요성+TV정당","retrieval_note":"직장내괴롭힘 징계+분리전보 TV정당 복합 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49459","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무지시불이행","동료마찰","사전면담협의","취업규칙준수","직장질서유지","TV3대요건충족"],"legal_focus":["TV정당성3요건"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무지시불이행동료마찰=사전면담협의=TV정당"],"exclude_for_queries":[],"summary_short":"업무지시 불이행·동료 마찰 전보 사전면담 협의=TV정당","holding_summary":"업무지시 불이행+동료 마찰=직장질서 유지 업무상 필요성+생활상 불이익 없음+사전 면담 협의=TV정당","retrieval_note":"직장질서 유지 업무상 필요성+사전면담 협의 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49479","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"unknown","disposition_type":["no_formal_disposition"],"fact_markers":["센터장사업경영담당자","인사권행사권한","예산편성권","대외업무대표권","근로자성부정","구제신청각하"],"legal_focus":["근로자성판단","사업경영담당자"],"industry_context":"unknown","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["센터장사업경영담당자=인사권예산편성권=근로자성부정=각하"],"exclude_for_queries":[],"summary_short":"센터장 사업경영담당자=근로자성 부정=각하","holding_summary":"센터장=인사권·예산편성권·대외업무대표권 행사=사업경영담당자=근기법상 근로자 아님=구제신청 각하","retrieval_note":"시설 센터장 사업경영담당자 근로자성 부정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49481","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["법원확정징계사유","경징계대상양정과도","표창장감경대상","정직2월부당","전환배치TV정당"],"legal_focus":["징계양정재량권","TV정당성3요건"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["법원인정징계사유+경징계대상+표창감경대상=정직2월과도=부당","전환배치TV정당"],"exclude_for_queries":[],"summary_short":"법원 확정 징계사유+경징계대상+표창 감경=정직2월 양정 과도=부당","holding_summary":"법원 확정 징계사유+경징계 대상+표창 감경 대상=정직2월 양정 과도=부당, 전환배치=업무상 필요성+생활상 불이익 경미=TV정당","retrieval_note":"법원 확정 징계사유에도 양정 재량권 남용 부당 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49487","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근무장소사무실특정","재택근무명령","동의없음","구제이익존재","TV부당"],"legal_focus":["근무장소변경동의필요","TV정당성3요건"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["근무장소사무실특정+재택근무명령=동의없음=TV부당"],"exclude_for_queries":[],"summary_short":"근무장소 사무실 특정+재택근무명령=동의없음=TV부당","holding_summary":"근무장소 회사 사무실로 특정됨+동의 없이 재택근무 명령=TV부당","retrieval_note":"근무장소 특정 재택근무 동의 없음 TV부당 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49495","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직장내괴롭힘분리조치","업무상필요성인정","시간외수당감소근로형태변경결과","생활상불이익없음","협의절차준수"],"legal_focus":["TV정당성3요건","직장내괴롭힘분리조치"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직장내괴롭힘분리조치=시간외수당감소=근로형태변경결과=생활상불이익아님=TV정당"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘 분리 전보=시간외수당 감소=근로형태 변경 결과=불이익 아님=TV정당","holding_summary":"직장내괴롭힘 분리조치=업무상 필요성+시간외수당 감소는 근로형태 변경 결과(실질임금 저하 아님)+협의=TV정당","retrieval_note":"시간외수당 감소가 근로형태 변경 결과여서 생활상 불이익 아님","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49507","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["구제신청인지후복직명령","진정성없음","서면통지없음","부당해고","금전보상명령"],"legal_focus":["해고서면통지의무","복직명령진정성","금전보상명령"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["구제신청인지후복직명령진정성없음+서면통지없음=부당해고=금전보상"],"exclude_for_queries":[],"summary_short":"구제신청 인지 후 복직명령 진정성 없음+서면통지없음=부당해고","holding_summary":"구제신청 인지 후 서면통지 하자 치유 목적 복직명령=진정성 없음=구제이익 존재+서면통지 없음=부당해고+금전보상","retrieval_note":"복직명령 진정성 없음 구제이익+서면통지 없음 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49513","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["면직취소복직과정전보","팀장팀원전보","후속징계고려","TV정당","정직6월정당","법원확정징계사유"],"legal_focus":["TV정당성3요건","징계양정"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["면직취소복직후팀장팀원전보=업무상필요성+생활상불이익없음=TV정당","법원확정징계사유=정직6월양정정당"],"exclude_for_queries":[],"summary_short":"면직 취소 복직 후 팀장→팀원 전보 TV정당+정직6월 정당","holding_summary":"면직 취소 후 복직 과정에서 팀장→팀원 전보=업무상 필요성+생활상 불이익 없음=TV정당, 법원 확정 징계사유=정직6월 양정 정당","retrieval_note":"법원 취소 후 복직·후속징계 복합 사례 TV정당+징계정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49533","issue_type_primary":"discrimination","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["단시간근로자차별","전일제비교대상","급식비직무수당실적수당차별","기간제법차별금지","최저임금산정이유불충분"],"legal_focus":["기간제법차별금지","동종유사업무비교대상"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["단시간근로자급식비직무수당실적수당차별=합리적이유없음=차별인정"],"exclude_for_queries":[],"summary_short":"단시간근로자 급식비·직무수당 차별=합리적 이유 없음=차별 인정","holding_summary":"단시간근로자=비교대상 적절+급식비·직무수당·실적수당·연장휴일수당 미지급=최저임금 산정 이유 불충분=차별적 처우","retrieval_note":"단시간근로자 임금 항목별 차별 기간제법 위반","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49547","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["직위해제구제이익","직책수당시간외근무금지","5개월지연처분","검찰무혐의","사유없음","권리남용"],"legal_focus":["직위해제정당성","인사재량권한계"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직위해제=직책수당금지=구제이익존재","직위해제사유없음+5개월지연+검찰무혐의=권리남용=부당"],"exclude_for_queries":[],"summary_short":"직위해제 사유없음+5개월 지연+검찰 무혐의=권리남용=부당","holding_summary":"직위해제=직책수당·시간외근무 금지=구제이익 존재+사유 없음+5개월 지연+검찰 무혐의=권리남용=부당 직위해제","retrieval_note":"직위해제 구제이익 및 재량권 한계 부당 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49565","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["동일취지재심신청각하아님","업무상필요성인정","생활상불이익없음","TV정당"],"legal_focus":["TV정당성3요건","재심신청요건"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요성인정+생활상불이익없음=TV정당"],"exclude_for_queries":[],"summary_short":"인사발령 TV정당","holding_summary":"동일 취지 구제신청이 아니라 각하 대상 아님+업무상 필요성+생활상 불이익 없음=TV정당","retrieval_note":"재심신청 적법성+TV정당 복합 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49567","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity","transfer_validity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["재심제척기간기산점","판정서배달미통지","수취인없는사무실","제척기간미도과","정직정당","전보정당"],"legal_focus":["제척기간기산점","재심신청요건","TV정당성3요건","징계정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["판정서배달미통지수취인부재=제척기간기산점=실제인지일기산=미도과"],"exclude_for_queries":[],"summary_short":"판정서 배달 미통지=제척기간 기산점=실제 인지일+정직·전보 모두 정당","holding_summary":"판정서 배달 시 수취인 없는 사무실+배달 사실 미통지=실제 인지일부터 기산=제척기간 미도과+정직·전보 모두 정당","retrieval_note":"판정서 배달 완료 기준 제척기간 기산점 판단 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49571","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직위해제사유없음","생활상불이익큼","인사규정해석직위해제아님","권리남용","TV부당"],"legal_focus":["TV정당성3요건","직위해제정당성","인사규정해석"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직위해제사유없음+생활상불이익큼=부당직위해제=TV부당"],"exclude_for_queries":[],"summary_short":"직위 해제 사유 없음+생활상 불이익 큼=권리남용=부당","holding_summary":"직위 해제 사유 없음+업무상 필요성 대비 생활상 불이익 큼=권리남용=부당 직위해제+이에 따른 전보도 부당","retrieval_note":"직위해제 사유 없음 권리남용 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49575","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"unknown","disposition_type":["no_formal_disposition"],"fact_markers":["파견근로자","사용사업주당사자적격없음","임원면접미실시","계약직전환미성립","근로관계미성립"],"legal_focus":["근로관계성립요건","사용사업주사용자적격"],"industry_context":"unknown","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["파견근로자계약직전환임원면접미실시=근로관계미성립=사용사업주당사자적격없음=각하"],"exclude_for_queries":[],"summary_short":"파견근로자 계약직 전환 임원면접 미완료=근로관계 미성립=각하","holding_summary":"파견근로자=임원면접 미실시로 계약직 근로관계 미성립=사용사업주는 당사자 적격 없음=각하","retrieval_note":"파견근로자 계약직 전환 절차 미완료 근로관계 미성립","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_4959","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["무단결근","사용자유발책임","징계사유불인정","부당해고","금전보상","가해자현업근무"],"legal_focus":["징계사유정당성","사용자귀책사유"],"industry_context":"sales","exclusion_flags":[],"include_for_queries":["무단결근사용자유발책임=징계사유불인정=부당해고"],"exclude_for_queries":[],"summary_short":"무단결근 사용자 유발 책임=징계사유 불인정=부당해고","holding_summary":"무단결근=사용자 유발 책임 있음=징계사유 불인정=부당해고+금전보상","retrieval_note":"사용자 유발 무단결근 징계사유 불인정 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49611","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직장내괴롭힘분리조치","업무상필요성인정","생활상불이익현저","권리남용","노조전보요구","TV부당"],"legal_focus":["TV정당성3요건","생활상불이익형량"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직장내괴롭힘분리조치=업무상필요성인정이나생활상불이익더큼=권리남용=TV부당"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘 분리조치 업무상 필요성 인정이나 생활상 불이익 더 큼=TV부당","holding_summary":"직장내괴롭힘 분리조치 전보=업무상 필요성 인정이나 생활상 불이익이 더 큼=권리남용=TV부당","retrieval_note":"업무상 필요성 인정에도 생활상 불이익 형량 실패 TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49613","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["인사권없는관리소장","묵시적추인","해고존재","징계절차미준수","대체근로자채용","복직명령진정성없음","구제이익존재"],"legal_focus":["해고존재여부","해고권한","징계절차","구제이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사권없는자해고통보+사용자묵시적추인=해고존재","구제신청후대체근로자채용후복직명령=진정성없음=구제이익존재"],"exclude_for_queries":[],"summary_short":"인사권 없는 관리소장 해고+사용자 묵시적 추인=해고존재+절차 미준수=부당해고","holding_summary":"인사권 없는 관리소장 해고 통보+사용자 묵시적 추인=해고 존재+징계 절차 미준수=부당해고","retrieval_note":"인사권 없는 자 해고+묵시적 추인 해고존재 판단","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49615","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사직서제출강요","사직서미제출","해고존재","서면통지없음","복직명령진정성없음금전보상회피","금전보상명령"],"legal_focus":["해고존재여부","사직강요","복직명령진정성","구제이익","금전보상명령"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사직서강요+서면통지없음=해고존재=부당해고","복직명령금전보상회피목적=진정성없음=구제이익존재=금전보상"],"exclude_for_queries":[],"summary_short":"사직서 강요=해고존재+서면통지없음=부당해고+복직명령 진정성없음=금전보상","holding_summary":"사직서 제출 강요=해고 존재+서면 통지 없음=부당해고+복직명령 금전보상 회피 목적=진정성 없음=구제이익 존재+금전보상","retrieval_note":"사직서 강요 해고존재+복직명령 진정성 없음 구제이익 금전보상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49617","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성없음","생활상불이익현저","협의불충분","TV부당","조합활동방해","부당노동행위불이익취급병존","조합원자격상실"],"legal_focus":["TV정당성3요건","부당노동행위불이익취급"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV3대요건모두미충족=TV부당+조합활동방해목적=부당노동행위병존"],"exclude_for_queries":[],"summary_short":"TV 3대요건 미충족=TV부당+조합활동 방해 부당노동행위 병존","holding_summary":"업무상 필요성 없음+생활상 불이익 현저+협의 불충분=TV부당+조합활동 방해 부당노동행위 의사 추단=불이익취급 부당노동행위 병존","retrieval_note":"TV부당과 부당노동행위(불이익취급) 병존 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49627","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["dismissal","transfer"],"fact_markers":["징계절차단체협약위반","절차하자부당징계","전보업무상필요성","불이익없음","전보정당","부당노동행위증거불충분","부분인용"],"legal_focus":["징계절차단체협약","TV정당성3요건","부당노동행위"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계절차단체협약위반=절차하자=부당징계","전보업무상필요성+불이익없음=TV정당"],"exclude_for_queries":[],"summary_short":"징계절차 단체협약 위반=부당징계+전보 TV정당=부분인용","holding_summary":"근로자1 징계=단체협약상 절차 미준수=부당징계+근로자1,2 전보=업무상 필요성+불이익 없음=TV정당+부당노동행위 증거 불충분=기각=부분인용","retrieval_note":"단체협약 징계절차 위반 부당+TV정당 병존 부분인용","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49637","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["임의결행","징계사유불인정","배치전환그밖의징벌","부당징계근거배치전환","고정승무원대운전승무원"],"legal_focus":["징계사유인정기준","그밖의징벌구제신청대상","배치전환정당성"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["임의결행사유정직불인정+부당징계근거배치전환=그밖의징벌=부당"],"exclude_for_queries":[],"summary_short":"임의결행 사유 정직 불인정+부당 징계 근거 배치전환=그밖의징벌=부당","holding_summary":"임의 결행 사유 정직=징계사유 불인정+부당 징계 근거 배치전환=근기법23조 그밖의 징벌=부당","retrieval_note":"부당 징계 근거 배치전환=그밖의 징벌 해당 부당 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49659","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["보직변경제안거부","자진퇴거숙소","해고입증불충분","계속근로의사미표명","해고없음"],"legal_focus":["해고존재여부","근로자의사"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["보직변경거부후자진퇴거+계속근로의사미표명=해고없음"],"exclude_for_queries":[],"summary_short":"보직변경 거부 후 자진 퇴거+계속근로 의사 미표명=해고없음","holding_summary":"보직변경 제안 거부 후 자진 퇴거+계속 근로 의사 미표명=해고 존재 입증 불충분=해고없음","retrieval_note":"보직변경 거부 자진퇴거 해고 존재 불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_4967","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["서면통지없음","해고사유불충분","부당해고","금전보상금액정정","복직명령진정성인정"],"legal_focus":["해고서면통지의무","금전보상금액산정","복직명령진정성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["복직명령진정성인정=금전보상금액=해고일다음날부터복직명령일까지"],"exclude_for_queries":[],"summary_short":"서면통지없음=부당해고, 복직명령 진정성 인정→금전보상금액 정정","holding_summary":"해고사유 불충분+서면통지 없음=부당해고. 복직명령 진정성 인정→금전보상금액=해고일 다음날~복직명령일까지 정정","retrieval_note":"금전보상금액 산정 기준 복직명령 진정성 인정 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_4969","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["동료폭행","경사휴가허위신청","무단이탈","안전규정위반","폭언욕설","다수징계사유인정","정직3월정당","통지된징계사유한정"],"legal_focus":["징계사유정당성","징계양정","통지된징계사유한정"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["다수징계사유인정+정직3월양정적정=징계정당","통지된징계사유만인정"],"exclude_for_queries":[],"summary_short":"다수 징계사유 인정+정직3월 정당","holding_summary":"다수 징계사유(폭행·허위연차·무단이탈 등) 인정+정직3월=양정 적정+절차 정당, 통지된 징계사유만 인정","retrieval_note":"다수 징계사유 중 통지된 사유만 인정 정직3월 정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49691","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["contract_termination"],"fact_markers":["위수탁계약해지조항","근로자인지","근로계약자동해지","해고없음","수탁업체다수전보시도"],"legal_focus":["근로계약종료원인","해고존재여부"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["위수탁계약해지=취업규칙근로계약자동해지조항+근로자인지=해고없음"],"exclude_for_queries":[],"summary_short":"위수탁계약해지 취업규칙 자동해지 조항 근로자 인지=해고없음","holding_summary":"취업규칙·근로계약서상 위수탁계약 해지 시 근로계약 자동 해지 조항+근로자 인지=해고 없음","retrieval_note":"위수탁계약 해지 근로계약 자동종료 해고없음","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49697","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer","pay_cut"],"fact_markers":["관리감독자업무부적절","업무상필요성인정","생활상불이익경미","협의일부확인","TV정당","감봉정당"],"legal_focus":["TV정당성3요건","징계양정"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["관리감독자부적절=TV정당","협의절차미준수=당연무효아님=TV정당"],"exclude_for_queries":[],"summary_short":"관리감독자 부적절=TV정당+감봉 정당","holding_summary":"관리감독자 업무 부적절 판단+업무상 필요성+생활상 불이익 경미+협의 일부=TV정당+감봉 정당","retrieval_note":"관리감독자 업무 부적절 TV정당+감봉 복합 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49699","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["dismissal","transfer"],"fact_markers":["위탁계약종료","새근무지전보정당","전보거부집단행동","징계해고정당","부당노동행위증거불충분"],"legal_focus":["TV정당성3요건","징계사유정당성","부당노동행위"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["위탁계약종료후전보정당+전보거부집단행동=징계해고정당"],"exclude_for_queries":[],"summary_short":"위탁계약 종료 후 전보 정당+전보거부 집단행동=징계해고 정당","holding_summary":"위탁계약 종료 후 새 근무지 전보=업무상 필요성+생활상 불이익 없음=TV정당+전보 거부 집단행동=징계해고 정당+부당노동행위 증거 불충분=기각","retrieval_note":"전보거부 집단행동 징계해고 정당+부당노동행위 불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49705","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["고용보험상실처리의도적","해고존재","서면통지없음","부당해고","금전보상"],"legal_focus":["해고서면통지의무","해고존재여부"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["고용보험상실처리의도적=해고존재+서면통지없음=부당해고"],"exclude_for_queries":[],"summary_short":"고용보험 상실 처리 의도적=해고존재+서면통지없음=부당해고","holding_summary":"고용보험 상실 처리=착오 아니라 일방적 해고 의사=해고 존재+서면 통지 없음=부당해고+금전보상","retrieval_note":"고용보험 상실처리 의도성으로 해고존재 인정 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49709","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["팀장팀원인사발령","대표이사지시불이행제재","그밖의징벌해당","구제신청대상","사유입증불충분","부당"],"legal_focus":["그밖의징벌구제신청대상","징계사유정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["팀장팀원인사발령=대표이사지시불이행제재=그밖의징벌=구제신청대상+사유입증불충분=부당"],"exclude_for_queries":[],"summary_short":"팀장→팀원 인사발령=그밖의 징벌=구제신청 대상+사유 입증 불충분=부당","holding_summary":"팀장→팀원 인사발령=대표이사 지시 불이행 제재=근기법23조 그밖의 징벌=구제신청 대상+사유 입증 불충분=부당","retrieval_note":"팀장팀원 인사발령 그밖의 징벌 구제신청 대상 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49721","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["복직명령진정성없음","퇴사처리문자메시지","해고존재","서면통지없음","부당해고","구제이익존재"],"legal_focus":["해고존재여부","해고서면통지의무","복직명령진정성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["퇴사처리문자+서면통지없음=해고존재=부당해고+복직명령진정성없음=구제이익존재"],"exclude_for_queries":[],"summary_short":"퇴사처리 문자+서면통지없음=해고존재=부당해고","holding_summary":"복직명령 진정성 없음=구제이익 존재+퇴사처리 문자메시지=해고 존재+서면 통지 없음=부당해고","retrieval_note":"문자 퇴사처리 해고존재+서면통지 없음 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49743","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["예비운전자지정운전원","유리한처분","그밖의징벌해당않음","구제신청대상아님"],"legal_focus":["그밖의징벌구제신청대상"],"industry_context":"transport","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["인사발령=유리한처분=그밖의징벌해당않음=구제신청대상아님"],"exclude_for_queries":[],"summary_short":"예비→지정운전원=유리한 처분=그밖의 징벌 해당않음=구제신청 대상 아님","holding_summary":"예비운전자→지정운전원 발령=유리한 처분=근기법23조 그밖의 징벌 해당 않음=구제신청 대상 아님","retrieval_note":"유리한 인사발령 그밖의 징벌 미해당 구제신청 각하","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49749","issue_type_primary":"disciplinary_severity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal","other"],"fact_markers":["대기발령1정당","대기발령2제척기간도과","교통사고11대과실","징계해고정당","피해추산1750만원"],"legal_focus":["제척기간도과","징계사유정당성","징계양정"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["대기발령2=제척기간도과=구제대상아님","교통사고11대과실=피해액1750만=징계해고정당"],"exclude_for_queries":[],"summary_short":"대기발령2 제척기간 도과+교통사고 11대 과실=징계해고 정당","holding_summary":"대기발령1=구제이익+업무상 필요성=정당, 대기발령2=제척기간 도과, 교통사고 11대 과실+피해 1750만=징계해고 정당","retrieval_note":"복수 대기발령 제척기간+교통사고 과실 징계해고 정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_4975","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["이메일해고통지","해고존재","해고사유불충분","서면미통지","부당해고","원직복직불가능구제신청이익"],"legal_focus":["해고서면통지의무","해고존재여부","구제신청이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["이메일해고통지=해고존재+해고사유불충분+서면미통지=부당해고"],"exclude_for_queries":[],"summary_short":"이메일 해고통지=해고존재+사유 불충분+서면 미통지=부당해고","holding_summary":"원직복직 불가능이나 제척기간 내 신청=구제신청 이익 존재+이메일 해고 통지=해고 존재+사유 불충분+서면 미통지=부당해고","retrieval_note":"이메일 해고통지 해고존재 서면통지 없음 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49751","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["TFT해체조직개편","역량태도리더십평가배치","업무상필요성경영판단","생활상불이익없음","협의절차"],"legal_focus":["TV정당성3요건","경영판단존중"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["조직개편TFT해체+역량평가재배치=업무능률포괄고려=TV정당"],"exclude_for_queries":[],"summary_short":"TFT 해체+역량평가 재배치=업무상 필요성+생활상 불이익 없음=TV정당","holding_summary":"내구재TFT 해체+역량·태도·리더십 평가 재배치=업무상 필요성(경영 판단)+생활상 불이익 없음+협의=TV정당","retrieval_note":"TFT 해체 역량 평가 재배치 TV정당 경영 판단 존중","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49763","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무미숙업무거부","동료충돌","근로계약담당업무변경조항","업무상필요성","생활상불이익감수범위","협의"],"legal_focus":["TV정당성3요건"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무미숙+업무거부+동료충돌=업무상필요성+생활상불이익감수범위=TV정당"],"exclude_for_queries":[],"summary_short":"업무 미숙·거부·동료 충돌=TV정당","holding_summary":"업무 미숙+업무 거부+동료 충돌=업무상 필요성(직장질서 유지)+생활상 불이익 감수범위(통근 증가이나 현저않음)+협의=TV정당","retrieval_note":"업무미숙 직장질서 유지 업무상 필요성 TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49781","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["9개징계사유중6개인정","양정적정","징계절차적법","징계해고정당","폭언업무방해비위중함"],"legal_focus":["징계사유정당성","징계양정","징계절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["다수징계사유일부인정+양정적정+절차적법=징계해고정당"],"exclude_for_queries":[],"summary_short":"9개 징계사유 중 6개 인정+양정 적정=징계해고 정당","holding_summary":"9개 징계사유 중 6개 인정+폭언·업무방해 비위 중함+양정 적정+절차 적법=징계해고 정당","retrieval_note":"다수 징계사유 일부 인정 양정 적정 징계해고 정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49807","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사무국장1인체제","업무능력부족지도필요","업무상필요성","생활상불이익없음","협의절차"],"legal_focus":["TV정당성3요건"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["업무능력부족지도필요=TV정당","사용자적격산하조직본부"],"exclude_for_queries":[],"summary_short":"업무능력 부족 지도 필요=TV정당","holding_summary":"사무국장 업무능력 부족+지도 필요=업무상 필요성+생활상 불이익 없음+협의=TV정당","retrieval_note":"업무능력 부족 지도 목적 TV정당 사례","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49843","issue_type_primary":"union_activity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["조합원승진누락","통계적유의격차","쟁의활동기인","불이익취급부당노동행위인정","지배개입불인정","업무조정전보미해당"],"legal_focus":["부당노동행위불이익취급","그밖의징벌해당여부","통계증거"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["조합원승진누락=통계적격차+쟁의활동기인=불이익취급부당노동행위"],"exclude_for_queries":[],"summary_short":"조합원 승진 누락=통계적 격차+쟁의활동 기인=불이익취급 부당노동행위","holding_summary":"조합원 집단 승진 누락=통계적 유의 격차+쟁의활동 기인=불이익취급 부당노동행위+업무조정=전보 미해당+지배개입 불인정","retrieval_note":"승진 누락 통계 증거 불이익취급 부당노동행위 인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49859","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["동료폭행분리조치","직장질서유지","업무상필요성","협의절차","TV정당","부당노동행위아님"],"legal_focus":["TV정당성3요건","부당노동행위"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["동료폭행분리배치전환=직장질서유지=TV정당+부당노동행위증거없음"],"exclude_for_queries":[],"summary_short":"동료 폭행 분리 배치전환=TV정당+부당노동행위 아님","holding_summary":"동료 폭행 분리 배치전환=직장질서 유지 업무상 필요성+생활상 불이익 없음+협의=TV정당+부당노동행위 아님","retrieval_note":"동료 폭행 후 분리 배치전환 TV정당 부당노동행위 불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49861","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사직원제출구제이익없음각하","직장내괴롭힘분리조치","업무상필요성","생활상불이익없음","TV정당"],"legal_focus":["TV정당성3요건","구제이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직장내괴롭힘분리전보=업무상필요성+불이익없음=TV정당","사직원제출=구제이익없음=각하"],"exclude_for_queries":[],"summary_short":"근로자1 직장내괴롭힘 분리 TV정당+근로자2 사직원 제출=구제이익없음=각하","holding_summary":"근로자2=사직원 제출로 구제이익 없음=각하+근로자1=직장내괴롭힘 분리조치=업무상 필요성+불이익 없음=TV정당","retrieval_note":"사직원 제출 구제이익 없음+TV정당 복합 부분인용","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49867","issue_type_primary":"redundancy","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["코로나매출감소","긴박한경영상필요성인정","해고회피노력인정","선정기준없음","근로자대표협의불충분","정리해고부당"],"legal_focus":["정리해고4요건","선정기준합리성","협의절차"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["정리해고긴박성인정+해고회피노력인정+선정기준없음+협의불충분=정리해고부당"],"exclude_for_queries":[],"summary_short":"정리해고=긴박성+해고회피노력 인정이나 선정기준없음+협의불충분=부당","holding_summary":"정리해고=긴박한 경영상 필요성+해고 회피 노력 인정이나 대상자 선정 기준 없음+근로자대표 협의 불충분=부당","retrieval_note":"정리해고 4요건 중 선정기준·협의 미충족 부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49881","issue_type_primary":"discrimination","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["단시간근로자차별주장","비교대상남성근로자","임금인상률임금아님","대기발령차별이나합리적이유","혼인임신차별불인정"],"legal_focus":["성별임신차별","기간제법차별","비교대상판단"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["임금인상률=임금상차별금지영역아님","대기발령차별이나합리적이유존재=기각"],"exclude_for_queries":[],"summary_short":"임금인상률=임금 아님+대기발령 차별이나 합리적 이유=기각","holding_summary":"임금인상률=임금 상 차별금지영역 아님+대기발령=차별이나 혼인·임신 아닌 업무역량 부족 사유=합리적 이유=기각","retrieval_note":"임금인상률 차별금지 영역 해당 여부+대기발령 합리적 이유","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_49887","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["지부독립비법인사단아님","본부사용자적격","해고사유입증불충분","징계위원회절차미준수","부당해고"],"legal_focus":["사용자적격","해고사유정당성","징계절차"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["산하지부=독립비법인사단아님=본부가사용자","해고사유입증불충분+징계절차하자=부당해고"],"exclude_for_queries":[],"summary_short":"지부=독립 비법인 사단 아님=본부 사용자+해고사유 불충분+절차 하자=부당해고","holding_summary":"유공자회 지부=독립 비법인 사단 아님=본부에 사용자 적격+해고사유 입증 불충분+징계위원회 절차 미준수=부당해고","retrieval_note":"산하 지부 독립성 부정 본부 사용자 적격+징계절차 하자 부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

output_path = r'C:\dev\labor-decisions-search\retagging\output\reviewed\transfer_batch_066_reviewed.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')
print(f'총 {len(records)}건 작성 완료')
