import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')

records = [
    # ── transfer_validity TV정당 (14건) ──────────────────────────────────────────
    {
        "case_id": "id_43097",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": ["union_activity"],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["근무노선변경=전보인사명령", "인사재량권범위내=남용불인정", "부당노동행위아님"],
        "legal_focus": ["TV정당성", "부당노동행위불인정"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["근무노선변경=인사재량권범위내=TV정당+부당노동행위불인정"],
        "exclude_for_queries": [],
        "summary_short": "근무노선변경=전보 인사명령=인사재량권 범위 내=TV 정당+부당노동행위 불인정",
        "holding_summary": "근무노선변경=징계 아닌 전보 인사명령+인사재량권 남용·일탈 없음=TV 정당. 정당한 인사명령=부당노동행위 해당 않음",
        "retrieval_note": "버스 노선변경 TV정당+부당노동행위 불인정 병존",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43203",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무상필요성인정", "생활상불이익=통상감수범위", "협의절차미준수=당연무효아님"],
        "legal_focus": ["협의절차미준수=당연무효아님", "TV정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["TV업무상필요성인정+생활상불이익통상범위+협의미준수=당연무효아님=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "업무상 필요성+생활상 불이익 감수 범위+협의절차 미준수=당연 무효 아님=TV 정당",
        "holding_summary": "업무상 필요성 인정+생활상 불이익=통상 감수 범위+신의칙상 협의 미준수라도 당연 무효 아님=TV 정당",
        "retrieval_note": "협의절차미준수=당연무효아님 패턴 재확인. batch_055 id_413251, batch_058 id_41579와 동일 법리",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43337",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무상필요성인정", "생활상불이익=감수범위", "면담의견청취=협의절차준수"],
        "legal_focus": ["전직3요건충족=TV정당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["업무상필요성+생활상불이익감수범위+면담협의=전직3요건충족=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "업무상 필요성+생활상 불이익 감수 범위+면담 협의=전직 3요건 충족=TV 정당",
        "holding_summary": "전보=업무상 필요성 인정+생활상 불이익=통상 감수 범위+전보 전 면담·의견 청취=협의 절차 준수=TV 정당",
        "retrieval_note": "전직 3요건 모두 충족=TV 정당 정석 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43347",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["직무분석업무효율저조직무조정", "신직무신설", "사용자재량범위+업무능률증진"],
        "legal_focus": ["업무상필요성인정", "조직효율화TV정당"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["직무분석+업무효율저조직무조정+신직무신설=사용자재량=업무능률증진=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "직무분석+저효율 직무 조정·신직무 신설=사용자 재량=업무 능률 증진=TV 정당",
        "holding_summary": "상반기 직무분석으로 업무효율 저조 직무 조정+신직무(1:1 고객센터) 신설=사용자 재량 범위+업무 능률 증진 목적=업무상 필요성 충분=TV 정당",
        "retrieval_note": "직무분석 기반 직무 재편+신직무 신설 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43461",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["근로내용포괄적+근로장소불특정=인사권범위", "동료불화=업무상필요성"],
        "legal_focus": ["근로계약미특정=TV재량확대", "업무상필요성인정"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["근로내용포괄근로장소불특정=인사권범위+동료불화=업무상필요성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "근로내용 포괄·근로장소 불특정=인사권 범위+동료 불화=업무상 필요성=TV 정당",
        "holding_summary": "근로내용 포괄적·근로장소 불특정=인사권 범위 내+동료 불화 해결=업무상 필요성+생활상 불이익=감수 범위=TV 정당",
        "retrieval_note": "근로계약 장소 불특정+동료 불화=TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43469",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["직무변경필요성존재", "주거비보조=생활상불이익감수범위", "신의칙협의"],
        "legal_focus": ["업무상필요성인정", "주거비보조=생활상불이익완화"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["직무변경필요성+주거비보조=생활상불이익감수범위=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "직무변경 필요성+주거비 보조=생활상 불이익 감수 범위=TV 정당",
        "holding_summary": "직무변경 필요성 존재+사용자 하숙비(주거비) 보조=생활상 불이익=통상 감수 범위+협의 절차=TV 정당",
        "retrieval_note": "주거비 보조가 생활상 불이익 완화하여 감수 범위로 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_4347",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["청주공장생산량감소=인력재배치경영상필요성", "징계이력업무역량고려=인원선택합리성", "연봉→호봉변경이나임금유지"],
        "legal_focus": ["업무상필요성인정", "인원선정합리성"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["생산량감소인력재배치+징계이력업무역량=인원선택합리성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "청주공장 생산량 감소=인력 재배치+징계이력·역량 고려=인원선택 합리성=TV 정당",
        "holding_summary": "청주공장 생산량 대폭 감소=인력 재배치 경영상 필요성+근로자 징계이력·업무역량 고려=인원 선택 합리성 인정+연봉→호봉 변경이나 임금 수준 유지=TV 정당",
        "retrieval_note": "생산량 감소+징계이력 기반 인원선정 합리성=TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43491",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["경기팀장=공식팀장아닌내부호칭", "차장직급유지", "다른차장도팀원근무=징계아닌인사발령"],
        "legal_focus": ["비공식호칭변경=징계아닌인사발령=TV정당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["경기팀장=공식보직아닌내부호칭+차장직급유지=징계아닌인사발령=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "경기팀장=공식 보직 아닌 내부 호칭+차장 직급 유지=징계 아닌 인사발령=TV 정당",
        "holding_summary": "경기팀장=공식 팀장 보직 아닌 내부 편의 호칭+차장 직급 유지+다른 차장도 팀원 근무=징계성 처분 아닌 인사발령=TV 정당",
        "retrieval_note": "비공식 직함 변경=징계 아닌 인사발령 판단",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43515",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["근로계약서취업규칙업무변경가능명시", "COVID19베트남출장업무감소=업무량감소"],
        "legal_focus": ["업무상필요성인정", "COVID19업무감소TV정당"],
        "industry_context": "manufacturing",
        "exclusion_flags": [],
        "include_for_queries": ["근로계약업무변경가능+COVID19출장업무감소=업무상필요성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "근로계약 업무 변경 가능+COVID-19로 베트남 출장 업무 감소=TV 정당",
        "holding_summary": "근로계약서·취업규칙에 업무 변경 가능 명시+COVID-19로 베트남 출장 관련 업무 상당 감소=업무상 필요성 인정=TV 정당",
        "retrieval_note": "COVID-19로 인한 업무량 감소=업무상 필요성 인정 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43747",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["안전사고+민원다수=노선변경업무상필요성", "2018년교대노조집행부변경시전례"],
        "legal_focus": ["업무상필요성인정", "안전민원목적TV정당"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["안전사고+배차민원=노선변경업무상필요성+전례=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "안전사고+배차 민원=노선변경 업무상 필요성+전례=TV 정당",
        "holding_summary": "안전사고 발생 및 배차시간 민원 다수+이를 바로잡기 위한 노선변경 업무상 필요성+2018년 전례 확인=TV 정당",
        "retrieval_note": "안전사고+민원+전례=버스 노선변경 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43763",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["조직개편홍보팀→마케팅팀통폐합", "홍보업무외부위탁축소", "보복성인사주장입증없음"],
        "legal_focus": ["업무상필요성인정", "조직개편TV정당"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["홍보팀마케팅팀통폐합+홍보업무외부위탁=업무상필요성+보복주장입증없음=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "홍보팀→마케팅팀 통폐합+업무 외부 위탁=업무상 필요성+보복성 주장 입증 없음=TV 정당",
        "holding_summary": "조직개편으로 홍보팀→마케팅팀 통폐합+홍보 업무 외부 위탁 축소=업무상 필요성+보복성 인사발령 입증 근거 없음=TV 정당",
        "retrieval_note": "조직개편 팀 통폐합+업무 외부위탁 축소=TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43913",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["조직개편후전보", "업무유사+업무평가팀원요구반영=업무상필요성", "동직급다른직원도팀원"],
        "legal_focus": ["업무상필요성인정", "조직개편TV정당"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["조직개편+업무유사+업무평가팀원요구반영=업무상필요성=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "조직개편+업무 유사+업무평가·팀원 요구 반영=업무상 필요성=TV 정당",
        "holding_summary": "조직개편 후 전보+전후 업무 상당 부분 유사+업무평가·팀원 요구사항 반영=업무상 필요성 인정=TV 정당",
        "retrieval_note": "조직개편+업무 유사+다면평가 반영 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_4363",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["원격검침전환으로지점업무량인력편차", "정년퇴직인력편차심화", "발령지점인력부족", "58명동시전보"],
        "legal_focus": ["업무상필요성인정", "대규모전보업무상필요성"],
        "industry_context": "public",
        "exclusion_flags": [],
        "include_for_queries": ["원격검침전환+정년퇴직인력편차=발령지점인력부족=58명전보=TV정당"],
        "exclude_for_queries": [],
        "summary_short": "원격검침 전환+정년퇴직 인력 편차=발령 지점 인력 부족=58명 동시 전보=TV 정당(재심 유지)",
        "holding_summary": "원격검침 전환 업무량 편차+정년퇴직으로 지점 간 인력 편차 심화+발령 지점 인력 부족+같은 날 58명 동시 전보=업무상 필요성 인정=TV 정당(재심 유지)",
        "retrieval_note": "기술변화+퇴직 인력 편차 해소를 위한 대규모 전보 TV 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43969",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": ["no_dismissal"],
        "employment_stage": "regular",
        "disposition_type": ["transfer", "dismissal"],
        "fact_markers": ["위탁계약해지=TV업무상필요성+불가피성인정", "협의절차미준수=당연무효아님=TV정당", "근로관계종료=해고여부판단"],
        "legal_focus": ["위탁계약해지TV정당", "해고존재여부"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["위탁계약해지=TV업무상필요성불가피성인정+협의미준수=당연무효아님=TV정당=부분인용"],
        "exclude_for_queries": [],
        "summary_short": "위탁계약 해지=TV 업무상 필요성+불가피성 인정+협의 미준수=당연 무효 아님=TV 정당(부분인용)",
        "holding_summary": "위탁계약 해지로 인한 전보=업무상 필요성+불가피성 인정+협의 미준수=당연 무효 아님=TV 정당. 근로관계 종료=해고 여부 별도 판단=부분인용",
        "retrieval_note": "위탁계약 해지 TV 정당+해고 여부 부분인용",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── transfer_validity TV부당 (8건) ───────────────────────────────────────────
    {
        "case_id": "id_43077",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["씨스포빌→정도산업=인적물적장소적분리독립", "재무회계분리=동일사업장아님", "별개법인=전적해당"],
        "legal_focus": ["별개법인간전보=전적=동의필요=TV부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["별개법인간전보=인적물적장소적분리=동일사업장아님=전적=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "별개 법인 간 전보=인적·물적 분리=동일 사업장 아님=전적=TV 부당(재심 유지)",
        "holding_summary": "씨스포빌→정도산업=인적·물적·장소적 분리·독립+재무·회계 분리=동일 사업장 아님=독립 법인 간 전보=전적=동의 없음=TV 부당(재심 유지)",
        "retrieval_note": "별개 법인 간 전보=전적 인정=동의 없음=TV 부당. batch_057 id_41499와 동일 법리",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43083",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["근로계약서업무내용경리부특정", "전직시동의없음", "부당해고판정후전보=실질징계"],
        "legal_focus": ["근로계약직무특정=다른직무TV부당", "부당해고후전보=실질징계"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["근로계약서경리부업무특정+동의없음+부당해고후전보=실질징계=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "근로계약서 경리부 업무 특정+동의 없음+부당해고 판정 후 전보=실질 징계=TV 부당(재심 유지)",
        "holding_summary": "근로계약서 업무내용 '경리부' 특정+전직 시 동의 없음+부당해고 판정 받은 후 전보=실질 징계=TV 부당(재심 유지)",
        "retrieval_note": "근로계약 직무 특정=다른 직무 TV 부당. 부당해고 후 전보=실질 징계 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43129",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["사업소정상화=근로자와직접관련없음", "업무상필요성구체적객관적입증못함", "노조징계항의후전보"],
        "legal_focus": ["업무상필요성불충분=TV부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["사업소정상화=근로자와무관+업무상필요성입증못함=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "사업소 정상화=근로자와 직접 관련 없음+업무상 필요성 객관적 입증 못 함=TV 부당",
        "holding_summary": "사업소 정상화·발주사 요청=근로자와 직접 관련 없음+업무상 필요성 구체적·객관적 입증 실패=TV 부당",
        "retrieval_note": "TV 업무상 필요성 구체적·객관적 입증 요구=실패=TV 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43211",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["인사처리매뉴얼=단체협약성질", "위반횟수따른훈계시말서배치전환=징계절차규정", "징계절차미준수=TV부당"],
        "legal_focus": ["단체협약에의한징계성배치전환=징계절차필요=TV부당"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["인사처리매뉴얼=단체협약+배치전환=징계성격=징계절차미준수=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "인사처리 매뉴얼=단체협약 성질+배치전환=징계 성격=징계 절차 미준수=TV 부당",
        "holding_summary": "인사처리 매뉴얼=노조와 합의한 단체협약 성질+위반 횟수별 훈계·시말서·배치전환 규정=배치전환의 징계 성격=징계 절차 미준수=TV 부당",
        "retrieval_note": "단체협약 성질 매뉴얼+징계성 배치전환=징계 절차 필요. TV 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43223",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["근로계약근무부서장애인주간보호센터특정", "다년간동일업무", "동의없이다른근무지변경=TV부당"],
        "legal_focus": ["근로계약근무부서특정=동의없이변경=TV부당"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["근로계약근무부서특정+다년간동일업무=동의없이변경=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "근로계약 근무부서 특정+다년간 동일 업무=동의 없이 변경=TV 부당",
        "holding_summary": "근로계약서 근무부서=장애인주간보호센터로 특정+다년간 전보 없이 동일 업무=근로자 동의 없이 다른 근무지 변경=TV 부당",
        "retrieval_note": "근로계약 근무부서 특정+장기 동일 업무=동의 없는 변경=TV 부당. batch_058 id_42357과 동일 법리",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43495",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["직장내불화근본원인미확인", "인권위원회결정만근거전보결정", "폭언의원인불명확"],
        "legal_focus": ["업무상필요성불충분=TV부당"],
        "industry_context": "education",
        "exclusion_flags": [],
        "include_for_queries": ["불화근본원인미확인+인권위결정만근거전보=업무상필요성불충분=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "직장 내 불화 근본 원인 미확인+인권위 결정만 근거=업무상 필요성 불충분=TV 부당",
        "holding_summary": "직장 내 불화 근본 원인 확인 않고 인권위원회 결정만 근거로 전보 결정=업무상 필요성 불충분=TV 부당",
        "retrieval_note": "내부 조사 없이 외부 결정만 근거 TV=업무상 필요성 불충분=TV 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43803",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["업무능률증진기여어려움", "조직쇄신경력관리아님", "업무상필요성불인정"],
        "legal_focus": ["업무상필요성불충분=TV부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["전직=업무능률증진기여어려움+조직쇄신경력관리아님=업무상필요성불인정=TV부당(재심번복)"],
        "exclude_for_queries": [],
        "summary_short": "전직=업무 능률 증진 기여 어려움+조직 쇄신 아님=업무상 필요성 불인정=TV 부당(재심 번복)",
        "holding_summary": "전직=근로자 전체 업무 능률 증진 기여 어렵고+조직 쇄신·경력관리 차원 아님=업무상 필요성 불인정=TV 부당(재심에서 초심 TV정당 번복)",
        "retrieval_note": "업무능률증진·조직쇄신 목적 미충족=TV부당 재심 번복",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43903",
        "issue_type_primary": "transfer_validity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["하극상지시불이행보기어려움", "정치부장인사발령"],
        "legal_focus": ["업무상필요성불충분=TV부당"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["하극상지시불이행보기어려움=정치부장인사발령=업무상필요성불충분=TV부당"],
        "exclude_for_queries": [],
        "summary_short": "하극상·지시 불이행 행위 보기 어려움=정치부장 인사발령=업무상 필요성 불충분=TV 부당",
        "holding_summary": "편집국장에 대한 하극상·중요 보고 미이행 보기 어려움+정치부장으로 인사발령=업무상 필요성 불충분=TV 부당",
        "retrieval_note": "징계사유 입증 실패+전보=업무상 필요성 불충분=TV 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── disciplinary_severity (15건) ─────────────────────────────────────────────
    {
        "case_id": "id_43103",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": ["transfer_validity"],
        "employment_stage": "regular",
        "disposition_type": ["pay_cut", "transfer"],
        "fact_markers": ["감봉3개월=사유+양정+절차정당", "인사명령(전보대기발령)업무상필요성"],
        "legal_focus": ["징계정당성", "TV정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["감봉3개월=사유양정절차정당+전보대기발령업무상필요성=모두정당"],
        "exclude_for_queries": [],
        "summary_short": "감봉 3개월=사유·양정·절차 정당+인사명령(전보·대기발령)=업무상 필요성=모두 정당",
        "holding_summary": "감봉 3개월=징계사유 존재+양정 적정+절차 적법=정당. 인사명령(전보·대기발령)=업무상 필요성 인정=정당",
        "retrieval_note": "징계+TV 병존 사건=모두 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43109",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["구두해고=서면통지없음=근기법27조위반", "경영상해고요건도미충족"],
        "legal_focus": ["해고=서면통지위반=부당", "경영상해고요건"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["구두해고=서면통지없음=근기법27조위반=부당해고"],
        "exclude_for_queries": [],
        "summary_short": "구두 해고=서면통지 없음=근기법 27조 위반=부당해고",
        "holding_summary": "사용자 구두 해고=근기법 제27조 서면통지 의무 위반=부당. 경영상 이유에 의한 해고도 경영상 해고 요건 미충족=부당",
        "retrieval_note": "구두 해고=서면통지 없음=부당해고. 경영상 이유 해고 요건 병존 판단",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43111",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["방역수칙위반+시설위신손상+보고질서무시+업무지시위반=사유인정", "성실의무위반=사유불인정", "코호트격리=면직양정과도"],
        "legal_focus": ["징계사유일부인정이나면직양정과도"],
        "industry_context": "healthcare",
        "exclusion_flags": [],
        "include_for_queries": ["방역수칙위반등사유인정이나코호트격리결과=면직양정과도=징계부당"],
        "exclude_for_queries": [],
        "summary_short": "방역수칙 위반 등 사유 인정이나 코호트 격리 결과로 면직 양정 과도=징계 부당",
        "holding_summary": "방역수칙 위반·위신 손상·보고질서 무시·업무지시 위반=징계사유 인정. 코로나 확진으로 요양원 코호트 격리 결과를 감안하면 면직=양정 과도=징계 부당",
        "retrieval_note": "코호트 격리 결과 고려한 면직 양정 과도 판정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43139",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "probation",
        "disposition_type": ["rejection_of_regular_employment"],
        "fact_markers": ["취업규칙수습3개월명시", "근로계약서수습3개월명시", "본채용거부정당성"],
        "legal_focus": ["수습기간본채용거부정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["취업규칙+근로계약서수습3개월명시=시용계약+본채용거부정당성판단=부당"],
        "exclude_for_queries": [],
        "summary_short": "취업규칙+근로계약서 수습 3개월 명시=시용계약=본채용 거부 부당",
        "holding_summary": "취업규칙·근로계약서에 수습기간 3개월 명시=시용근로계약. 사용자 스스로 퇴직 주장이나 입증 실패=본채용 거부 부당",
        "retrieval_note": "수습기간 명시=시용계약 인정. 본채용 거부 정당성 판단",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43191",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": ["transfer_validity"],
        "employment_stage": "regular",
        "disposition_type": ["suspension", "transfer"],
        "fact_markers": ["업무지시거부+팀장고성비아냥=징계사유", "기능향상지원팀발령후업무거부=징계"],
        "legal_focus": ["징계사유인정=징계정당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["업무지시거부+팀장비아냥+인사발령후업무거부=징계사유=정당"],
        "exclude_for_queries": [],
        "summary_short": "업무지시 거부+팀장 비아냥+발령 후 업무 거부=징계사유 인정=징계 정당",
        "holding_summary": "상급자 업무지시 거부·불이행+팀장에 고성·비아냥=징계사유. 기능향상지원팀 발령 후 장기간 업무 거부+정당한 업무 지시 불이행=징계 정당",
        "retrieval_note": "업무지시 거부+발령 후 업무 거부 징계 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_4325",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["근로자1=반송여신부당취급+운전자금부당취급+대표자변경부당여신+부당신용평가여신=모두징계사유", "근로자2=최종결재"],
        "legal_focus": ["금융여신부당취급=징계사유=징계정당"],
        "industry_context": "finance",
        "exclusion_flags": [],
        "include_for_queries": ["금융여신부당취급복수행위=모두징계사유=복수근로자징계정당"],
        "exclude_for_queries": [],
        "summary_short": "금융 여신 부당취급 복수 행위=모두 징계사유=징계 정당",
        "holding_summary": "반송여신 부당취급·운전자금 부당취급·대표자 변경 부당여신·부당 신용평가 여신=모두 인사규정 징계사유 해당=징계 정당",
        "retrieval_note": "금융기관 복수 여신 부당취급=징계사유 모두 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43301",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "probation",
        "disposition_type": ["rejection_of_regular_employment"],
        "fact_markers": ["근로계약서수습기간명시=시용근로계약", "본채용거부=사용자주장스스로퇴직이나입증실패"],
        "legal_focus": ["수습기간본채용거부정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["수습기간명시=시용계약+스스로퇴직주장입증실패=본채용거부부당"],
        "exclude_for_queries": [],
        "summary_short": "수습기간 명시=시용계약+스스로 퇴직 주장 입증 실패=본채용 거부 부당",
        "holding_summary": "근로계약서 수습기간 3개월 명시=시용근로계약. 사용자 주장 스스로 퇴직=입증 실패=본채용 거부 부당",
        "retrieval_note": "시용계약 인정+스스로 퇴직 주장 입증 실패=본채용 거부 부당. batch_059 id_43139와 동일 패턴",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43403",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["협박문자메시지", "노래방참석대가급여인상약속", "부당업무지시등부적절면모", "업무..."],
        "legal_focus": ["징계사유인정"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["협박문자+노래방성희롱발언+부당업무지시=징계사유=징계정당(재심번복)"],
        "exclude_for_queries": [],
        "summary_short": "협박 문자+노래방 대가 약속+부당 업무지시=징계사유=징계 정당(재심에서 초심 번복)",
        "holding_summary": "퇴사 직원 협박 문자+노래방 참석 대가 급여인상 약속+부당 업무지시 부적절=징계사유 인정=징계 정당(재심에서 초심 결과 번복)",
        "retrieval_note": "협박문자+성희롱성 발언+부당업무지시=징계사유 인정 재심 번복",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43405",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["징계사유3가지인정(본인인정)", "응급실전환배치배경+과실정도+병원징계사례고려=면직양정과도"],
        "legal_focus": ["징계사유인정이나면직양정과도=징계부당"],
        "industry_context": "healthcare",
        "exclusion_flags": [],
        "include_for_queries": ["업무과실3가지인정이나응급실전환배치배경고려=면직양정과도=징계부당"],
        "exclude_for_queries": [],
        "summary_short": "업무과실 3가지 인정이나 응급실 전환배치 배경+과실 정도 고려=면직 양정 과도=징계 부당",
        "holding_summary": "3가지 업무과실 징계사유 인정이나 응급실 전환배치 배경·과실 정도·병원 징계 사례 종합=면직 양정 과도=징계 부당",
        "retrieval_note": "징계사유 인정+전환배치 배경 고려=면직 양정 과도 판정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43415",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["demotion"],
        "fact_markers": ["인사위원회개최=징계절차", "출석통지서회의록징계처분통지서=강등을징계로기재", "급여삭감=징계로인정"],
        "legal_focus": ["강등=징계인정=징계정당성판단"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["인사위원회+징계처분통지서강등기재+급여삭감=강등=징계인정=정당성판단"],
        "exclude_for_queries": [],
        "summary_short": "인사위원회+징계통지서 강등 기재+급여 삭감=강등=징계로 인정=정당성 판단",
        "holding_summary": "인사위원회 개최+출석통지서·회의록·징계처분통지서에 강등을 징계로 기재+급여 삭감=강등=징계로 인정=징계 정당성(사유·양정) 판단 후 부당",
        "retrieval_note": "강등=징계 인정의 기준(서류 기재+급여 삭감). 이후 양정 과도=징계 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43431",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["9회지각=출퇴근기록+메신저확인", "업무계획표약속업무중1개제외미이행"],
        "legal_focus": ["징계사유인정=징계정당(재심번복)"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["9회지각+업무계획약속미이행=징계사유=징계정당(재심번복)"],
        "exclude_for_queries": [],
        "summary_short": "9회 지각+업무계획 미이행=징계사유 인정=징계 정당(재심에서 초심 번복)",
        "holding_summary": "출퇴근 기록·메신저 확인으로 9회 지각 확인+업무계획표 약속 업무 대부분 미이행=징계사유 인정=징계 정당(재심에서 초심 징계부당 번복)",
        "retrieval_note": "지각+업무계획 미이행 객관적 증거=징계사유 인정 재심 번복",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43639",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["전자우편삭제+컴퓨터초기화+문서파쇄=사유인정", "나머지혐의=불인정", "2가지사유로해고=양정과도=부분인용"],
        "legal_focus": ["징계사유일부인정이나해고양정과도=부분인용"],
        "industry_context": "office",
        "exclusion_flags": [],
        "include_for_queries": ["전자우편삭제컴퓨터초기화문서파쇄=사유인정+해고양정과도=부분인용"],
        "exclude_for_queries": [],
        "summary_short": "전자우편 삭제·컴퓨터 초기화·문서파쇄=사유 인정+해고 양정 과도=부분인용",
        "holding_summary": "전자우편 삭제·컴퓨터 초기화·문서파쇄=징계사유 인정. 나머지 혐의=불인정. 2가지 인정 사유에 비해 해고=양정 과도=부분인용",
        "retrieval_note": "증거인멸성 행위 징계사유 인정이나 해고 양정 과도=부분인용",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43655",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["suspension"],
        "fact_markers": ["총지배인직무대리인사발령=직무규정위반주장", "직무대리=임시대행=상급자공석시", "검토소홀=징계사유주장"],
        "legal_focus": ["징계사유정당성"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["총지배인직무대리인사발령직무규정위반주장=임시대행성격=징계사유판단"],
        "exclude_for_queries": [],
        "summary_short": "총지배인 직무대리 인사발령=직무규정 위반 주장이나=임시대행 성격=징계사유 판단(재심 유지)",
        "holding_summary": "총지배인 직무대리=직무규정 위반·이사회 권한 침해 징계사유. 직무대리=상급자 공석·결원 시 하급자 임시 대행=관련 규정 확인 소홀 징계사유 판단(재심 유지)",
        "retrieval_note": "직무대리 인사발령=직무규정 위반 여부 및 검토 소홀 징계사유",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43807",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["인사위원회미개최=소명기회미부여", "해고통지서서면통지없음=절차하자"],
        "legal_focus": ["해고절차하자=해고부당"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["인사위원회미개최소명기회미부여+서면해고통지없음=절차하자=해고부당"],
        "exclude_for_queries": [],
        "summary_short": "인사위원회 미개최 소명기회 미부여+서면 해고통지 없음=절차 하자=해고 부당",
        "holding_summary": "취업규칙상 인사위원회 미개최=소명기회 미부여+해고 통지서 서면 통지 없음=절차 하자=해고 부당. 금전보상 수용",
        "retrieval_note": "인사위원회 미개최+서면통지 없음=이중 절차 하자=해고 부당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43975",
        "issue_type_primary": "disciplinary_severity",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["disciplinary_dismissal"],
        "fact_markers": ["채용비리+업무방해죄=벌금200만원집행유예1년확정", "인사규정면직사유적용"],
        "legal_focus": ["형사처벌확정=면직사유=면직정당"],
        "industry_context": "public",
        "exclusion_flags": [],
        "include_for_queries": ["채용비리업무방해죄벌금200만원+집행유예1년확정=인사규정면직사유=면직정당"],
        "exclude_for_queries": [],
        "summary_short": "채용비리 업무방해죄 벌금 200만원+집행유예 1년 확정=인사규정 면직 사유=면직 정당",
        "holding_summary": "채용비리 관련 업무방해죄 벌금 200만원+집행유예 1년 확정판결=인사규정 면직 사유 해당=면직 정당. 사유·시기 명시 통지=절차 적법",
        "retrieval_note": "형사처벌 확정=인사규정 면직사유 해당=면직 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── procedure (7건) ──────────────────────────────────────────────────────────
    {
        "case_id": "id_43183",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["8개팀중팀간이동", "공사규정전보=부서간이동", "팀=부서아님=전보해당않음"],
        "legal_focus": ["전보미해당=구제신청대상아님"],
        "industry_context": "public",
        "exclusion_flags": ["procedure_dominant"],
        "include_for_queries": ["팀간이동=공사규정전보=부서간이동이나팀=부서아님=전보해당않음=각하"],
        "exclude_for_queries": [],
        "summary_short": "팀 간 이동=공사 규정상 전보=부서 간 이동이나 '팀'=부서 아님=전보 해당 않음",
        "holding_summary": "8개 팀 중 전기재생팀→기술팀 이동=공사 규정상 전보=부서 간 이동이나 '팀'=부서 아님=전보 해당 않음=구제신청 대상 아님",
        "retrieval_note": "팀 간 이동=부서 간 이동 아님=전보 미해당=각하. 내부 규정 부서 정의 기준",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43305",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["전보인사명령일2021.9.7", "3개월도과2021.12.9구제신청", "제척기간도과=각하"],
        "legal_focus": ["제척기간3개월도과=각하"],
        "industry_context": "unknown",
        "exclusion_flags": ["procedure_dominant"],
        "include_for_queries": ["전보발령일2021.9.7기준3개월도과2021.12.9신청=제척기간도과=각하"],
        "exclude_for_queries": [],
        "summary_short": "전보 발령일 기준 3개월 도과=각하",
        "holding_summary": "전보 인사명령일 2021.9.7로부터 3개월 도과한 2021.12.9 구제신청=근기법 제28조 제척기간 도과=각하",
        "retrieval_note": "전보 발령일 기준 제척기간 3개월=도과=각하",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43401",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["민법111조의사표시도달=전보알린시점효력발생", "전보통지일=제척기간기산점"],
        "legal_focus": ["전보효력발생시기=제척기간산정"],
        "industry_context": "service",
        "exclusion_flags": [],
        "include_for_queries": ["민법111조=의사표시도달시효력발생=전보알린날=제척기간기산"],
        "exclude_for_queries": [],
        "summary_short": "민법 제111조=의사표시 도달 시 효력=전보 알린 날=제척기간 기산점",
        "holding_summary": "민법 제111조 의사표시 효력발생시기=전보를 알린 2021.5.23 시점부터 효력 발생=전보 알린 날이 제척기간 기산점=3개월 이내 구제신청 판단(재심 유지)",
        "retrieval_note": "전보 효력발생시기=통지일(도달일). 제척기간 기산점 판단",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43597",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["원직복직명령+출근독촉+임금일부지급=원직복직이행"],
        "legal_focus": ["원직복직이행=구제이익소멸"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["원직복직명령+출근독촉+임금일부지급=원직복직이행=구제이익소멸"],
        "exclude_for_queries": [],
        "summary_short": "원직복직 명령+출근 독촉+임금 일부 지급=원직복직 이행=구제이익 소멸",
        "holding_summary": "사용자가 원직복직 명령 내용증명 발송+출근 독촉+임금 일부 지급=원직복직 이행=구제이익 소멸",
        "retrieval_note": "원직복직 이행(명령+독촉+임금지급)=구제이익 소멸",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43753",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["사용자1=상표권자+공동임차인=관련있으나사용자적격입증부족", "사용자2=근로자근무"],
        "legal_focus": ["사용자적격판단"],
        "industry_context": "retail",
        "exclusion_flags": [],
        "include_for_queries": ["상표권자=사용자적격입증부족+근로자직접근무법인=사용자2적격"],
        "exclude_for_queries": [],
        "summary_short": "상표권자=관련 있으나 사용자 적격 입증 부족+근로자 직접 근무 법인=사용자 적격 인정",
        "holding_summary": "사용자1=상표권자+공동임차인=매장 관련 있으나 사용자 적격 구체적 입증 자료 부족. 사용자2=근로자 실제 근무=사용자 적격 인정(재심 유지)",
        "retrieval_note": "상표권자≠당연 사용자. 근로자 직접 근무 법인=사용자 적격",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43765",
        "issue_type_primary": "procedure",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["transfer"],
        "fact_markers": ["징계해고전업무직위임금동일복직=원직복직이행", "업무변경인사명령=원직복직아님주장이나인정안됨"],
        "legal_focus": ["원직복직이행=구제이익소멸"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["징계해고전업무직위임금동일복직=원직복직이행=구제신청대상아님"],
        "exclude_for_queries": [],
        "summary_short": "징계해고 전 업무·직위·임금 동일 복직=원직복직 이행=구제신청 대상 아님",
        "holding_summary": "사용자가 징계해고 전 근로자 업무·직위·임금 동일하게 유지하여 복직 명령=원직복직 이행=업무변경 인사명령=구제신청 대상 아님",
        "retrieval_note": "징계해고 전 조건 동일 복직=원직복직 이행 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43769",
        "issue_type_primary": "procedure",
        "issue_type_secondary": ["disciplinary_severity"],
        "employment_stage": "regular",
        "disposition_type": ["transfer", "dismissal"],
        "fact_markers": ["근로계약서작성거부+결근=배치전환명령없음", "배치전환=구제명령대상아님", "무단결근=해고정당"],
        "legal_focus": ["배치전환미존재=구제신청대상없음", "무단결근해고정당"],
        "industry_context": "unknown",
        "exclusion_flags": ["procedure_dominant"],
        "include_for_queries": ["근로계약서거부+결근상태=배치전환명령없음=구제신청대상아님+무단결근=해고정당"],
        "exclude_for_queries": [],
        "summary_short": "근로계약서 작성 거부+결근=배치전환 명령 없음=구제신청 대상 없음+무단결근=해고 정당",
        "holding_summary": "복직 과정에서 근로계약서 서명 거부+결근 상태=배치전환 명령 없음=구제명령 대상 아님. 장기 무단결근=해고 정당(재심 유지)",
        "retrieval_note": "복직 시 근로계약서 거부+결근=배치전환 미존재. 무단결근 해고 정당",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── no_dismissal (4건) ───────────────────────────────────────────────────────
    {
        "case_id": "id_43165",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["권고사직통보서=일방적근로관계종료=해고의사표시", "근로자동의사직서없음", "사용자1개월해고예고수당언급"],
        "legal_focus": ["권고사직통보서=해고의사표시=해고존재"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["권고사직통보서=일방적종료=해고의사표시+동의사직서없음=해고존재"],
        "exclude_for_queries": [],
        "summary_short": "권고사직 통보서=일방적 종료=해고 의사표시+동의·사직서 없음=해고 존재(재심 유지)",
        "holding_summary": "권고사직 통보서=사용자 일방적 근로관계 종료 통보=해고 의사표시+근로자 동의·사직서 없음+1개월 해고예고수당 언급=해고 존재(재심 유지)",
        "retrieval_note": "권고사직 통보서=해고 의사표시 인정. 동의 없음=해고 존재",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43535",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["형식일용직이나10년이상계속근로=상용근로자", "2021.4.30공사종료통보=해고"],
        "legal_focus": ["형식일용직+장기계속근로=상용근로자인정=해고존재"],
        "industry_context": "construction",
        "exclusion_flags": [],
        "include_for_queries": ["형식일용직이나10년이상계속근로=상용근로자인정+공사종료통보=해고존재"],
        "exclude_for_queries": [],
        "summary_short": "형식 일용직이나 10년 이상 계속 근로=상용근로자 인정=공사 종료 통보=해고 존재(재심 번복)",
        "holding_summary": "형식상 일용직이나 동일 사용자에게 10년 이상 계속 근로=근로관계 단절 없음=상용근로자 인정+2021.4.30 공사 종료 이유 일방적 근로관계 종료 통보=해고 존재(재심에서 초심 번복)",
        "retrieval_note": "형식 일용직+장기 계속 근로=상용근로자 인정. 공사 종료 통보=해고 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43865",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["사직철회수용했다면서2021.9.7사직입장확인전화", "팀새롭게꾸린다전달+복직배치전환논의없음"],
        "legal_focus": ["해고의사표시인정=해고존재"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["사직철회수용주장이나사직입장확인전화+팀재구성전달복직논의없음=해고존재"],
        "exclude_for_queries": [],
        "summary_short": "사직 철회 수용 주장이나 사직 입장 확인 전화+팀 재구성 전달=해고 존재(재심 유지)",
        "holding_summary": "사직 철회 수용했다면서도 2021.9.7 사직 입장 확인 전화+팀 새롭게 꾸린다 전달+복직·배치전환 논의 없음=해고 존재(재심 유지)",
        "retrieval_note": "사직 철회 수용 주장 불신=해고 의사표시 행태 증거=해고 존재",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    {
        "case_id": "id_43929",
        "issue_type_primary": "no_dismissal",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["사직서제출거부에도", "사직의사표시동의사실확인없이", "고용보험피보험자격상실신고임의=해고"],
        "legal_focus": ["사직서거부에도일방상실신고=해고존재"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["사직서제출거부에도사직의사확인없이고용보험일방상실신고=해고존재"],
        "exclude_for_queries": [],
        "summary_short": "사직서 제출 거부에도 사직의사 확인 없이 고용보험 일방 상실신고=해고 존재",
        "holding_summary": "근로자 사직서 제출 거부에도 사직의사 표시·동의 사실 확인 없이 고용보험 피보험자격 상실신고 임의 처리=사용자 일방적 근로관계 종료=해고 존재",
        "retrieval_note": "사직서 거부에도 고용보험 일방 상실신고=해고 존재 인정",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── union_activity (1건) ─────────────────────────────────────────────────────
    {
        "case_id": "id_43629",
        "issue_type_primary": "union_activity",
        "issue_type_secondary": ["procedure"],
        "employment_stage": "regular",
        "disposition_type": ["other"],
        "fact_markers": ["7.5인사발령=정당한인사권범위=부당노동행위아님", "7월성과급미지급"],
        "legal_focus": ["부당노동행위불인정"],
        "industry_context": "unknown",
        "exclusion_flags": [],
        "include_for_queries": ["인사발령=정당인사권=부당노동행위의사불인정(재심번복)"],
        "exclude_for_queries": [],
        "summary_short": "인사발령=정당한 인사권 범위=부당노동행위 의사 불인정(재심에서 초심 번복)",
        "holding_summary": "7.5 인사발령=정당한 인사권 범위+부당노동행위 의사에 기인한 것이라고 단정 어려움=부당노동행위 불인정(재심에서 초심 인용 번복)",
        "retrieval_note": "인사발령=정당 인사권 범위=부당노동행위 의사 불인정 재심 번복",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
    # ── redundancy (1건) ─────────────────────────────────────────────────────────
    {
        "case_id": "id_43029",
        "issue_type_primary": "redundancy",
        "issue_type_secondary": [],
        "employment_stage": "regular",
        "disposition_type": ["dismissal"],
        "fact_markers": ["민영제버스노선운영", "운전직인건비연료비차량감가상각=입찰대상아님", "업무효율화비용절감재량"],
        "legal_focus": ["정리해고요건", "경영상해고"],
        "industry_context": "transport",
        "exclusion_flags": [],
        "include_for_queries": ["민영제버스노선=운전직인건비입찰대상아님=효율화재량=정리해고관련(재심번복)"],
        "exclude_for_queries": [],
        "summary_short": "민영제 버스 노선=운전직 인건비 입찰 대상 아님=사용자 비용절감 재량=정리해고 관련(재심 번복)",
        "holding_summary": "민영제 버스 노선 운영+운전직 인건비·연료비·차량감가상각=입찰 대상 아님+사용자의 업무 효율화 비용 절감 재량 범위=정리해고 관련 판단(재심에서 초심 번복)",
        "retrieval_note": "버스 운영 민영화+비용구조=정리해고 정당성 판단",
        "confidence": "high",
        "review_status": "approved",
        "tag_version": "v3"
    },
]

out_path = "retagging/output/reviewed/transfer_batch_059_reviewed.jsonl"
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print(f"Written {len(records)} records")
