import json, pathlib
out = pathlib.Path("retagging/output/reviewed/transfer_batch_023_reviewed.jsonl")
records = [
# ── transfer_validity (23건) ──────────────────────────────────────────────────
{"case_id":"id_3107","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["3요건충족","업무상필요성인정","생활상불이익작음","절차정당","근로계약서변경가능명시"],"legal_focus":["업무상필요성","생활상불이익","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사발령3요건충족_업무상필요성인정_절차정당_생활상불이익작음"],"exclude_for_queries":[],"summary_short":"인사발령 3요건 충족 정당","holding_summary":"근로계약서에 근무지·담당업무 변경 가능 명시. 인사발령에 있어 업무상 필요성이 인정되고, 근로자의 생활상의 불이익이 크다고 볼 수 없으며, 절차상의 하자도 없어 정당","retrieval_note":"전보 3요건 충족 정당. 근로계약서 변경가능 명시 전보 정당 근거로 작용","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31121","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["관리자→생소업무","재택근무명령","업무상필요성없음","신분불이익"],"legal_focus":["업무상필요성없음","생활상불이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["관리자생소업무재택근무명령_업무상필요성없음_신분불이익_부당"],"exclude_for_queries":[],"summary_short":"관리자→모니터링+재택근무 명령 업무상필요성없음 부당","holding_summary":"사용자가 관리자로 근무해 온 근로자에게 생소한 업무를 맡기면서 재택근무를 명한 것에 업무상 필요성이 있다고 볼 수 없고, 사실상 신분에 불이익을 주는 등 불이익의 정도도 커 부당인사발령","retrieval_note":"관리자→생소업무+재택근무 발령. 업무상필요성없음+신분불이익 복합. batch_022 id_30773(센터장하향)과 유사","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31135","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사무직→운전직","기본급1/4감소","업무상필요성없음","육체적정신적부담과다"],"legal_focus":["업무상필요성없음","생활상불이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사무직→운전직전직_기본급1/4감소_업무상필요성없음_부당"],"exclude_for_queries":[],"summary_short":"사무직→운전직 기본급 1/4 감소 업무상필요성없음 부당","holding_summary":"사무직을 운전직으로 변경한 전직명령은 업무상 필요성이 확인되지 않고, 기본급이 1/4로 줄었고, 3년 이상 사무업무에서 갑자기 운전업무를 하게 되는 육체적·정신적 부담이 수인범위 초과하여 부당","retrieval_note":"사무직→운전직 이질배치. 기본급 1/4 감소 생활상불이익 인정. batch_018 id_26569(단기계약+이질배치)와 유사","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_3115","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity","union_activity"],"employment_stage":"regular","disposition_type":["transfer","suspension"],"fact_markers":["단체협약잠정합의서위반","사전합의없는인사발령","부당인사발령사유정직도부당","부당노동행위의사없음"],"legal_focus":["단체협약잠정합의서","협의절차위반","부당노동행위의사"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["단체협약잠정합의서위반인사발령_부당_부당사유정직도부당_부당노동행위의사없음기각"],"exclude_for_queries":[],"summary_short":"단체협약 잠정합의서 위반 인사발령 부당 + 정직도 부당 + 부당노동행위 의사없음 기각","holding_summary":"인사발령은 사전에 노동조합과 합의하여야 한다는 단체협약 잠정합의서를 위반하여 부당하고, 부당한 인사발령을 사유로 행한 정직처분도 부당하나, 사용자에게 부당노동행위 의사 있다고 단정하기 어려워 기각","retrieval_note":"단체협약 잠정합의서 위반이 전보 협의절차 위반 근거. 부당인사발령+파생징계 동시 부당. batch_020 id_28915(단체협약위반전보=부당노동행위)와 비교 — 이 사건은 부당노동행위 의사 불인정","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31277","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["포장부→영업부이질배치","업무상필요성없음","생활상불이익크다","협의절차미준수"],"legal_focus":["업무상필요성없음","생활상불이익","협의절차"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["포장부영업부이질배치_업무상필요성없음_생활상불이익_협의없음_부당"],"exclude_for_queries":[],"summary_short":"포장부→영업부 이질배치 3요건 모두 불충족 부당","holding_summary":"포장부 근로자를 영업부로 전환배치한 것은 경영상 필요에 적합한 수단이라고 볼 수 없어 업무상 필요성이 인정되지 않고, 근로자들의 생활상 불이익이 크며, 신의칙상 요구되는 절차도 준수하지 않아 부당","retrieval_note":"생산직→영업직 이질배치 부당. 3요건 모두 불충족. batch_016 id_25049, batch_020 id_2829(설계→청소) 이질배치 반복 패턴","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31329","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["보직해임","인사발령","업무상필요성인정","생활상불이익작음","사전협의완료"],"legal_focus":["업무상필요성","생활상불이익","협의절차"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["보직해임후인사발령_3요건충족_사전협의완료_정당"],"exclude_for_queries":[],"summary_short":"보직해임+인사발령 3요건 충족 사전협의 정당","holding_summary":"보직해임 및 인사발령의 업무상 필요성이 인정되고, 생활상 불이익이 크지 않고, 사전협의도 거쳐 정당한 인사권 행사","retrieval_note":"보직해임+전보 동시 다툼에서 3요건 충족 정당. education 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31339","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요배치전환","부당노동행위의사없음","배치전환정당"],"legal_focus":["업무상필요성","부당노동행위의사"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요배치전환_부당노동행위의사없음_기각"],"exclude_for_queries":[],"summary_short":"배치전환 정당 + 부당노동행위 의사없음 기각","holding_summary":"업무상 필요에 따른 배치전환은 정당하고 부당노동행위에 해당하지 않아 기각","retrieval_note":"배치전환+부당노동행위 동시 다툼. 배치전환 정당+부당노동행위의사없음 기각 패턴","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31367","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion"],"fact_markers":["직급강등","업무상필요성없음","생활상불이익상당","협의없음"],"legal_focus":["업무상필요성없음","생활상불이익","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직급강등_3요건모두불충족_부당"],"exclude_for_queries":[],"summary_short":"직급강등 업무상필요성없음+생활상불이익+협의없음 부당","holding_summary":"업무상 필요성이 인정되지 않고, 생활상의 불이익이 상당하며 근로자와의 성실한 협의가 이루어지지 않은 직급강등은 부당","retrieval_note":"직급강등 3요건 모두 불충족 부당. disposition_type=demotion","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31385","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion"],"fact_markers":["팀장→팀원강등","정당사유없음","징벌해당","재량권남용"],"legal_focus":["실질강등","그밖의징벌","재량권남용"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["팀장팀원강등_정당사유없음_징벌해당_재량권남용_부당"],"exclude_for_queries":[],"summary_short":"팀장→팀원 강등 정당사유없음 재량권 남용 부당","holding_summary":"정당한 사유 없이 팀원으로 강등조치 한 것은 근로기준법상의 그 밖의 징벌에 해당하며 인사재량권의 남용으로 부당","retrieval_note":"강등이 근로기준법상 징벌에 해당함을 명시. 재량권남용 판단 기준. batch_022 id_30303(점장→사원 실질강등)과 동일 법리","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31395","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영업팀장→1인영업직","업무상필요성없음","생활상불이익크다","협의절차미준수"],"legal_focus":["업무상필요성없음","생활상불이익","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["영업팀장1인영업직배치_3요건모두불충족_부당"],"exclude_for_queries":[],"summary_short":"영업팀장→1인 영업직 3요건 불충족 부당","holding_summary":"영업팀장이던 근로자를 갑자기 1인 영업직으로 배치한 것은 업무상 필요성이 있다고 보기 어렵고, 생활상 불이익이 크며, 신의칙상 요구되는 협의절차도 준수하지 않아 부당","retrieval_note":"팀장→1인업무 이질배치 부당. 3요건 모두 불충족","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31469","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성대비생활상불이익현저히크다","비례성불충족"],"legal_focus":["생활상불이익","비례성원칙"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["업무상필요성인정되나_생활상불이익현저히크다_부당"],"exclude_for_queries":[],"summary_short":"업무상필요성 대비 생활상불이익 현저히 커 부당","holding_summary":"전보가 업무상 필요성에 비해 생활상의 불이익이 현저히 크므로 부당","retrieval_note":"업무상필요성 인정되나 생활상불이익이 현저히 커 부당 판정. 비례성 판단. manufacturing 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31489","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["배치전환재량권일탈아님","부당노동행위아님"],"legal_focus":["인사재량권","부당노동행위의사"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["배치전환재량권일탈아님_부당노동행위아님_기각"],"exclude_for_queries":[],"summary_short":"배치전환 재량권 일탈 아님 + 부당노동행위 아님 기각","holding_summary":"사용자가 근로자에게 행한 배치전환은 인사재량권을 현저히 일탈한 것으로 보기 어렵고, 이러한 배치전환이 부당노동행위에 해당하지 않아 기각","retrieval_note":"배치전환+부당노동행위 동시 다툼 기각. 재량권 일탈 여부 기준","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31501","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["조직개편전보","전보정당","부당노동행위아님"],"legal_focus":["업무상필요성","부당노동행위의사"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["조직개편전보_정당_부당노동행위아님_초심유지"],"exclude_for_queries":[],"summary_short":"조직개편 전보 정당 + 부당노동행위 아님","holding_summary":"이 사건 전보는 조직개편에 따른 것으로서 정당하고 부당노동행위에도 해당하지 않아 초심유지","retrieval_note":"조직개편 전보 정당+부당노동행위 불인정 패턴. batch_023 반복","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31675","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영업추진역선정","업무상필요성인정","생활상불이익작음","절차이행"],"legal_focus":["업무상필요성","생활상불이익","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["영업추진역선정_업무상필요성인정_절차이행_정당"],"exclude_for_queries":[],"summary_short":"영업추진역 선정 3요건 충족 정당","holding_summary":"업무상 필요성이 인정되고 생활상 불이익 크지 않아 정당한 인사명령이라고 판단","retrieval_note":"영업추진역 선정 전보 정당. 3요건 충족","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_3169","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성없음","생활상불이익있음","협의절차미준수"],"legal_focus":["업무상필요성없음","생활상불이익","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보_업무상필요성없음_생활상불이익_협의없음_3요건불충족_부당"],"exclude_for_queries":[],"summary_short":"전보 3요건 모두 불충족 부당","holding_summary":"전보는 업무상 필요성이 없고, 더 나아가 생활상 불이익이 있으며 협의절차를 준수하지 않아 부당","retrieval_note":"전보 3요건 모두 불충족 부당. 권고사직거부자 연관 패턴","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31709","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사전협의","업무상필요성","수인범위내불이익"],"legal_focus":["업무상필요성","생활상불이익수인범위","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보협의완료_업무상필요성인정_생활상불이익수인범위_정당"],"exclude_for_queries":[],"summary_short":"전보 협의+업무상필요성+수인범위 정당","holding_summary":"사전에 협의 절차를 거쳤으며, 업무상 필요성에 비해 생활상 불이익은 통상 감수하여야 할 범위 내에 있어 정당한 인사명령","retrieval_note":"전보 3요건 충족 정당. 생활상불이익 수인범위 내 판단","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31859","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer","pay_cut"],"fact_markers":["안성물류팀배치","업무경력불일치","급여감소","협의없음"],"legal_focus":["업무상필요성없음","생활상불이익","협의절차"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["업무경력불일치물류팀배치_급여감소_협의없음_3요건불충족_부당"],"exclude_for_queries":[],"summary_short":"안성물류팀배치 업무경력 불일치+급여감소+협의없음 부당","holding_summary":"근로자의 업무경력 등을 볼 때 안성물류팀으로 배치한 것은 업무상 필요성이 없고, 급여 감소로 생활상 불이익이 크며, 신의칙상 협의절차도 준수하지 않아 부당","retrieval_note":"업무경력 기반 전보 업무상필요성 부정. 급여감소+협의없음 추가. manufacturing 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31959","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["권고사직거부후전보","업무상필요성미비","생활상불이익심대","협의없음"],"legal_focus":["업무상필요성없음","생활상불이익","협의절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["권고사직거부후전보_3요건모두불충족_부당"],"exclude_for_queries":[],"summary_short":"권고사직 거부 후 전보 3요건 모두 불충족 부당","holding_summary":"업무상 필요성이 미비하고, 근로자의 생활상 불이익이 심대하며, 성실한 사전협의 등 절차를 준수하지 않아 전보명령이 부당","retrieval_note":"권고사직거부 후 전보 = 퇴출목적 패턴. 3요건 모두 불충족. batch_018 id_26935(권고사직불응자선별)와 동일 패턴","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31969","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["조직개편","협의이행","업무상필요성","생활상불이익없음"],"legal_focus":["업무상필요성","생활상불이익","협의절차"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["조직개편전직_협의이행_3요건충족_정당"],"exclude_for_queries":[],"summary_short":"조직개편 전직 협의 이행 3요건 충족 정당","holding_summary":"조직개편 등 전직 명령에 업무상 필요성이 있고, 생활상 불이익은 달리 없으며, 당사자가 협의 절차를 거쳐 정당한 인사명령","retrieval_note":"조직개편 전직 3요건 충족 정당. manufacturing 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31981","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["정당재량권행사","원청책임관련"],"legal_focus":["인사재량권","업무상필요성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보_정당재량권행사_원청책임"],"exclude_for_queries":[],"summary_short":"전보 정당한 재량권 행사","holding_summary":"근로자에 대한 전보처분은 사용자의 정당한 재량권 행사에 해당","retrieval_note":"원청 책임 관련 전보 정당. 재량권 행사 정당 인정","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31985","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성인정","생활상불이익과도하지않음"],"legal_focus":["업무상필요성","생활상불이익수인범위"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["전보_업무상필요성인정_생활상불이익과도하지않음_정당"],"exclude_for_queries":[],"summary_short":"전보 업무상필요성 인정+생활상불이익 과도하지않음 정당","holding_summary":"업무상 필요성이 인정되고 생활상의 불이익의 정도가 과도하지 않아 전보가 정당","retrieval_note":"전보 3요건 충족 정당. construction 업종 공공기관","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_32047","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성인정","생활상불이익작음"],"legal_focus":["업무상필요성","생활상불이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보_업무상필요성인정_생활상불이익작음_정당"],"exclude_for_queries":[],"summary_short":"전보 업무상필요성 인정+생활상불이익 작음 정당","holding_summary":"전보의 업무상 필요성이 인정되고 생활상 불이익 크지 않아 정당한 인사명령","retrieval_note":"전보 정당 일반 사례","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_32105","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["담당업무소멸","인력필요사업장배치","업무상필요성인정","수인가능불이익"],"legal_focus":["업무상필요성","생활상불이익수인범위"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["담당업무소멸후인사발령_업무상필요성인정_수인가능_정당"],"exclude_for_queries":[],"summary_short":"담당업무 소멸 후 인사발령 업무상필요성 정당","holding_summary":"근로자의 담당업무가 없어진 상황에서 인력이 필요한 사업장의 통리원에 인사발령 한 것은 업무상 필요성이 인정되고 근로자에 대한 생활상 불이익은 감내할 수 있는 정도에 해당하여 정당","retrieval_note":"담당업무 소멸 후 타사업장 발령. 업무상필요성 인정. batch_022 id_30909(담당업무없이당연면직=부당)과 대비","confidence":"high","review_status":"reviewed","tag_version":"v3"},

# ── procedure (12건) ──────────────────────────────────────────────────────────
{"case_id":"id_30931","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["복직후취하서제출","구제이익소멸","해고부존재","복수사건"],"legal_focus":["구제이익소멸","해고부존재","취하"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["복직후취하서제출_구제이익소멸각하_별건해고부존재"],"exclude_for_queries":[],"summary_short":"복직 후 취하서 제출 구제이익 소멸 + 별건 해고부존재","holding_summary":"2018.2.13 해고구제신청은 복직 후 취하서 제출로 구제이익 소멸 각하, 2018.3.5 해고제기건은 해고가 존재하지 않아 기각","retrieval_note":"복수 사건 분리 판단. 취하+구제이익소멸 복합 각하","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_30955","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal","transfer"],"fact_markers":["전직다투던중해고","원직복직실현불가","구제이익없음"],"legal_focus":["구제이익","원직복직실현가능성"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["전직다투던중해고_원직복직실현불가_구제이익없음각하"],"exclude_for_queries":[],"summary_short":"전직 다투던 중 해고로 구제이익 없음 각하","holding_summary":"전직 및 전보처분에 대하여 구제신청을 제기하여 다투던 중 해고로 근로관계가 종료되어 원직복직 명령을 사실상 실현할 수 없으므로 구제이익이 존재하지 않아 각하","retrieval_note":"전보다투던중해고로구제이익소멸. batch_019 id_27791(기간제전보다투던중계약만료)과 유사 구조","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_30997","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["제척기간도과"],"legal_focus":["제척기간"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":[],"exclude_for_queries":["전보정당성"],"summary_short":"전보 제척기간 도과 각하","holding_summary":"구제신청이 제척기간을 도과하여 각하","retrieval_note":"전보 제척기간 3개월 도과 각하","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31193","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["전직다투던중사직","원직복직실현불가","구제이익없음"],"legal_focus":["구제이익","원직복직실현가능성"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["전직다투던중사직_구제이익없음각하"],"exclude_for_queries":[],"summary_short":"전직 다투던 중 사직 구제이익 없음 각하","holding_summary":"근로자가 전직에 대한 구제신청을 제기한 이후에 사직하여 원직복직 명령을 사실상 실현할 수 없고, 주소보정 및 출석 요구에도 응하지 아니하여 구제이익이 존재하지 않아 각하","retrieval_note":"전직다투던중사직=구제이익소멸 각하. batch_018 id_26803(퇴직원제출)과 유사","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31267","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["해고당일업무복귀명령","근로자미응","구제이익없음"],"legal_focus":["구제이익","업무복귀명령"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["해고당일업무복귀명령_근로자정당사유없이미응_구제이익없음각하"],"exclude_for_queries":[],"summary_short":"해고 당일 업무복귀 명령 + 근로자 미응 구제이익 없음","holding_summary":"사용자는 해고 당일에 업무복귀 명령을 하였고, 정당한 사유 없이 근로자들이 이에 응하지 않아 구제이익이 없어 각하","retrieval_note":"해고당일 업무복귀명령으로 구제이익소멸. 근로자의 복직 거부가 구제이익 소멸 요인","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_3135","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["보직변경=강임아님=정당","전보구제이익없음"],"legal_focus":["구제이익","보직변경=강임구분"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["보직변경=강임아님_정당인사권_전보구제이익없음각하"],"exclude_for_queries":[],"summary_short":"보직변경=강임아님 정당 + 전보 구제이익없음","holding_summary":"인사발령은 강임이 아니라 보직변경 및 전보에 해당하나 보직변경은 정당한 인사권의 행사이며, 전보는 구제이익이 없어 각하","retrieval_note":"보직변경이 강임(강등)이 아님을 판단. 전보는 구제이익없음각하","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31425","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["구제내용실현불가명백","구제이익없음"],"legal_focus":["구제이익","구제명령실현가능성"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":[],"exclude_for_queries":["전보정당성"],"summary_short":"구제내용 실현불가 명백 구제이익 없음 각하","holding_summary":"신청하는 구제의 내용이 법령상이나 사실상 실현할 수 없음이 명백하여 구제신청의 이익이 없어 각하","retrieval_note":"구제명령 실현불가 명백한 경우 구제이익없음 각하","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31453","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["일방적근로관계종료","서면통지없음","해고사유서면미통지","근로자성인정"],"legal_focus":["서면통지의무","해고사유서면통지"],"industry_context":"finance","exclusion_flags":["procedure_dominant"],"include_for_queries":["일방적근로관계종료_서면통지없음_부당해고"],"exclude_for_queries":[],"summary_short":"일방적 근로관계 종료 + 서면통지 없음 부당해고","holding_summary":"사용자의 일방적 의사로 근로관계가 종료되었고, 해고사유와 시기를 서면으로 통지하지 않아 부당해고에 해당","retrieval_note":"서면통지 없는 부당해고. finance 업종. 근로자성 인정 전제","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31475","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["근로조건위반","손해배상청구","구제신청대상아님"],"legal_focus":["구제신청대상","근로기준법제19조"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":[],"exclude_for_queries":["전보정당성"],"summary_short":"근로조건 위반 손해배상청구 구제신청 대상 아님 각하","holding_summary":"취업 후에 근로조건이 변경된 경우에는 근로기준법 제19조(근로조건의 위반)의 손해배상 청구 대상에 해당되지 않아 각하","retrieval_note":"근로기준법 제19조 근로조건위반 손해배상청구 노동위원회 구제신청 대상 아님. fact_specific","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31997","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["당연면직","제척기간도과","3개월초과"],"legal_focus":["제척기간"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["당연면직_제척기간도과각하"],"exclude_for_queries":[],"summary_short":"당연면직 제척기간 도과 각하","holding_summary":"당연면직처분이 있은 날(2017.12.17.)로부터 3개월이 지나 구제신청 제척기간이 도과하여 각하","retrieval_note":"당연면직 후 3개월 제척기간. 구제신청 시점 기산일 확인","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_32011","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["부당해고인정","금전보상명령수용","서면통지없음"],"legal_focus":["서면통지의무","금전보상명령"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["부당해고인정_금전보상명령수용"],"exclude_for_queries":[],"summary_short":"부당해고 인정 금전보상명령 수용","holding_summary":"사용자가 근로자들을 부당해고 한 사실이 인정되어 금전보상명령신청을 수용. 권고사직 형식이나 해고 사실 인정","retrieval_note":"부당해고 인정+금전보상명령 수용 사례. 절차위반(서면통지없음) 기반 부당해고","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_32103","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["대기발령취소","원직복직","구제이익없음","업무분장=배치전환아님"],"legal_focus":["구제이익소멸","업무분장구제신청대상"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["대기발령취소원직복직_구제이익없음_업무분장배치전환아님"],"exclude_for_queries":[],"summary_short":"대기발령 취소 원직복직 구제이익없음 + 업무분장=배치전환아님","holding_summary":"사용자가 대기발령을 취소하여 근로자가 원직에 복직하였으므로 구제할 이익이 없고, 사용자가 행한 업무분장(근로자가 담당하던 업무 중 일부를 타 직원에게 부여)은 배치전환에 해당하는 인사처분으로 볼 수 없어 기각","retrieval_note":"대기발령 취소=구제이익소멸. 업무분장(업무일부제거)은 배치전환이 아님","confidence":"high","review_status":"reviewed","tag_version":"v3"},

# ── disciplinary_severity (5건) ───────────────────────────────────────────────
{"case_id":"id_31019","issue_type_primary":"disciplinary_severity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["정직사유일부인정","양정과다부당","전보재심제척기간도과"],"legal_focus":["징계양정","제척기간"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["정직사유일부인정_양정과다_부당_전보재심제척기간각하"],"exclude_for_queries":[],"summary_short":"정직 양정과다 부당 + 전보 재심 제척기간 도과 각하","holding_summary":"정직은 징계사유의 일부가 인정되나 양정이 과다하여 부당하고, 전보는 재심신청 기간이 도과하여 각하","retrieval_note":"정직 양정과다 부당 + 전보 제척기간 각하. 처분별 분리 판단","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31287","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],"fact_markers":["징계사유일부인정","법인카드사적유용","해고양정과다"],"legal_focus":["징계사유","징계양정"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["징계사유일부인정_해고양정과다_부당"],"exclude_for_queries":[],"summary_short":"징계사유 일부 인정이나 해고 양정과다 부당","holding_summary":"비위행위의 일부가 징계사유로 인정되나, 이를 이유로 해고한 것은 양정이 과도하여 부당. 법인카드 사적유용 등 일부 사유만 인정","retrieval_note":"비위행위 일부 사유만 인정, 해고양정과다 부당. finance 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31397","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],"fact_markers":["징계사유모두인정","양정적정","절차하자없음"],"legal_focus":["징계사유","징계양정","징계절차"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["징계사유모두인정_양정적정_절차정당_해고정당"],"exclude_for_queries":[],"summary_short":"징계사유+양정+절차 모두 정당한 해고","holding_summary":"징계사유가 모두 인정되고, 그 양정도 적정하며, 징계절차에서도 하자가 없어 부당해고가 아니라고 판정","retrieval_note":"징계 3요건(사유+양정+절차) 모두 정당. public 교육기관","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31561","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["pay_cut","transfer"],"fact_markers":["성희롱감봉정당","피해자보호전보정당"],"legal_focus":["성희롱징계","피해자보호조치전보","감봉양정"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["성희롱감봉정당_피해자보호전보정당"],"exclude_for_queries":[],"summary_short":"성희롱 감봉 정당 + 피해자 보호전보 정당","holding_summary":"근로자에게 성희롱을 사유로 행한 1개월의 감봉처분은 징계 사유, 양정 및 절차가 정당하고, 성희롱 피해자의 보호조치를 위한 전보처분은 사용자에게 주어진 인사권에 근거한 정당한 처분","retrieval_note":"성희롱 감봉+피해자보호전보 동시 정당 인정. batch_020 id_28939, batch_021 id_29719 동일 패턴 3회 이상 확인","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_32061","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["음주운전징역집행유예","인사규정당연면직","당연면직정당"],"legal_focus":["징계사유","당연면직규정","인사규정"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["음주운전징역당연면직_인사규정준수_정당"],"exclude_for_queries":[],"summary_short":"음주운전 징역 집행유예 당연면직 정당","holding_summary":"음주운전으로 징역 6월, 집행유예 2년을 선고받은 근로자를 인사규정에 따라 당연면직 처분한 것은 정당","retrieval_note":"형사판결(징역+집행유예)에 따른 당연면직 인사규정 적용 정당. public 기관","confidence":"high","review_status":"reviewed","tag_version":"v3"},

# ── contract_expiry (5건) ─────────────────────────────────────────────────────
{"case_id":"id_31071","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["사용자1각하","사용자2기각","갱신기대권불인정","공공기관금융"],"legal_focus":["갱신기대권","사용자특정","구제신청자격"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["갱신기대권불인정_기간만료정당_사용자특정쟁점"],"exclude_for_queries":[],"summary_short":"사용자1 각하+사용자2 기각 갱신기대권 불인정","holding_summary":"사용자1은 실질 사용자가 아니어서 각하, 사용자2는 갱신기대권을 인정하지 않아 기각. 공공기관 금융 업종","retrieval_note":"복수 사용자 중 실질 사용자 특정. 갱신기대권 불인정. finance 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31151","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["계약기간명시","당연퇴직규정","갱신기대권없음"],"legal_focus":["갱신기대권","계약기간만료"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약서계약기간명시_당연퇴직규정_갱신기대권없음_기간만료정당"],"exclude_for_queries":[],"summary_short":"계약기간 명시+당연퇴직 규정 갱신기대권 없음 기간만료 정당","holding_summary":"근로계약서에 계약기간이 명시되어 있고 전문직직원관리지침에 계약기간 만료를 당연퇴직 사유로 규정하며 갱신 요건·절차 규정이 없어 갱신기대권 불인정, 기간 만료로 근로관계 종료 정당","retrieval_note":"내부규정 당연퇴직+갱신절차규정없음=갱신기대권불인정. 전문직직원 특수","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31327","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["무기계약전환기대권인정","객관기준미달","전환거절합리적이유인정"],"legal_focus":["무기계약전환기대권","객관적합리적기준","평가공정성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["무기계약전환기대권인정_객관기준미달_전환거절합리적이유인정_기각"],"exclude_for_queries":[],"summary_short":"무기계약전환 기대권 인정이나 객관기준 미달 전환거절 정당","holding_summary":"기간제근로자에게 무기계약직 전환의 기대권은 인정되나, 사용자가 객관적이고 합리적인 기준에 따라 평가를 실시하고 근로자가 합격기준에 미달하여 무기계약직 전환 거절에 합리적인 이유가 있어 기각","retrieval_note":"무기계약전환기대권 인정 + 객관기준 미달 = 전환거절 합리적이유 인정 정당. batch_023 id_31341(평가불공정 부당)과 대비","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31341","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["무기계약전환기대권인정","평가불공정","전환거절합리적이유없음","부당해고"],"legal_focus":["무기계약전환기대권","평가공정성","합리적이유"],"industry_context":"it","exclusion_flags":[],"include_for_queries":["무기계약전환기대권인정_평가불공정_전환거절합리적이유없음_부당해고"],"exclude_for_queries":[],"summary_short":"무기계약전환 기대권 인정 + 평가 불공정 = 부당해고","holding_summary":"무기계약직 전환 기대권이 존재하는 근로자에 대한 평가가 객관적이고 공정하게 진행되지 아니하여 무기계약직 전환 거절의 합리적인 이유가 없으므로 부당해고","retrieval_note":"무기계약전환 기대권 인정 + 평가불공정 = 부당해고. IT 공공기관. batch_023 id_31327(객관기준미달=정당)과 대비 — 핵심은 평가의 공정성","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31567","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["갱신기대권인정","합리적이유없는거절","부당해고","초심취소"],"legal_focus":["갱신기대권","합리적이유","초심취소패턴"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["갱신기대권인정_합리적이유없는갱신거절_부당해고_초심취소"],"exclude_for_queries":[],"summary_short":"갱신기대권 인정 + 합리적이유 없는 거절 = 부당 (초심취소)","holding_summary":"근로자에게 갱신기대권이 인정됨에도 사용자가 합리적 이유 없이 근로계약 갱신을 거절한 것은 부당하다고 판정. 초심 기각에서 재심 인용으로 변경","retrieval_note":"갱신기대권 인정 + 합리적이유없는거절 = 부당해고. 재심에서 초심 취소. batch_022 id_30849(관행2건=불인정)와 대비","confidence":"high","review_status":"reviewed","tag_version":"v3"},

# ── no_dismissal (3건) ────────────────────────────────────────────────────────
{"case_id":"id_31845","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["조건부사직권고","해고통보아님","해고부존재"],"legal_focus":["해고의사표시","조건부사직권고","합의해지"],"industry_context":"unknown","exclusion_flags":["resignation_dispute","settlement_or_mutual_termination"],"include_for_queries":["해고통보=조건부사직권고=해고의사표시아님_해고부존재"],"exclude_for_queries":[],"summary_short":"해고 통보가 조건부 사직권고에 해당 해고 부존재","holding_summary":"사용자가 같은 내용의 전보 명령을 또다시 하였다고 볼 수 없고, 근로자가 주장하는 해고 통보는 조건부로 사직을 권고하는 청약의 의사표시로 봄이 타당하여 해고는 존재하지 않아 기각","retrieval_note":"조건부사직권고=해고의사표시불인정. 해고부존재 판단. batch_022 id_30911(자진사직)과 유사","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_31955","issue_type_primary":"no_dismissal","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["촉탁직계약거부","근로관계종료=해고부존재","부당노동행위아님"],"legal_focus":["합의해지","촉탁직전환거부","부당노동행위의사"],"industry_context":"unknown","exclusion_flags":["settlement_or_mutual_termination"],"include_for_queries":["촉탁직계약거부_근로관계종료=해고부존재_부당노동행위아님"],"exclude_for_queries":[],"summary_short":"촉탁직계약 거부로 근로관계 종료 해고부존재 + 부당노동행위 아님","holding_summary":"근로자가 촉탁직 근로계약 체결 요청을 거부하여 근로관계가 종료된 것으로 부당해고가 아니고, 불이익 취급의 부당노동행위에도 해당되지 않아 초심유지","retrieval_note":"촉탁직전환 거부=자진사직형 해고부존재. batch_021 id_29535(정년도과후촉탁거부=해고부존재)와 유사","confidence":"high","review_status":"reviewed","tag_version":"v3"},

{"case_id":"id_32059","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["인사발령불만","다음날출근않음","해고부존재"],"legal_focus":["해고의사표시","자진사직"],"industry_context":"finance","exclusion_flags":["resignation_dispute"],"include_for_queries":["인사발령불만다음날출근않음_해고부존재"],"exclude_for_queries":[],"summary_short":"인사발령 불만 다음날 출근 않음 해고 부존재","holding_summary":"근로자가 사용자의 인사발령에 불만을 품고 인사발령일 다음 날부터 더 이상 출근하지 않은 것일 뿐 해고는 존재하지 않아 기각","retrieval_note":"인사발령 불만에 따른 자진 불출근 = 해고부존재. finance 업종","confidence":"high","review_status":"reviewed","tag_version":"v3"},

# ── union_activity (1건) ──────────────────────────────────────────────────────
{"case_id":"id_31999","issue_type_primary":"union_activity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["반노조의사전보","부당전보","부당노동행위"],"legal_focus":["부당노동행위의사","지배개입","전보정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["반노조의사전보=부당전보+부당노동행위_지배개입"],"exclude_for_queries":[],"summary_short":"반노조 의사 전보 = 부당전보 + 부당노동행위","holding_summary":"전보 사유가 업무상 필요성보다 반노조 의사로 전보한 것은 부당전보임과 동시에 부당노동행위(지배개입)에 해당","retrieval_note":"반노조의사전보=부당전보+지배개입부당노동행위. 부당노동행위의사가 인정된 사례. batch_020 id_28915(단체협약위반전보=부당노동행위)와 비교","confidence":"high","review_status":"reviewed","tag_version":"v3"},

# ── discrimination (1건) ─────────────────────────────────────────────────────
{"case_id":"id_31595","issue_type_primary":"discrimination","issue_type_secondary":["contract_expiry"],"employment_stage":"fixed_term","disposition_type":["other"],"fact_markers":["기간제근로자","성과상여금불지급","불합리한차별","비교대상근로자"],"legal_focus":["차별시정","성과상여금","기간제근로자"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["기간제근로자성과상여금불지급_불합리한차별_차별시정인용"],"exclude_for_queries":[],"summary_short":"기간제 근로자 성과상여금 불지급 불합리한 차별 시정 인용","holding_summary":"기간제근로자들에게 비교대상근로자에 비해 성과상여금을 지급하지 않은 것은 불합리한 차별이라고 판정하여 차별시정 인용","retrieval_note":"기간제근로자 성과상여금 차별시정 인용. education 업종. 합리적사유없는차별","confidence":"high","review_status":"reviewed","tag_version":"v3"},
]
out.parent.mkdir(parents=True, exist_ok=True)
with open(out, 'w', encoding='utf-8') as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')
print(f"Written {len(records)} records")
