import json, pathlib, sys
sys.stdout.reconfigure(encoding='utf-8')

OUT = pathlib.Path("retagging/output/reviewed/transfer_batch_052_reviewed.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)

records = [

{"case_id":"id_410023","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["해고의사표시근거불명확","수차례출근독려","임금지급","진정성있는복직명령"],"legal_focus":["해고의사표시명확근거없음+수차례출근독려+임금지급=진정성있는복직명령=구제이익없음"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["진정성있는복직명령수차례출근독려+임금지급=구제이익없음=기각"],"exclude_for_queries":[],"summary_short":"해고 의사표시 명확 근거없음+수차례 출근독려+임금지급=진정성있는 복직명령=구제이익 없음=기각","holding_summary":"해고의사표시근거불명확+수차례출근독려+임금지급=진정성있는원직복직명령=구제이익없음=기각","retrieval_note":"진정성 있는 복직명령 인정 기각 유형 (출근독려+임금지급)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410045","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer","other"],"fact_markers":["대기발령구제이익없음","후행전보로종료","정상급여지급","최근2년2건수행"],"legal_focus":["대기발령=정상급여+후행전보종료=구제이익없음","최근2년2건=업무부진=업무상필요성인정=TV정당"],"industry_context":"retail","exclusion_flags":["procedure_dominant"],"include_for_queries":["대기발령구제이익없음+후행전보종료=기각","최근2년2건업무부진=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"대기발령=정상급여+후행전보종료=구제이익없음+TV 정당(최근2년2건=업무부진=업무상필요성)","holding_summary":"대기발령정상급여지급+후행전보로종료=대기발령구제이익없음+최근2년점포개발2건=업무부진=업무상필요성인정=TV정당","retrieval_note":"대기발령 구제이익 없음 + TV 정당 복합 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410061","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["동료갈등","분리조치","업무능률증진","직장질서유지"],"legal_focus":["동료갈등지속+동료반대=분리조치=업무상필요성인정=TV정당"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["동료갈등지속분리조치=직장질서유지=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"원질팀 동료들과 갈등 지속+동료 반대=분리조치 업무상필요성 인정+생활상불이익 통상감수=TV 정당","holding_summary":"원질팀4조3교대업무중동료들과지속적크고작은갈등+동료반대=업무능률증진직장질서유지분리조치=업무상필요성인정=TV정당","retrieval_note":"동료 갈등 분리조치 TV 정당 유형 (제조업)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410083","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["수습기간경과=정규근로자","근태불량능력부족","해고양정과중"],"legal_focus":["수습기간경과후해고=정규근로자기준적용","일부징계사유인정이나해고양정과중=부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["수습기간경과정규근로자=일부징계사유인정이나해고양정과중=부당해고"],"exclude_for_queries":[],"summary_short":"수습기간 경과 정규근로자=근태불량·능력부족 일부 인정이나 해고 양정 과중=부당해고","holding_summary":"수습기간3개월경과=정규근로자해당+근태불량능력부족지시불이행일부인정이나인정사유대비해고과다=양정과중=부당해고","retrieval_note":"수습기간 경과 후 정규 기준 해고 양정 판단 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410103","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal","demotion"],"fact_markers":["일방적강등","업무변경","진정성없는복직명령(금전보상회피)"],"legal_focus":["일방적강등+업무변경+진정성없는복직명령=구제이익소멸불인정","해고사유없음=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["진정성없는복직명령금전보상회피수단=구제이익소멸불인정","일방적강등+업무변경=징계사유없음=부당해고"],"exclude_for_queries":[],"summary_short":"사용자 복직명령=금전보상 회피 수단=진정성없음=구제이익소멸불인정+부당해고","holding_summary":"복직명령전근로자의견묻지않고일방적통보+사유없이강등업무변경+복직명령목적=금전보상회피=진정성없는복직명령=구제이익소멸불인정+부당해고","retrieval_note":"금전보상 회피 목적 복직명령 진정성 없음 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410151","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사직권고주장","녹취록","오늘나가라발언","서면통지결여"],"legal_focus":["통화녹취록=오늘나가라+한달전서면통보필요발언=해고의사표시=해고존재","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["통화녹취록오늘나가라발언=해고존재","서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"면담+녹취록 '오늘 나가라'·'한달전 서면통보해야' 발언=해고 존재+서면통지없음=부당해고","holding_summary":"2024.7.5.면담에서사직권고주장이나20:00통화녹취록에오늘나가라이유+한달전서면통보필요발언=해고의사표시=해고존재+서면통지없음=부당해고","retrieval_note":"녹취록에서 해고 의사표시 추출 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410157","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],"fact_markers":["시용근로자","구체적조사없음","당사자다툼","일회성비위"],"legal_focus":["시용근로자본채용거부=구체적조사없음+다툼있음+일회성=합리적이유없음=부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["시용근로자본채용거부=구체적조사없음+일회성비위=합리적이유없음=부당"],"exclude_for_queries":[],"summary_short":"시용근로자 본채용거부=구체적 조사없음+당사자 다툼+일회성=합리적 이유없음=부당","holding_summary":"비위행위관련구체적조사없음+당사자간다툼있음+일회성에그침=본채용거부합리적이유없음=부당+금전보상명령신청수용","retrieval_note":"시용 본채용 거부 조사 미흡 + 일회성 부당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410159","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["관리위원회소집","소명기회부여근거없음","인사위원회대신관리위원회","중대절차하자"],"legal_focus":["인사위원회대신관리위원회소집+소명기회부여근거없음=중대절차하자=부당해고"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["인사위원회대신관리위원회소집+소명기회부여근거없음=중대절차하자=부당해고"],"exclude_for_queries":[],"summary_short":"인사위원회 대신 관리위원회 소집+소명기회 부여 근거자료 없음=중대 절차하자=부당해고","holding_summary":"취업규칙상징계위원회의결전소명기회부여규정이나인사위원회대신관리위원회소집+소명기회부여근거자료없음=중대절차하자=부당해고","retrieval_note":"인사위원회 아닌 관리위원회 소집 + 소명기회 불비 절차하자","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410213","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["위탁계약","사업양도아님","당사자적격","사용자2인사발령권한없음무효"],"legal_focus":["위탁계약=사업양도아님=당사자적격사용자1만","사용자2인사발령=권한없는자처분=무효"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["위탁계약=사업양도아님=당사자적격사용자1만인정","사용자2인사발령=권한없음=무효"],"exclude_for_queries":[],"summary_short":"위탁계약=사업양도 아님=당사자적격 위탁사(사용자1)만 인정+사용자2 인사발령=권한없는자 처분=무효=부분인용","holding_summary":"위탁계약=업무만위탁=사업양도아님=당사자적격사용자1만인정+사용자2의인사발령=권한없는자처분=무효=부분인용","retrieval_note":"위탁계약과 사업양도 구별 + 당사자 적격 판단","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410217","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["해고인정+임금지급","원직복직명령","근로자계속근로의사없음"],"legal_focus":["임금지급+원직복직명령=진정성있는복직명령+근로자계속근로의사없음=구제이익없음=기각"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["임금지급+원직복직명령=진정성있는복직명령=구제이익없음=기각"],"exclude_for_queries":[],"summary_short":"해고 인정+임금 지급+원직복직 명령=진정성있는 복직명령+근로자 계속근로 의사없음=구제이익없음=기각","holding_summary":"해고인정후임금상당액지급+2024.9.30.원직복직명령=진정성있는복직명령+근로자금전보상신청이유복직명령거부계속근로의사없음=구제이익없음=기각","retrieval_note":"진정성 있는 복직명령 인정 (임금지급 + 원직복직 명령 요건 충족)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410221","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["해고증거정황없음","사업장변경요청","구제신청대상여부"],"legal_focus":["해고객관적증거정황없음=해고없음","사업장변경요청=구제신청대상아님"],"industry_context":"unknown","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["해고객관적증거정황없음=해고없음=기각","사업장변경요청=구제신청대상아님"],"exclude_for_queries":[],"summary_short":"해고 객관적 증거·정황 없음=해고없음+사업장변경요청=구제신청 대상 아님=기각","holding_summary":"해고입증객관적증거정황없음=일방적종료아님=해고없음+사업장변경요청신청취지=직업안정기관장소관=구제신청대상아님=기각","retrieval_note":"해고 증거 부재 기각 + 사업장 변경 청구 대상 아님 복합","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_41025","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["순환근무명목","합리적기준없음","특정근로자선발설명없음"],"legal_focus":["순환근무합리적기준없음+설명없이특정근로자선발=업무상필요성없음=TV부당"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["순환근무합리적기준없음+특정근로자선발설명없음=업무상필요성없음=TV부당"],"exclude_for_queries":[],"summary_short":"순환근무 명목이나 합리적 기준 없음+특정 근로자만 선발 설명없음=업무상필요성 없음=TV 부당","holding_summary":"동일직무장기근무자순환근무주장이나비슷한조건계산원중합리적기준없이설명없이특정근로자만전보선발=업무상필요성없음=TV부당","retrieval_note":"순환근무 명목 TV - 합리적 기준 없어 부당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410259","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["여객운수책임감상기","생활상불이익크지않음","절차하자없음","부당노동행위아님"],"legal_focus":["업무상필요성있음+생활상불이익크지않음+절차하자없음=TV정당","부당노동행위뚜렷한증거없음=부당노동행위아님"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["여객운수책임감상기목적TV=업무상필요성인정=TV정당","노조변경이유인사발령뚜렷한증거없음=부당노동행위아님"],"exclude_for_queries":[],"summary_short":"여객운수 종사자 책임감 상기 목적=업무상필요성+생활상불이익 크지않음+절차하자없음=TV 정당+부당노동행위 아님","holding_summary":"여객운수종사자책임감의무감상기목적업무상필요성있음+생활상불이익크지않음+절차하자없음=TV정당+노조변경이유인사발령뚜렷한증거없음=부당노동행위아님","retrieval_note":"TV 정당 + 부당노동행위 아님 복합 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410261","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["도급계약해지","당연퇴직사유아님","근로자귀책없음","서면통지결여"],"legal_focus":["도급계약해지=당연퇴직사유아님=해고해당","근로자귀책없음+서면통지없음=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["도급계약해지=당연퇴직사유아님=해고해당","근로자귀책없음+서면통지없음=부당해고"],"exclude_for_queries":[],"summary_short":"도급계약 해지=당연퇴직 사유 아님=해고 해당+근로자 귀책없음+서면통지없음=부당해고","holding_summary":"도급계약해지=당연퇴직사유아님=사용자일방적의사근로계약종료=해고해당+근로자귀책확인안됨+서면통지없음=부당해고","retrieval_note":"도급계약 해지 근거 당연퇴직 불인정 = 해고 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_41027","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["배차지시","통상적업무수행명령","부당노동행위아님"],"legal_focus":["배차지시=통상적업무수행명령=업무상필요성인정=TV정당","노조변경이유인사발령근거없음=부당노동행위아님"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["배차지시=통상적업무수행명령=TV정당","노조변경이유인사발령증거없음=부당노동행위아님"],"exclude_for_queries":[],"summary_short":"배차 지시=통상적 업무수행명령=업무상필요성+생활상불이익 통상감내=TV 정당+부당노동행위 아님","holding_summary":"근로자들에대한인사명령=사용자통상적업무수행명령배차지시=업무상필요성인정+생활상불이익통상감수범위=TV정당+노조변경이유인사발령증거없음=부당노동행위아님","retrieval_note":"배차 지시의 TV 해당 여부 + 부당노동행위 아님 복합","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410303","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상신청","복직후재해고목적복직명령","구제명령회피"],"legal_focus":["복직명령목적=구제명령회피+재해고=진정성없음=구제이익소멸불인정","부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["복직후재해고목적복직명령=구제명령회피=진정성없음=구제이익소멸불인정"],"exclude_for_queries":[],"summary_short":"복직명령 목적=구제명령 회피+재해고=진정성없음=구제이익소멸불인정+부당해고","holding_summary":"금전보상신청이유구제이익없다단정어려움+복직명령실질목적=회사내절차재해고=구제명령회피=진정성없는복직명령=구제이익소멸불인정+부당해고","retrieval_note":"재해고 목적 복직명령 = 진정성없음 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_41031","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["인사발령직위해제주장","전보표현","기본급100%지급","직위해제아님"],"legal_focus":["인사발령=직위해제표현없음+기본급100%=직위해제아님=전보=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사발령직위해제주장이나전보표현+기본급100%=직위해제아님=TV정당"],"exclude_for_queries":[],"summary_short":"인사발령=직위해제 표현없음+기본급100% 지급=직위해제 아님=전보로 판단=TV 정당","holding_summary":"이전직위해제와달리직위해제표현없음+기본급100%각종수당미삭감=직위해제아님=전보로판단=TV정당","retrieval_note":"인사발령의 직위해제 vs 전보 구별 판단 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410337","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion","transfer"],"fact_markers":["팀장→팀원인사발령","강등아님","특별생활상불이익없음","인사관리규정"],"legal_focus":["팀장→팀원인사발령=강등아님+특별생활상불이익없음=TV정당","원심부당취소"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["팀장에서팀원인사발령=강등아닌TV=업무상필요성인정+생활상불이익없음=TV정당=원심취소"],"exclude_for_queries":[],"summary_short":"팀장→팀원 인사발령=강등아님+업무상필요성+특별생활상불이익없음=TV 정당=원심(부당) 취소","holding_summary":"인사권재량범위+업무상필요성+순환보직필요성증가=팀장→팀원=강등아님+특별생활상불이익없음=TV정당=원심부당취소","retrieval_note":"보직 변경(팀장→팀원) TV 정당 원심 취소 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410341","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["취업규칙연봉계약서명시","경영효율화팀축소통합","C등급2년","인사평가객관공정"],"legal_focus":["취업규칙+연봉계약서명시+경영효율화팀축소+C등급2년=업무상필요성+인사평가객관공정=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["취업규칙연봉계약서명시+경영효율화팀통합+C등급2년=업무상필요성=TV정당"],"exclude_for_queries":[],"summary_short":"취업규칙·연봉계약서 명시+경영효율화 팀통합+인사평가 C등급 2년=업무상필요성+객관공정=TV 정당","holding_summary":"취업규칙및연봉계약서능력적성경력고려인사명령규정+경영효율화팀축소통합+C등급2년=업무상필요성+인사평가객관성공정성인정=TV정당","retrieval_note":"취업규칙 명시 + 인사평가 결과 근거 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410347","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상액재산정","재심신청자격없음","초심인용","각하"],"legal_focus":["금전보상액재산정요청재심=재심신청자격없음=각하"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["금전보상액재산정요청재심=재심신청자격없음=각하"],"exclude_for_queries":[],"summary_short":"초심 부당해고 인용+금전보상명령=근로자 금전보상액 재산정 재심=재심신청 자격없음=각하","holding_summary":"초심부당해고인용금전보상명령=근로자금전보상액재산정요청재심신청=재심신청자격은지노위구제명령당사자만=금전보상액재산정불복대상아님=각하","retrieval_note":"금전보상액 재산정 재심 각하 유형 (batch_048 id_407397 패턴 재확인)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410369","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["생산설비오퍼레이터","CNS선반한정아님","산재상병근로자","중량부담감소부서","주간근무"],"legal_focus":["오퍼레이터=CNS선반설비전반+산재상병근로자중량부담적은주간근무=합리적TV=정당"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["산재상병근로자중량부담적은부서전보=합리적이유있음=TV정당"],"exclude_for_queries":[],"summary_short":"생산설비 오퍼레이터=CNS선반 한정 아님+산재 상병 근로자 중량부담 적은 절삭3파트·주간근무=합리적 TV=정당","holding_summary":"오퍼레이터=CNS선반업무한정아님=설비전반업무+산재상병근로자중량부담적은부서주간근무전보=합리적이유있음=TV정당","retrieval_note":"산재 상병 근로자 중량 부담 감소 부서 전보 = 합리적 TV 정당 (batch_051 id_409327 반대 유형)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410393","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"pre_hire","disposition_type":["dismissal"],"fact_markers":["채용내정","합격통지+근로조건협의","근무복제작논의","출근예정일확인"],"legal_focus":["합격통지+구체적근로조건협의+근무복논의+출근예정일확인=채용내정성립","채용내정해지=부당해고"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["합격통지+구체적근로조건협의=채용내정성립","채용내정해지=부당해고"],"exclude_for_queries":[],"summary_short":"합격통지+급여·수습기간·4대보험 등 구체적 근로조건 협의+근무복 제작+출근예정일=채용내정 성립+해지=부당해고","holding_summary":"면접후합격통지+구체적근로조건협의(급여수습기간근무시간4대보험연차)+근무복제작논의+출근예정일확인=채용내정성립+채용내정해지=부당해고","retrieval_note":"채용내정 성립 요건 - 구체적 근로조건 협의가 핵심","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410413","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["응급실의료공백","업무상필요성인정","척추질환","환자이송업무","건강악화우려","노조사전합의없음"],"legal_focus":["응급실의료공백=업무상필요성인정이나척추질환근로자환자이송=건강악화우려+노조대의원인사사전합의없음=TV부당"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["업무상필요성인정이나척추질환근로자환자이송업무=건강악화우려=TV부당","노조대의원인사사전합의없음=협의위반=TV부당"],"exclude_for_queries":[],"summary_short":"응급실 의료공백=업무상필요성 인정이나 척추질환 근로자 환자이송=건강악화 우려+노조 사전합의없음=TV 부당","holding_summary":"응급실의료공백인력충원필요=업무상필요성인정이나척추질환근로자에게응급실환자이송업무=건강악화우려높음+단체협약노조대의원인사사전합의없음=TV부당","retrieval_note":"업무상 필요성 있으나 건강 악화 우려 + 노조 협의 위반 TV 부당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410417","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["직위해제규정없음","실제처분없음","인사발령정당성판단","1년이상이동제한규정"],"legal_focus":["직위해제아닌인사발령판단=1년이상근무이동제한규정위반=TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["1년이상근무이동제한규정위반=TV부당"],"exclude_for_queries":[],"summary_short":"직위해제 규정없음=인사발령 정당성 판단+1년이상 이동제한 규정 위반=TV 부당","holding_summary":"직위해제규정없음=실제처분없음=인사발령정당성판단+1년이상근무자이동제한내부규정위반=TV부당","retrieval_note":"내부 인사규정상 이동 제한 위반으로 TV 부당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410423","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["임금상당액전액지급","원직복직명령","근로자복직불응"],"legal_focus":["임금상당액전액지급+원직복직명령=진정성있는복직명령+근로자불응=구제이익없음=기각"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["임금상당액전액지급+원직복직명령=진정성있는복직명령=구제이익없음=기각"],"exclude_for_queries":[],"summary_short":"임금상당액 전액 지급+원직복직 명령=진정성있는 복직명령+근로자 불응=구제이익없음=기각","holding_summary":"원직복직명령일이전까지임금상당액전액지급+원직복직명령=진정성있는복직명령+근로자복직명령미이행=구제이익없음=기각","retrieval_note":"임금 전액 지급 + 원직복직 명령 = 진정성 있는 복직명령 기각","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410429","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["전보구제이익없음","근로자사직","징계정당"],"legal_focus":["전보=근로자사직=구제이익없음","징계사유인정=정직양정정당"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["전보중근로자사직=구제이익없음=기각","근태징계사유=정직양정정당"],"exclude_for_queries":[],"summary_short":"TV=근로자 사직으로 구제이익없음+징계(정직)=근태 징계사유 인정=양정 정당=기각","holding_summary":"전보구제이익있으나근로자사직=구제이익없음+근태근로자기본=징계사유인정+정직양정정당=기각","retrieval_note":"사직으로 TV 구제이익 소멸 + 징계 정당 복합","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410443","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약서명시","검판업무감소","조판업무인력부족","업무상필요성인정"],"legal_focus":["근로계약명시+검판감소조판인력부족=업무상필요성인정=TV정당"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["검판업무감소조판업무인력부족=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"근로계약 명시+신문지면 축소 검판업무 감소+조판업무 인력부족=업무상필요성+생활상불이익없음=TV 정당","holding_summary":"근로계약소관외업무및다른부서배치가능명시+지면축소검판업무감소+조판수행인력퇴직인원충원필요=업무상필요성인정=TV정당","retrieval_note":"미디어 업종 - 업무 감소 + 인력 부족 근거 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410463","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["합의해지아님","사용자일방적의사해고","서면통지결여"],"legal_focus":["합의해지아님=사용자일방적의사=해고존재","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["합의해지아님=사용자일방적의사=해고존재","서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"합의 해지 아님=사용자 일방적 의사 2024.7.18. 해고=해고 존재+서면통지없음=부당해고","holding_summary":"합의해지아님=사용자2024.7.18.일방적의사근로계약종료=해고존재+해고사유시기서면통지없음=부당해고","retrieval_note":"합의해지 주장 깨고 해고 존재 인정 + 서면통지결여 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410513","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["사용자귀책휴업","가용자금소멸도산","근기법제46조","부득이한사유사업계속불가"],"legal_focus":["가용자금소멸사실상도산=사용자귀책사유휴업=근기법제46조해당","부득이사업계속불가여부판단"],"industry_context":"unknown","exclusion_flags":["fact_specific_low_reusability"],"include_for_queries":["가용자금소멸사실상도산=사용자귀책사유휴업=근기법제46조적용"],"exclude_for_queries":[],"summary_short":"가용자금 소멸 사실상 도산=사용자 귀책사유 휴업=근기법제46조 해당+부득이 사업계속 불가 여부 판단","holding_summary":"재무제표+공인회계사자문=가용자금소멸사실상도산=사용자귀책사유휴업=근기법제46조해당+부득이사업계속불가여부판단","retrieval_note":"사실상 도산 상태에서의 사용자 귀책 휴업 법리 적용","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410523","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["공갈협박비위행위","금전보상요구","기본신뢰관계파괴","중대비위"],"legal_focus":["공갈협박비위=취업규칙단체협약위반=징계사유","기본신뢰관계파괴중대비위=해고정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["공갈협박비위=기본신뢰관계파괴중대비위=해고정당"],"exclude_for_queries":[],"summary_short":"희망퇴직 위로금 요구하며 공갈·협박=취업규칙 위반=중대비위=기본 신뢰관계 파괴=해고 정당","holding_summary":"희망퇴직위로금등금전보상요구하며공갈협박지속=취업규칙단체협약인사규정위반=징계사유+기본신뢰관계파괴중대비위=해고정당","retrieval_note":"공갈·협박 비위행위 = 기본 신뢰 파괴 = 해고 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410541","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["경영정상화와전직간인관관계없음","생활상불이익현저","협의없음"],"legal_focus":["경영정상화와전직인관관계없음=업무상필요성없음+생활상불이익현저+협의없음=TV3요건전부불충족=TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["경영정상화와전직인관관계없음=업무상필요성없음=TV부당","TV3요건전부불충족=TV부당"],"exclude_for_queries":[],"summary_short":"경영정상화와 전직 간 인과관계없음=업무상필요성없음+생활상불이익 현저+협의없음=TV 3요건 전부 불충족=TV 부당","holding_summary":"경영정상화와전직인과관계없음=업무상필요성없음+생활상불이익현저초과+협의없음=TV3요건전부불충족=TV부당","retrieval_note":"TV 3요건 전부 불충족 명시 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410571","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion"],"fact_markers":["집단진정서","고용노동부제출","조직내처리사안초과","집단행동","강등징계사유인정","원심취소"],"legal_focus":["집단진정서=조직내처리사안초과=권한범위외집단행동=징계사유인정=강등정당","원심부당결정취소"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["집단진정서=조직내처리사안초과집단행동=징계사유인정=강등정당=원심취소"],"exclude_for_queries":[],"summary_short":"5명 기관장 집단 진정서=조직내 처리사안 초과+청원사항 해당안됨=집단행동=징계사유 인정=강등 정당=원심(부당) 취소","holding_summary":"전임회장퇴진요구포함집단진정서=청원법청원사항해당안됨+조직내처리사안초과집단행동=징계사유인정=강등정당=원심부당취소","retrieval_note":"집단 진정서 = 징계사유 인정 원심 취소 유형 (batch_051 id_409379 반대 사례)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410605","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["해고사유보기어려움","통상해고·징계해고중복","징계절차미준수","절차하자"],"legal_focus":["해고사유=통상/징계해고중복=징계절차필수+징계절차미준수=절차하자=부당해고"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["통상해고징계해고중복=징계절차필수이나미준수=절차하자=부당해고"],"exclude_for_queries":[],"summary_short":"해고사유=통상해고·징계해고 중복해당=징계절차 필수이나 미준수=절차하자=부당해고","holding_summary":"해고사유=취업규칙복무의무위반중대하게보기어려움+통상해고징계해고중복해당시징계절차준수필요=취업규칙징계절차미준수=절차하자=부당해고","retrieval_note":"통상/징계해고 중복 시 징계절차 필수 법리","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410643","issue_type_primary":"disciplinary_severity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["근무협조사적사용","코로나병가중국외여행","노조활동합의서","징계사유인정","양정과중"],"legal_focus":["근무협조사적사용=정당징계사유","코로나병가국외여행=징계사유","인정사유대비해고=양정과중=부당"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["근무협조사적사용+코로나병가중국외여행=징계사유인정이나해고양정과중=부당"],"exclude_for_queries":[],"summary_short":"근무협조 사적사용+코로나 병가 중 국외여행=징계사유 인정이나 해고=양정 과중=부당해고","holding_summary":"근무협조사적사용=정당징계사유+코로나확진병가기간자가격리않고국외여행=징계사유+인정사유대비해고=양정과중=부당해고","retrieval_note":"노조 근무협조 사적 사용 + 코로나 병가 중 국외여행 징계사유 양정 과중 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410743","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["nonrenewal","dismissal"],"fact_markers":["기간제법제4조단서제1호","특정업무완성기간해당안됨","일부무기전환","일부고령자기간제"],"legal_focus":["특정업무완성기간기간제단서해당안됨=일부근로자무기전환","고령자2년미만=기간제유지"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["기간제법제4조단서특정업무완성해당안됨=일부무기전환","고령자또는2년미만=기간제유지"],"exclude_for_queries":[],"summary_short":"기간제법 제4조단서 특정업무완성 기간 해당 안됨=일부 무기전환+고령자·2년미만=기간제 유지","holding_summary":"기간제법제4조제1항단서특정업무완성기간해당안됨=근로자2,5,7무기전환+근로자1,3,4,6=고령자또는2년미만=기간제유지","retrieval_note":"기간제법 단서 조항 해당 여부 + 무기전환 일부 인정","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410747","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["1개월단위11차례갱신","별도논의협의없이전자계약","공사계약기간1년","갱신기대권인정"],"legal_focus":["1개월단위11차례갱신+별도논의없이전자계약서명=갱신기대권인정","합리적이유없는갱신거절=부당"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["1개월단위11차례갱신+별도협의없이서명=갱신기대권인정","합리적이유없는갱신거절=부당"],"exclude_for_queries":[],"summary_short":"1개월 단위 11차례 갱신+별도 협의없이 전자계약 서명=갱신기대권 인정+합리적 이유없는 갱신거절=부당","holding_summary":"1개월단위11차례갱신+별도논의협의없이전자계약서명방식+공사계약기간1년+갱신기대권인정+합리적이유없는갱신거절=부당","retrieval_note":"단기 반복 갱신 전자계약 서명 = 갱신기대권 인정 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_41075","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["언어폭력","안전교육무단이탈","출퇴근기록불응","일부징계사유불인정","해고양정과중"],"legal_focus":["언어폭력+안전교육무단이탈+출퇴근기록불응=징계사유인정이나협박상급자폭언=불인정","인정사유대비해고=양정과중=부당"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["언어폭력+안전교육무단이탈=징계사유인정이나일부불인정+해고양정과중=부당해고"],"exclude_for_queries":[],"summary_short":"언어폭력·안전교육무단이탈=징계사유 인정이나 협박·폭언부분=불인정+해고 양정 과중=부당해고","holding_summary":"언어폭력+산업안전보건교육무단이탈거부+출퇴근기록불응=징계사유인정이나협박상급자폭언=징계사유불인정+인정사유대비해고=양정과중=부당해고","retrieval_note":"징계사유 일부 불인정 + 해고 양정 과중 복합 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410763","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["사직권고수용","자유의사근로관계종료","해고없음"],"legal_focus":["사직권고수용+자유의사근로관계종료=해고없음=기각"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["사직권고수용자유의사근로관계종료=해고없음=기각"],"exclude_for_queries":[],"summary_short":"사직 권고 수용+자유 의사 근로관계 종료=해고없음=기각","holding_summary":"사직권고수용근로자자유의사에의한근로관계종료=해고없음=기각","retrieval_note":"사직 권고 수용 = 해고 없음 기각 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410799","issue_type_primary":"no_dismissal","issue_type_secondary":["contract_expiry"],"employment_stage":"renewal_stage","disposition_type":["dismissal","nonrenewal"],"fact_markers":["해고존재","서면통지결여","자동종료규정","갱신기대권없음"],"legal_focus":["사용자일방적의사종료=해고존재+서면통지결여=부당해고","자동종료규정+갱신기대권없음(별도판단)"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사용자일방적의사종료=해고존재+서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"사용자 일방적 의사 종료=해고 존재+서면통지없음=부당해고(초심 결과 유지)+갱신기대권없음=별도기각","holding_summary":"사용자일방적의사근로관계종료=해고존재+해고사유시기서면통지없음=부당해고+갱신기대권자동종료규정+갱신기대권없음=갱신거절부분기각","retrieval_note":"해고 존재 부당해고 + 갱신기대권 불인정 복합 (upheld)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410821","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["5인이상동일사업장","협의소홀인정","경영재량","차량판매","업무상필요성"],"legal_focus":["5인이상동일사업장+협의소홀인정이나경영재량+차량판매=업무상필요성인정+생활상불이익없음=TV정당"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["별개사업장동일사업장인정+협의소홀이나경영재량차량판매=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"5인이상 동일사업장 인정+협의 소홀이나 경영재량+차량판매=업무상필요성+특근감소 생활상불이익 작음=TV 정당","holding_summary":"주식회사제이유와동일사업장5인이상+협의소홀인정이나경영재량+차량판매차량변경=업무상필요성인정+경제상불이익작음=TV정당","retrieval_note":"복수 법인 동일 사업장 + TV 정당 복합 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410837","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["other","transfer"],"fact_markers":["대기발령후전직실효","대기발령임금지급","법무→건설안전관리전직","변호사시험합격"],"legal_focus":["대기발령=전직실효+임금지급=구제이익없음","건설안전인력부족+실적악화=전직업무상필요성인정=TV정당"],"industry_context":"construction","exclusion_flags":["procedure_dominant"],"include_for_queries":["대기발령후전직실효+임금지급=대기발령구제이익없음","건설안전인력부족=전직업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"대기발령=전직으로 실효+임금지급=구제이익없음+건설안전인력 부족 법무→건설안전 전직=업무상필요성=TV 정당","holding_summary":"대기발령2025.9.4.전직실효+대기발령기간임금전액지급=법률상불이익없음=구제이익없음+실적악화건설현장안전관리인력부족=전직업무상필요성인정=TV정당","retrieval_note":"대기발령 구제이익 없음 + TV 정당 복합 (변호사 합격자 건설안전 전직)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410839","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["합의해지주장","근로자대표통해합의주장","합의입증없음","일방적해고"],"legal_focus":["합의해지입증없음=사용자일방적의사해고=해고존재","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["합의해지입증없음=사용자일방적의사=해고존재","서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"근로자대표 통한 합의해지 주장이나 합의입증 없음=일방적 해고=해고 존재+서면통지없음=부당해고","holding_summary":"근로자대표통해합의해지주장이나합의또는스스로퇴사사정입증없음=사용자일방적의사해고=해고존재+서면통지결여=부당해고","retrieval_note":"근로자대표 합의해지 주장 실패 = 해고 존재 인정","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410897","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["pay_cut"],"fact_markers":["출퇴근미준수","휴게공간숙박행위","사리사욕도모불인정","일부징계사유불인정","감봉3월양정과중"],"legal_focus":["출퇴근미준수=징계사유인정이나숙박행위+사리사욕=불인정","인정사유대비감봉3월=양정과중=일부부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["출퇴근미준수=징계사유인정이나숙박행위사리사욕=불인정+감봉3월양정과중=부분인용"],"exclude_for_queries":[],"summary_short":"출퇴근 미준수=징계사유 인정이나 숙박행위·사리사욕=불인정+감봉3월 양정 과중=부분 부당=부분인용","holding_summary":"출퇴근미준수=징계사유인정이나숙박행위업무외목적단정불가+사리사욕도모불인정=징계사유불인정+인정사유대비감봉3월=양정과중=부분인용","retrieval_note":"징계사유 일부 불인정 + 감봉 양정 과중 부분인용 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410901","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["이마트기술파트전면외주화","전환배치필요성","근무시간변동없음","급여휴무소폭증가"],"legal_focus":["기술파트전면외주화=전환배치필요성인정+근무시간불변+급여휴무소폭증가=생활상불이익없음=TV정당"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["기술파트전면외주화=전환배치필요성인정+급여휴무오히려증가=TV정당"],"exclude_for_queries":[],"summary_short":"이마트 기술파트 전면 외주화=전환배치 필요성+근무시간 불변+급여·휴무 소폭 증가=TV 정당","holding_summary":"이마트기술파트수급업체관리외전면외주화결정=기술파트업무없어짐=전환배치필요성인정+전체근무시간불변+휴무급여소폭증가=생활상불이익없음=TV정당","retrieval_note":"대형유통 기술파트 전면 외주화 근거 전환배치 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410907","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["업무대기통보","고보상실신고일방적","근로자기다리고있음확인"],"legal_focus":["업무대기통보후일방적고보상실신고=해고존재","해고사유근거없음=부당해고"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["업무대기통보후일방적고보상실신고=해고존재","해고사유근거없음=부당해고"],"exclude_for_queries":[],"summary_short":"수급자 계약해지 이유 업무대기 통보+일방적 고보상실신고=해고 존재+해고사유 근거없음=부당해고","holding_summary":"요양보호수급자계약해지로업무대기통보후2025.6.27.일방적고보상실신고+근로자계속기다림확인=해고존재+해고사유근거없음=부당해고","retrieval_note":"고보 상실신고 일방적 처리 = 해고 존재 인정 유형 (요양보호 업종)","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410913","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["사직의사확인자료없음","문자메시지사직의사없음","실질경영자해고통지","서면통지결여"],"legal_focus":["사직의사객관적자료없음+문자메시지사직의사없음=해고존재","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사직의사확인객관적자료없음=해고존재","서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"사직 의사표시 객관적 자료없음+문자메시지에 사직의사 없음=해고 존재+서면통지없음=부당해고","holding_summary":"사직의사표시객관적확인자료없음+근로자와문자메시지사직의사없음+실질경영자해고통지=해고존재+서면통지결여=부당해고","retrieval_note":"사직 의사 없음 문자메시지 증거 + 해고 존재 인정","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410925","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["매니저변경","직무부여교육","근기법제23조제1항해당아님","제재불이익처분아님"],"legal_focus":["매니저변경+직무부여교육=근기법제23조제1항제재불이익처분아님=구제신청대상아님"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["매니저변경+직무부여교육=근기법제23조제1항제재불이익아님=구제신청대상아님"],"exclude_for_queries":[],"summary_short":"매니저 변경+직무부여교육=근기법 제23조제1항 '제재로서 가하는 불이익처분' 아님=구제신청 대상 아님=기각","holding_summary":"매니저변경직무부여교육=근기법제23조제1항해고정직전직감봉그밖징벌해당안됨+제재로서가하는불이익처분아님=구제신청대상아님=기각","retrieval_note":"구제신청 대상 해당 여부 - '제재로서 가하는 불이익처분' 기준 적용","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410947","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["rejection_of_regular_employment"],"fact_markers":["채용공고정규직전환가능명시","계약직관리지침신분전환규정","1년후평가정규직전환안내","정규직전환기대권인정"],"legal_focus":["채용공고명시+지침규정+사전안내=정규직전환기대권인정","전환거절합리적이유여부판단"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["채용공고정규직전환가능명시+관리지침규정+사전안내=정규직전환기대권인정"],"exclude_for_queries":[],"summary_short":"채용공고 정규직전환 가능 명시+지침 신분전환 규정+1년후 전환안내=정규직전환 기대권 인정+전환거절 합리적 이유 여부 판단","holding_summary":"채용공고정규직전환가능명시+계약직관리지침신분전환규정+재계약시1년후평가정규직전환안내=정규직전환기대권인정+전환거절합리적이유여부판단","retrieval_note":"정규직 전환 기대권 - 채용공고 + 내부지침 + 사전안내 근거","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_410999","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["관리과인력충원필요","동료갈등심화","공간업무분리필요","임금출퇴근변동없음"],"legal_focus":["관리과인력충원+동료갈등심화분리=업무상필요성인정+임금출퇴근변동없음=생활상불이익없음=TV정당"],"industry_context":"office","exclusion_flags":[],"include_for_queries":["관리과인력충원+동료갈등심화분리=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"관리과 인력충원 필요+동료 갈등심화 분리조치=업무상필요성+임금·출퇴근 변동없음=TV 정당","holding_summary":"관리과업무량증가인력충원필요+심사과동료갈등심화공간업무분리필요=업무상필요성인정+임금출퇴근근무시간변동없음=생활상불이익없음=TV정당","retrieval_note":"인력 충원 + 갈등 분리 복합 근거 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_411009","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["원청ID/IRP회수","주한미군부대경비업무배제","실업급여수급권오해","사직경위"],"legal_focus":["원청ID/IRP회수=업무배제=사실상해고여부","실업급여오해에의한사직귀책"],"industry_context":"unknown","exclusion_flags":["fact_specific_low_reusability"],"include_for_queries":["원청ID/IRP회수=업무배제=사실상해고여부"],"exclude_for_queries":[],"summary_short":"원청 ID·IRP 회수=주한미군부대 경비업무 배제+실업급여 오해에 의한 사직 경위=해고 여부 판단=기각","holding_summary":"원청ID/IRP회수=주한미군부대경비업무불가+송상무실업급여수급권오해발언=고의아닌오해=사직경위판단=기각","retrieval_note":"원청 통한 업무 배제 + 실업급여 오해에 의한 사직 복잡 유형","confidence":"high","review_status":"done","tag_version":"v3"},

]

with open(OUT, 'w', encoding='utf-8') as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')

print(f"Written {len(records)} records")
