import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = [
{"case_id":"id_351313","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["dismissal_exists","written_notice_missing","unilateral_termination"],"legal_focus":["written_notice_requirement"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["일방적의사에의한근로관계종료=해고+서면통지의무위반=부당해고","서면통지결여부당해고"],"exclude_for_queries":[],"summary_short":"일방적의사에의한근로관계종료=해고+서면통지의무위반=부당해고","holding_summary":"근로관계가 근로자의 의사에 반하여 사용자의 일방적 의사에 의해 종료+서면통지 의무를 위반하여 절차상 위법이 존재=부당해고","retrieval_note":"서면통지결여 부당해고 반복 패턴","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351361","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer","dismissal"],"fact_markers":["transfer_found_unfair","no_business_necessity","no_just_cause","dismissal_exists"],"legal_focus":["transfer_validity_3prong","just_cause_standard"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성없음=부당전보+해고징계사유미입증=부당해고","전보+해고복합부당"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성없음=부당전보+해고=징계사유미입증=부당해고","holding_summary":"전보는 업무상 필요성이 확인되지 않아 부당하고 해고는 징계사유에 대한 입증이 없어 부당","retrieval_note":"전보부당+징계해고부당 복합","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351379","issue_type_primary":"redundancy","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["five_or_more_employees","redundancy_requirements_unmet","written_notice_missing","monetary_compensation"],"legal_focus":["redundancy_4prong_test","written_notice_requirement","employee_count_threshold"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["경영상해고요건미충족+서면통지없음=부당해고+금전보상","정리해고요건불충족+서면통지결여=부당"],"exclude_for_queries":[],"summary_short":"5인이상+경영상해고요건미충족+서면통지없음=부당해고+금전보상","holding_summary":"상시근로자수 5인 이상+해고 존재+경영상 이유에 의한 해고의 요건을 충족하지 못함+해고시기를 서면으로 통지하지 않아 부당해고+금전보상명령","retrieval_note":"경영상해고 요건 불충족 + 서면통지 결여 부당해고","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351401","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","negotiation_conducted"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사발령업무상필요성+협의절차=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"인사발령=업무상필요성+불이익없음+협의절차=정당","holding_summary":"인사발령의 업무상 필요성이 인정되고 생활상 불이익이 과도하지 않으며 협의절차 등을 거쳤으므로 정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351417","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["no_dismissal_found"],"legal_focus":["dismissal_existence"],"industry_context":"unknown","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["해고존재볼수없음=해고부존재기각","해고부존재기각"],"exclude_for_queries":[],"summary_short":"해고존재볼수없음=기각","holding_summary":"해고가 존재한다고 볼 수 없어 기각","retrieval_note":"해고부존재 기각","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35143","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["moot_case","reinstatement_completed","no_adverse_rule"],"legal_focus":["remedial_interest"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["직위해제복원+승진승급제한규정없음=구제이익없음각하","직위해제취소=구제이익소멸각하"],"exclude_for_queries":[],"summary_short":"직위해제복원+승진·승급제한규정없음=구제이익없음각하","holding_summary":"사용자가 직위해제를 복원하고 인사규정에 승진·승급에 제한을 가하는 규정이 없으므로 구제의 이익이 없다고 판정=각하","retrieval_note":"직위해제 복원으로 구제이익 소멸 각하","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351453","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["disciplinary_grounds_proven","disproportionate_sanction","transfer_found_unfair","excessive_hardship","sexual_harassment_case"],"legal_focus":["proportionality_review","transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["성희롱징계사유인정이나정직양정과다=부당+전보불이익과다=부당","성희롱관련징계+전보복합부당"],"exclude_for_queries":[],"summary_short":"성희롱징계사유인정이나정직양정과다=부당+전보=업무상필요성대비불이익과다=부당","holding_summary":"직장 내 성희롱이라는 징계사유가 인정되나 정직 처분은 징계양정이 과한 것으로 부당+전보처분은 업무상 필요성에 비해 생활상의 불이익이 근로자가 감수해야 할 정도를 현저하게 벗어났다고 보아 부당","retrieval_note":"성희롱 징계+후속 전보 양방 부당 (사유 인정이나 양정 과다 + 불이익 과다)","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351473","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요성+불이익수인가능=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"인사발령=업무상필요성+불이익수인가능=정당","holding_summary":"인사발령의 업무상 필요성이 인정되고 생활상 불이익이 수인가능한 범위에 있어 정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351503","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["reinstatement_completed","back_pay_paid","moot_case"],"legal_focus":["remedial_interest"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["원직복직+임금상당액지급=구제이익없음각하","복직+임금지급=구제이익소멸"],"exclude_for_queries":[],"summary_short":"원직복직+임금상당액지급=구제이익없음각하","holding_summary":"근로자의 원직복직 및 임금상당액 지급으로 구제이익이 없다고 판정=각하","retrieval_note":"복직+임금지급으로 구제이익 완전 소멸 각하","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351545","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],"fact_markers":["significant_procedural_defect","procedure_violated"],"legal_focus":["disciplinary_procedure"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계절차중대하자=해고부당","징계절차중대하자단독사유=부당"],"exclude_for_queries":[],"summary_short":"징계절차에 중대한 하자=해고부당","holding_summary":"징계절차에 중대한 하자가 있어 해고는 부당하다고 판정","retrieval_note":"징계절차 중대하자 단독 사유 부당해고","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35155","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer","dismissal"],"fact_markers":["transfer_found_unfair","improper_purpose_transfer","constructive_dismissal","standby_order"],"legal_focus":["transfer_validity_3prong","improper_purpose"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["대기발령=퇴사수단으로활용=부당+당연면직=부당","퇴사유도목적대기발령=부당"],"exclude_for_queries":[],"summary_short":"대기발령=퇴사수단으로활용=부당+당연면직=부당","holding_summary":"대기발령이 퇴사의 수단으로 활용되어 부당하므로 그에 기초한 당연면직도 부당하다고 판정","retrieval_note":"퇴사유도목적 대기발령 부당 + 당연면직 부당 연쇄 판단","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351573","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],"fact_markers":["no_disciplinary_grounds","gift_giving_not_misconduct"],"legal_focus":["just_cause_standard","disciplinary_validity"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["선물제공=징계사유미인정=해고부당","원활한직무수행목적선물=징계사유아님=부당해고"],"exclude_for_queries":[],"summary_short":"선물제공=원활한직무수행목적+부당한영향가능성없음=징계사유미인정=해고부당","holding_summary":"근로자가 제공한 선물=원활한 직무수행을 목적으로 하고 있다는 점 배제하기 어렵고 선물의 가액으로 보아 직무에 부당한 영향을 미칠 가능성이 있다고 판단하기 어려워 징계사유 미인정=해고부당","retrieval_note":"선물 제공을 징계사유로 삼기 어렵다는 특수 판단","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351589","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","good_faith_negotiation"],"legal_focus":["transfer_validity_3prong","good_faith_negotiation"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요성+성실협의절차=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성+불이익없음+성실협의절차준수=정당","holding_summary":"전보의 업무상 필요성이 인정되고 생활상 불이익이 통상 근로자로서 감당해야할 범위 내이며 신의칙상 요구되는 성실한 협의절차를 준수하였으므로 정당","retrieval_note":"성실협의절차 준수 포함 3요건 충족 정당","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35159","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["partial_grounds_proven","disproportionate_sanction"],"legal_focus":["proportionality_review","disciplinary_validity"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["정직6월=사유일부있으나양정과도=부당재심유지","징계양정과도부당재심유지"],"exclude_for_queries":[],"summary_short":"정직6월=사유일부있으나양정과도=부당=재심유지","holding_summary":"근로자가 직원들을 부당하게 대하여 일부 퇴사·전직하는 등 징계사유일부 존재하나 그 비위행위의 정도에 비해 정직 6월은 양정이 과도하여 부당=재심유지","retrieval_note":"사유 일부 + 양정 과도 부당 정직 재심유지","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35163","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","worker_representative_negotiation"],"legal_focus":["transfer_validity_3prong","good_faith_negotiation"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성+근로자대표협의=정당재심유지","근로자대표협의이행=정당"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성+불이익없음+근로자대표협의=정당=재심유지","holding_summary":"전보는 업무상 필요성이 인정되고 전보로 인해 근로자가 겪는 생활상 불이익의 정도가 크지 않으며 근로자대표와 협의하는 등 관련 절차도 준수하여 정당=재심유지","retrieval_note":"근로자대표 협의 이행 포함 TV 정당 재심유지","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351633","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성+불이익없음=정당재심유지","TV정당재심유지"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성+불이익통상수준=정당=재심유지","holding_summary":"전보의 업무상 필요성이 인정되고 근로자의 생활상 불이익이 통상 감수하여야 할 정도를 벗어났다고 보기 어려워 정당=재심유지","retrieval_note":"TV 정당 재심유지","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351653","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["dismissal_exists","procedure_violated","resignation_vs_dismissal_dispute"],"legal_focus":["dismissal_existence","dismissal_procedure"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["사직의사표시볼수없음+해고통지=해고존재+절차하자=부당해고","해고통지에의한종료=해고+절차하자=부당"],"exclude_for_queries":[],"summary_short":"사직의사표시로근로관계종료볼수없음+해고통지=해고존재+절차하자=부당해고","holding_summary":"근로자의 사직의 의사표시로 근로관계가 이미 종료되었다고 볼 수 없고 사용자의 해고통지로 근로관계가 종료+해고절차에 하자가 있어 부당","retrieval_note":"사직 vs 해고 다툼에서 해고 인정 + 절차하자 부당","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351711","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성+불이익없음=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성+불이익감수가능=정당","holding_summary":"전보의 업무상 필요성이 인정되고 생활상 불이익이 감수할 수 있는 범위를 벗어났다고 보기 어려워 정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351725","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["no_disciplinary_grounds"],"legal_focus":["just_cause_standard"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계사유없음=해고부당","징계사유부존재=부당해고"],"exclude_for_queries":[],"summary_short":"징계사유없음=해고부당","holding_summary":"근로자에 대한 징계사유가 인정되지 않아 해고의 징계가 부당","retrieval_note":"징계사유 없음 단독 부당해고","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351741","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요성+불이익없음=정당인사발령","TV정당기각"],"exclude_for_queries":[],"summary_short":"업무상필요성+불이익없음=정당인사발령","holding_summary":"업무상 필요성과 생활상 불이익의 정도를 고려할 때 정당한 인사발령에 해당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351789","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["dismissal_found_unfair"],"legal_focus":["dismissal_validity"],"industry_context":"unknown","exclusion_flags":["evidence_too_thin"],"include_for_queries":["부당해고인정"],"exclude_for_queries":[],"summary_short":"부당해고인정","holding_summary":"인정으로 판결됨","retrieval_note":"holding 상세 불명 — 부당해고 인정만 확인","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351795","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","no_unfair_labor_practice"],"legal_focus":["transfer_validity_3prong","unfair_labor_practice"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전직정당+부당노동행위해당안됨","TV정당+부당노동행위기각재심유지"],"exclude_for_queries":[],"summary_short":"전직=업무상필요성+불이익없음=부당전직아님+부당노동행위해당안됨","holding_summary":"전직 처분은 업무상 필요성이 인정되고 생활상 불이익이 근로자들이 통상 감수하여야 할 정도를 현저히 벗어난 것으로 보기 어려워 부당전직에 해당하지 않고 부당노동행위에도 해당하지 않음","retrieval_note":"전직 정당 + 부당노동행위 기각 재심유지","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351803","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성+불이익없음=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성+불이익통상수준=정당","holding_summary":"근로자에 대한 전보는 업무상 필요성이 인정되며 전보에 따른 생활상 불이익이 근로자가 통상 감수하여야 할 정도를 현저하게 벗어난 것이라고 볼 수 없어 정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351819","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","negotiation_conducted","inter_company_transfer"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전직업무상필요성+사전협의+불이익없음=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"전직=업무상필요성+불이익없음+사전협의=정당","holding_summary":"전직은 업무상 필요성이 존재하고 생활상 불이익이 크다고 보기 어려우며 사전 협의 절차도 거쳐 정당","retrieval_note":"전직 3요건 충족 정당","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351821","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_found_unfair","excessive_hardship","business_necessity_proven"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성대비불이익지나치게큼=부당전보","업무상필요성인정이나불이익과대=부당"],"exclude_for_queries":[],"summary_short":"근로자1,2전보=업무상필요성대비불이익지나치게큼=부당전보","holding_summary":"근로자1, 2에 대한 전보가 업무상 필요성에 비해 생활상 불이익이 지나치게 크므로 부당","retrieval_note":"업무상 필요성 인정이나 불이익이 이를 압도하는 경우 부당전보","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351827","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_found_unfair","no_business_necessity","excessive_hardship","no_consultation"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보3요건불충족=부당전보","업무상필요성없음+불이익+협의없음=부당"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성없음+불이익상당+협의없음=부당전보","holding_summary":"전보의 업무상 필요성이 인정되지 않고 생활상 불이익도 상당하며 신의칙상 요구되는 협의절차를 준수하였다고 보기 어려워 부당","retrieval_note":"3요건 모두 불충족 부당전보","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351833","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","procedure_followed"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사명령업무상필요성+불이익없음+절차정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"인사명령=업무상필요성+불이익없음+절차정당","holding_summary":"인사명령은 업무상 필요성이 있고 생활상 불이익이 크다고 볼 수 없으며 절차에 하자가 없어 정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351841","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["dismissal_exists","reinstatement_order_not_genuine","remedial_interest_exists","written_notice_missing","monetary_compensation"],"legal_focus":["written_notice_requirement","remedial_interest","reinstatement_genuineness"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["복직명령진정성없음=구제이익존재+서면미통지=부당해고+금전보상","복직명령진정성부인+서면통지결여=부당"],"exclude_for_queries":[],"summary_short":"복직명령진정성없음=구제이익존재+서면미통지=부당해고+금전보상","holding_summary":"해고가 존재하고 원직복직명령에 진정성이 없어 구제이익도 인정+해고사유 및 시기를 서면으로 통지하지 않아 절차상 하자로 인한 부당해고+금전보상","retrieval_note":"복직명령 진정성 부인 → 구제이익 소멸 불인정 + 서면통지 결여 (batch_033 id_351091과 동일 패턴)","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35185","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["nonrenewal"],"fact_markers":["moot_case","contract_expired"],"legal_focus":["remedial_interest"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["근로계약기간종료=구제신청이익없음각하","계약기간종료=구제이익없음각하"],"exclude_for_queries":[],"summary_short":"근로계약기간종료=구제신청이익없음각하","holding_summary":"근로계약기간이 종료되어 부당해고 구제신청의 이익이 존재하지 않는다고 판정=각하","retrieval_note":"계약기간 만료 구제이익 없음 각하","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351887","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["five_or_more_employees","written_notice_missing","dismissal_exists"],"legal_focus":["employee_count_threshold","written_notice_requirement"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["5인이상+서면통지위반=부당해고","상시근로자5인이상+해고서면통지결여=부당"],"exclude_for_queries":[],"summary_short":"5인이상사업장+해고서면통지위반=부당해고","holding_summary":"사업장의 상시 근로자 수는 5인 이상으로 근로기준법의 적용을 받는 사업장+해고서면통지 위반으로 부당해고","retrieval_note":"5인이상 + 서면통지결여 부당해고","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351895","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["performance_review_as_discipline","performance_review_justified"],"legal_focus":["jurisdiction_scope","disciplinary_validity"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근무평정=근기법23조징벌해당이나공정하지않다보기어려움=기각","근무평정=징벌에해당=구제대상이나실체판단=정당기각"],"exclude_for_queries":[],"summary_short":"근무평정=근기법23조징벌해당이나공정하지않다보기어려워=기각","holding_summary":"근무평정이 근로기준법 제23조제1항의 그 밖의 징벌에는 해당하나+근무평정기준이 공정하지 못하고 신빙성이 없는 부당한 근무평정이라 보기는 어렵다고 판단=기각","retrieval_note":"근무평정=징벌에 해당(구제대상 인정)이나 공정성 심사에서 정당 기각 — batch_032 id_350377(성과평가=징벌아님)의 반대 유형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351897","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","negotiation_conducted"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["업무상필요성+불이익없음+협의절차=인사발령정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"인사발령=업무상필요성+불이익없음+협의절차이행=정당","holding_summary":"인사발령의 업무상 필요성이 인정되고 생활상 불이익이 사회통념상 감수할 수 없을 정도로 현저하다고 보기 어려우며 신의칙상 요구되는 절차를 거치지 않았다고 보기 어려움=정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351913","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","negotiation_conducted"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사명령업무상필요성+협의절차=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"인사명령=업무상필요성+불이익없음+협의절차=정당","holding_summary":"인사명령은 업무상 필요성이 인정되며 생활상의 불이익이 근로자가 통상 감수하여야 할 정도를 현저하게 벗어난 것으로 보기 어렵고 근로자와 신의칙상 요구되는 협의절차를 준수하였으므로 정당","retrieval_note":"TV 정당 전형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_351917","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보업무상필요성+불이익없음=인사권재량범위내정당","인사상재량권범위내=정당"],"exclude_for_queries":[],"summary_short":"전보=업무상필요성+불이익없음=인사상재량권범위내정당","holding_summary":"전보는 업무상 필요성이 인정되고 생활상 불이익이 근로자가 통상 감수하여야 할 정도를 현저하게 벗어난 것이라고 보기 어려우므로 인사상 재량권 범위 내에서 행해진 정당한 인사명령","retrieval_note":"TV 정당 — 인사재량권 범위 명시","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35197","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_found_unfair","no_business_necessity","excessive_hardship","no_consultation","work_location_specified_in_contract"],"legal_focus":["transfer_validity_3prong","contractual_working_conditions"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약서근로장소특정+업무상필요성없음+장거리출퇴근+협의없음=부당전직","근로계약특정+3요건불충족=부당전직"],"exclude_for_queries":[],"summary_short":"근로계약서근로장소특정+업무상필요성없음+불이익큼+협의없음=부당전직","holding_summary":"근로계약서에 근로장소와 업무내용이 특정되어 있는 상황에서 업무상 필요성이 없고 장거리 출퇴근으로 생활상 불이익이 크며 신의칙상 협의절차도 준수하지 않은 전직=부당","retrieval_note":"근로계약서에 근무장소 특정 + 3요건 불충족 부당전직 (batch_032 id_350689 정반대 사례)","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35203","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["no_dismissal_found","no_objection_raised","amicable_termination"],"legal_focus":["dismissal_existence","voluntary_resignation"],"industry_context":"unknown","exclusion_flags":["settlement_or_mutual_termination"],"include_for_queries":["이의제기없음+우호적방식종료=해고부존재재심유지","근로관계우호적종료=해고부존재"],"exclude_for_queries":[],"summary_short":"이의제기없음+우호적방식근로관계종료=해고부존재=재심유지","holding_summary":"근로자가 근로관계 종료에 대하여 이의를 제기하지 아니하였을 뿐만 아니라 사용자와 우호적인 방식으로 근로관계를 종료한 것에 대하여 해고가 존재하지 아니한다고 판정=재심유지","retrieval_note":"우호적 종료 + 이의제기 없음 = 해고부존재","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35239","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["five_or_fewer_employees","outside_jurisdiction"],"legal_focus":["employee_count_threshold","jurisdiction_scope"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["상시5인미만=부당해고구제신청대상아님각하","5인미만사업장=근기법적용제외=각하재심유지"],"exclude_for_queries":[],"summary_short":"상시5인미만사업장=부당해고구제신청대상아님각하=재심유지","holding_summary":"상시 5명 미만의 근로자를 사용하는 사업장으로 부당해고 구제신청의 대상이 되지 않는다고 판정=재심유지","retrieval_note":"5인 미만 = 부당해고 구제신청 대상 아님","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35285","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["statute_of_limitations_expired"],"legal_focus":["filing_deadline"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["부당전직구제신청제척기간도과각하","제척기간경과=각하"],"exclude_for_queries":[],"summary_short":"부당전직구제신청제척기간도과각하","holding_summary":"부당전직 구제신청은 제척기간을 도과하였다고 판정=각하","retrieval_note":"제척기간 도과 각하","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35299","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["no_dismissal_found","absenteeism","no_termination_notice"],"legal_focus":["dismissal_existence"],"industry_context":"unknown","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["해고통지없음+장기무단결근=스스로출근않음=해고부존재","해고통지받은사실없음=해고부존재"],"exclude_for_queries":[],"summary_short":"해고통지받은사실없음+장기무단결근=스스로출근안함=해고부존재","holding_summary":"해고 여부를 결정할 만한 지위에 있는 자에게 해고 통지를 받은 사실이 없고 사용자의 출근명령에도 어떠한 의사 표시 없이 장기간 무단결근 한 근로자는 스스로 출근을 하지 않은 것=해고부존재","retrieval_note":"해고통지 없음 + 무단결근 = 스스로 출근 안 함 = 해고부존재","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35317","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","remedial_interest_exists"],"legal_focus":["transfer_validity_3prong","remedial_interest"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["구제이익존재+전보업무상필요성+불이익없음=정당재심유지","TV정당재심유지"],"exclude_for_queries":[],"summary_short":"구제이익존재+전보=업무상필요성+불이익없음=정당=재심유지","holding_summary":"구제신청의 이익은 존재하나 전보의 업무상 필요성이 인정되고 근로자에게 생활상 불이익이 크다고 보기 어려워 정당=재심유지","retrieval_note":"구제이익 인정 후 전보 정당 재심유지","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35321","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_found_unfair","insufficient_consultation","no_unfair_labor_practice"],"legal_focus":["transfer_validity_3prong","consultation_requirement","unfair_labor_practice"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["충분한협의없이전보=부당전보+부당노동행위증거없어기각","협의불충분=부당전보+부당노동행위기각"],"exclude_for_queries":[],"summary_short":"충분한협의없이전보=부당전보+부당노동행위=증거없어기각","holding_summary":"충분한 협의절차 없이 이루어진 전보명령은 부당전보로 인정+부당노동행위는 구체적인 증거가 없어 기각","retrieval_note":"협의 불충분 = 부당전보 + 부당노동행위 증거 부족 기각","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35325","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","no_prior_consultation","discretion_within_managerial_rights"],"legal_focus":["transfer_validity_3prong","managerial_discretion"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사전협의없이전보이나인사권재량+업무상필요성=정당","협의없어도업무상필요성+불이익없음=정당"],"exclude_for_queries":[],"summary_short":"사전협의없이전보이나인사권재량+업무상필요성+불이익없음=정당","holding_summary":"사전 협의 절차 없이 전보 발령이 이루어졌으나 전보는 인사권자인 사용자의 권한으로 상당한 재량권을 가지며 업무상 필요성이 인정되고 생활상 불이익도 구체적으로 확인되지 않으므로 정당","retrieval_note":"협의 없어도 인사권 재량 + 업무상 필요성 충족 = 정당 유형","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_3535","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["suspension","transfer"],"fact_markers":["disciplinary_grounds_proven","proportionate_sanction","procedure_followed","transfer_upheld","sexual_harassment_case","victim_separation_transfer"],"legal_focus":["disciplinary_validity","transfer_validity_3prong","business_necessity_standard"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["성희롱발언정직=정당+피해자분리전보=업무상필요성=정당","성희롱관련피해자분리전보=업무상필요성인정=정당"],"exclude_for_queries":[],"summary_short":"성희롱발언정직=정당+피해자분리전보=업무상필요성=정당=재심유지","holding_summary":"다수의 여직원에게 성희롱적 발언을 한 행위에 따른 정직처분은 정당+근로자와 피해자들을 분리하기 위한 전보 발령도 업무상 필요성이 있어 정당=재심유지","retrieval_note":"성희롱 정직 정당 + 피해자 분리목적 전보 업무상 필요성 인정 (batch_033 id_350889 고충처리분리조치와 동계열)","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_3537","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship"],"legal_focus":["transfer_validity_3prong"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["인사명령+전보모두업무상필요성+불이익없음=정당","TV정당기각"],"exclude_for_queries":[],"summary_short":"인사명령+전보모두업무상필요성+불이익없음=정당","holding_summary":"인사명령과 전보 모두 업무상 필요성이 인정되고 그에 따른 생활상 불이익이 근로자들이 통상 감수하여야 할 정도를 현저하게 벗어나지 않았으므로 정당","retrieval_note":"인사명령+전보 복수 처분 양방 정당","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35395","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_upheld","business_necessity_proven","no_significant_hardship","productivity_improvement"],"legal_focus":["transfer_validity_3prong","business_necessity_standard"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["생산성제고업무상필요성+불이익없음=전환배치정당","생산성향상목적전환배치=업무상필요성인정=정당"],"exclude_for_queries":[],"summary_short":"생산성제고등업무상필요성+불이익없음=전환배치정당","holding_summary":"생산성 제고 등의 업무상 필요성이 인정되고 생활상 불이익도 크지 않아 전환배치는 정당","retrieval_note":"생산성 제고 목적 = 업무상 필요성 인정","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35397","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["disciplinary_dismissal"],"fact_markers":["disciplinary_grounds_proven","proportionate_sanction","procedure_followed","moonlighting_misconduct"],"legal_focus":["disciplinary_validity","proportionality_review"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["겸업행위=징계사유인정+양정적정+절차정당=해고정당","겸업금지위반=징계해고정당"],"exclude_for_queries":[],"summary_short":"겸업행위인정+양정적정+절차정당=해고정당","holding_summary":"근로자의 겸업 행위가 인정되고 사용자의 사업 특성 및 근로자의 근무환경 등을 고려하면 징계양정이 적정하며 징계절차에 하자가 없으므로 해고가 정당","retrieval_note":"겸업 금지 위반 징계해고 정당","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35435","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer","suspension"],"fact_markers":["transfer_upheld","business_necessity_proven","disciplinary_grounds_proven"],"legal_focus":["transfer_validity_3prong","disciplinary_validity"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["부당전직+부당정직구제신청기각","전직정당+정직정당기각"],"exclude_for_queries":[],"summary_short":"부당전직·부당정직구제신청기각","holding_summary":"부당전직 및 부당정직 구제신청 모두 기각","retrieval_note":"전직+정직 복합 기각","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35445","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["disciplinary_grounds_proven","proportionate_sanction","procedure_followed","refusal_to_comply_with_transfer","defamation_by_email"],"legal_focus":["disciplinary_validity","proportionality_review"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보명령불응+상급자비방이메일=정직3월=정당재심유지","전보불응=징계사유+비방이메일=정직정당"],"exclude_for_queries":[],"summary_short":"전보명령불응+상급자비방이메일=정직3월정당=재심유지","holding_summary":"사용자의 전보 명령에 장기간 불응하고 상급자를 비방하는 전자우편을 동료 근로자들에게 보낸 행위 등에 대한 정직 3월의 징계처분은 정당=재심유지","retrieval_note":"전보명령 불응이 징계사유(정직)가 된 특수 사례 — 전보와 징계의 역전","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35479","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["transfer_found_unfair","no_business_necessity","excessive_hardship","no_consultation","abuse_of_managerial_discretion"],"legal_focus":["transfer_validity_3prong","managerial_discretion"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["지방→본사전보업무상필요성부족+불이익큼+협의없음=인사재량권남용=부당전보","TV부당_3요건불충족+인사재량권남용"],"exclude_for_queries":[],"summary_short":"지방→본사전보=업무상필요성부족+불이익큼+협의없음=인사재량권남용=부당전보","holding_summary":"지방에서 본사로 전보발령한 업무상 필요성이 부족하고 생활상 불이익의 정도가 크며 성실한 협의를 거치지 않아 인사재량권을 남용한 부당전보","retrieval_note":"3요건 불충족 + 인사재량권 남용 명시 부당전보","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},

{"case_id":"id_35495","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["no_transfer_found","reinstatement_to_original_position"],"legal_focus":["transfer_existence"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["복직명령으로원래업무복직=전보처분부존재","해고전업무및장소복직=전보부존재"],"exclude_for_queries":[],"summary_short":"해고전원래업무및근로장소복직명령=전보처분존재하지않음","holding_summary":"사용자는 해고 전에 근로자가 수행하던 업무 및 근로 장소에 복직명령을 하여 전보처분이 존재하지 않는다고 판정","retrieval_note":"복직명령으로 원래 업무에 복귀 = 전보처분 부존재","confidence":"high","review_status":"auto_tagged_v3","tag_version":"v3"},
]

out_path = 'retagging/output/reviewed/transfer_batch_034_reviewed.jsonl'
with open(out_path, 'w', encoding='utf-8') as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')
print(f'Written {len(records)} records')
