import json, pathlib, sys
sys.stdout.reconfigure(encoding='utf-8')

OUT = pathlib.Path("retagging/output/reviewed/transfer_batch_049_reviewed.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)

records = [
# ── transfer_validity (TV 정당) ───────────────────────────────────────────
{
  "case_id": "id_40761",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "rotation_policy", "clinical_vs_admin"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "healthcare",
  "exclusion_flags": [],
  "include_for_queries": ["행정업무직원→임상업무부서전보=다양한직무경험=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "행정직→임상업무 부서 전보=다양한 직무경험=TV 정당",
  "holding_summary": "권역심뇌혈관질환센터 행정업무 직원의 임상 업무 부서 전보=다양한 직무경험을 통한 업무능력 향상 목적=업무상 필요성 인정=TV 정당",
  "retrieval_note": "의료기관 행정→임상 부서 전보=직무경험 목적 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407615",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "minimal_life_disruption", "consultation_procedure_followed"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["TV3-prong모두충족=인사발령정당"],
  "exclude_for_queries": [],
  "summary_short": "TV 3-prong 모두 충족=인사발령 정당",
  "holding_summary": "인사발령 업무상 필요성 인정, 생활상 불이익 없음, 협의절차 하자 없음=TV 3-prong 모두 충족=정당",
  "retrieval_note": "TV 3-prong 완전 충족 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407651",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "cba_provision", "contractual_transfer_clause"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["단체협약취업규칙인사권=업무상필요성인정=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "단체협약·취업규칙 인사권 규정+업무상 필요성=TV 정당",
  "holding_summary": "단체협약과 취업규칙에 배치전환 인사권 회사에 있음 규정+준공영제 임금협정 내용 고려=업무상 필요성 인정=TV 정당",
  "retrieval_note": "단체협약·취업규칙 인사권 규정 근거 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407695",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "scope_of_work_adjustment", "order_not_disciplinary"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["업무범위축소외근로조건동일=업무범위조정에불과=인사명령정당"],
  "exclude_for_queries": [],
  "summary_short": "업무범위 축소 외 근로조건 동일 유지=업무범위 조정에 불과=인사명령 정당",
  "holding_summary": "인사명령 이후 업무범위 축소 외 근로 종류·내용·장소·임금·직급·보고체계 동일 유지=업무범위 조정에 불과=인사명령 정당",
  "retrieval_note": "업무범위 조정에 불과=인사명령 정당 (TV 기준 미달 분쟁 아님) 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407719",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "order_not_disciplinary", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사명령=징계아님+업무상필요성+생활상불이익없음=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "인사명령=징계 아님+업무상 필요성+생활상 불이익 없음=TV 정당",
  "holding_summary": "인사명령은 징계 해당하지 않고, 업무상 필요성 인정, 생활상 불이익 현저하지 않음=TV 정당",
  "retrieval_note": "인사명령=징계 아님 확인+TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407771",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "worker_requested_transfer", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로자스스로이동요청+원청불만=TV정당+해고없음"],
  "exclude_for_queries": [],
  "summary_short": "근로자 스스로 근무지 이동 요청+원청 불만=TV 정당+해고 없음",
  "holding_summary": "근로계약서에 전보 규정, 근로자가 사용자에게 근무지 이동 요청, 원청사의 근로자에 대한 불만 제기=업무상 필요성 인정+생활상 불이익 없음=TV 정당+해고 없음",
  "retrieval_note": "근로자 요청+원청 불만으로 TV 정당+해고 없음 기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407791",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "performance_evaluation_poor", "disciplinary_history"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "retail",
  "exclusion_flags": [],
  "include_for_queries": ["팀실적저조+홈쇼핑오노출사고징계이력+업무지시위반=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "TC식품팀 실적 저조+홈쇼핑 오노출 사고 징계이력+업무지시 위반=TV 정당",
  "holding_summary": "팀장인 근로자가 이끈 TC식품팀 실적 저조+홈쇼핑 방송 오노출 사고 징계이력+업무지시·절차 위반 등 사유 종합=업무상 필요성 인정=TV 정당",
  "retrieval_note": "팀 실적 저조+징계이력+업무지시위반 복합 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407833",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer", "demotion"],
  "fact_markers": ["business_necessity_recognized", "merger_reorganization", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["자회사간합병=경영상필요성인정=전보+강등정당"],
  "exclude_for_queries": [],
  "summary_short": "자회사 간 합병=경영상 필요성+TV 정당+강등 정당",
  "holding_summary": "자회사 간 합병에 따른 경영상 필요성 인정, 생활상 불이익 통상 감수 범위 내=전보·강등=사용자 정당한 인사권 범위 내",
  "retrieval_note": "합병에 따른 경영상 필요성 인정 전보+강등 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407879",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "public_contract_reorganization"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["화성시시립도서관위수탁변경=기술직인력재배치필요성=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "화성시 도서관 위·수탁 변경=기술직 인력 재배치=TV 정당",
  "holding_summary": "재단의 화성시 시립도서관 위·수탁 변경 협약+조직개편+서버 관리 주체 변경=기술직 담당 직원 인력 재배치 업무상 필요성 인정=TV 정당",
  "retrieval_note": "공공 위수탁 변경에 따른 기술직 인력 재배치 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407895",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "vacancy_due_to_resignation"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "service",
  "exclusion_flags": [],
  "include_for_queries": ["전재무회계팀장갑작스러운사직=업무공백=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "전 재무회계팀장 갑작스러운 사직=공백 보충=TV 정당",
  "holding_summary": "전 재무회계팀장의 갑작스러운 사직으로 전보 필요성 발생, 근로자가 거부하여 원 부서로 재발령=업무상 필요성 인정=TV 정당",
  "retrieval_note": "전임자 갑작스러운 사직으로 인한 전보 필요성 인정 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407935",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "remedial_interest_preserved", "coworker_conflict"],
  "legal_focus": ["transfer_validity_3prong", "remedial_interest"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["교대제→일근제전직=임금감소=구제이익있음+업무상필요성인정=TV정당확정"],
  "exclude_for_queries": [],
  "summary_short": "교대제→일근제 전직=임금 감소=구제이익 있음+업무상 필요성=TV 정당 확정",
  "holding_summary": "교대제→일근제 전직=임금 감소=구제이익 존재. 고객사 불량 발생+팀원 마찰=타 팀원 분리 필요=업무상 필요성 인정=TV 정당 확정(재심 유지)",
  "retrieval_note": "교대제→일근제 임금감소=구제이익 있음+업무상필요성 인정 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407945",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "coworker_conflict", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["팀장팀원불화=원만한조직관리=배치전환필요성=TV정당+해고없음"],
  "exclude_for_queries": [],
  "summary_short": "팀장-팀원 불화=원만한 조직관리=배치전환 필요성=TV 정당",
  "holding_summary": "인사규정+팀장-팀원 불화=원만한 조직관리를 위한 인사조치 필요성=업무상 필요성 인정=TV 정당+해고 없음",
  "retrieval_note": "팀장-팀원 불화를 근거로 한 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408143",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "operational_needs"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "it",
  "exclusion_flags": [],
  "include_for_queries": ["아나운서리포터업무한정어렵+경영악화시대변화=편집요원전환=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "아나운서·리포터 업무 한정 어렵+경영 악화·시대 변화=편집요원 전환=TV 정당",
  "holding_summary": "근로자 업무가 아나운서·리포터로만 한정되어 있다고 보기 어렵고, 경영상황 악화·시대변화에 따라 보도국 편집요원으로 배치전환=업무상 필요성 인정=TV 정당",
  "retrieval_note": "방송미디어업 아나운서→편집요원 전환 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408227",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "coworker_conflict"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["상급자갈등후어연공장시설관리업무=업무상필요성인정=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "같은 팀 상급자 갈등=어연공장 시설관리 업무=TV 정당",
  "holding_summary": "인사총무팀 상급자들과 업무상 갈등, 공사 종료 후에도 어연공장 시설관리 업무 지속=업무상 필요성 인정=TV 정당",
  "retrieval_note": "상급자 갈등 후 격리·재배치 전보 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408359",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "industry_specific_long_distance_transfer"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "sales",
  "exclusion_flags": [],
  "include_for_queries": ["전국유통점원거리근무특수성=광양점전보정당"],
  "exclude_for_queries": [],
  "summary_short": "전국 유통점 원거리 근무 특수성=광양점 전보 정당",
  "holding_summary": "회사가 전국 유통점 운영=원거리 근무 불가피한 특수성, 수도권→광양점 전보 전례 있음=업무상 필요성 인정=TV 정당",
  "retrieval_note": "전국 유통점 업종의 원거리 전보 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── transfer_validity (TV 부당) ───────────────────────────────────────────
{
  "case_id": "id_408027",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "worker_consent_required", "working_condition_change"],
  "legal_focus": ["transfer_validity_3prong", "consent_validity"],
  "industry_context": "retail",
  "exclusion_flags": [],
  "include_for_queries": ["조직활동가→매장활동가=근로조건변경=동의필요+동의없음+취업규칙위반=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "조직활동가→매장활동가=근로조건 변경=동의 필요+동의 없음=TV 부당",
  "holding_summary": "조직활동가·매장활동가 근로조건 다름=인사이동 시 동의 필요+근로자 동의 없음+직책 변경 후 1년 내 인사이동=취업규칙 위반=TV 부당",
  "retrieval_note": "직책별 근로조건 다름=인사이동 동의 필요+미동의=TV 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408061",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["insincere_reinstatement_order", "remedial_interest_preserved", "inadequate_business_necessity"],
  "legal_focus": ["transfer_validity_3prong", "remedial_interest"],
  "industry_context": "construction",
  "exclusion_flags": [],
  "include_for_queries": ["진정성없는복직명령=구제이익소멸불인정+TV부당"],
  "exclude_for_queries": [],
  "summary_short": "진정성 없는 복직명령=구제이익 소멸 불인정+TV 부당",
  "holding_summary": "사용자가 진정사건 답변으로 복직 의사 표명했을 뿐 정식 복직명령 없음+임금 미지급+복직일 미특정+육아 문제 무시=진정성 없는 복직명령=구제이익 유지+TV 부당",
  "retrieval_note": "진정성없는복직명령배척+구제이익유지+TV부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40815",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "severe_life_disruption", "disguised_forced_resignation"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["저성과영업직→생산공장=업무상필요성입증부족+자진퇴사권유+원거리=TV부당=부분인용"],
  "exclude_for_queries": [],
  "summary_short": "저성과 영업직→생산공장=업무상 필요성 입증 부족+원거리+퇴사권유=TV 부당=부분인용",
  "holding_summary": "영업직 저성과를 이유로 생산공장 전보=인력충원 필요성 입증 부족+업무상 필요성 없음+원거리 생소한 업무+자진퇴사 권유=정신적 고통+생활상 불이익 큼=TV 부당=부분인용",
  "retrieval_note": "저성과 영업직→생산공장 전보=위장 퇴직 유도+TV 부당 부분인용 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408185",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": ["disciplinary_severity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer", "suspension"],
  "fact_markers": ["inadequate_business_necessity", "severe_life_disruption", "consultation_not_conducted", "disciplinary_grounds_rejected_partial"],
  "legal_focus": ["transfer_validity_3prong", "disciplinary_grounds_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["배치전환TV3-prong모두불충족=TV부당+정직징계사유일부불인정=양정과중=부당"],
  "exclude_for_queries": [],
  "summary_short": "TV 3-prong 모두 불충족=TV 부당+정직 징계사유 일부 불인정=양정 과중=부당",
  "holding_summary": "배치전환=업무상필요성없음+생활상불이익큼+신의칙협의없음=TV 3-prong 모두 불충족=TV 부당. 정직=담당팀장결재라인무시·지시불이행 불인정+정보삭제만 인정이나 중징계 과중=부당",
  "retrieval_note": "TV 부당+정직 양정 과중 병합 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408277",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "financial_claim_disproven"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["비상경영주장이나재무제표안정=업무상필요성입증부족=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "비상경영 주장이나 재무제표 안정적=업무상 필요성 입증 부족=TV 부당",
  "holding_summary": "사용자가 비상경영 체제+구미사업소 물류시스템 구축 필요성 주장하나, 공인회계사 자문=재무상황 안정적+물류시스템 구축 계획서 미제출=업무상 필요성 입증 부족=TV 부당",
  "retrieval_note": "비상경영 주장-재무 안정성 검증으로 업무상 필요성 입증 부족 TV 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── no_dismissal ──────────────────────────────────────────────────────────
{
  "case_id": "id_407619",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["employer_threshold_5_workers", "dismissal_found_unfair", "lack_of_written_notice"],
  "legal_focus": ["employer_definition", "dismissal_existence", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["상시6명인정(6.04명)=5인이상사업장+해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "상시 6명(6.04명) 인정=5인 이상 사업장+해고 존재=부당해고",
  "holding_summary": "사용자가 5인 미만 주장하나 6명 근무 인정+산정기간 상시근로자 6.04명=5인 이상 사업장=근로기준법 적용+해고 존재=부당해고",
  "retrieval_note": "상시근로자 산정 결과 5인 이상 확인 후 해고 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407711",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "dismissal_found_unilateral"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["사용자일방적의사=근로관계종료=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "사용자 일방적 의사로 근로관계 종료=해고 존재=부당해고",
  "holding_summary": "2024.9.5. 사용자의 일방적 의사에 의한 근로관계 종료=해고 존재. 근로자 퇴직 의사에 따른 것이라는 사용자 주장=충분한 입증 없음=부당해고",
  "retrieval_note": "사용자 일방적 의사 근로관계종료=해고 존재=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407721",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "resignation_under_duress", "disability_worker"],
  "legal_focus": ["dismissal_existence", "coerced_resignation"],
  "industry_context": "unknown",
  "exclusion_flags": ["settlement_or_mutual_termination"],
  "include_for_queries": ["장애근로자강요사직=반복사직종용+신체접촉공포=강요된사직=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "장애 근로자 사직 반복 강요=공포로 서명=강요된 사직=해고 존재=부당해고",
  "holding_summary": "사용자가 '같이 일할 수 없다·오늘까지 근무하라'며 사직 강요+지체장애3급 근로자가 신체접촉 공포로 권고사직서 작성=의사 없는 강요 사직=해고 존재=부당해고",
  "retrieval_note": "장애 근로자 신체적 공포 이용 강요 사직=해고 존재=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407761",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "verbal_dismissal", "lack_of_written_notice"],
  "legal_focus": ["dismissal_existence", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["유선해고통보=해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "유선 해고 통보=해고 존재+서면통지 없음=부당해고",
  "holding_summary": "사용자가 유선으로 '업무 적응이 안된다며 미안하다'=해고 통보=해고 존재+서면 해고통지 없음=부당해고",
  "retrieval_note": "유선 해고 통보=해고 존재+서면통지 흠결 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407793",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "annual_leave_misclassified_as_absence"],
  "legal_focus": ["dismissal_existence", "annual_leave_rights"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["연차휴가사용=무단결근불인정=해고사유없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "연차휴가 사용=무단결근 불인정=해고사유 없음=부당해고",
  "holding_summary": "잔여 연차휴가 사용 신청=사업 운영에 막대한 지장 없음=연차휴가 사용=근로계약·취업규칙 위반 아님=무단결근 불인정=해고사유 없음=부당해고",
  "retrieval_note": "연차휴가 사용을 무단결근으로 보고 해고=해고사유 불인정=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407837",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "probation",
  "disposition_type": ["dismissal"],
  "fact_markers": ["probation_refusal_is_dismissal", "disciplinary_grounds_rejected"],
  "legal_focus": ["probationary_employment", "disciplinary_grounds_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["사용자승인후교육참여=징계사유불인정=본채용거부=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "사용자 승인 후 교육 참여=징계사유 불인정=본채용 거부=부당해고",
  "holding_summary": "수습기간 중 4차례 교육 참여=모두 사용자 승인 후 참여 확인=다른 부서 지원으로 인한 불이익도 근로자 귀책 아님=징계사유 불인정=본채용 거부=부당해고",
  "retrieval_note": "사용자 승인 교육 참여=징계사유 불인정=본채용거부 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407927",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "dismissal_found_unilateral"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["대화내용및제반사정=사용자일방적의사=해고존재=부당해고확정"],
  "exclude_for_queries": [],
  "summary_short": "대화 내용·제반 사정=사용자 일방적 의사=해고 존재=부당해고 확정(재심)",
  "holding_summary": "근로관계 종료 과정의 대화 내용·제반 사정=사용자 일방적 의사에 따른 해고=해고 존재=부당해고 인정 재심 유지",
  "retrieval_note": "대화 내용·제반 사정으로 일방적 의사 해고 인정 부당해고 확정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407933",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["no_dismissal_found", "termination_notice_refused"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "construction",
  "exclusion_flags": ["unrelated_to_dismissal"],
  "include_for_queries": ["근로관계종료통지서수령거부=해고의사표시아님+차기현장인사명령=해고철회=해고없음=취소"],
  "exclude_for_queries": [],
  "summary_short": "종료 통지서 수령 거부=해고 아님+인사명령=해고 철회=해고 없음=원심 취소",
  "holding_summary": "근로관계 종료일 통지서 수령 거부=일방적 해고 의사표시로 보기 어렵고, 설령 해고로 보더라도 2024.5.21. 새 근무지 인사명령=해고 철회로 볼 수 있음=해고 없음=원심 취소",
  "retrieval_note": "종료 통지서 수령 거부=해고 불인정+인사명령=해고 철회 원심취소 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408343",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "resignation_under_duress_rejected"],
  "legal_focus": ["dismissal_existence", "consent_validity"],
  "industry_context": "unknown",
  "exclusion_flags": ["settlement_or_mutual_termination"],
  "include_for_queries": ["합의서동의거절=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "합의서 동의 거절=해고 존재=부당해고",
  "holding_summary": "사용자가 합의서 제시 여부 다투나, 근로자가 합의서에 동의할 수 없어 거절했다고 주장=사용자 주장 입증 없음=해고 존재=부당해고",
  "retrieval_note": "합의서 동의 거절=해고 존재=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408361",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "agent_authority_for_dismissal"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "construction",
  "exclusion_flags": [],
  "include_for_queries": ["현장팀장해고통보=채용과정주도=해고권한인정=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "현장 팀장 해고 통보=채용 과정 주도=해고 권한 인정=해고 존재=부당해고",
  "holding_summary": "현장 팀장이 작업 물량 부진을 이유로 근무 종료 날짜 특정 해고 통보+팀장이 채용 과정 주도=해고 권한 인정=해고 존재=부당해고",
  "retrieval_note": "현장 팀장 해고 권한 인정=해고 존재 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── disciplinary_severity ──────────────────────────────────────────────────
{
  "case_id": "id_407661",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["disciplinary_grounds_rejected_partial", "insufficient_evidence"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무태만외징계사유입증부족=사유불인정=징계해고부당"],
  "exclude_for_queries": [],
  "summary_short": "업무 태만 외 징계사유=객관적 입증 근거 부족=사유 불인정=징계해고 부당",
  "holding_summary": "업무 태만=징계사유 인정이나, 다른 징계사유=객관적 입증 근거 부족=불인정. 징계양정도 과중=징계해고 부당",
  "retrieval_note": "일부 징계사유 불인정+양정 과중 징계해고 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407685",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["disciplinary_grounds_rejected", "insufficient_evidence"],
  "legal_focus": ["disciplinary_grounds_validity"],
  "industry_context": "service",
  "exclusion_flags": [],
  "include_for_queries": ["경비원하대지시+타아파트비교주장=사실관계입증안됨=징계사유불인정=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "경비원 하대·지시 등 주장=사실관계 입증 안됨=징계사유 불인정=부당해고",
  "holding_summary": "경비원들에게 하대 및 지시성 발언+타 아파트 비교 등 징계사유 주장=사실관계 입증 안됨=기계·전기 업무 담당자로 징계사유 불인정=부당해고",
  "retrieval_note": "아파트 관리직 징계사유 입증 불비=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407705",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["disciplinary_grounds_recognized_partial", "proportionate_sanction"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["병가중외부심사참석+출장여비부적정=정직정당(병가중교육참석은사유불인정)"],
  "exclude_for_queries": [],
  "summary_short": "병가 중 외부심사 참석+출장여비 부적정=정직 정당 (교육 참석은 불인정)",
  "holding_summary": "병가 중 교육 참석=징계사유 불인정. 주말·공휴일 근무지 이탈·부당 지시요구+병가 중 외부심사위원 참석+출장여비 수령 부적정=정직 정당",
  "retrieval_note": "병가 중 다수 비위(근무지이탈+외부심사참석+출장여비부적정) 정직 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407715",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["disciplinary_grounds_rejected", "legitimate_right_exercise"],
  "legal_focus": ["disciplinary_grounds_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["구제신청및소권행사=헌법상재판청구권=징계사유불인정=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "구제신청·소권 행사=헌법상 재판청구권=징계사유 불인정=부당해고",
  "holding_summary": "근로자의 노동위원회 구제신청·법원 소제기=헌법·법률 보장 재판청구권의 정당한 권리행사=사용자 괴롭힐 목적의 남용으로 보기 어려움=징계사유 불인정=부당해고",
  "retrieval_note": "구제신청·소권행사=적법 권리행사=징계사유 불인정=부당해고 패턴 (batch_045 id_404749 유사)",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407967",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["disciplinary_grounds_recognized", "proportionate_sanction", "insubordination"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["동료폭언욕설+인사명령거부+근무지이탈=정직정당"],
  "exclude_for_queries": [],
  "summary_short": "동료 폭언·욕설+인사명령 거부+근무지 이탈=정직 정당",
  "holding_summary": "동료 근로자 폭언·욕설(위화감·정신적 고통)+인사발령 거부+근무지 이탈=징계사유 인정=정직 정당",
  "retrieval_note": "폭언+인사명령거부+근무지이탈 복합 징계 정직 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407999",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["disciplinary_grounds_rejected", "unfair_performance_evaluation", "no_improvement_opportunity"],
  "legal_focus": ["disciplinary_grounds_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근무성적평가불공정+직무교육전환배치기회없음=해고사유불인정=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "근무성적 평가 불공정+직무교육·전환배치 기회 없음=해고사유 불인정=부당해고",
  "holding_summary": "근무성적·능력 평가=합리적·공정한 평가로 보기 어렵고, 직무교육·전환배치 등 개선 기회 미제공=해고사유 불인정=부당해고",
  "retrieval_note": "평가 불공정+개선기회 미제공=해고사유 불인정=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408135",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["disciplinary_grounds_recognized", "proportionate_sanction", "management_position"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["전임회장퇴진주도+관계기관진정=공직유관단체임원=정직1월정당"],
  "exclude_for_queries": [],
  "summary_short": "전임 회장 퇴진 주도+관계기관 진정=공직유관단체 임원=정직 1월 정당",
  "holding_summary": "전임 회장 퇴진 주도+퇴진 요구 진정서 관계기관 제출=징계사유 인정. 공직유관단체 기관장 지위임에도 비위행위+반성 태도 없음=정직 1월 정당",
  "retrieval_note": "공직유관단체 임원 조직 내부 분란 주도 정직 1월 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408353",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["reprimand"],
  "fact_markers": ["disciplinary_grounds_recognized", "proportionate_sanction"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["금품수수=임직원행동규칙상수수금지해당여부=견책정당"],
  "exclude_for_queries": [],
  "summary_short": "금품 수수=수수 금지 범위 해당 여부=견책 정당",
  "holding_summary": "임직원 행동규칙상 농수산물 15만원 이내는 수수금지 금품 해당 않으나, 안전경영실장으로서 금품 관련 행위=견책 정당",
  "retrieval_note": "금품 수수 견책 정당 패턴 (행동규칙 예외 한도 내 포함)",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── procedure ─────────────────────────────────────────────────────────────
{
  "case_id": "id_407739",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["employer_threshold_below_5", "separate_legal_entities"],
  "legal_focus": ["employer_definition"],
  "industry_context": "unknown",
  "exclusion_flags": ["unrelated_to_dismissal"],
  "include_for_queries": ["두법인사업목적업종임원구성상이=하나의사업장아님=상시5인미만=기각"],
  "exclude_for_queries": [],
  "summary_short": "두 법인 사업목적·업종·임원 구성 상이=별개 사업장=상시 5인 미만=기각",
  "holding_summary": "두 법인의 사업목적·업종이 상이하고 임원 구성에 차이=하나의 사업장으로 보기 어려움=상시근로자 5인 미만=근로기준법 적용 안됨=기각",
  "retrieval_note": "두 법인 별개 사업장 확인=5인 미만=기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407877",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["remedial_interest_expired", "reinstatement_order_valid", "worker_refused_reinstatement"],
  "legal_focus": ["remedial_interest"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["2차원직복직통지+복귀않음+금전보상만원한다=구제이익소멸=기각"],
  "exclude_for_queries": [],
  "summary_short": "2차 원직복직 통지에도 미출근+금전보상만 원함=구제이익 소멸=기각",
  "holding_summary": "사용자가 2차례 원직복직 통지+불복귀 시 자발적 사직 처리 통보. 근로자는 수령 후에도 복직 않고 금전보상만 원함=구제이익 소멸=기각",
  "retrieval_note": "복직 통지 2회+금전보상만 고집=구제이익 소멸 기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407919",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["reexamination_standing_rejected"],
  "legal_focus": ["remedial_interest"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["재심신청당사자아님=초심인용결정에불복자격없음=각하"],
  "exclude_for_queries": [],
  "summary_short": "재심 신청 당사자 자격 없음=각하",
  "holding_summary": "근로기준법 제31조 제1항=재심 신청 당사자는 구제명령·기각결정에 불복하는 사용자나 근로자. 노동위원회규칙 제89조=당사자의 재심신청. 근로자 측 신청 자격 없음=각하",
  "retrieval_note": "재심신청 당사자 자격 요건 불충족=각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407939",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["filing_deadline_exceeded"],
  "legal_focus": ["procedural_deadline"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전직통보후3개월초과=구제신청기간도과=각하"],
  "exclude_for_queries": [],
  "summary_short": "전직 통보 후 3개월 초과 구제신청=기간 도과=각하",
  "holding_summary": "전직 통보일(2024.6.25.) 기산=3개월 초과한 2024.9.30. 구제신청=근로기준법 제28조제2항 기간 도과=각하",
  "retrieval_note": "전직 통보 후 3개월 초과 구제신청=각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408025",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["disciplinary_grounds_recognized"],
  "legal_focus": ["remedial_interest", "disciplinary_grounds_validity"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["근무평정=그밖의징벌=구제신청대상해당+근무평정정당"],
  "exclude_for_queries": [],
  "summary_short": "근무평정=그 밖의 징벌=구제신청 대상 해당+근무평정 정당",
  "holding_summary": "근무평정 결과로 승격 심사에서 불리한 지위=구제신청 대상(해고 등에 준하는 징벌적 성격)=구제 가능. 근무평정=순환근무 반발+방사선 과다노출 사건=정당",
  "retrieval_note": "근무평정=구제신청 대상 해당 확인+근무평정 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408283",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["filing_deadline_exceeded"],
  "legal_focus": ["procedural_deadline"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사발령일로부터3개월초과=11개월후구제신청=기간도과=각하"],
  "exclude_for_queries": [],
  "summary_short": "인사발령 후 11개월 지난 구제신청=기간 도과=각하",
  "holding_summary": "2022.7.1. 인사발령 후 2023.6.12. 구제신청=11개월 경과=근로기준법 제28조제2항 3개월 기간 도과=각하",
  "retrieval_note": "인사발령 3개월 초과 구제신청=각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── union_activity ─────────────────────────────────────────────────────────
{
  "case_id": "id_408059",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["anti_union_motive_rejected", "business_necessity_recognized"],
  "legal_focus": ["unfair_labor_practice", "transfer_validity_3prong"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["1인시위→현장직전보=부당노동행위가능성있으나노조동의=부당노동행위불인정"],
  "exclude_for_queries": [],
  "summary_short": "1인 시위→현장직 전보=부당노동행위 가능성 있으나 노조 동의=부당노동행위 불인정",
  "holding_summary": "내근직 노조 임원의 청사 앞 1인 시위 이유로 현장직 전보=부당노동행위 가능성 있으나, 노동조합이 이를 수용하였고 뚜렷한 부당노동행위 의사 증거 없음=불이익취급·지배개입 불인정",
  "retrieval_note": "1인시위→현장직전보=부당노동행위 가능성+노조동의=불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40817",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["anti_union_motive_rejected", "business_necessity_recognized"],
  "legal_focus": ["unfair_labor_practice", "transfer_validity_3prong"],
  "industry_context": "service",
  "exclusion_flags": [],
  "include_for_queries": ["용역계약갱신1명증원=업무변경=TV정당+부당노동행위불인정"],
  "exclude_for_queries": [],
  "summary_short": "용역계약 갱신 1명 증원=업무 변경=TV 정당+부당노동행위 불인정",
  "holding_summary": "용역계약 갱신으로 1명 증원에 따른 업무 변경=업무상 필요성 인정, 임금 등 근로조건 변동 없음=TV 정당+부당노동행위 의사 없음=불인정",
  "retrieval_note": "용역계약 변경에 따른 TV 정당+부당노동행위 불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408365",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["anti_union_motive_rejected"],
  "legal_focus": ["unfair_labor_practice"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["배차운영시스템변경=사무직노조조합원차별적용근거없음=부당노동행위불인정"],
  "exclude_for_queries": [],
  "summary_short": "배차 운영시스템 변경=사무직 노조 조합원 차별 적용 근거 없음=부당노동행위 불인정",
  "holding_summary": "배차 운영시스템 변경 시 10분 대기시간 누락+사무직 노조 조합원만 휴게시간 전 식사 허용 주장=객관적 증거 없음=사무직 노조 조합원 차별 대우 불인정=부당노동행위 불인정",
  "retrieval_note": "배차시스템 변경 중 조합원 차별 주장=증거 없음=부당노동행위 불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_408441",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": ["disciplinary_severity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer", "suspension"],
  "fact_markers": ["anti_union_motive_rejected", "consultation_procedure_followed"],
  "legal_focus": ["unfair_labor_practice"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사발령+기간제채용계획=단협위반여부별개로협의진행인정=부당노동행위불인정"],
  "exclude_for_queries": [],
  "summary_short": "인사발령+기간제 채용 계획=단협 위반 별개로 실질적 협의 진행=부당노동행위 불인정",
  "holding_summary": "인사발령+기간제근로자 채용계획=단체협약 위반 여부와 별개로 노사간 실질적 협의 진행=뚜렷한 부당노동행위 의사 없음=부당노동행위 불인정",
  "retrieval_note": "노사 협의 진행 인정=부당노동행위 의사 없음 불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── redundancy ─────────────────────────────────────────────────────────────
{
  "case_id": "id_407671",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": ["contract_expiry"],
  "employment_stage": "fixed_term",
  "disposition_type": ["dismissal"],
  "fact_markers": ["supra_agency_contract_termination", "premature_dismissal"],
  "legal_focus": ["redundancy_requirements"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["아동복지시설통폐합=위탁종료전조기배치전환=해고시점근거없음=통상해고부당"],
  "exclude_for_queries": [],
  "summary_short": "아동복지시설 통폐합·위탁 종료=조기 배치전환 시점 근거 없음=통상해고 부당",
  "holding_summary": "위탁 아동복지시설 통폐합+수탁기간 종료=통상해고이나, 시설 폐쇄로 인한 배치전환 시점을 2024.10.1.로 지정한 근거 없음=해고 시점 부당",
  "retrieval_note": "위탁사업 종료=통상해고이나 해고 시점 근거 없음=부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── contract_expiry ─────────────────────────────────────────────────────────
{
  "case_id": "id_408289",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "fixed_term",
  "disposition_type": ["contract_termination"],
  "fact_markers": ["contract_period_expired"],
  "legal_focus": ["fixed_term_contract"],
  "industry_context": "unknown",
  "exclusion_flags": ["renewal_expectation_dominant"],
  "include_for_queries": ["기간만료퇴직=근로계약종료=전보아님=기각"],
  "exclude_for_queries": [],
  "summary_short": "기간만료 퇴직=근로계약 종료=전보 아님=기각",
  "holding_summary": "2023.1.1.~6.30. 근로계약+2023.6.30. 기간만료 퇴직 사직서 제출=근로계약 종료=전보 해당 없음=기각",
  "retrieval_note": "기간만료 계약 종료=전보 불인정=기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
]

with open(OUT, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Written {len(records)} records")
