import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = []

# id_48281: 전보=이중징계아님+직장내괴롭힘폭언=징계사유+양정적정=정당
records.append({"id": "id_48281", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["pay_cut", "transfer"], "fact_markers": ["전보=이중징계아님", "직장내괴롭힘폭언", "징계사유인정", "양정적정", "감봉정당"], "legal_focus": ["징계사유", "징계양정", "이중징계", "전보징계성"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["전보이중징계아님직장내괴롭힘징계정당", "인사권행사전보이중징계해당않음징계정당"], "exclude_for_queries": [], "summary_short": "전보=인사권행사=이중징계아님+직장내괴롭힘폭언=징계사유+반성참작감봉=정당", "holding_summary": "사용자의 전보조치는 인사권의 행사로서 이중징계에 해당하지 않으며, 직장 내 괴롭힘 피해자에 대한 폭언 및 모욕은 징계사유로 인정되어 반성문 제출을 참작한 감봉 처분은 정당", "retrieval_note": "전보의 이중징계 해당 여부: 인사권 행사이면 이중징계 아님", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48287: 퇴사후정직처분=통상인사권아님=구제이익없음
records.append({"id": "id_48287", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["suspension"], "fact_markers": ["퇴사후정직", "통상인사권아님", "구제이익없음"], "legal_focus": ["구제이익", "퇴사후징계", "인사권범위"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["퇴사후정직처분구제이익없음", "근로관계종료후징계구제신청대상아님"], "exclude_for_queries": [], "summary_short": "퇴사후정직처분=통상인사권행사아님=구제이익없음", "holding_summary": "근로관계 종료 후에 이루어진 정직처분은 통상적인 인사권 행사로서의 징계가 아니라 비위행위 확인의 의미를 갖는 처분이어서 구제이익이 없음", "retrieval_note": "근로관계 종료 후 징계의 구제이익 부인 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48327: 직장내괴롭힘8건중6건인정=징계사유+양정적정=정당
records.append({"id": "id_48327", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["직장내괴롭힘44건중6건인정", "징계사유인정", "부하직원지휘감독", "양정적정"], "legal_focus": ["직장내괴롭힘", "징계사유", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직장내괴롭힘다수사례인정징계정당", "부하직원괴롭힘징계사유인정양정적정"], "exclude_for_queries": [], "summary_short": "직장내괴롭힘44건신고중6건인정=징계사유충분+양정적정=정당", "holding_summary": "44건의 직장 내 괴롭힘 신고 중 6건이 인정되어 징계사유가 충분하고, 부하직원을 지휘·감독하는 위치에서 행한 괴롭힘이라는 점에서 양정도 적정하여 징계 정당", "retrieval_note": "다수 직장내괴롭힘 사례 인정으로 징계 정당. 상급자라는 가중요소", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48331: 대기발령=인사명령+감봉+전보정당
records.append({"id": "id_48331", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["disciplinary_severity"], "employment_stage": "regular", "disposition_type": ["transfer", "pay_cut"], "fact_markers": ["대기발령=인사명령정당", "감봉처분정당", "전보처분정당", "구제신청기각"], "legal_focus": ["대기발령성격", "전보정당성3요건", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["대기발령인사명령감봉전보정당기각", "대기발령신분상불이익없음인사명령"], "exclude_for_queries": [], "summary_short": "대기발령=인사규정신분상불이익없음=인사명령정당+감봉전보정당=기각", "holding_summary": "대기발령은 인사규정에 신분상 불이익이 명시되지 않고 피해자 분리·업무 재배치 필요성을 고려한 인사명령으로 정당하며, 감봉 및 전보 처분도 정당하여 기각", "retrieval_note": "대기발령의 징계 해당 여부 판단 + 감봉·전보 동시 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48349: 갱신기대권인정+갱신거절합리적사유없음=부당
records.append({"id": "id_48349", "issue_type_primary": "contract_expiry", "issue_type_secondary": [], "employment_stage": "renewal_stage", "disposition_type": ["nonrenewal"], "fact_markers": ["갱신기대권인정", "갱신거절합리적사유없음", "부당"], "legal_focus": ["갱신기대권", "부당갱신거절"], "industry_context": "construction", "exclusion_flags": [], "include_for_queries": ["갱신기대권인정합리적사유없음부당갱신거절", "대다수계약갱신=갱신기대권인정부당"], "exclude_for_queries": [], "summary_short": "대다수근로자계약갱신+갱신기대권인정+거절합리적사유없음=부당", "holding_summary": "대다수 현장 근로자의 계약이 갱신되었고 근로자에게도 갱신 기대권이 인정되는데 이를 거절할 합리적 사유가 없어 부당한 갱신거절", "retrieval_note": "다수 계약 갱신 관행으로 갱신기대권 인정. 합리적 거절사유 없음으로 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48351: 3개월후재차의사반하는발령=생활상불이익누적=TV부당
records.append({"id": "id_48351", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["경영상필요성인정", "3개월만에재차의사반전보", "생활상불이익현저", "TV부당"], "legal_focus": ["전보정당성3요건", "생활상불이익", "반복전보"], "industry_context": "service", "exclusion_flags": [], "include_for_queries": ["3개월만에재차의사반전보생활상불이익현저TV부당", "반복전보생활상불이익누적TV부당"], "exclude_for_queries": [], "summary_short": "경영상필요성인정이나3개월만에재차의사반전보=생활상불이익현저=TV부당", "holding_summary": "생활재활교사 이용인 감소에 따른 경영상 필요성은 인정되나 3개월 만에 재차 근로자의 의사에 반하는 인사발령을 하여 생활상 불이익이 현저하여 TV 부당", "retrieval_note": "반복 전보로 인한 생활상 불이익 누적 가중 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48353: 조합원희망근무지불일치=지배개입주장입증부족=부당노동행위불인정
records.append({"id": "id_48353", "issue_type_primary": "union_activity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["조합원희망근무지불일치", "지배개입입증부족", "부당노동행위불인정"], "legal_focus": ["부당노동행위", "지배개입", "조합원차별"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["조합원희망근무지불일치지배개입주장입증부족불인정", "특정노조조합원인사불이익주장입증실패불인정"], "exclude_for_queries": [], "summary_short": "조합원희망근무지불일치=지배개입부당노동행위주장=입증부족=불인정", "holding_summary": "조합원의 희망근무지 불일치 비율이 다른 노조보다 높더라도 지배·개입의 부당노동행위가 있었다는 증명을 충분히 하지 못하여 불인정", "retrieval_note": "통계적 불균형만으로는 지배·개입 부당노동행위 인정 불가. 적극적 입증 필요", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48357: 전보제척기간도과각하+해고존재(녹취록)=부당해고
records.append({"id": "id_48357", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal", "transfer"], "fact_markers": ["전보제척기간도과각하", "해고통보녹취록인정", "해고존재", "부당해고"], "legal_focus": ["해고존재여부", "제척기간", "녹취증거", "해고의사표시"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["전보제척기간도과각하해고존재녹취인정부당해고", "녹취록해고통보인정해고존재부당"], "exclude_for_queries": [], "summary_short": "전보=제척기간도과=각하+해고=녹취록인정=해고존재=부당해고", "holding_summary": "전보에 대한 구제신청은 제척기간을 도과하여 각하되고, 해고는 사용자가 녹취록에서 해고 통보를 인정한 점으로 해고 존재가 확인되어 부당해고", "retrieval_note": "녹취록 증거로 해고 사실 인정 사례. 전보 각하와 해고 부당의 분리 판단", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48361: 대기발령=징계아닌인사명령+정당
records.append({"id": "id_48361", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["대기발령=인사명령", "이중징계아님", "피해자분리조치", "정당"], "legal_focus": ["대기발령성격", "인사명령", "이중징계"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["대기발령징계아닌인사명령이중징계주장기각정당", "피해자분리대기발령인사명령정당"], "exclude_for_queries": [], "summary_short": "대기발령=취업규칙징계아님+피해자분리업무재배치필요=인사명령정당", "holding_summary": "취업규칙에 대기발령을 징계로 규정하지 않고, 피해자 분리 및 업무 재배치 필요성을 고려한 인사권 범위 내 인사명령으로서 이중징계에 해당하지 않아 정당", "retrieval_note": "대기발령의 징계 여부: 취업규칙 미규정 + 분리조치 목적 → 인사명령으로 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48389: 기간제근로자+해고서면통지절차준수이나사유부당=부당해고
records.append({"id": "id_48389", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "fixed_term", "disposition_type": ["dismissal"], "fact_markers": ["기간제근로자", "수습아님", "서면통지절차준수", "해고사유부당"], "legal_focus": ["해고사유", "기간제근로자해고", "서면해고통지"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["기간제근로자해고사유부당", "서면통지했어도해고사유불충분부당"], "exclude_for_queries": [], "summary_short": "기간제근로자(수습아님)+서면통지절차준수이나해고사유부당=부당해고", "holding_summary": "수습 약정 없어 수습 근로자로 볼 수 없고, 서면 통지 절차는 준수하였으나 해고 사유가 정당하지 않아 부당해고", "retrieval_note": "절차(서면통지) 준수하더라도 해고 사유 불충분이면 부당해고. 수습 여부 별도 심사", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4841: 코로나화재경영악화=업무상필요성인정+생활상불이익감내범위=TV정당
records.append({"id": "id_4841", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["코로나경영사정악화", "공장화재", "업무상필요성인정", "생활상불이익감내범위", "TV정당"], "legal_focus": ["전보정당성3요건", "경영상이유업무상필요성", "생활상불이익"], "industry_context": "manufacturing", "exclusion_flags": [], "include_for_queries": ["코로나화재경영악화전보업무상필요성인정TV정당", "경영사정악화업무상필요성인정TV정당"], "exclude_for_queries": [], "summary_short": "코로나+공장화재경영사정악화=업무상필요성인정+생활상불이익감내범위=TV정당", "holding_summary": "코로나와 공장 화재에 따른 경영사정 악화로 업무상 필요성이 인정되고, 전보로 인한 불이익이 감내 수준 내에 있어 TV 정당", "retrieval_note": "경영사정 악화(코로나+재해)에 따른 전보의 업무상 필요성 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48453: 업무상필요성불인정+생활상불이익+협의없음=TV부당(재심유지)
records.append({"id": "id_48453", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무상필요성불인정", "생활상불이익", "협의없음", "TV부당", "재심유지"], "legal_focus": ["전보정당성3요건", "업무상필요성", "생활상불이익", "협의절차"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["TV3요건모두불충족TV부당재심유지", "순환관행형평성문제인사발령TV부당"], "exclude_for_queries": [], "summary_short": "업무상필요성불인정+생활상불이익+협의없음=TV부당=재심유지", "holding_summary": "인사발령 동기, 순환 관행, 원거리 발령 형평성 문제 등을 종합하면 업무상 필요성 불인정, 생활상 불이익 발생, 협의 미이행으로 TV 3요건 모두 불충족=TV 부당. 재심에서도 유지", "retrieval_note": "TV 3요건 모두 불충족으로 부당 인정. 재심 유지 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48485: 근로계약부서이동가능+직장내괴롭힘분리=TV정당
records.append({"id": "id_48485", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["근로계약부서이동가능명시", "직장내괴롭힘분리조치", "업무상필요성인정", "TV정당"], "legal_focus": ["전보정당성3요건", "근로계약해석", "직장내괴롭힘분리"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["근로계약부서이동가능직장내괴롭힘분리전보TV정당", "근로계약전직가능명시직장내괴롭힘전보정당"], "exclude_for_queries": [], "summary_short": "근로계약부서이동가능명시+직장내괴롭힘피해자분리=업무상필요성인정=TV정당", "holding_summary": "근로계약서에 부서이동 가능이 명시되어 있고 직장 내 괴롭힘 관련 피해자 분리를 위한 전보는 업무상 필요성이 인정되어 TV 정당", "retrieval_note": "근로계약 전직 가능 조항 + 직장내괴롭힘 분리 목적으로 TV 정당 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48493: 시용근로자+본채용거부합리적사유=정당
records.append({"id": "id_48493", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "probation", "disposition_type": ["rejection_of_regular_employment"], "fact_markers": ["시용근로자인정", "본채용거부합리적사유", "취업규칙시용기간명시", "정당"], "legal_focus": ["시용기간", "본채용거부", "합리적이유"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["시용근로자본채용거부합리적사유정당", "수습기간후본채용거부이유충분정당"], "exclude_for_queries": [], "summary_short": "시용근로자+본채용거부합리적사유있음=정당", "holding_summary": "근로계약서와 취업규칙에 시용기간이 명시되어 시용 근로자에 해당하며, 본채용 거부에 합리적 사유가 있어 정당", "retrieval_note": "시용근로자 요건 + 본채용거부 합리적 이유 충족으로 정당(batch_063 id_44821과 대조)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48503: 징계후외부영업분리=업무상필요성+취업규칙근거=TV정당
records.append({"id": "id_48503", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["징계후외부영업분리", "경영위기관리", "취업규칙직무변경가능", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "징계후후속전보"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["징계후외부영업분리전보업무상필요성인정TV정당", "비위행위후분리전보경영위기관리TV정당"], "exclude_for_queries": [], "summary_short": "비위행위후법적다툼중=경영위기관리분리필요+취업규칙근거=TV정당", "holding_summary": "외부 영업 비위행위 확인 후 법적 다툼이 지속되는 상황에서 경영상 위기관리를 위해 분리할 필요성이 있고 취업규칙에 직무 변경 가능이 규정되어 TV 정당", "retrieval_note": "징계 후속 전보이나 이중징계 아님. 경영위기관리·분리 목적의 TV 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48511: 5인미만사업장=구제신청불가=각하
records.append({"id": "id_48511", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["5인미만사업장", "배우자=근로자아님", "구제신청불가", "각하"], "legal_focus": ["상시근로자수", "5인미만사업장", "구제신청적용대상"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["5인미만사업장구제신청각하", "배우자근로자아님5인미만각하"], "exclude_for_queries": [], "summary_short": "배우자+임대개인사업자=근로자아님=5인미만=구제신청각하", "holding_summary": "사용자의 배우자와 사업장 일부 공간을 임대한 개인 차량정비업자들은 사용종속관계의 근로자가 아니어서 제외하면 상시근로자 5인 미만 사업장=구제신청 적용 대상 아님=각하", "retrieval_note": "상시근로자 수 산정에서 배우자·임차인 제외. 5인 미만 사업장 각하", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48559: 폐업신고전정당이유없는해고+절차미준수=부당+금전보상
records.append({"id": "id_48559", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["폐업신고전해고", "법인존속", "구제이익인정", "정당이유없음", "절차미준수", "금전보상"], "legal_focus": ["해고사유", "폐업과해고", "구제이익", "금전보상"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["폐업신고전정당이유없는해고절차미준수부당금전보상", "폐업전해고구제이익인정부당"], "exclude_for_queries": [], "summary_short": "폐업신고일까지법인존속=구제이익인정+폐업전정당이유없는해고+절차미준수=부당+금전보상", "holding_summary": "폐업신고일까지 법인이 존속하여 구제이익이 있으며, 사업 폐지 이전에 정당한 이유 없이 근로자를 해고하고 해고 절차도 미준수하여 부당해고. 금전보상명령 적용", "retrieval_note": "폐업 신고일 전 법인 존속 기간 동안의 해고 구제이익 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48567: 구두해고통보=서면통지미이행=부당+금전보상
records.append({"id": "id_48567", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["구두해고통보", "서면통지미이행", "근기법27조위반", "부당해고", "금전보상"], "legal_focus": ["서면해고통지", "근로기준법27조", "금전보상명령"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["구두해고통보서면통지미이행근기법27조위반부당해고", "서면통지없는해고부당금전보상"], "exclude_for_queries": [], "summary_short": "구두해고통보=근기법27조서면통지요건미충족=부당해고+금전보상", "holding_summary": "구두로 해고 통보한 것은 근로기준법 제27조의 서면 통지 요건을 갖추지 못하여 부당해고이며, 금전보상명령으로 금7,491,680원 산정", "retrieval_note": "구두 해고 = 서면 통지 위반 = 부당해고. 금전보상액 산정 구체적 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48621: 결원발생=전보필요성+근로계약포괄담당업무=TV정당
records.append({"id": "id_48621", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["결원발생전보필요성", "근로계약포괄담당업무", "근무장소비특정", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "근로계약해석"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["결원발생전보필요성근로계약포괄업무TV정당", "근무장소비특정포괄업무전보정당"], "exclude_for_queries": [], "summary_short": "결원발생전보필요성+근로계약근무장소비특정포괄담당=TV정당", "holding_summary": "결원 발생에 따른 전보의 필요성이 인정되고 근로계약서상 근무장소가 특정 지점에 한정되지 않고 담당 업무도 포괄적으로 기재되어 있어 TV 정당", "retrieval_note": "결원 보충 목적 전보 + 근로계약 포괄 담당 조항으로 TV 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48625: 업무축소불확인+채권이관지시불이행=업무상필요성없음=TV부당
records.append({"id": "id_48625", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무축소불확인", "채권이관지시불이행=전보시점연체아님", "업무상필요성없음", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "입증책임"], "industry_context": "finance", "exclusion_flags": [], "include_for_queries": ["업무축소주장불확인채권이관업무상필요성없음TV부당", "사용자주장업무상필요성입증실패TV부당"], "exclude_for_queries": [], "summary_short": "업무축소주장불확인+채권이관불이행사유도전보시점연체아님=업무상필요성없음=TV부당", "holding_summary": "구매·판매량 감소가 업무 축소로 직결되는지 불확인이고, 채권 이관 지시 불이행도 전보 시점에 연체가 아니어서 전보의 업무상 필요성이 없어 TV 부당", "retrieval_note": "사용자의 TV 업무상 필요성 주장이 구체적 입증에 실패한 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48629: 14년영업직→물류직=업무상필요성자료미제출+컴퓨터없음=TV부당
records.append({"id": "id_48629", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["14년영업직", "물류직전직", "업무상필요성자료미제출", "컴퓨터없음근무", "TV부당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "생활상불이익"], "industry_context": "manufacturing", "exclusion_flags": [], "include_for_queries": ["장기영업직물류직전직업무상필요성자료미제출TV부당", "영업직물류직전직관련자료없음TV부당"], "exclude_for_queries": [], "summary_short": "14년영업직→물류직=업무상필요성구체계획서미제출+컴퓨터없는근무=TV부당", "holding_summary": "14년간 영업 업무를 담당한 근로자를 물류직으로 전직하면서 구체적인 SUPPLY CHAIN 강화 계획서 등 업무상 필요성 자료를 제출하지 않았고, 전직 후 컴퓨터도 없이 업무하는 등 생활상 불이익도 있어 TV 부당", "retrieval_note": "장기 동일 직무 근로자의 타 직무 전직. 업무상 필요성 자료 미제출 + 생활상 불이익으로 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48631: 업무무관이메일반복경고후=직무명령불이행=징계정당
records.append({"id": "id_48631", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["reprimand"], "fact_markers": ["업무무관이메일반복", "구두서면경고후반복", "직무명령불이행", "견책정당"], "legal_focus": ["징계사유", "직무명령", "반복비위"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["업무무관이메일반복직무명령불이행견책정당", "서면경고후반복비위징계정당"], "exclude_for_queries": [], "summary_short": "업무무관이메일반복발송+경고후에도반복=직무명령불이행=견책정당", "holding_summary": "업무와 무관한 이메일을 불특정 다수에게 발송하고 구두·서면 경고 후에도 반복하여 직무명령을 불이행한 것은 징계사유에 해당하며, 3회 경고 이력을 고려하면 견책 양정도 적정하여 정당", "retrieval_note": "반복 직무명령 불이행의 경고 후에도 반복 = 징계사유 + 양정 적정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48687: 재가요양업무=근무장소변경수반직무+취업규칙근거=TV정당
records.append({"id": "id_48687", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["재가요양서비스", "근무장소변경수반직무특성", "취업규칙근로계약근거", "TV정당"], "legal_focus": ["전보정당성3요건", "업무특성", "근로계약해석"], "industry_context": "healthcare", "exclusion_flags": [], "include_for_queries": ["재가요양서비스근무장소변경수반전보TV정당", "업무특성상근무장소변경불가피전보정당"], "exclude_for_queries": [], "summary_short": "재가요양서비스업무=근무장소변경수반직무특성+취업규칙근거=TV정당", "holding_summary": "재가요양서비스 업무는 성격상 근무장소 변경이 수반되며 취업규칙과 근로계약서에 근무장소 변경 가능이 규정되어 있고 관행도 있어 TV 정당", "retrieval_note": "업무 특성(재가요양)으로 인한 근무장소 변경 불가피성 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4869: 수서지점만분리=법인전체기준긴박성없음=정리해고부당
records.append({"id": "id_4869", "issue_type_primary": "redundancy", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["법인전체기준긴박성판단", "수서지점단독기준불가", "긴박한경영상필요성없음", "정리해고부당"], "legal_focus": ["정리해고4요건", "긴박한경영상필요성", "법인전체경영사정"], "industry_context": "manufacturing", "exclusion_flags": [], "include_for_queries": ["일부지점기준아닌법인전체기준긴박성없음정리해고부당", "정리해고긴박성법인전체재무기준판단"], "exclude_for_queries": [], "summary_short": "정리해고=법인전체재무기준=긴박한경영상필요성없음=부당", "holding_summary": "긴박한 경영상 필요성은 법인 전체의 경영 사정을 기준으로 판단해야 하며, 수서지점만 분리하여 경영상 이유로 해고한 것은 전체 법인의 긴박한 경영상 필요성이 충족되었다고 보기 어려워 정리해고 부당", "retrieval_note": "정리해고 긴박성 판단 기준: 일부 사업부문이 아닌 법인 전체 재무 기준 적용(batch_064 id_4791 패턴)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4871: 근로계약갱신규정없음+자동연장아님명시=갱신기대권불인정
records.append({"id": "id_4871", "issue_type_primary": "contract_expiry", "issue_type_secondary": [], "employment_stage": "renewal_stage", "disposition_type": ["nonrenewal"], "fact_markers": ["갱신규정없음", "자동연장아님명시", "갱신기대권불인정"], "legal_focus": ["갱신기대권", "근로계약규정해석"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["근로계약갱신규정없음자동연장아님갱신기대권불인정", "갱신기대권불인정기간만료정당"], "exclude_for_queries": [], "summary_short": "근로계약갱신명시규정없음+자동연장아님명시=갱신기대권불인정=기각", "holding_summary": "근로계약서와 취업규칙에 갱신에 관한 명시적 규정이 없고 자동 연장이 되지 않는다고 명시하여 갱신기대권 불인정=정당한 기간 만료", "retrieval_note": "갱신 기대권 부인: 근로계약에 자동 연장 불가 명시 + 몇 차례 갱신만으로는 기대권 불충분", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48729: 전국공무원노조단체협약조항=비교섭사항포함=공무원노조법위반=무효
records.append({"id": "id_48729", "issue_type_primary": "union_activity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["no_formal_disposition"], "fact_markers": ["단체협약조항위반", "채용비교섭사항", "여성비율할당비교섭", "공무원노동조합법위반", "무효"], "legal_focus": ["단체협약", "공무원노동조합법", "비교섭사항"], "industry_context": "public", "exclusion_flags": [], "include_for_queries": ["공무원노조단체협약비교섭사항위반무효", "채용임용권사항단체협약비교섭사항무효"], "exclude_for_queries": [], "summary_short": "전국공무원노조단체협약=채용사항+여성비율할당=비교섭사항=공무원노조법위반=무효", "holding_summary": "단체협약 제37조 제4항(채용 관련 사항)과 제5항(여성 비율 할당)은 관계법령에 의한 임용권 행사에 관한 비교섭 사항이어서 공무원노동조합법에 위반되어 무효", "retrieval_note": "공무원 노조 단체협약의 비교섭 사항 범위: 채용·임용권 행사 관련 사항", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48761: 서비스통합신설+업무상필요성+생활상불이익통상범위+협의=TV정당
records.append({"id": "id_48761", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["서비스통합신설", "업무상필요성인정", "생활상불이익통상범위", "협의절차", "TV정당"], "legal_focus": ["전보정당성3요건"], "industry_context": "service", "exclusion_flags": [], "include_for_queries": ["서비스통합신설인력배치TV정당3요건충족", "TV3요건충족TV정당재심유지"], "exclude_for_queries": [], "summary_short": "서비스통합신설인력배치=업무상필요성인정+생활상불이익통상범위+협의=TV정당", "holding_summary": "서비스 통합·신설로 인한 인력 배치는 업무상 필요성이 있고 생활상 불이익도 통상 감수 범위 내에 있으며 협의도 거쳐 TV 3요건 충족=TV 정당. 재심에서도 유지", "retrieval_note": "TV 3요건 모두 충족으로 TV 정당. 재심 유지 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48765: 근기법19조항목=별도법령=구제신청대상아님
records.append({"id": "id_48765", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["no_formal_disposition"], "fact_markers": ["근기법19조", "별도법령적용항목", "구제신청대상아님", "각하"], "legal_focus": ["구제신청대상", "근로기준법19조", "청구대상"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["근기법19조별도법령항목구제신청대상아님각하", "근로조건위반이외청구항목노동위원회관할아님"], "exclude_for_queries": [], "summary_short": "근기법19조관련손해=해고예고수당등별도법령항목=구제신청대상아님=각하", "holding_summary": "근로자가 주장하는 손해액 항목들이 근로기준법 제19조 제1항(근로조건의 위반)이 아닌 별도의 법령에 의해 청구해야 할 사항이어서 노동위원회 구제신청 대상이 아님", "retrieval_note": "근기법19조 청구 대상의 범위 확인. 해고예고수당 등은 별도 청구(batch_063 id_47007, id_47229 동일 법리)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48775: 복직명령+임금상당액완전지급=구제이익소멸
records.append({"id": "id_48775", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["복직명령", "임금상당액완전지급", "식대미포함정당", "구제이익소멸"], "legal_focus": ["구제이익", "복직명령", "임금상당액", "식대임금해당여부"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["복직명령임금상당액완전지급구제이익소멸", "식대임금상당액미포함정당구제이익소멸"], "exclude_for_queries": [], "summary_short": "복직명령+임금상당액완전지급(식대제외정당)=구제이익소멸", "holding_summary": "사용자가 복직 명령을 내리고 해고기간 임금상당액을 지급하였으며, 식대는 실제 식사하는 직원에게만 지급되는 금품으로 임금상당액에 포함되지 않아 완전 이행=구제이익 소멸", "retrieval_note": "복직 + 임금상당액 완전이행 구제이익 소멸. 식대의 임금상당액 포함 여부 확인", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4879: 보직변경=그밖의징벌아님+정직정당
records.append({"id": "id_4879", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["suspension"], "fact_markers": ["보직변경=그밖의징벌아님", "구제신청대상아님", "정직정당"], "legal_focus": ["그밖의징벌여부", "구제신청대상", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["보직변경그밖의징벌아님구제신청대상아님정직정당", "보직변경징벌해당않음"], "exclude_for_queries": [], "summary_short": "보직변경=그밖의징벌해당않음=구제신청대상아님+정직=정당", "holding_summary": "보직 변경은 근로기준법 제23조 제1항의 '그 밖의 징벌'에 해당하지 않아 구제신청 대상이 아니며, 정직 처분은 정당하여 기각", "retrieval_note": "보직 변경의 '그밖의 징벌' 해당 여부 부인 사례(batch_063 id_47075와 대조)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48793: 재택근무+직무교육=구제신청대상아님
records.append({"id": "id_48793", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["no_formal_disposition"], "fact_markers": ["재택근무", "직무교육", "구제신청대상아님", "임금피크제대상관리"], "legal_focus": ["구제신청대상", "근로기준법23조", "재택근무지위"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["재택근무직무교육구제신청대상아님각하", "임금피크제재택근무근기법23조해당않음"], "exclude_for_queries": [], "summary_short": "재택근무+직무교육=근기법23조구제신청대상아님=각하", "holding_summary": "재택근무와 직무교육은 근로기준법 제23조 제1항의 해고·휴직·정직·전직·감봉 등 구제신청 대상에 해당하지 않아 각하", "retrieval_note": "재택근무와 직무교육이 구제신청 대상 사유에 해당하지 않는다는 판단", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48841: 사직종용→비진의사직서=해고존재+서면통지위반=부당
records.append({"id": "id_48841", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["사직종용", "비진의사직서", "해고존재", "서면통지위반", "부당해고"], "legal_focus": ["해고존재여부", "사직서비진의", "강요사직", "서면해고통지"], "industry_context": "unknown", "exclusion_flags": ["resignation_dispute"], "include_for_queries": ["사직종용비진의사직서해고존재서면통지위반부당", "강요사직서해고인정절차위반부당"], "exclude_for_queries": [], "summary_short": "사직종용→비진의사직서=해고존재+서면통지위반=부당", "holding_summary": "사용자의 사직 종용으로 사직 의사 없는 근로자가 제출한 사직서는 비진의 의사표시로 해고에 해당하며, 서면 통지 없는 부당해고", "retrieval_note": "사직 종용 + 비진의 사직서 = 해고 존재 패턴(batch_064 id_47539와 동일)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4885: 2020.8.1인사발령제척기간도과각하+2020.12.11인사발령정당
records.append({"id": "id_4885", "issue_type_primary": "procedure", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["제척기간도과각하", "후속인사발령정당", "복수인사발령분리심사"], "legal_focus": ["제척기간", "복수처분분리심사", "전보정당성"], "industry_context": "manufacturing", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["선행인사발령제척기간도과각하후속인사발령정당", "복수인사발령제척기간분리판단"], "exclude_for_queries": [], "summary_short": "2020.8.1인사발령=제척기간도과=각하+2020.12.11인사발령=TV정당=부분기각", "holding_summary": "2020. 8. 1. 인사발령에 대한 구제신청은 3개월 제척기간을 도과하여 각하하고, 2020. 12. 11. 인사발령은 업무상 필요성이 인정되어 정당", "retrieval_note": "복수 인사발령에서 제척기간 도과 각하 + 후속 인사발령 정당 분리 판단", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48851: 직장내괴롭힘조산=징계사유+양정적정+절차무하자=정당
records.append({"id": "id_48851", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["직장내괴롭힘", "피해자조산", "징계사유인정", "양정적정", "절차하자없음"], "legal_focus": ["징계사유", "직장내괴롭힘피해정도", "징계양정", "징계절차"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직장내괴롭힘조산피해징계사유인정양정적정정당", "중대피해직장내괴롭힘징계정당"], "exclude_for_queries": [], "summary_short": "직장내괴롭힘=피해자조산중대피해=징계사유+양정적정+절차정당", "holding_summary": "직장 내 괴롭힘으로 피해자가 조산을 할 정도의 심각한 정신적·육체적 피해를 입어 징계사유가 인정되며, 양정도 과도하지 않고 절차 하자도 없어 징계 정당", "retrieval_note": "직장내괴롭힘 중대 피해(조산) 결과까지 인정된 사안에서 징계 정당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48875: 감봉=양정과도=부당+전보=직장내괴롭힘분리=TV정당=부분인용
records.append({"id": "id_48875", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": ["transfer_validity"], "employment_stage": "regular", "disposition_type": ["pay_cut", "transfer"], "fact_markers": ["감봉양정과도부당", "전보=직장내괴롭힘분리TV정당", "부분인용"], "legal_focus": ["징계양정", "전보정당성3요건", "직장내괴롭힘분리", "복수처분분리심사"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["감봉양정과도부당전보직장내괴롭힘분리TV정당부분인용", "징계부당전보정당부분인용"], "exclude_for_queries": [], "summary_short": "감봉=일부징계사유인정이나양정과도=부당+전보=직장내괴롭힘분리TV정당=부분인용", "holding_summary": "감봉은 일부 징계사유가 인정되나 비위의 정도에 비해 중징계인 감봉은 양정이 과도하여 부당하고, 전보는 직장 내 괴롭힘 조사 결과에 따른 분리조치로 필요성이 있어 TV 정당하여 부분인용", "retrieval_note": "징계(감봉) 부당 + 분리조치 전보 정당 부분인용 패턴", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_4891: 업무이관+발령거부후콜센터대안=TV정당
records.append({"id": "id_4891", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["업무이관필요성", "발령거부후대안제시", "콜센터전보", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "전보거부후대안"], "industry_context": "public", "exclusion_flags": [], "include_for_queries": ["업무이관전보필요성인정콜센터대안TV정당", "전보거부후대안전보TV정당"], "exclude_for_queries": [], "summary_short": "업무이관전보필요성+근로자발령거부=콜센터대안전보=TV정당", "holding_summary": "국정감사 결과에 따른 업무 이관으로 전보 필요성이 있고, 근로자가 1차 발령을 거부하여 콜센터로 전보한 것도 업무상 필요성이 인정되어 TV 정당. 재심 유지", "retrieval_note": "전보 거부 후 대안 전보의 TV 정당 인정 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48925: 부당노동행위계속행위=단일성동일성연속성불인정=제척기간도과=각하+TV정당
records.append({"id": "id_48925", "issue_type_primary": "union_activity", "issue_type_secondary": ["transfer_validity", "procedure"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["부당노동행위계속행위불인정", "단일성동일성연속성불인정", "제척기간도과각하", "TV정당"], "legal_focus": ["부당노동행위계속행위", "제척기간", "전보정당성"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["부당노동행위계속행위단일성동일성연속성불인정제척기간도과각하", "부당노동행위계속행위요건미충족"], "exclude_for_queries": [], "summary_short": "전직처분=부당노동행위의사단일성·동일성·시간적연속성불인정=계속행위아님=제척기간도과=각하+TV정당", "holding_summary": "인사명령들이 부당노동행위 의사의 단일성, 행위의 동일성·동종성, 시간적 연속성이 인정되지 않아 계속되는 행위에 해당하지 않아 근로자3, 4의 구제신청은 제척기간 도과로 각하. 근로자1, 2의 전직은 TV 정당", "retrieval_note": "부당노동행위 계속 행위 요건: 의사 단일성+행위 동일성+시간적 연속성 모두 필요(batch_062 id_46741과 동일 법리)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_48997: 특정노조소속아니라는이유해고=해고존재+서면통지위반=부당+금전보상
records.append({"id": "id_48997", "issue_type_primary": "union_activity", "issue_type_secondary": ["no_dismissal"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["특정노조소속아님이유해고", "해고존재", "서면통지위반", "부당노동행위", "금전보상"], "legal_focus": ["부당노동행위", "조합원차별해고", "해고존재여부", "서면해고통지"], "industry_context": "construction", "exclusion_flags": [], "include_for_queries": ["특정노조소속아님이유해고부당노동행위서면통지위반부당", "노조차별해고부당노동행위금전보상"], "exclude_for_queries": [], "summary_short": "특정노조소속아니라는이유=일방적해고=해고존재+서면통지위반=부당노동행위=부당+금전보상", "holding_summary": "특정 노조 소속이 아니라는 이유로 일방적으로 근로관계를 종료한 것은 해고에 해당하고, 서면 통지를 하지 않아 부당노동행위 및 부당해고. 신뢰관계 파탄으로 금전보상명령 적용", "retrieval_note": "노조 소속 이유 차별 해고 = 부당노동행위 + 부당해고 복합 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49003: 직장내괴롭힘+성희롱+부당업무지시=징계사유+양정적정=정당
records.append({"id": "id_49003", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["동물호칭모욕", "성희롱", "부당업무지시", "담배연기피해자", "징계사유인정", "양정적정"], "legal_focus": ["징계사유", "직장내괴롭힘", "성희롱", "징계양정"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직장내괴롭힘성희롱복수비위징계정당", "모욕성희롱부당업무지시징계사유인정정당"], "exclude_for_queries": [], "summary_short": "동물호칭+성희롱+부당업무지시+담배연기=복수비위=징계사유+양정적정=정당", "holding_summary": "피해자를 동물에 빗댄 호칭, 신체 접촉 요구, 부당한 업무 지시, 저녁 식사 강제 참석, 담배 연기 피해 등 복수의 직장 내 괴롭힘·성희롱 행위가 인정되어 징계사유 충분하고 양정도 적정하여 정당", "retrieval_note": "복수 비위행위 인정으로 징계 정당. 성희롱+괴롭힘 복합 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49005: 성범죄징역2년=채용결격사유=징계해고정당
records.append({"id": "id_49005", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["징역2년집행유예", "채용결격사유", "서울시공무직조례", "징계해고정당"], "legal_focus": ["징계사유", "형사처벌확정", "채용결격사유", "공무직"], "industry_context": "public", "exclusion_flags": [], "include_for_queries": ["성범죄형사확정채용결격사유징계해고정당", "공무직징역2년집행유예결격사유정당"], "exclude_for_queries": [], "summary_short": "성범죄징역2년집행유예확정=서울시공무직조례채용결격사유=징계해고정당", "holding_summary": "공무직 근로자의 징역 2년(집행유예 3년) 형 확정은 서울시 공무직 채용 및 복무 등에 관한 조례의 채용 결격사유에 해당하여 징계해고 정당. 성범죄는 사생활 영역이라도 정당성 인정", "retrieval_note": "형사처벌 확정 = 채용 결격사유 = 징계해고 정당(batch_059 id_43975 패턴 유사)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49041: 5인미만사업장=구제신청적용대상아님=각하
records.append({"id": "id_49041", "issue_type_primary": "procedure", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["5인미만사업장", "구제신청적용대상아님", "각하"], "legal_focus": ["상시근로자수", "5인미만사업장"], "industry_context": "unknown", "exclusion_flags": ["procedure_dominant"], "include_for_queries": ["5인미만사업장부당해고구제신청각하", "상시근로자5인미만근기법28조비적용"], "exclude_for_queries": [], "summary_short": "상시근로자5인미만=근기법28조비적용사업장=구제신청각하", "holding_summary": "주장된 근로자들이 사용종속관계의 근로자가 아니어서 제외하면 상시근로자 5인 미만 사업장으로 부당해고 구제신청 적용 대상이 아님=각하", "retrieval_note": "5인 미만 사업장 구제신청 각하 패턴(batch_065 id_48511과 동일)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_491: 근로계약경리업무명시+3년경리만수행+동의없이전직=TV부당
records.append({"id": "id_491", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["근로계약경리업무명시", "3년경리만수행", "시말서거부이유전직", "동의없음", "TV부당"], "legal_focus": ["전보정당성3요건", "근로계약특정업무", "동의없는전직"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["근로계약경리업무명시3년경리만수행동의없이전직TV부당", "채용당시업무특정동의없는전직TV부당"], "exclude_for_queries": [], "summary_short": "근로계약경리업무명시+3년이상경리만수행+시말서거부이유전직=인사권범위아님=TV부당", "holding_summary": "근로계약서에 경리업무로 명시되어 있고 입사 후 3년 이상 경리업무만 수행하였는데, 시말서 작성 거부를 이유로 근로자 동의 없이 일방적으로 전직 명령한 것은 인사권 범위를 벗어나 TV 부당", "retrieval_note": "근로계약 특정 업무 + 장기 동일 업무 수행 후 동의 없는 전직 부당 패턴(batch_059 id_43083, batch_063 id_491 패턴 반복)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49167: 성희롱징계사유=증거불충분=불인정=징계취소
records.append({"id": "id_49167", "issue_type_primary": "disciplinary_severity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["disciplinary_dismissal"], "fact_markers": ["성희롱징계", "증거불충분", "사실불인정", "징계취소"], "legal_focus": ["징계사유입증", "성희롱사실인정", "고도의개연성증명"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["성희롱징계증거불충분사실불인정징계취소", "성희롱징계입증부족고도개연성미충족부당"], "exclude_for_queries": [], "summary_short": "성희롱징계=신체접촉인정이나주물렀다는행위=증거불충분=고도개연성미달=사실불인정=징계취소", "holding_summary": "피해자의 가슴을 주물렀다는 성희롱 행위는 고도의 개연성이 증명되었다고 보기에 부족하여 사실 불인정=징계사유 불충분=징계 취소", "retrieval_note": "성희롱 징계 사유의 고도의 개연성 증명 기준. 증거 불충분으로 징계 부당", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49193: 직장내괴롭힘신고후인사발령주장이나단체협약순환근무대상=TV정당
records.append({"id": "id_49193", "issue_type_primary": "transfer_validity", "issue_type_secondary": ["union_activity"], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["직장내괴롭힘신고후인사발령", "단체협약순환근무대상", "인사계획에따른발령", "TV정당"], "legal_focus": ["전보정당성3요건", "업무상필요성", "보복전보주장배척"], "industry_context": "healthcare", "exclusion_flags": [], "include_for_queries": ["직장내괴롭힘신고후인사발령보복주장배척순환근무TV정당", "신고후인사발령보복주장순환규정충족TV정당"], "exclude_for_queries": [], "summary_short": "직장내괴롭힘신고후인사발령=보복주장이나단체협약순환근무대상+인사계획=TV정당", "holding_summary": "직장 내 괴롭힘 신고 후 인사발령이 불이익 조치라고 주장하나, 단체협약에 따른 순환근무 대상자에 해당하고 인사계획에 따른 발령이며 신고 전부터 알고 있었던 점 등으로 보복 주장 배척=TV 정당", "retrieval_note": "신고 후 인사발령에서 순환근무 규정으로 보복 주장 배척 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49257: 부채비율증가+코로나폐업+공인회계사자문=긴박성인정이나(기타요건)=정리해고부당
records.append({"id": "id_49257", "issue_type_primary": "redundancy", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["부채비율증가", "코로나영향폐업", "공인회계사자문긴박성인정", "정리해고부당"], "legal_focus": ["정리해고4요건", "긴박한경영상필요성", "해고회피노력", "합리적기준", "협의"], "industry_context": "service", "exclusion_flags": [], "include_for_queries": ["긴박한경영상필요성인정이나해고회피노력등미충족정리해고부당", "공인회계사자문긴박성인정이나나머지요건부당"], "exclude_for_queries": [], "summary_short": "부채비율증가+코로나폐업+공인회계사자문=긴박성인정이나해고회피노력등미충족=정리해고부당", "holding_summary": "부채비율 매년 증가, 코로나로 사업장 폐업, 공인회계사 자문으로 긴박한 경영상 필요성은 인정되나, 해고 회피 노력, 합리적 기준, 근로자 측 협의 등 나머지 요건을 충족하지 못하여 정리해고 부당", "retrieval_note": "긴박성 인정 + 나머지 3요건 미충족 정리해고 부당(batch_062 id_46359, batch_063 id_47307 패턴)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49259: 부장그만두라발언+현장소장승인=해고존재(재심번복)+부당
records.append({"id": "id_49259", "issue_type_primary": "no_dismissal", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["부장그만두라발언", "현장소장묵시적승인", "해고존재인정", "재심번복"], "legal_focus": ["해고존재여부", "해고의사표시", "묵시적승인"], "industry_context": "construction", "exclusion_flags": [], "include_for_queries": ["인사권없는부장해고발언현장소장묵시적승인해고존재", "재심에서해고존재번복인정"], "exclude_for_queries": [], "summary_short": "인사권없는부장그만두라발언+현장소장아무런조치없음=묵시적승인=해고존재=재심번복+부당", "holding_summary": "인사권 없는 부장의 '그만두라'는 발언에 인사권자인 현장소장이 아무런 조치를 하지 않아 사실상 승인한 것으로 해고가 존재함을 재심에서 번복하여 인정. 부당해고", "retrieval_note": "해고 의사표시자의 인사권 유무+상급자 묵시적 승인 결합으로 해고 존재 인정", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49265: 직장내괴롭힘=분리조치직위해제+전보=업무상필요성=TV정당
records.append({"id": "id_49265", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer", "suspension"], "fact_markers": ["직장내괴롭힘신고", "분리조치직위해제", "전보", "업무상필요성인정", "TV정당"], "legal_focus": ["전보정당성3요건", "직위해제정당성", "직장내괴롭힘분리"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["직장내괴롭힘분리직위해제전보모두정당", "피해자분리직위해제전보업무상필요성인정"], "exclude_for_queries": [], "summary_short": "직장내괴롭힘신고=분리조치필요=직위해제+전보=업무상필요성+잠정조치=TV정당", "holding_summary": "직장 내 괴롭힘 신고에 따라 피해자 분리 조치가 객관적으로 필요하고, 잠정적 인사조치로 근로자의 불이익이 크지 않으며 조치 경과를 설명하여 직위해제 및 전보 모두 정당", "retrieval_note": "직장내괴롭힘 분리 조치의 직위해제+전보 동시 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_493: 간호직임상업무전보=직무순환인사원칙+생활상불이익통상범위=TV정당
records.append({"id": "id_493", "issue_type_primary": "transfer_validity", "issue_type_secondary": [], "employment_stage": "regular", "disposition_type": ["transfer"], "fact_markers": ["간호직임상전보", "직무순환인사원칙", "업무상필요성인정", "생활상불이익통상범위", "TV정당"], "legal_focus": ["전보정당성3요건", "직무순환인사원칙", "간호직전보"], "industry_context": "healthcare", "exclusion_flags": [], "include_for_queries": ["간호직임상전보직무순환인사원칙TV정당", "의료기관간호직직무순환전보정당"], "exclude_for_queries": [], "summary_short": "간호직행정→임상전보=직무순환인사원칙=업무상필요성+생활상불이익통상범위=TV정당", "holding_summary": "행정 업무를 담당하던 간호직 근로자를 직무순환 인사원칙에 따라 임상 간호 업무로 전보한 것은 업무상 필요성이 인정되고 생활상 불이익도 통상 감수 범위 내에 있어 TV 정당", "retrieval_note": "의료기관 간호직 직무순환 전보 TV 정당 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49317: 금전보상명령액재심위법없음+채용내정해제=부당해고
records.append({"id": "id_49317", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "pre_hire", "disposition_type": ["dismissal"], "fact_markers": ["채용내정해제", "근로관계성립인정", "금전보상명령액재심각하"], "legal_focus": ["채용내정해제", "근로관계성립", "금전보상명령액"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["채용내정해제부당해고", "채용내정근로관계성립인정해제부당"], "exclude_for_queries": [], "summary_short": "채용내정최종합격공고+이메일통보=근로관계성립+채용내정해제=부당해고", "holding_summary": "채용내정 최종 합격 공고 및 이메일 통보로 근로관계가 성립하였으며, 채용내정 해제는 해고에 해당하여 부당. 금전보상명령액에 대한 재심신청은 위법 없어 각하", "retrieval_note": "채용내정 근로관계 성립 요건 + 채용내정 해제 = 부당해고 패턴(pre_hire 단계)", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

# id_49337: 내부명령=공식문서아님=해고일=2022.4.18아님+해고존재+부당
records.append({"id": "id_49337", "issue_type_primary": "no_dismissal", "issue_type_secondary": ["procedure"], "employment_stage": "regular", "disposition_type": ["dismissal"], "fact_markers": ["인사발령내부명령", "공식문서아님", "해고일불인정", "제척기간주장배척", "해고존재부당"], "legal_focus": ["해고존재여부", "해고일기산점", "제척기간", "공식문서해고"], "industry_context": "unknown", "exclusion_flags": [], "include_for_queries": ["내부명령공식문서아님해고일불인정제척기간배척해고존재", "공식문서아닌내부명령해고일기산제척기간불성립"], "exclude_for_queries": [], "summary_short": "4.18인사발령=내부명령=공식문서아님=해고일불인정=제척기간도과주장배척+해고존재=부당", "holding_summary": "2022. 4. 18. 인사발령은 공식 문서가 아닌 내부 명령에 불과하여 해고일로 볼 수 없어 제척기간 도과 주장이 배척되고, 해고가 존재하여 부당해고", "retrieval_note": "내부 명령의 공식 해고 문서 해당 여부. 해고일 기산점 쟁점 사례", "confidence": "high", "review_status": "approved", "tag_version": "v3"})

output_path = r'C:\dev\labor-decisions-search\retagging\output\reviewed\transfer_batch_065_reviewed.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')

print(f"총 {len(records)}건 작성 완료")
