"""
write_batch045.py — transfer_batch_045 tagging
Distribution: TV20, procedure10, no_dismissal6, disciplinary_severity8, contract_expiry3, redundancy2, union_activity1
"""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = [
{
  "case_id": "id_404359",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["transfer_order_valid", "consultation_held", "living_disadvantage_within_normal_range", "business_necessity_recognized"],
  "legal_focus": ["transfer_3prong_test", "business_necessity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사발령3요건충족=정당전보", "업무상필요성+생활상불이익통상범위+협의거침=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "인사발령 3요건 충족=정당 전보",
  "holding_summary": "업무상 필요성 인정+생활상 불이익 통상 감수 범위+협의 절차도 거침=정당 인사발령",
  "retrieval_note": "TV 3요건 모두 충족 정당 패턴 — 기본 정당 사례",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404363",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["no_business_necessity", "insufficient_consultation"],
  "legal_focus": ["transfer_3prong_test", "business_necessity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전보부당_업무상필요성불인정", "업무상필요성없음+협의불충분=부당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성 없음+협의 불충분=부당 전보",
  "holding_summary": "인사발령 업무상 필요성 인정 불가+충분한 협의 없음=부당 전보",
  "retrieval_note": "TV 1+3 요건 불충족 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404367",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed"],
  "legal_focus": ["disciplinary_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계사유O+양정적정+절차O=정당"],
  "exclude_for_queries": [],
  "summary_short": "징계사유·양정·절차 모두 정당",
  "holding_summary": "징계사유 인정+양정 적정+절차 하자 없음=정당 징계",
  "retrieval_note": "징계 3요건 충족 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40437",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["relief_interest_extinguished", "transfer_order_cancelled"],
  "legal_focus": ["relief_interest"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["전직명령취소=구제이익소멸=각하"],
  "exclude_for_queries": [],
  "summary_short": "전직명령 취소=구제이익 소멸=각하",
  "holding_summary": "사용자가 전직명령 취소→구제신청 목적 달성=구제이익 없음=각하",
  "retrieval_note": "전보/전직 취소 후 구제이익 소멸 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404415",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+서면통지 없음=부당해고",
  "holding_summary": "해고 존재, 서면통지 의무 미이행=부당해고",
  "retrieval_note": "서면통지결여 부당해고 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404461",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["no_business_necessity", "living_disadvantage_significant", "no_consultation", "long_tenure_worker"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["25년영업직물류팀전보=업무상필요성없음+협의없음=부당", "장기근속자업종변경전보=3요건불충족=부당"],
  "exclude_for_queries": [],
  "summary_short": "25년 영업직→물류팀 전보=3요건 불충족=부당",
  "holding_summary": "25년 영업직 근로자를 물류팀으로 전보—업무상 필요성 없음+생활상 불이익+충분한 협의 없음=부당",
  "retrieval_note": "장기근속 업종전환 전보 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404465",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["disciplinary_dismissal"],
  "fact_markers": ["disciplinary_grounds_found", "excessive_sanction", "procedure_followed"],
  "legal_focus": ["proportionality_review"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계사유O+절차O이나해고양정과다=부당"],
  "exclude_for_queries": [],
  "summary_short": "징계사유·절차 정당이나 해고 양정 과다=부당",
  "holding_summary": "징계사유 인정+절차 하자 없으나 비위행위 정도에 비해 해고 양정 과다=부당",
  "retrieval_note": "양정 과다 부당 패턴 — 사유·절차는 인정",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404469",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "renewal_stage",
  "disposition_type": ["nonrenewal"],
  "fact_markers": ["renewal_expectation_recognized", "no_rational_reason_for_refusal", "fixed_term_worker"],
  "legal_focus": ["renewal_expectation_right"],
  "industry_context": "unknown",
  "exclusion_flags": ["renewal_expectation_dominant"],
  "include_for_queries": ["기간제갱신기대권인정+갱신거절합리적이유없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "기간제 갱신기대권+갱신거절 합리적 이유 없음=부당",
  "holding_summary": "기간제 근로자+갱신기대권 인정+갱신거절 합리적 이유 없음=부당해고",
  "retrieval_note": "갱신기대권 인정 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404471",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": ["disciplinary_severity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer", "dismissal"],
  "fact_markers": ["business_necessity_recognized", "vehicle_accident_history", "client_access_ban", "unauthorized_absence"],
  "legal_focus": ["transfer_3prong_test", "disciplinary_validity"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["다수차량사고뺑소니고객사출입금지=업무상필요성인정=정당전보", "전보항의무단결근27일=해고사유인정=정당해고"],
  "exclude_for_queries": [],
  "summary_short": "차량사고→출입금지=전보정당+무단결근27일=해고정당",
  "holding_summary": "다수 차량사고+뺑소니로 고객사 출입 금지=업무상 필요성 인정=전보 정당; 전보 항의 무단결근 27일=해고 사유 인정=정당",
  "retrieval_note": "전보 정당 + 이후 무단결근 해고 정당 병합 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404501",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["unauthorized_agent_fired", "employer_liability_recognized", "authority_exceeded"],
  "legal_focus": ["employer_responsibility", "authority_delegation"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["현장관리자위임권한초과해고=사용자책임인정=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "현장관리자 권한 초과 해고=사용자 책임=부당",
  "holding_summary": "현장소장이 위임 권한 범위 초과 해고→사용자 책임 인정=부당해고",
  "retrieval_note": "대리인 권한 초과 해고=사용자 귀책 인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404547",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["pay_cut"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "personnel_order_not_reviewable"],
  "legal_focus": ["disciplinary_validity", "relief_scope"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["역량개선기간연장상벌위원회회부=구제신청대상아님", "감봉정당+인사명령구제신청대상외"],
  "exclude_for_queries": [],
  "summary_short": "감봉 정당+역량개선기간 연장 등은 구제신청 대상 아님",
  "holding_summary": "감봉 6개월 징계 정당; 역량개선기간 연장·상벌위원회 회부 인사명령은 근기법 제23조 구제신청 대상 아님",
  "retrieval_note": "구제신청 대상 해당 여부 판단 — 인사명령 vs 징계",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404549",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["filing_period_expired"],
  "legal_focus": ["statute_of_limitations"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": [],
  "exclude_for_queries": [],
  "summary_short": "제척기간 3개월 도과=각하",
  "holding_summary": "구제신청 3개월 신청기간 도과=각하",
  "retrieval_note": "제척기간 도과 각하 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404559",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["no_dismissal_grounds", "procedure_violated"],
  "legal_focus": ["dismissal_grounds", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고사유부존재+절차미준수=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고사유 없음+절차 미준수=부당해고",
  "holding_summary": "해고 사유 부존재+해고 절차 미준수=부당해고",
  "retrieval_note": "사유+절차 이중 위반 부당해고",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404565",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["worker_status_confirmed", "dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement", "worker_status"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로자성인정+해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "근로자성+해고 존재+서면통지 없음=부당",
  "holding_summary": "근기법상 근로자 해당+해고 존재+서면통지 없음=부당해고",
  "retrieval_note": "근로자성+서면통지 복합 쟁점",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404591",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "probation",
  "disposition_type": ["probation_termination"],
  "fact_markers": ["probationary_rejection_invalid", "no_rational_grounds"],
  "legal_focus": ["probationary_employee_rights", "rejection_grounds"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["본채용거부객관적합리적이유없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "본채용 거부 객관적·합리적 이유 없음=부당",
  "holding_summary": "본채용 거부에 객관적으로 합리적 이유 존재하지 않음=부당한 해고",
  "retrieval_note": "시용근로자 본채용 거부=합리적 이유 필요 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404641",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["no_formal_disposition"],
  "fact_markers": ["no_dismissal_found", "new_employee_hired"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["새직원채용사실만으로해고인정불가=해고없음"],
  "exclude_for_queries": [],
  "summary_short": "새 직원 채용만으로 해고 인정 불가=해고 없음",
  "holding_summary": "새 직원 채용+일방적 근로관계 종료 의사표시 확인 안됨=해고 없음",
  "retrieval_note": "간접적 사실만으로 해고 인정 불가 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404643",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["suspension", "demotion", "transfer"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed", "business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["disciplinary_validity", "transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["정직정당+보직해임전보업무상필요성O+불이익통상범위=모두정당"],
  "exclude_for_queries": [],
  "summary_short": "정직 정당+보직해임·전보도 정당",
  "holding_summary": "정직 징계 정당+보직해임·전보 업무상 필요성 인정·생활상 불이익 통상 범위=모두 정당",
  "retrieval_note": "징계+보직해임+전보 병합 모두 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404651",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["suspension", "demotion", "transfer"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed", "business_necessity_recognized"],
  "legal_focus": ["disciplinary_validity", "transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["정직정당+보직해임전보정당"],
  "exclude_for_queries": [],
  "summary_short": "정직·보직해임·전보 모두 정당",
  "holding_summary": "정직 정당+보직해임·전보 업무상 필요성 인정·생활상 불이익 통상 범위=정당",
  "retrieval_note": "징계+보직해임+전보 병합 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404707",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["illegal_dispatch_direct_employment", "transfer_after_direct_hire_unfair"],
  "legal_focus": ["illegal_dispatch", "transfer_3prong_test", "direct_employment_conditions"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["불법파견대법원판결직고용시근무장소변경=부당전보", "불법파견직고용=기존근무조건유지의무"],
  "exclude_for_queries": [],
  "summary_short": "불법파견 직고용 후 근무장소 변경=부당",
  "holding_summary": "대법원 불법파견 판결에 따른 직접고용 시 근무장소 변경 인사발령=부당",
  "retrieval_note": "불법파견 직고용 후 전보=기존 근무조건 유지 요구 패턴. batch_042 id_402405 동일 패턴 재확인",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404729",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_significant", "no_consultation"],
  "legal_focus": ["transfer_3prong_test", "living_disadvantage"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전보업무상필요성인정이나생활상불이익크고협의없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성 인정이나 생활상 불이익+협의 없음=부당",
  "holding_summary": "전보 업무상 필요성 인정, 생활상 불이익 크고 협의 절차 미준수=부당",
  "retrieval_note": "TV 1요건O이나 2+3요건X 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404745",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["redundancy_requirements_unmet", "urgent_necessity_insufficient"],
  "legal_focus": ["managerial_dismissal_requirements"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영상해고요건미충족=부당"],
  "exclude_for_queries": [],
  "summary_short": "경영상 해고 요건 미충족=부당",
  "holding_summary": "경영상 해고 요건 갖추지 못함=부당해고",
  "retrieval_note": "경영상 해고 요건 미충족 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404747",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "renewal_stage",
  "disposition_type": ["nonrenewal"],
  "fact_markers": ["renewal_expectation_recognized", "open_recruitment_used_to_avoid_renewal"],
  "legal_focus": ["renewal_expectation_right", "discriminatory_nonrenewal"],
  "industry_context": "education",
  "exclusion_flags": ["renewal_expectation_dominant"],
  "include_for_queries": ["갱신기대권+공개채용방식전환으로갱신기회박탈=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "갱신기대권+공개채용 전환으로 갱신 기회 박탈=부당",
  "holding_summary": "갱신기대권 인정+공개채용 방식으로 전환하여 갱신 경쟁하게 한 것=갱신 기회 박탈=부당해고",
  "retrieval_note": "공개채용 방식 전환으로 갱신기대권 침해 패턴 — 교사 등 계약직 교원",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404749",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["union_activity"],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["legitimate_rights_exercise_punished", "retaliation_against_complaints", "labor_board_filing_retaliation"],
  "legal_focus": ["disciplinary_grounds_validity", "retaliation"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["권리구제신청을이유로정직처분=적법권리행사=징계사유불인정=부당", "노동위구제신청이유징계=부당노동행위유사"],
  "exclude_for_queries": [],
  "summary_short": "노동위 구제신청 권리행사를 이유로 정직=징계사유 불인정",
  "holding_summary": "적법한 권리행사(노동위 구제신청 등)를 이유로 정직 6개월=징계사유 불인정=부당",
  "retrieval_note": "적법 권리행사=징계사유 불인정 패턴 — 보복성 징계",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404755",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "pre_hire",
  "disposition_type": ["dismissal"],
  "fact_markers": ["job_offer_accepted", "invalid_cancellation_reason", "no_written_notice"],
  "legal_focus": ["employment_offer_cancellation", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["채용내정성립+취소사유절차부당=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "채용내정 성립+취소 사유·절차 부당=부당해고",
  "holding_summary": "채용내정 성립+취소 사유·절차 정당하지 않음=부당해고",
  "retrieval_note": "채용내정 취소 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40477",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range", "consultation_held", "workplace_not_specifically_designated"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근무지미특정+업무상필요성O+생활상불이익통상범위+협의O=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "근무지 미특정+TV 3요건 충족=정당 전보",
  "holding_summary": "근무장소 특정 안됨+업무상 필요성 인정+생활상 불이익 통상 범위+협의 거침=정당 전보",
  "retrieval_note": "근무지 특정 여부+TV 3요건 충족 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404781",
  "issue_type_primary": "redundancy",
  "issue_type_secondary": ["procedure"],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["redundancy_requirements_unmet", "no_written_notice"],
  "legal_focus": ["managerial_dismissal_requirements", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영상해고요건미충족+서면통지없음=부당해고", "금전보상명령신청수용"],
  "exclude_for_queries": [],
  "summary_short": "경영상 해고 요건 미충족+서면통지 없음=부당",
  "holding_summary": "경영상 해고 요건 미충족+서면통지 미준수=부당해고, 금전보상명령 수용",
  "retrieval_note": "경영상해고 요건+절차 이중 위반 + 금전보상명령 병합",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404807",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice", "partial_relief_interest_extinguished", "employer_identity_confirmed"],
  "legal_focus": ["written_notice_requirement", "relief_interest", "employer_identification"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["복귀요청받은근로자=구제이익없음+복귀요청못받은3명=서면통지없음=부당(부분인용)"],
  "exclude_for_queries": [],
  "summary_short": "복귀요청 받은 근로자=구제이익 없음, 미통보 3명=부당(부분인용)",
  "holding_summary": "사용자=사용자2, 복귀요청받은 근로자=구제이익 없음, 복귀요청 못받은 3명=서면통지 없음=부당해고(부분인용)",
  "retrieval_note": "동일 사안에서 복귀요청 수령 여부에 따른 구제이익 분기 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404829",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "pre_hire",
  "disposition_type": ["dismissal"],
  "fact_markers": ["job_offer_accepted", "no_written_notice"],
  "legal_focus": ["employment_offer_cancellation", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["채용내정+서면통지없이취소=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "채용내정 성립+서면통지 없이 취소=부당",
  "holding_summary": "채용내정 성립, 서면 통지 없이 취소=부당해고",
  "retrieval_note": "채용내정 취소+서면통지 없음 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404849",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range", "consultation_held", "consent_not_required"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전보동의불필요+업무상필요성O+생활상불이익통상범위+협의O=정당"],
  "exclude_for_queries": [],
  "summary_short": "전보 동의 불필요+TV 3요건 충족=정당",
  "holding_summary": "전보 시 근로자 동의 전제 불필요+업무상 필요성 인정+생활상 불이익 통상 범위+협의 거침=정당",
  "retrieval_note": "전보 동의 요부+TV 3요건 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404891",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성O+생활상불이익현저하지않음+절차하자없음=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성+불이익 미현저+절차 하자 없음=정당",
  "holding_summary": "업무상 필요성 인정+생활상 불이익 현저하게 크지 않음+절차 하자 없음=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40491",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성O+생활상불이익통상범위=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성+불이익 통상 범위=정당",
  "holding_summary": "업무상 필요성 인정+생활상 불이익 통상 감내 범위=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404913",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["no_formal_disposition"],
  "fact_markers": ["transfer_order_not_proven", "no_dismissal_found"],
  "legal_focus": ["dismissal_existence", "burden_of_proof"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전직사실확인불가=전직없음"],
  "exclude_for_queries": [],
  "summary_short": "전직명령 사실 확인 불가=전직 없음",
  "holding_summary": "전직명령 사실 확인 불가=근로자 주장 전직 없음",
  "retrieval_note": "전직 사실 입증 실패=해고/전직 없음 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404927",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근무지변경전보=업무상필요성O+불이익통상범위=정당"],
  "exclude_for_queries": [],
  "summary_short": "근무지 변경 전보=업무상 필요성+불이익 통상 범위=정당",
  "holding_summary": "근무지 변경 전보 업무상 필요성 충분+생활상 불이익 통상 범위=정당",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404931",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["disciplinary_dismissal"],
  "fact_markers": ["disciplinary_grounds_found", "proportionate_sanction", "procedure_followed"],
  "legal_focus": ["disciplinary_validity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["징계해고사유O+양정O+절차O=정당"],
  "exclude_for_queries": [],
  "summary_short": "징계해고 사유·양정·절차 모두 정당",
  "holding_summary": "징계사유 인정+양정 적정+절차 하자 없음=정당 징계해고",
  "retrieval_note": "징계해고 3요건 충족 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404935",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "team_abolished_transfer", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test", "business_necessity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["담당팀폐지후영업업무전보=업무상필요성인정=정당", "팀폐지변경=동일업무유지안됨=전보업무상필요성O"],
  "exclude_for_queries": [],
  "summary_short": "인테리어팀 폐지→영업 전보=업무상 필요성 인정=정당",
  "holding_summary": "인테리어팀 폐지·변경으로 동일 업무 실질 유지 안됨+근로자 영업 경험=업무상 필요성 인정=정당",
  "retrieval_note": "팀 폐지 후 업종 변경 전보 업무상 필요성 인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404949",
  "issue_type_primary": "contract_expiry",
  "issue_type_secondary": [],
  "employment_stage": "renewal_stage",
  "disposition_type": ["contract_termination"],
  "fact_markers": ["succession_expectation_recognized", "no_rational_reason", "employment_succession"],
  "legal_focus": ["employment_succession_expectation"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["고용승계기대권인정+합리적이유없는거부=부당"],
  "exclude_for_queries": [],
  "summary_short": "고용승계 기대권+합리적 이유 없는 거부=부당",
  "holding_summary": "고용승계 기대권 존재+합리적 이유 없는 거부=부당, 금전보상명령 수용",
  "retrieval_note": "고용승계기대권(갱신기대권 유사, 도급/하청 교체 시) 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404953",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성O+생활상불이익통상범위=정당인사권행사"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성+불이익 통상 범위=정당 인사권 행사",
  "holding_summary": "업무상 필요성 있음+생활상 불이익 통상 범위=정당한 인사권 행사",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404959",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["no_business_necessity", "living_disadvantage_exists", "no_consultation"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["배치전환업무상필요성없음+생활상불이익+협의없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "배치전환=업무상 필요성 없음+불이익+협의 없음=부당",
  "holding_summary": "배치전환 업무상 필요성 없음+생활상 불이익+신의칙상 협의 절차 미준수=부당",
  "retrieval_note": "TV 3요건 모두 불충족 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404981",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["filing_period_expired"],
  "legal_focus": ["statute_of_limitations"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": [],
  "exclude_for_queries": [],
  "summary_short": "3개월 신청기간 도과=각하",
  "holding_summary": "부당해고 등 있었던 날로부터 3개월 경과=신청기간 도과=각하",
  "retrieval_note": "제척기간 도과 각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_404985",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["pay_cut", "transfer"],
  "fact_markers": ["harassment_grounds_rejected", "no_business_necessity", "separation_transfer_invalid"],
  "legal_focus": ["disciplinary_grounds_validity", "transfer_3prong_test", "harassment_investigation"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["성희롱징계사유불인정=감봉부당+분리전보업무상필요성없음=부당", "성희롱사유불인정시분리전보도부당"],
  "exclude_for_queries": [],
  "summary_short": "성희롱 징계사유 불인정=감봉 부당+분리전보 업무상 필요성 없음=부당",
  "holding_summary": "성희롱 징계사유 인정 불가=감봉 부당+분리조치 업무상 필요성 불인정=전보 부당",
  "retrieval_note": "성희롱 사유 불인정=감봉+분리전보 모두 부당 병합 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405009",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice"],
  "legal_focus": ["written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재+서면통지 없음=부당",
  "holding_summary": "해고 존재+서면통지 의무 위반=부당해고",
  "retrieval_note": "서면통지결여 부당해고 정형 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405017",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "living_disadvantage_within_normal_range", "consultation_held"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전직업무상필요성O+불이익크지않음+협의O=정당"],
  "exclude_for_queries": [],
  "summary_short": "전직 업무상 필요성+불이익 크지 않음+협의=정당",
  "holding_summary": "업무상 필요성 인정+생활상 불이익 크지 않음+협의 거침=정당 전직",
  "retrieval_note": "TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405025",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_exists", "no_written_notice", "employer_identity_confirmed"],
  "legal_focus": ["written_notice_requirement", "employer_identification"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["사용자특정+배차관리자면직=해고+서면통지없음=부당"],
  "exclude_for_queries": [],
  "summary_short": "사용자=사용자1, 배차관리자 면직=해고+서면통지 없음=부당",
  "holding_summary": "사용자=사용자1, 배차관리자면직=해고 해당+서면통지 없음=부당해고(부분인용)",
  "retrieval_note": "사용자 특정+서면통지결여 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405027",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "consultation_not_required_by_rules", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test", "consultation_requirement_source"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["취업규칙협의절차별도규정없음=협의미이행만으로전보무효아님", "협의절차규정없는경우미이행=전보유효"],
  "exclude_for_queries": [],
  "summary_short": "취업규칙 협의 규정 없으면 미이행만으로 전보 무효 아님",
  "holding_summary": "업무상 필요성 있고 불이익 크지 않으며, 취업규칙에 협의 절차 별도 규정 없어 협의 미이행만으로 전보 무효 아님=정당",
  "retrieval_note": "협의절차 법적 근거 없을 때 미이행=전보 무효 아님 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405053",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["relief_interest_extinguished", "employment_ended"],
  "legal_focus": ["relief_interest"],
  "industry_context": "unknown",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": ["근로관계종료후부당인사발령취소=구제이익없음"],
  "exclude_for_queries": [],
  "summary_short": "근로관계 종료 후 구제신청=구제이익 없음",
  "holding_summary": "근로관계 종료 상태에서 부당인사발령 취소 구제신청=구제이익 없음=각하",
  "retrieval_note": "근로관계 소멸 후 전보 다툼 구제이익 없음 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405059",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer", "dismissal"],
  "fact_markers": ["relief_interest_extinguished", "employment_terminated_during_relief", "dismissal_extinguishes_transfer_relief"],
  "legal_focus": ["relief_interest", "employment_termination_effect"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["부당전직다투던중해고=근로관계종료=부당전직구제이익소멸"],
  "exclude_for_queries": [],
  "summary_short": "부당전직 다투던 중 해고=근로관계 종료=전직 구제이익 소멸",
  "holding_summary": "부당전직 다투던 중 해고=근로관계 종료와 동시에 부당전직 구제이익 소멸",
  "retrieval_note": "전직 구제신청 중 해고→전직 구제이익 소멸 특수 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405069",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["demotion", "transfer"],
  "fact_markers": ["no_business_necessity", "living_disadvantage_significant", "no_consultation"],
  "legal_focus": ["transfer_3prong_test"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성없음+생활상불이익현저+협의없음=부당인사발령"],
  "exclude_for_queries": [],
  "summary_short": "TV 3요건 모두 불충족=부당 인사발령",
  "holding_summary": "업무상 필요성 없음+생활상 불이익 현저+협의 절차 미준수=부당 인사발령",
  "retrieval_note": "강등+전보 병합 TV 3요건 모두 불충족 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405079",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["demotion"],
  "fact_markers": ["no_business_necessity", "mental_distress_as_living_disadvantage"],
  "legal_focus": ["transfer_3prong_test", "living_disadvantage"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성없음+정신적고통=생활상불이익인정=부당전직"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성 없음+정신적 고통=생활상 불이익=부당전직",
  "holding_summary": "업무상 필요성 없음+정신적 고통으로 발생한 생활상 불이익=부당 전직",
  "retrieval_note": "정신적 고통=생활상 불이익으로 인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405141",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["no_formal_disposition"],
  "fact_markers": ["relief_scope_limitation", "promise_unfulfilled"],
  "legal_focus": ["relief_scope"],
  "industry_context": "transport",
  "exclusion_flags": ["fact_specific_low_reusability"],
  "include_for_queries": [],
  "exclude_for_queries": [],
  "summary_short": "사용자 약속 불이행=구제신청 대상 아님",
  "holding_summary": "전기버스 승무(보직변경) 약속 불이행=구제신청 대상 아님=기각",
  "retrieval_note": "단순 약속 불이행은 노동위 구제신청 대상 밖 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_405145",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "organizational_restructuring", "living_disadvantage_within_normal_range"],
  "legal_focus": ["transfer_3prong_test", "business_necessity"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["조직개편업무상필요성O+불이익크지않음=정당전보"],
  "exclude_for_queries": [],
  "summary_short": "조직개편=업무상 필요성+불이익 크지 않음=정당",
  "holding_summary": "조직개편 등 업무상 필요성 인정+생활상 불이익 크지 않음=정당 전보",
  "retrieval_note": "조직개편 이유 전보 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
}
]

out_path = "retagging/output/reviewed/transfer_batch_045_reviewed.jsonl"
with open(out_path, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print(f"Written {len(records)} records")
