import json, sys
sys.stdout.reconfigure(encoding='utf-8')

records = []

records.append({"id":"id_57209","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["박물관관리자갈등","근로장소학교로특정않음","학교내전보"],"legal_focus":["업무상필요성","근로장소특정여부"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["TV정당","관리자갈등전보"],"exclude_for_queries":[],"summary_short":"박물관관리자갈등+근로장소학교한정아님=업무상필요성인정=TV정당","holding_summary":"박물관관리자지속갈등+근로계약근무장소박물관한정않음+전보후급여계속지급+학교내이동=생활상불이익없음=TV정당","retrieval_note":"관리자갈등근로장소비특정전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57227","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"fixed_term","disposition_type":["contract_termination"],"fact_markers":["기간제근로자","갱신기대권없음","기간만료","구제이익없음"],"legal_focus":["갱신기대권","구제이익"],"industry_context":"unknown","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["갱신기대권없음기간만료","기간제구제이익없음"],"exclude_for_queries":[],"summary_short":"기간제근로자+갱신기대권없음=기간만료=금전보상구제이익없음=각하","holding_summary":"근로계약서기간제근로자+갱신기대권미인정=기간만료종료=기간만료후구제신청=금전보상구제이익불인정=각하","retrieval_note":"기간제갱신기대권없음기간만료구제이익없음각하","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57233","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["해고철회문자","복직후출근","원하는부서인사발령아님","사직"],"legal_focus":["해고철회","복직","구제이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["해고철회복직","복직후부서배치거부"],"exclude_for_queries":[],"summary_short":"해고철회문자+복직출근+원하는부서아닌배치=사직=구제이익판단","holding_summary":"2023.5.11해고취소문자+다음날출근업무수행+업무배치면담에서원하는부서아닌배치=근로자반응=구제이익판단","retrieval_note":"해고철회복직후배치불만사직구제이익","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57261","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["산재요양복귀","야간작업특수건강진단질병요관찰자","혈압170이상","산업안전보건법132조"],"legal_focus":["업무상필요성","근무형태변경","근로자건강보호"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["건강이유근무형태변경","야간→주간전환TV"],"exclude_for_queries":[],"summary_short":"산재복귀+야간특수건강진단질병요관찰자+혈압170이상=산안법=근무형태변경정당","holding_summary":"산재요양복귀+매주1~2회병원조퇴+야간특수건강진단질병요관찰자+혈압170가까이상승+산업안전보건법132조=근무형태변경(야간→주간)=업무상필요성인정=정당","retrieval_note":"산재복귀건강이유야간주간전환근무형태변경정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57273","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["reprimand"],"fact_markers":["보직해제부존재","사무공간재배치","견책정당"],"legal_focus":["처분부존재","견책정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["보직해제부존재","처분없음각하"],"exclude_for_queries":[],"summary_short":"보직해제=사무공간재배치직위변동없음=부존재+견책=징계사유인정=정당","holding_summary":"2023.2.1병가재택+사무공간재배치직위직접변동없음=보직해제부존재+부하직원부적절발언=견책사유인정=정당","retrieval_note":"보직해제부존재사무공간재배치견책정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57281","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["통상해고=실질징계동일","징계절차미이행","절차하자"],"legal_focus":["해고정당성","징계절차","통상해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["통상해고징계절차미이행부당","해고절차위반"],"exclude_for_queries":[],"summary_short":"통상해고사유=징계사유와실질동일=징계절차미이행=해고부당","holding_summary":"취업규칙통상해고사유=징계사유와실질동일=징계절차거치지않음=절차하자=해고부당","retrieval_note":"통상해고징계절차동일징계절차미이행부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57289","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["건설현장","팀장에의한해고","사유입증불충분","서면통지없음"],"legal_focus":["해고정당성","서면통지"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["해고부당","서면통지없음해고부당"],"exclude_for_queries":[],"summary_short":"팀장해고유효+해고사유입증불충분+서면통지없음=절차하자=해고부당","holding_summary":"건설현장팀장해고유효인정+사용자해고사유정당성입증불충분+서면통지없음=절차하자=해고부당","retrieval_note":"팀장해고유효해고사유입증불충분서면통지없음부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57295","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["순환보직","미흡평가2년연속","직권전보대상","욕설폭언동료지적"],"legal_focus":["업무상필요성","성과관리"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["순환보직미흡평가전보TV정당","직권전보TV정당"],"exclude_for_queries":[],"summary_short":"순환보직+미흡평가2년+직권전보대상+동료욕설폭언=TV정당","holding_summary":"순환보직원칙+2년연속미흡평가직권전보대상+동료3인욕설비방지적+업무의견대립=조직질서성과관리인화위한TV=TV정당","retrieval_note":"미흡평가2년직권전보욕설폭언TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57307","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["서면통지없음","실질경영자이사해고","금전보상"],"legal_focus":["해고정당성","서면통지"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["서면통지없음부당해고","금전보상"],"exclude_for_queries":[],"summary_short":"이사가해고+서면통지없음=절차하자=부당해고+금전보상","holding_summary":"실질경영자이사2023.4.8해고+서면통지없음=당사자간다툼없음=절차하자=부당해고+금전보상11,085,490원","retrieval_note":"서면통지없음절차하자부당해고금전보상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57311","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["육아휴직전퇴직의사","후임자무기계약채용","복직후전직"],"legal_focus":["업무상필요성","육아휴직복직"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["육아휴직복직후전직","퇴직의사표명후복직전직"],"exclude_for_queries":[],"summary_short":"육아휴직전퇴직의사수차례+후임자무기계약채용=복직후전직=업무상필요성판단","holding_summary":"육아휴직전이메일구두퇴직의사수차례+조직도퇴사예정표기+후임자무기계약채용=육아휴직복직후전직=업무상필요성판단","retrieval_note":"육아휴직전퇴직의사후임자채용복직후전직","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57313","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["reprimand"],"fact_markers":["경고처분","직장내괴롭힘","근기법23조1항징벌","경고정당"],"legal_focus":["근기법23조1항","징벌해당","경고정당성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["경고징벌해당구제대상","직장내괴롭힘경고정당"],"exclude_for_queries":[],"summary_short":"경고=직장내괴롭힘제재=근기법23조1항징벌해당=구제대상+직장내괴롭힘인정=경고정당","holding_summary":"경고처분=직장내괴롭힘제재=징벌적성격인정=근기법23조1항그밖의징벌=구제신청대상+직장내괴롭힘사실인정=경고양정적정=정당","retrieval_note":"경고처분근기법23조1항징벌구제대상직장내괴롭힘정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57319","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["점장발언다닐수없다","면담거부","출근않음"],"legal_focus":["해고존재","확정적의사표시"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["해고존재여부","점장발언해고의사표시"],"exclude_for_queries":[],"summary_short":"점장다닐수없다발언+면담거부=해고존재여부판단","holding_summary":"점장다닐수없다발언+면담수차례거부+심적고통출근않음=확정적해고의사표시여부=해고존재판단","retrieval_note":"점장발언해고의사표시해고존재여부","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57323","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성인정","출퇴근거리다소증가","전직원고지+면담협의"],"legal_focus":["업무상필요성","생활상불이익","협의절차"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["TV정당","전직원고지협의TV정당"],"exclude_for_queries":[],"summary_short":"업무상필요성+출퇴근거리다소증가=감수범위+전직원고지면담협의=TV정당","holding_summary":"업무상필요성인정+출퇴근거리다소증가이나다른근로조건변화없음=감수범위+전보전전직원필요성고지+근로자면담협의=TV정당","retrieval_note":"전보전전직원고지면담협의TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57327","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion"],"fact_markers":["L5팀장→S팀원","승진promote표현사용","강등=근기법23조1항징벌"],"legal_focus":["근기법23조1항","징벌해당","구제신청적격"],"industry_context":"it","exclusion_flags":[],"include_for_queries":["팀장→팀원강등징벌구제대상","L5→S보직변경징벌"],"exclude_for_queries":[],"summary_short":"L5팀장→S팀원=사내공모로승진표현=강등=근기법23조1항징벌=구제대상","holding_summary":"사내공모S→L5=사용자승진표현사용=팀장직위선임과정명확+L5→S강등=보직변경아닌강등=근기법23조1항징벌해당=구제신청대상","retrieval_note":"L5팀장S팀원강등근기법23조1항징벌구제대상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57359","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["인마표현","칼로배찌르겠다발언","직장내괴롭힘","징계사유인정"],"legal_focus":["직장내괴롭힘","징계사유"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["칼발언직장내괴롭힘징계","폭언직장내괴롭힘"],"exclude_for_queries":[],"summary_short":"인마표현+흉기발언=직장내괴롭힘=징계사유인정","holding_summary":"인마표현=정신적고통=업무적정범위초과+흉기로배찌르겠다발언=모욕감=징계사유인정","retrieval_note":"폭언흉기발언직장내괴롭힘징계사유인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57375","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion","dismissal"],"fact_markers":["보직변경징계=업무상필요성없음","징계종류아님","징계해고=징계사유불인정+절차위반"],"legal_focus":["징계정당성","해고정당성","절차위반"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계부당","징계해고절차위반"],"exclude_for_queries":[],"summary_short":"보직변경징계=업무상필요성없음+종류해당아님=부당+징계해고=사유불인정+절차위반=부당","holding_summary":"보직변경징계=업무상필요성불인정+취업규칙징계종류미해당=부당+징계해고=사유불인정+절차위반=부당","retrieval_note":"보직변경징계부당징계해고사유불인정절차위반","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57395","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영업실적저조않음","갈등해소","긴급필요없음","사직권유인센티브영향"],"legal_focus":["업무상필요성"],"industry_context":"sales","exclusion_flags":[],"include_for_queries":["TV부당","업무상필요성없음사직권유영향"],"exclude_for_queries":[],"summary_short":"영업실적저조않음+갈등해소+긴급필요없음+사직권유영향=업무상필요성없음=TV부당","holding_summary":"영업실적저조아님+영업팀갈등해소+영업지원현장팀긴급인원불필요+인센티브사직권유전직영향=업무상필요성불인정=TV부당","retrieval_note":"사직권유인센티브영향전직업무상필요성없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57405","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["권고사직승낙없음","서면통지없음","원직복직","금전보상불인정"],"legal_focus":["해고존재","권고사직","금전보상"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["권고사직승낙없음해고","해고원직복직금전보상불인정"],"exclude_for_queries":[],"summary_short":"권고사직승낙없음+서면통지없음=해고+원직복직=금전보상불인정","holding_summary":"권고사직청약승낙없음+권고사직입증불분명+서면통지없음=해고+사용자원직복직의사있음=금전보상명령수용않음","retrieval_note":"권고사직승낙없음해고존재원직복직금전보상불인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57411","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["사직서제출","강요기망입증부족","전보구제이익없음","임금감소없음"],"legal_focus":["해고존재","사직","구제이익"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["사직서제출해고없음","전보구제이익없음임금감소없음"],"exclude_for_queries":[],"summary_short":"사직서제출강요기망입증부족=해고없음+임금감소없음=전보구제이익없음","holding_summary":"사직의사표시강요기망객관적입증부족+사직서수리=근로계약종료=해고없음+전보로임금감소없음=전보구제이익없음","retrieval_note":"사직서강요입증부족해고없음전보구제이익없음","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57421","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["pay_cut"],"fact_markers":["성희롱","감봉1월","피해자목격자진술구체적","외부노무법인조사"],"legal_focus":["징계사유","징계양정"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["성희롱감봉정당","직장내성희롱징계"],"exclude_for_queries":[],"summary_short":"성희롱=피해자목격자진술구체적+외부조사=감봉1월=양정적정=징계정당","holding_summary":"피해자목격자진술구체적+외부노무법인객관적조사+일부신체접촉인정=징계사유인정+학생다수목격=감봉취업규칙합치=양정적정=징계정당","retrieval_note":"성희롱외부조사감봉양정적정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57431","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["못가겠네발언=사직아님","근로관계계속설명없음","연차수당지급"],"legal_focus":["해고존재","사직의사표시"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["해고존재","사직의사표시아님해고존재"],"exclude_for_queries":[],"summary_short":"못가겠네발언=사직의사표시아님+계속근로설명없음=해고존재","holding_summary":"회사이전구내식당없어서근로자직무소멸의견=확정적사직의사아님+근로관계계속취지설명없음=연차수당지급정황=해고존재","retrieval_note":"발언사직아님계속근로설명없음해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57445","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약전보가능","CPT교관자격불합격","인사평가낮음","경고장3회"],"legal_focus":["업무상필요성","자격심사"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["교관자격불합격전보TV정당","저성과경고3회전보"],"exclude_for_queries":[],"summary_short":"근로계약전보가능+CPT교관자격불합격+낮은평가+경고3회=TV업무상필요성인정=TV정당","holding_summary":"근로계약취업규칙전보가능+CPT교관심사불합격시범강의불합격+6년간낮은평가=지침상학술교관면직사항+경고3회=업무상필요성인정=TV정당","retrieval_note":"교관자격불합격경고3회전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57461","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["저유소김대장해고","서면통지없음","해고부당"],"legal_focus":["해고존재","서면통지"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["해고존재서면통지없음부당","중간관리자해고"],"exclude_for_queries":[],"summary_short":"저유소김대장인사권행사=해고존재+서면통지없음=부당해고","holding_summary":"저유소김대장의사에따른해고=유효해고+서면통지없음=근기법절차하자=부당해고","retrieval_note":"저유소중간관리자해고존재서면통지없음부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57473","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["pay_cut","demotion"],"fact_markers":["직장내괴롭힘신고자진술","사과문","감봉","보직해임정당"],"legal_focus":["징계사유","징계양정","절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["직장내괴롭힘감봉보직해임정당","감봉경징계양정적정"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘=감봉경징계+보직해임=양정적정=절차준수=징계정당","holding_summary":"신고자일관진술+근로자사과문=징계사유인정+감봉경징계재량남용아님+징계위원회소명기회절차준수=징계정당","retrieval_note":"직장내괴롭힘감봉보직해임양정적정절차준수","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57479","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["기관장급인사재량폭넓게","게시글분란","조직안정화"],"legal_focus":["업무상필요성","인사재량권"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["기관장급인사재량TV정당","게시글분란조직안정화전보"],"exclude_for_queries":[],"summary_short":"기관장급인사재량폭넓게+게시글분란=조직안정화업무상필요성=TV정당","holding_summary":"기관장급책임보직자인사재량폭넓게인정+공개게시판게시글노조반발분란=조직안정화업무상필요성인정+생활상불이익없음=TV정당","retrieval_note":"기관장급인사재량게시글분란TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57481","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion","transfer"],"fact_markers":["우수등급이나이사회재임용부결","업무상필요성없음","생활상불이익현저"],"legal_focus":["업무상필요성","생활상불이익"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV부당","이사회재임용부결보직해임TV부당"],"exclude_for_queries":[],"summary_short":"이사회재임용부결만으로보직해임=업무상필요성없음+생활상불이익현저=부당","holding_summary":"인사규정우수등급+이사회전무재임용안건부결이유만으로보직해임=업무상필요성객관적불인정+생활상불이익현저=부당","retrieval_note":"이사회재임용부결보직해임업무상필요성없음부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57485","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["배우자고소이유해고","근무태도불량주장","서면통지없음"],"legal_focus":["해고존재","서면통지"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["서면통지없음부당해고","배우자고소이유해고"],"exclude_for_queries":[],"summary_short":"배우자고소이유해고+서면통지없음=부당해고","holding_summary":"사용자배우자고소이유해고진술+근무태도불량퇴사조치=해고=서면통지없음=근기법27조위반=부당해고","retrieval_note":"배우자고소이유해고서면통지없음부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57489","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["의료법위반민원","감사목적대기발령","인사명령(징계아님)","유사선례"],"legal_focus":["대기발령","인사명령성격"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["대기발령인사명령징계아님","감사목적대기발령"],"exclude_for_queries":[],"summary_short":"의료법위반민원=감사위한대기발령=인사명령(징계아님)=과거유사선례=정당성판단","holding_summary":"의료법위반행위민원제보+면담후감사대기발령=2년전유사대기발령선례=인사명령(징계아님)=정당성판단","retrieval_note":"감사목적대기발령인사명령징계아님","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5749","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["수행기사→지게차운전원","전보선례없음","사직권고거부후전보","협의없음"],"legal_focus":["업무상필요성","보복성인사"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV부당","사직권고거부후전보보복"],"exclude_for_queries":[],"summary_short":"수행기사→지게차운전원=전보선례없음+사직권고거부후전보=보복성=협의없음=TV부당","holding_summary":"수행기사지게차운전원전보선례없음+수행기사채용경력+사직권고거부후전보=보복성의심+협의없음=TV부당","retrieval_note":"사직권고거부보복성전보선례없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_575","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["조리파트근로계약특정","조리실장채용","설거지업무전담=근로계약내용변경"],"legal_focus":["근로계약내용특정","업무상필요성"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["근로계약직무특정변경TV부당","조리실장설거지전담TV부당"],"exclude_for_queries":[],"summary_short":"조리파트근로계약특정+조리실장채용=설거지전담전보=근로계약내용변경=TV부당","holding_summary":"근로계약조리파트명시+조리실장명함채용=설거지업무전담배치=근로계약내용과현저차이=동의없는근로조건변경=TV부당","retrieval_note":"근로계약직무특정조리실장설거지전담TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57519","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["인사규정전보가능","직원분리필요","업무효율성"],"legal_focus":["업무상필요성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV정당","직원분리전보"],"exclude_for_queries":[],"summary_short":"인사규정전보가능+직원분리필요+업무효율성=TV업무상필요성인정=TV정당","holding_summary":"인사규정근무장소업무변경가능+직원분리업무효율최적화필요=업무상필요성인정=TV정당","retrieval_note":"인사규정전보가능직원분리업무효율TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57521","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["동일임원","동일주소동일업종","대표이사모자관계","영업장소집기이어받음"],"legal_focus":["사용자적격","실질동일법인"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["실질동일법인사용자적격","형식별개법인실질동일"],"exclude_for_queries":[],"summary_short":"동일임원+동일주소업종+모자관계대표+영업장이어받음=실질동일법인=사용자적격","holding_summary":"이도맨숀동일임원사용자감사동일+동일주소동일업종동일상호+대표이사모자관계동거+영업장집기무상이어받음=실질동일법인=사용자적격인정","retrieval_note":"형식별개법인실질동일사용자적격","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57529","issue_type_primary":"union_activity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["단협부위원장전보시노조합의","구두합의주장이나부인","합의입증없음"],"legal_focus":["단체협약","노조합의의무"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["단협노조합의위반전보부당","부위원장전보노조합의"],"exclude_for_queries":[],"summary_short":"단협부위원장전보시노조합의규정+구두합의주장이나입증없음=TV부당","holding_summary":"단체협약부위원장인사이동시노조합의규정+구두합의주장=근로자부인+이의제기+2차면담합의불성립=합의입증없음=TV부당","retrieval_note":"단협노조합의의무부위원장전보합의없음TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57535","issue_type_primary":"union_activity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["다른근로자인사발령","노조위원장선거자율성침해","지배개입부당노동행위"],"legal_focus":["부당노동행위","지배개입","신청인적격"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["지배개입부당노동행위","노조위원장선거침해"],"exclude_for_queries":[],"summary_short":"다른근로자인사발령=노조위원장선거자율성침해=지배개입부당노동행위신청","holding_summary":"다른근로자인사발령=노조위원장선거자율성침해=지배개입부당노동행위해당가능=신청인적격인정=지배개입부당노동행위여부판단","retrieval_note":"노조위원장선거자율성인사발령지배개입부당노동행위","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57545","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["전화해고통지","서면통지없음","부당해고","금전보상"],"legal_focus":["해고존재","서면통지"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전화해고통지서면통지없음","부당해고금전보상"],"exclude_for_queries":[],"summary_short":"전화해고통지+서면통지없음=중대절차하자=부당해고+금전보상","holding_summary":"2023.5.7전화나오지말것통지=근로자의사무관하게일방종료=해고존재+서면통지없음=중대절차하자=부당해고","retrieval_note":"전화해고통지서면통지없음부당해고","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57551","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상명령구제이익","문자해고","해고존재"],"legal_focus":["구제이익","해고존재"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["금전보상구제이익","문자해고존재"],"exclude_for_queries":[],"summary_short":"금전보상신청=구제이익존재+문자해고=해고존재","holding_summary":"원직복직원하지않아금전보상명령신청=구제이익존재+문자내용+면담내용=해고존재","retrieval_note":"금전보상구제이익문자해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57569","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["채용공고갱신명시","갱신관행","상시지속업무","만료일인사발령"],"legal_focus":["갱신기대권"],"industry_context":"unknown","exclusion_flags":["renewal_expectation_dominant"],"include_for_queries":["갱신기대권인정","채용공고갱신명시관행인정"],"exclude_for_queries":[],"summary_short":"채용공고갱신명시+갱신관행+상시업무+만료일인사발령=갱신기대권인정","holding_summary":"근로계약서채용공고갱신명시+기간제갱신관행확인+상시지속업무+만료일신지점인사발령=갱신기대권인정","retrieval_note":"채용공고갱신명시관행상시업무갱신기대권인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57571","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["실장문자해고통지","즉시고용보험상실","사직의사없음","해고존재"],"legal_focus":["해고존재","해고의사표시"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["문자해고통지즉시보험상실","해고존재사직아님"],"exclude_for_queries":[],"summary_short":"실장문자해고통지+즉시고용보험상실+사직의사없음=해고존재","holding_summary":"대표지시실장문자=시정요구없음+출근독촉아닌즉시고용보험상실신고+사직의사근거없음=해고의사표시=해고존재","retrieval_note":"문자해고통지즉시보험상실사직아님해고존재","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57575","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["징계사유객관적입증없음","출퇴근기록없음","이전조치없음"],"legal_focus":["징계사유","객관적입증"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계부당","징계사유입증없음"],"exclude_for_queries":[],"summary_short":"징계사유=재직직원진술뿐+출퇴근기록없음+이전조치없음=객관적입증없음=징계부당","holding_summary":"재직직원진술외객관적명확입증없음+출퇴근기록민원관리없음+시말서이전조치없음=징계사유정당성불충분=징계부당","retrieval_note":"징계사유객관적입증없음출퇴근기록없음부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_5759","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["경영상업무조정","근무시간축소","시간외수당감소","인사권범위정당"],"legal_focus":["업무상필요성","인사재량권","근기법19조"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV정당","시간외수당감소인사명령정당"],"exclude_for_queries":[],"summary_short":"경영상업무조정인사발령=근무시간축소시간외수당감소=인사권범위내=TV정당","holding_summary":"경영상업무조정인사발령=근무부서근무형태변경=시간외수당감소=인사권범위내정당인사명령=경제적불이익구제근기법19조해당않음=각하","retrieval_note":"경영상업무조정시간외수당감소인사명령정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57597","issue_type_primary":"union_activity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["corrective_order_related"],"fact_markers":["공무원노조법시행령","단체협약무효","예산편성집행사항","임용권사항"],"legal_focus":["공무원노조법","단체협약효력","협약무효"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["공무원노조단체협약무효","임용권예산편성단체협약효력"],"exclude_for_queries":[],"summary_short":"단체협약=공무원노조법시행령4조예산편성임용권사항=단체협약효력없음","holding_summary":"단체협약19~21조=공무원노조법시행령4조4호예산편성집행사항+32조34~39조41~42조=2호임용권사항=법령에따른효력없음=단체협약무효","retrieval_note":"공무원노조법단체협약효력예산편성임용권사항무효","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57625","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["이사발령=급여인상아닌인사발령","노사협의회과장이상호봉외급여인상없음","임의급여인상"],"legal_focus":["징계사유","인사발령성격"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["이사발령급여인상아님징계","임의급여인상징계사유"],"exclude_for_queries":[],"summary_short":"이사발령=급여인상없는인사발령+노사협의회호봉외급여인상금지=임의급여인상=징계사유","holding_summary":"노사협의회과장이상호봉외급여인상금지+대표이사이사발령승진아닌인사발령인식=임의급여인상=징계사유","retrieval_note":"이사발령급여인상아님임의급여인상징계사유","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57627","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영업비밀유출","컴퓨터배제이미완료","울산본사인력필요불명"],"legal_focus":["업무상필요성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV부당","영업비밀유출컴퓨터배제이미완료TV부당"],"exclude_for_queries":[],"summary_short":"영업비밀유출로컴퓨터배제이미완료+울산본사인력필요불명=업무상필요성불충분=TV부당","holding_summary":"서울지점컴퓨터배제창고재고관리이미배치+울산본사업무지원필요주장입증없음=울산전보객관적사유기업효율성불명=TV부당","retrieval_note":"컴퓨터배제이미완료울산전보업무상필요성불명TV부당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57657","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["직장내괴롭힘","모욕언행","업무떠넘기기","따돌림","CCTV근무스케줄"],"legal_focus":["직장내괴롭힘","징계사유","징계양정"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["직장내괴롭힘징계정당","모욕따돌림업무떠넘기기"],"exclude_for_queries":[],"summary_short":"직장내괴롭힘4가지유형=CCTV객관자료=징계사유인정=징계정당","holding_summary":"모욕언행+업무떠넘기기+차별처우업무누락+따돌림=CCTV근무스케줄교차진술=직장내괴롭힘해당=징계사유인정=징계정당","retrieval_note":"직장내괴롭힘4유형CCTV객관자료징계사유인정","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57671","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["징계절차전혀없음","2일만에해고","서둘러해고","금전보상"],"legal_focus":["해고정당성","징계절차"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계절차없음2일해고부당","절차중대하자금전보상"],"exclude_for_queries":[],"summary_short":"징계절차전혀없이2일만에해고=중대절차하자=부당해고+금전보상","holding_summary":"관련법령징계절차전혀없이사건2일만에해고서두름=절차중대하자=부당해고+근로관계신뢰없음=금전보상9,817,410원","retrieval_note":"징계절차없이2일만해고절차중대하자부당금전보상","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57699","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["구제이익존재","근로계약근무장소약정없음","TV정당"],"legal_focus":["구제이익","업무상필요성","근로계약"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약근무장소약정없음TV정당","구제이익전보"],"exclude_for_queries":[],"summary_short":"구제이익존재+근로계약근무장소약정없음=TV정당","holding_summary":"부당인사발령시임금청구구제이익존재+근로계약근무장소에서만근로약정없음+한정직무아님=TV정당","retrieval_note":"근로계약근무장소약정없음TV정당구제이익","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57719","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer","suspension"],"fact_markers":["전보제척기간3개월도과","대기발령"],"legal_focus":["제척기간","구제신청대상"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전보제척기간도과각하","3개월제척기간"],"exclude_for_queries":[],"summary_short":"전보제척기간3개월도과=구제대상아님+대기발령별도판단","holding_summary":"2023.2.27전보명령+2023.6.2구제신청=3개월제척기간도과=각하+대기발령별도구제신청대상여부판단","retrieval_note":"전보구제신청3개월제척기간도과각하","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57723","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영업이익적자","조직개편","생산관리경력자","숙식제공주말교통비"],"legal_focus":["업무상필요성","생활상불이익"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["TV정당","영업적자조직개편전보"],"exclude_for_queries":[],"summary_short":"영업이익적자+조직개편+생산관리경력자전보=업무상필요성+숙식교통비=생활상불이익없음=TV정당","holding_summary":"영업이익적자+구미사업소생산관리강화+생산관리경력자=업무상필요성+임금직급불변+숙식교통비제공=생활상불이익크지않음=TV정당","retrieval_note":"영업적자조직개편생산관리경력자전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57739","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["그룹감사후속조치","사이버보안프로젝트리더","급여직급불변"],"legal_focus":["업무상필요성","인사재량권"],"industry_context":"it","exclusion_flags":[],"include_for_queries":["TV정당","그룹감사후속조치전보"],"exclude_for_queries":[],"summary_short":"그룹감사후속조치+사이버보안프로젝트리더임명=업무상필요성=TV정당","holding_summary":"모그룹감사후속조치조직개편=업무상필요성+사이버보안프로젝트리더임명=인사재량권범위+급여직급불변=생활상불이익없음=TV정당","retrieval_note":"그룹감사후속조치사이버보안전보TV정당","confidence":"high","review_status":"approved","tag_version":"v3"})

records.append({"id":"id_57747","issue_type_primary":"procedure","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["복직명령수차례","진정성확인노력없이불응","구제이익소멸"],"legal_focus":["구제이익소멸","복직명령진정성"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["구제이익소멸","복직명령수차례불응구제이익소멸"],"exclude_for_queries":[],"summary_short":"복직명령수차례+진정성확인노력없이불응=구제이익소멸","holding_summary":"2023.6.15~7.13수차례원직복직통보+근로자진정성결여주장만+확인노력없이불응=형식조치추정불가=구제이익소멸","retrieval_note":"복직명령수차례불응진정성확인없음구제이익소멸","confidence":"high","review_status":"approved","tag_version":"v3"})

output_path = r'C:\dev\labor-decisions-search\retagging\output\reviewed\transfer_batch_075_reviewed.jsonl'
with open(output_path, 'w', encoding='utf-8') as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + '\n')
print(f'총 {len(records)}건 작성 완료')
