import json, pathlib, sys
sys.stdout.reconfigure(encoding='utf-8')

OUT = pathlib.Path("retagging/output/reviewed/transfer_batch_048_reviewed.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)

records = [
# ── transfer_validity (TV 정당) ──────────────────────────────────────────
{
  "case_id": "id_406771",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["performance_evaluation_poor", "business_necessity_recognized", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["평가최하위+시말서=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "인사평가 최하위+시말서 작성=전보 정당",
  "holding_summary": "취업규칙·근로계약서에 전보 근거규정 있고, 근로자가 인사평가 최하위 등급+시말서 작성 등 업무역량 문제=업무상 필요성 인정+생활상 불이익 크지 않음=전보 정당",
  "retrieval_note": "인사평가 최하위 등급을 전보 사유로 한 TV 3-prong 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406775",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": ["redundancy"],
  "employment_stage": "regular",
  "disposition_type": ["dismissal", "transfer"],
  "fact_markers": ["employer_threshold_5_workers", "business_necessity_recognized"],
  "legal_focus": ["transfer_validity_3prong", "employer_definition"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["관계사합산상시5인이상=근로기준법적용+전보정당"],
  "exclude_for_queries": [],
  "summary_short": "관계사 합산 상시5인이상=근로기준법 적용+전보 정당",
  "holding_summary": "이 사건 회사+관계사(알엑스오그룹, 알엑스오)를 하나의 사업장으로 보아 상시5인이상 확인=근로기준법 적용+전보 정당",
  "retrieval_note": "관계사 합산으로 5인 이상 사업장 확인 후 TV 적용 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406847",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["contractual_transfer_clause", "business_necessity_recognized", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로계약서전보조항+업무상필요성인정=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "근로계약서 전보 조항+업무상 필요성=전보 정당",
  "holding_summary": "근로계약서에 업무상 필요 시 전보 발령 가능 규정 있고, 업무상 필요성 인정, 생활상 불이익 크지 않음=전보 정당",
  "retrieval_note": "계약서 근거규정+업무상 필요성 인정 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406857",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "coworker_conflict", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["17명동료진술서제출=동료불화객관화=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "17명 동료 진술서=동료 불화 객관화=전보 정당",
  "holding_summary": "취업규칙에 전보 근거규정, 17명 동료 직원이 근로자와 근무하기 불편하다는 진술서 제출=업무상 필요성 인정, 생활상 불이익 크지 않음=전보 정당",
  "retrieval_note": "다수 동료 진술서로 직장 내 갈등 객관화 → TV 정당 사례",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406973",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["specialized_expertise", "business_necessity_recognized"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["전문분야전문성없어지시감독불가=전보대상제외=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "전문분야 지시감독 불가=전보 대상 제외=TV 정당",
  "holding_summary": "근로자 담당업무(극세선 전선산업)에 전문지식 없어 지시감독 어려움=인력배치 상 전보 대상 제외 필요성 인정=TV 정당",
  "retrieval_note": "전문분야 지시감독 불가를 이유로 한 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407003",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "remedial_interest_preserved"],
  "legal_focus": ["transfer_validity_3prong", "remedial_interest"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["직위여전히존재=구제이익있음+TV정당"],
  "exclude_for_queries": [],
  "summary_short": "코디네이터 직위 여전히 존재=구제이익 있음+TV 정당",
  "holding_summary": "인사발령 이후에도 코디네이터 직위를 두지 않는다는 내용 확인되지 않음=구제이익 존재+TV 3-prong 정당",
  "retrieval_note": "전보 후 직위 존속 여부로 구제이익 판단+TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407025",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["coworker_conflict", "business_necessity_recognized", "contractual_transfer_clause"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로자-직원불화=업무상필요성인정=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "근로자-직원 불화=업무상 필요성 인정=전보 정당",
  "holding_summary": "근로계약서·취업규칙에 전보 규정, 근로자와 직원들 간 불화 사실+보복 전보 단정 어려움=업무상 필요성 인정=TV 정당",
  "retrieval_note": "직원 간 불화를 업무상 필요성으로 인정한 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407047",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "layoff_avoidance_effort"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영효율화인력재배치=고용조정회피노력=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "경영효율화 인력재배치=고용조정 회피 노력=전보 정당",
  "holding_summary": "대주주 콜옵션 포기+시장상황=경영효율화 인사조치 필요성, 인력재배치=고용조정 회피 노력의 일환=업무상 필요성 인정=TV 정당",
  "retrieval_note": "경영효율화·고용조정회피 목적 인력재배치 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407073",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["보복전보단정어려움=업무상필요성인정=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "보복 전보 단정 어려움=업무상 필요성 인정=전보 정당",
  "holding_summary": "근로계약서·취업규칙에 전보 근거규정, 보복 조치 단정 어렵고 업무상 필요성 인정, 생활상 불이익 크지 않음=TV 정당",
  "retrieval_note": "보복전보 주장 배척+업무상 필요성 인정 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407085",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "order_not_disciplinary"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["인사명령=징계아님+업무상필요성인정=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "인사명령=징계 아님+업무상 필요성=전보 정당",
  "holding_summary": "인사명령은 징계로 볼 수 없고, 조직 변경이 근로자에게 불리한 조치라 볼 수 없으며, 유사직무 매니저로 재직=업무상 필요성 인정=TV 정당",
  "retrieval_note": "인사명령≠징계 구별+TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407089",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "layoff_avoidance_effort"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["경영효율화인력재배치=고용조정회피노력=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "경영효율화 인력재배치=고용조정 회피=전보 정당 (id_407047 자매)",
  "holding_summary": "대주주 콜옵션 포기+시장상황=경영효율화 필요성, 인력재배치=고용조정 회피 노력=업무상 필요성 인정=TV 정당 (id_407047과 동일 법인 동일 쟁점)",
  "retrieval_note": "경영효율화 TV 정당 패턴 (id_407047 자매 사건)",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40709",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "minimal_life_disruption"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["계약시근로조건과배치시근로조건차이없음=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "근로계약 후 동일업무 4개월 근무=근로조건 차이 없음=전보 정당",
  "holding_summary": "근로자가 계약 시 근로조건과 배치 시 근로조건 차이로 인한 계약해지가 없었으므로 손해배상 없음. 이후 전보=업무상 필요성 인정=TV 정당",
  "retrieval_note": "배치 후 근로조건 차이 없음 확인 후 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407119",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "intra_company_transfer_not_inter_company"],
  "legal_focus": ["transfer_validity_3prong", "transfer_vs_assignment"],
  "industry_context": "public",
  "exclusion_flags": [],
  "include_for_queries": ["법인내사업장간이동=전적아님=전보=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "A시설→B시설 이동=전적 아님=전보=TV 정당",
  "holding_summary": "법인 산하 A시설 사무국장을 B시설 시설장으로 발령=동일 법인 내 이동=전적 아님=전보 해당+공개모집 절차 지원자 없어 업무상 필요성 인정=TV 정당",
  "retrieval_note": "동일 법인 내 산하기관 간 이동=전보(전적 아님) 구별 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407135",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["remedial_interest_preserved", "business_necessity_recognized"],
  "legal_focus": ["transfer_validity_3prong", "remedial_interest"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["전보후해고있어도전보구제이익존속=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "전보 후 해고=해고 정당성 미확정=전보 구제이익 여전히 존재+TV 정당",
  "holding_summary": "전보 이후 해고가 있었다 하더라도 해고의 효력 미확정 상태에서 전보 구제이익 여전히 존재=구제이익 인정+TV 3-prong 정당",
  "retrieval_note": "전보 후 해고가 발생해도 전보 구제이익 유지되는 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407151",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "consultation_procedure_followed"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["평택사업장전입업무상필요성+신의칙협의절차=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "평택 사업장 전입=업무상 필요성+신의칙 협의절차=전직 정당",
  "holding_summary": "평택 사업장 전입 인력 필요성 인정, 생활상 불이익 크지 않음, 신의칙상 요구되는 협의절차도 충족=TV 3-prong 정당",
  "retrieval_note": "신의칙 협의절차까지 충족한 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407279",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "employer_discretion_within_bounds"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사명령=사용자재량범위내=TV정당+징계사유불인정"],
  "exclude_for_queries": [],
  "summary_short": "인사명령=사용자 재량 범위 내=TV 정당+인사명령 거부 징계사유 인정",
  "holding_summary": "근로계약서에 사용자 지정 업무 수행 규정, 인사명령=사용자 재량=부당 볼 수 없음+해고=절차 준수=정당",
  "retrieval_note": "인사명령 재량권 범위 인정+징계 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407415",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "standby_order_valid"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["대기발령사유미명시만으로무효아님=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "대기발령 사유 명시 않아도 무효 아님=TV 정당",
  "holding_summary": "대기발령 시 사유를 명시하지 않았다는 사정만으로 대기발령 무효 아님, 업무 통폐합으로 보직 없어 일시적 대기발령=업무상 필요성 인정=TV 정당",
  "retrieval_note": "대기발령 사유 미명시=무효 아님 확인 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40723",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "seniority_based_selection"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "service",
  "exclusion_flags": [],
  "include_for_queries": ["기도원단독방송업무필요=최선임직원전보=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "기도원 단독 방송업무=최선임 직원 전보=TV 정당",
  "holding_summary": "기도원에 방송업무 단독 수행 가능한 중견급 직원 필요성 인정, 근로자=교회 방송실 최장기 근무 최선임=업무상 필요성 인정=TV 정당",
  "retrieval_note": "종교기관 내 전문 업무 필요성 인정 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407531",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "workplace_order_restoration"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["기구신설조직확대+직장질서유지=TV정당"],
  "exclude_for_queries": [],
  "summary_short": "기구 신설·조직 확대+직장질서 유지=전보 정당",
  "holding_summary": "회사 기구 신설 및 조직 확대 개편 필요성, 직장질서 유지·회복=업무상 필요성 인정. 임금·수당·근무장소 변동 없거나 미미=생활상 불이익 크지 않음=TV 정당",
  "retrieval_note": "조직 개편+직장질서 유지 필요성 인정 TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── transfer_validity (TV 부당) ──────────────────────────────────────────
{
  "case_id": "id_40681",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["unequal_treatment_in_transfer", "coworker_conflict", "inadequate_business_necessity"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["동료불화귀책특정근로자에게만없음=특정근로자만전보=업무상필요성없음=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "동료 불화 귀책=특정 근로자에게만 없음에도 전보=TV 부당",
  "holding_summary": "동료 불화 원인이 특정 근로자에게만 있다고 볼 수 없는데 특정 근로자만 전보 대상으로 선정=업무상 합리적 사유 없음=업무상 필요성 불인정+생활상 불이익 발생=TV 부당",
  "retrieval_note": "동료불화 귀책불명확=특정 근로자만 전보 대상 선정=TV 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406923",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "severe_life_disruption", "consultation_not_conducted"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["대상자선정합리성담보어려움=업무상필요성불인정+생활상불이익+협의없음=TV3-prong부당"],
  "exclude_for_queries": [],
  "summary_short": "대상자 선정 합리성 없음+생활상 불이익+협의 없음=전직 부당",
  "holding_summary": "한시적 인사수요 존재하나 대상자 선정의 합리성 담보 어려워 업무상 필요성 불인정+가족 상황상 생활상 불이익+신의칙상 협의 없음=TV 3-prong 모두 불충족=전직 부당",
  "retrieval_note": "TV 3-prong 모두 불충족(선정합리성 없음+생활상불이익+협의없음) 전직 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406935",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "disguised_forced_resignation", "unfavorable_working_conditions"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["희망퇴직거부자TF배치=컴퓨터미구비업무지시불명확=위장퇴직유도=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "희망퇴직 거부자 TF팀 배치=근무여건 미비+위장퇴직 유도=TV 부당",
  "holding_summary": "희망퇴직 거부 근로자들만으로 TF팀 구성+발령 시부터 컴퓨터 미구비·업무지시 불명확=업무상 필요성 없음, 위장 퇴직 유도 성격=TV 부당",
  "retrieval_note": "희망퇴직 거부자 TF팀 배치=위장 퇴직 유도 성격 TV 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406937",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "disguised_forced_resignation", "unfavorable_working_conditions"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["희망퇴직거부자TF리더배치=컴퓨터미구비업무지시불명확=위장퇴직유도=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "희망퇴직 거부자 TF 리더 배치=업무 미비+위장퇴직 유도=TV 부당 (id_406935 자매)",
  "holding_summary": "희망퇴직 거부한 근로자를 TF 리더로 배치+컴퓨터 미구비·업무지시 불명확+리더인 근로자보다 근속·직급 높은 팀원=업무상 필요성 없음=TV 부당 (id_406935 자매 사건)",
  "retrieval_note": "TF 리더 배치=업무상 필요성 없음 TV 부당 (id_406935 자매)",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407087",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["inadequate_business_necessity", "severe_life_disruption", "unprecedented_transfer"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["업무능률증진기대못함+전례없는이례적전보+생활상불이익큼=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "업무능률 증진 기대 못함+이례적 전보+생활상 불이익=TV 부당",
  "holding_summary": "부서 변경 필요성은 인정되나 근로자 근무경력·연령·채용직군 고려 시 업무능률 증진 기대 불가+전례 없는 이례적 전보=업무상 필요성 불인정+주말근무 등 생활상 불이익 큼=TV 부당",
  "retrieval_note": "업무능률증진기대불가+이례적 전보+생활상불이익 큼 TV 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40753",
  "issue_type_primary": "transfer_validity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "severe_life_disruption", "employer_discretion_exceeded"],
  "legal_focus": ["transfer_validity_3prong"],
  "industry_context": "sales",
  "exclusion_flags": [],
  "include_for_queries": ["업무상필요성인정이나생활상불이익감수주장배척=TV부당"],
  "exclude_for_queries": [],
  "summary_short": "업무상 필요성 인정이나 생활상 불이익 감수 주장 배척=TV 부당",
  "holding_summary": "대구영업소 CS인력 재배치 필요성은 인정되나, 비상경영 이유로 생활상 불이익 감수 주장=배척. 의구심이 드는 보직변경 배경 등=생활상 불이익이 통상 감수 범위 초과=TV 부당",
  "retrieval_note": "업무상필요성 인정이나 생활상불이익 과도=TV 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── no_dismissal ──────────────────────────────────────────────────────────
{
  "case_id": "id_406737",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "probation",
  "disposition_type": ["dismissal"],
  "fact_markers": ["probation_refusal_is_dismissal"],
  "legal_focus": ["probationary_employment"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["시용근로본채용거부=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "시용근로 본채용 거부=부당해고",
  "holding_summary": "시용근로관계에 따른 본채용 거부=부당해고에 해당 (간략 판정 사례)",
  "retrieval_note": "시용근로 본채용 거부=부당해고 인정 간략 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406759",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["employer_liability_confirmed", "dismissal_found_unfair"],
  "legal_focus": ["employer_definition", "dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로조건결정임금지급=사용자해당+해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "사용자=근로조건 결정·임금 지급자 확인+해고 존재=부당해고",
  "holding_summary": "근로자의 근로조건을 결정하고 임금을 지급한 자=근로기준법상 사용자 해당+해고 존재 확인=서면통지 없음=부당해고",
  "retrieval_note": "사용자 해당성 확인 후 해고 존재+부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406809",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "resignation_under_duress_rejected"],
  "legal_focus": ["dismissal_existence", "consent_validity"],
  "industry_context": "retail",
  "exclusion_flags": ["settlement_or_mutual_termination"],
  "include_for_queries": ["합의(권고사직)주장=객관적증거없음=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "권고사직 합의 주장=객관적 증거 없음=해고 존재=부당해고",
  "holding_summary": "사용자가 합의 퇴직 주장하나 근로자가 합의 확정 안 했고 억울함 호소+사직서·합의 객관적 증거 없음=해고 존재 인정=부당해고",
  "retrieval_note": "합의퇴직 주장 배척=해고 존재 인정 패턴 (빵집 폐기용 빵 분쟁)",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406815",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["no_dismissal_found", "continuous_absence"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": ["unrelated_to_dismissal"],
  "include_for_queries": ["결근후문자=해고통보아님=해고없음=기각"],
  "exclude_for_queries": [],
  "summary_short": "결근 후 센터장 문자=해고 통보 아님=해고 없음=기각",
  "holding_summary": "센터장이 근로자에게 보낸 문자(결근 확인+당일 근무 불가 판단+마지막)=해고 의사표시로 보기 어렵고 해고 없음=구제신청 기각",
  "retrieval_note": "결근 중 문자=해고 의사표시 불인정=해고 없음 기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407013",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "probation",
  "disposition_type": ["dismissal"],
  "fact_markers": ["probation_refusal_justified", "performance_evaluation_poor"],
  "legal_focus": ["probationary_employment"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["본채용기준40점미달=본채용거부정당"],
  "exclude_for_queries": [],
  "summary_short": "본채용 기준(80점)에 40점=평가 미달=본채용 거부 정당",
  "holding_summary": "본채용 기준 80점에 근로자 평가 40점=부적격 평가 항목들 사용자 제출자료로 확인=본채용 거부 정당",
  "retrieval_note": "수치 기준 미달 평가 근거 본채용 거부 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407041",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "lack_of_written_notice"],
  "legal_focus": ["dismissal_existence", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["해고존재인정+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재 인정+서면통지 없음=부당해고",
  "holding_summary": "사용자가 합의 퇴직 주장하나 해고 존재 인정=서면 해고 통지 없음=절차적 하자=부당해고",
  "retrieval_note": "해고 존재 인정+서면통지 흠결 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407043",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "verbal_dismissal", "lack_of_written_notice"],
  "legal_focus": ["dismissal_existence", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["그만두라취지발언=일방적근로관계종료=해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "그만두라는 취지 발언=해고 의사표시=서면통지 없음=부당해고",
  "holding_summary": "대표이사가 '우리 회사와 맞지 않으니 그만두라'는 취지 발언=근로관계 일방적 종료 의사=해고 존재+서면통지 없음=부당해고",
  "retrieval_note": "구두 해고 발언=해고 존재 인정+서면통지 흠결 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407059",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "agent_authority_for_dismissal", "lack_of_written_notice"],
  "legal_focus": ["dismissal_existence", "written_notice_requirement", "employer_definition"],
  "industry_context": "construction",
  "exclusion_flags": [],
  "include_for_queries": ["현장소장해고권한인정+사용자묵인=해고존재+서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "현장소장 해고 권한 인정+사용자 묵인=해고 존재+서면통지 없음=부당해고",
  "holding_summary": "현장소장=채용·작업관리·계속고용 판단 권한 부여받은 자로 해고 권한 있음+사용자 묵인=해고 존재+서면통지 없음=절차 위법=부당해고",
  "retrieval_note": "현장소장 해고권한 인정+사용자 묵인=해고 존재=서면통지흠결 부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407213",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "probation",
  "disposition_type": ["dismissal"],
  "fact_markers": ["probation_refusal_is_dismissal", "no_basis_for_probation_extension"],
  "legal_focus": ["probationary_employment", "dismissal_existence"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["수습연장근거없음+동의않자본채용거부=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "수습 연장 근거 없음+동의 않자 본채용 거부=해고 존재=부당해고",
  "holding_summary": "근로계약서에 수습기간 3개월+연장 규정 없음+연장 제안에 근로자 미동의=수습 종료=본채용 거부=해고 존재=부당해고",
  "retrieval_note": "수습연장 근거 없음+동의 불비=본채용 거부=해고 부당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407277",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["no_dismissal_found"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": ["unrelated_to_dismissal"],
  "include_for_queries": ["해고없음=기각"],
  "exclude_for_queries": [],
  "summary_short": "해고 존재 불인정=기각",
  "holding_summary": "순환근무·희망퇴직·성과평가 부정적 등 전보 조치=해고 아님, 해고 없음=구제신청 기각",
  "retrieval_note": "전보 조치=해고 아님, 해고 없음 확인 기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407345",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "lack_of_written_notice"],
  "legal_focus": ["dismissal_existence", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["근로계약서재작성요구+해고통보=해고존재=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "근로계약서 재작성 요구+갈등 후 해고=해고 존재=부당해고",
  "holding_summary": "사용자가 근로계약서 재작성 요구, 근로자 거부로 갈등=해고 존재+서면통지 없음=부당해고",
  "retrieval_note": "근로계약서 재작성 거부 후 해고=해고 존재=부당해고 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407503",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["dismissal_found_unfair", "insincere_reinstatement_order", "lack_of_written_notice"],
  "legal_focus": ["remedial_interest", "dismissal_existence", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["진정성없는복직명령=구제이익소멸불인정+해고서면통지없음=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "진정성 없는 복직명령=구제이익 소멸 불인정+서면통지 없음=부당해고",
  "holding_summary": "금전보상 신청 근로자에게 당일 복직 명령(현실적 불가)=진정성 없는 복직명령=구제이익 소멸 불인정+서면 해고통지 없음=부당해고 (batch_046 id_405699 유사 패턴)",
  "retrieval_note": "진정성없는복직명령=구제이익소멸시도 배척+부당해고 패턴 (id_405699 유사)",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407569",
  "issue_type_primary": "no_dismissal",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["no_dismissal_found", "business_necessity_recognized"],
  "legal_focus": ["dismissal_existence"],
  "industry_context": "unknown",
  "exclusion_flags": ["unrelated_to_dismissal"],
  "include_for_queries": ["인사이동제한규정없음+인원배치변경필요성=TV정당+해고없음=기각"],
  "exclude_for_queries": [],
  "summary_short": "인사이동 제한 없음+인원배치 필요성=TV 정당+해고 없음=기각",
  "holding_summary": "개발본부장 퇴사로 인원배치 변경 필요, 근로계약·취업규칙에 인사이동 제한 없음=업무상 필요성 인정=TV 정당+해고 없음=기각",
  "retrieval_note": "TV 정당+해고 없음 이중 기각 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── disciplinary_severity ─────────────────────────────────────────────────
{
  "case_id": "id_406719",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["suspension", "transfer"],
  "fact_markers": ["safety_rule_violation", "disciplinary_grounds_recognized", "proportionate_sanction", "business_necessity_recognized"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality", "transfer_validity_3prong"],
  "industry_context": "manufacturing",
  "exclusion_flags": [],
  "include_for_queries": ["안전규칙위반지게차기물파손=정직1월정당+전보정당"],
  "exclude_for_queries": [],
  "summary_short": "지게차 안전규칙 위반+기물 파손=정직 1개월 정당+전보 정당",
  "holding_summary": "진입금지구역 지게차 임의진입·기물파손=안전규칙 위반=중대 비위=정직 1월 과하지 않음+징계절차 하자 없음+사고예방·인력재배치 전보=업무상필요성 인정=TV 정당",
  "retrieval_note": "제조업 안전규칙 위반 정직+전보 모두 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406795",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["conflicting_authority", "disciplinary_grounds_rejected"],
  "legal_focus": ["disciplinary_grounds_validity"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["이사회의결vs이사장인사명령충돌=인사명령거부징계사유불인정=부당해고"],
  "exclude_for_queries": [],
  "summary_short": "이사회 의결 vs 이사장 인사명령 충돌=인사명령 거부=징계사유 불인정=부당해고",
  "holding_summary": "이사회가 이사장 직무정지 의결한 상황에서 이사장의 인사명령과 이사회 의결 중 어느 쪽을 따를지 혼란스러운 상황=인사명령 거부=징계사유 불인정=부당해고",
  "retrieval_note": "이사회의결-이사장인사명령 충돌=인사명령 거부 징계사유 불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406877",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["insubordination", "disciplinary_grounds_recognized", "proportionate_sanction"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "office",
  "exclusion_flags": [],
  "include_for_queries": ["상급자지시반항+대표이사반대의견무시+허위정보유포=징계해고정당"],
  "exclude_for_queries": [],
  "summary_short": "상급자 지시 반항+대표이사 반대 무시+허위 정보 유포=징계해고 정당",
  "holding_summary": "상급자 지시 반하여 겸직 추진+대표이사 부정적 메일에도 '협의완료'라고 허위 정보 유포+지시 명백히 위반=징계사유 인정=해고 정당",
  "retrieval_note": "조직 내 지시 반항+허위 정보 유포 징계해고 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_406919",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["workplace_violence", "disciplinary_grounds_recognized", "proportionate_sanction"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["부서전체회식장폭행=업무연장선=정직정당"],
  "exclude_for_queries": [],
  "summary_short": "부서 전체 회식장 폭행=업무 연장선=정직 정당",
  "holding_summary": "부서 전체 회식자리에서 무방비 피해자 일방 폭행+전치2주+피해자 사과 거부=업무 연장선의 사건=단순 개인 폭행과 달리 판단=정직 정당",
  "retrieval_note": "부서 회식장 폭행=업무 연장선=정직 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407113",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["suspension"],
  "fact_markers": ["workplace_harassment", "disciplinary_grounds_recognized", "proportionate_sanction", "management_position"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["관리자직장내괴롭힘성격행위=정직정당"],
  "exclude_for_queries": [],
  "summary_short": "관리자 직장 내 괴롭힘 성격 행위=정직 정당",
  "holding_summary": "근로자 행위=업무상 적정범위 초과+조직분위기 훼손+직장질서 침해=징계사유 인정, 관리자로서 모범 보여야 할 지위=징계양정 적정=정직 정당",
  "retrieval_note": "관리자 직장내괴롭힘 성격 행위 정직 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407431",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["pay_cut"],
  "fact_markers": ["disciplinary_grounds_recognized", "proportionate_sanction"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "education",
  "exclusion_flags": [],
  "include_for_queries": ["외국인교육생부적절언행+기숙사규정임의적용=감봉정당"],
  "exclude_for_queries": [],
  "summary_short": "외국인 교육생 부적절 언행+기숙사 규정 임의 적용=감봉 정당",
  "holding_summary": "외국인 교육생에 대한 부적절한 언행+기숙사 규정 임의 적용=징계사유 인정+감봉=적정 양정=징계 정당",
  "retrieval_note": "교육기관 교육생 대상 부적절 언행 감봉 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407449",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["demotion", "dismissal"],
  "fact_markers": ["disciplinary_grounds_rejected_partial", "temporal_scope_of_misconduct"],
  "legal_focus": ["disciplinary_grounds_validity", "disciplinary_proportionality"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["보직해임정당+전직전사업장비위=징계사유인정범위제한=파면부당=부분인용"],
  "exclude_for_queries": [],
  "summary_short": "보직해임 정당+전직 전 사업장 비위=당해 근로관계 기간 한정=파면 부당=부분인용",
  "holding_summary": "보직해임=업무상필요성+생활상불이익없음+협의의무규정없음=정당. 파면=전직 전 사업장 비위행위를 징계사유로 삼은 것은 부당=당해 근로관계 기간 비위만 인정=파면 부당=부분인용",
  "retrieval_note": "보직해임 정당+전직전 비위=징계사유 범위 제한=파면 부당 부분인용 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407525",
  "issue_type_primary": "disciplinary_severity",
  "issue_type_secondary": ["procedure"],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["disciplinary_grounds_recognized", "standing_by_succession", "blood_alcohol_violation"],
  "legal_focus": ["disciplinary_grounds_validity", "remedial_interest"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["상속인지위승계+구제이익인정+음주위반징계해고정당"],
  "exclude_for_queries": [],
  "summary_short": "상속인 지위 승계+구제이익 인정+음주 위반 징계해고 정당",
  "holding_summary": "근로자 사망 후 상속인(아들)의 재심 단계 지위 승계=노동위원회규칙·행정심판법 준용=구제이익 인정+수차례 음주측정 결과 음주사실=단협 제22조 위반=징계해고 정당",
  "retrieval_note": "사망 근로자 상속인 지위 승계+구제이익 인정+음주 징계해고 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── procedure ────────────────────────────────────────────────────────────
{
  "case_id": "id_407267",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["remedial_interest_expired", "reinstatement_order_valid", "worker_failed_to_return"],
  "legal_focus": ["remedial_interest"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["복직명령후미출근=개인사정=구제이익소멸"],
  "exclude_for_queries": [],
  "summary_short": "복직명령 후 개인 사정으로 미출근=구제이익 소멸",
  "holding_summary": "사용자 복직명령+임금상당액 지급 확인에도 근로자 미출근=타 사업장 근로 제공은 사용자 책임 있는 사유 아님=진정성 없는 복직명령 볼 수 없음=구제이익 소멸",
  "retrieval_note": "복직명령 후 개인 사정 미출근=구제이익 소멸 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_407397",
  "issue_type_primary": "procedure",
  "issue_type_secondary": [],
  "employment_stage": "regular",
  "disposition_type": ["dismissal"],
  "fact_markers": ["lack_of_written_notice", "reexamination_standing_rejected"],
  "legal_focus": ["remedial_interest", "written_notice_requirement"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["서면통지없음=부당해고인용된초심+금전보상액재산정요청재심=신청자격없음=재심각하"],
  "exclude_for_queries": [],
  "summary_short": "초심 부당해고 인용 후 금전보상액 재산정 요청 재심=신청 자격 없음=재심 각하",
  "holding_summary": "초심에서 서면통지의무 위반 부당해고 인용+금전보상명령 발령. 근로자가 보상금액 재산정 요청 재심 신청=금전보상액은 노동위원회 직권 산정=불복 대상 아님=재심 신청 자격 없음=각하",
  "retrieval_note": "금전보상액 재산정 요청 재심=신청 자격 없음 각하 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
# ── union_activity ────────────────────────────────────────────────────────
{
  "case_id": "id_407315",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["business_necessity_recognized", "anti_union_motive_rejected"],
  "legal_focus": ["unfair_labor_practice", "transfer_validity_3prong"],
  "industry_context": "transport",
  "exclusion_flags": [],
  "include_for_queries": ["신차입고노선변경불가피+입사순배정=부당노동행위의사없음=전직정당"],
  "exclude_for_queries": [],
  "summary_short": "신차 입고 노선변경 불가피+입사순 배정=부당노동행위 의사 없음=전직 정당",
  "holding_summary": "신차 입고에 따른 중간 차 배정=노선변경 불가피+입사순 배정 기준 합리적=부당노동행위 의사 뚜렷한 증거 없음=전직 정당",
  "retrieval_note": "운수업 노선변경 부당노동행위 주장 배척+TV 정당 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
{
  "case_id": "id_40745",
  "issue_type_primary": "union_activity",
  "issue_type_secondary": ["transfer_validity"],
  "employment_stage": "regular",
  "disposition_type": ["transfer"],
  "fact_markers": ["anti_union_motive_rejected", "intra_company_staffing_basis"],
  "legal_focus": ["unfair_labor_practice"],
  "industry_context": "unknown",
  "exclusion_flags": [],
  "include_for_queries": ["인사발령배제=감사조사중+인력수급=부당노동행위의사없음=정당"],
  "exclude_for_queries": [],
  "summary_short": "인사발령 배제=감사조사 중+인력수급 사정=부당노동행위 의사 없음=정당",
  "holding_summary": "근로자1=감사조사 중, 근로자2=고충처리 미신청+희망지 인력수급=인사발령 배제 정당 이유 인정=부당노동행위 의사 뚜렷한 증거 없음=불이익취급·지배개입 부당노동행위 불인정",
  "retrieval_note": "인사발령 배제=정당 사유 인정, 부당노동행위 의사 불인정 패턴",
  "confidence": "high",
  "review_status": "done",
  "tag_version": "v3"
},
]

with open(OUT, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Written {len(records)} records")
