"""
transfer_batch_060 tagging script
Distribution: TV20(정당18/부당1/부분인용1) / procedure12 / disciplinary6 / no_dismissal6 / union_activity4 / redundancy1 / discrimination1 = 50건
"""
import json, pathlib

OUTPUT = pathlib.Path("retagging/output/reviewed/transfer_batch_060_reviewed.jsonl")
OUTPUT.parent.mkdir(parents=True, exist_ok=True)

records = [

# ── procedure ──

{"case_id":"id_43977","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],
"employment_stage":"regular","disposition_type":["dismissal","no_formal_disposition"],
"fact_markers":["사용자해고철회","원직복직명령","구제이익소멸"],
"legal_focus":["구제이익소멸요건","복직명령효과"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant","unrelated_to_dismissal"],
"include_for_queries":["사용자스스로해고철회복직명령구제이익소멸","구제신청목적달성구제이익소멸"],
"exclude_for_queries":[],
"summary_short":"사용자 자체 해고 철회+복직명령=구제이익 소멸",
"holding_summary":"사용자스스로해고철회+복직명령=구제신청목적달성=구제이익소멸",
"retrieval_note":"사용자가 스스로 해고를 철회하고 복직명령을 한 경우 구제이익 소멸 확인 사례",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44035","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["금전보상신청전복직명령","금전보상회피목적"],
"legal_focus":["구제이익소멸","금전보상명령신청시점"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["금전보상신청전복직명령구제이익소멸","금전보상회피목적단정어려움구제이익소멸"],
"exclude_for_queries":[],
"summary_short":"금전보상 신청 전 복직명령=구제이익 소멸",
"holding_summary":"금전보상신청전사용자복직명령=금전보상회피목적단정어려움=구제이익소멸",
"retrieval_note":"금전보상 신청 전 이루어진 복직명령은 구제이익을 소멸시킴. id_44113(구제신청후복직=구제이익존재)과 대조되는 패턴",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44113","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["구제신청후복직명령","금전보상회피목적추정"],
"legal_focus":["구제이익존부","복직명령시점","금전보상회피의도"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["구제신청사실인지후복직명령구제이익존재","금전보상회피목적추정구제이익소멸않음"],
"exclude_for_queries":[],
"summary_short":"구제신청 인지 후 복직명령=구제이익 소멸 안 됨",
"holding_summary":"사용자구제신청사실인지후복직명령=금전보상회피목적추정=구제이익소멸않음",
"retrieval_note":"구제신청 사실을 안 후 이루어진 복직명령은 구제이익을 소멸시키지 않음. id_44035(신청전복직=소멸)와 대조",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44131","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["원직복직","구제이익없음","노조갈등해소목적"],
"legal_focus":["구제이익소멸","업무상필요성"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["원직복직구제이익없음각하","방론노조갈등해소목적업무상필요성불인정"],
"exclude_for_queries":[],
"summary_short":"복직=구제이익 없음=각하 + 방론 TV부당",
"holding_summary":"원직복직=구제이익없음=각하+방론으로노조갈등해소목적전보=업무상필요성불인정",
"retrieval_note":"복직으로 구제이익 소멸→각하. 방론에서 노조 갈등 해소 목적은 업무상 필요성으로 인정 어렵다고 판시",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44177","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["상시5인이상인날22일","구두해고","서면통지위반","금전보상"],
"legal_focus":["상시근로자수판단기준","근기법적용여부","해고서면통지","금전보상"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["5인이상인날22일근기법적용","상시근로자수산정기준5인이상인날"],
"exclude_for_queries":[],
"summary_short":"5인 이상인 날 22일=근기법 적용, 구두해고=서면통지위반=부당",
"holding_summary":"상시근로자수4.38이나5인이상인날22일=근기법제28조적용+구두해고=서면통지의무위반=부당+금전보상",
"retrieval_note":"상시근로자 수 평균 4.38이더라도 5인 이상인 날 22일=근기법 적용 사업장 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44335","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["판정일전복직","임금차액없음","구제이익없음"],
"legal_focus":["구제이익소멸","야간→주간전환임금"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["판정일전복직임금차액없음구제이익없음각하"],
"exclude_for_queries":[],
"summary_short":"판정일 전 복직+임금 차액 없음=구제이익 없음=각하",
"holding_summary":"판정일전복직+야간→주간전환배치후임금차액없음=구제이익없음=각하",
"retrieval_note":"전보 후 복직되고 임금 차액도 없는 경우 구제이익 소멸=각하",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44411","issue_type_primary":"procedure","issue_type_secondary":["no_dismissal"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["용역계약이나실질근로자성","5인이상근기법적용"],
"legal_focus":["근로자성판단","상시근로자수","근기법적용여부"],
"industry_context":"service","exclusion_flags":["procedure_dominant"],
"include_for_queries":["용역계약이나실질지휘감독근로자성인정","5인이상근기법적용"],
"exclude_for_queries":[],
"summary_short":"용역계약이나 실질 근로자성 인정+5인 이상=근기법 적용",
"holding_summary":"용역계약명칭이나실질근로시간장소특정+지휘감독=근로자성인정=근기법적용사업장",
"retrieval_note":"계약 형식이 용역계약이더라도 실질 지휘감독+근로시간/장소 특정=근로자성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44415","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전직명령일3개월경과","구제신청제척기간도과"],
"legal_focus":["제척기간","구제신청기간"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["전직명령일3개월경과구제신청제척기간도과각하"],
"exclude_for_queries":[],
"summary_short":"전직명령 후 3개월 경과 구제신청=제척기간 도과=각하",
"holding_summary":"전직명령일로부터3개월경과후구제신청=근기법제28조제2항제척기간도과=각하",
"retrieval_note":"전보 명령일 기준 3개월 제척기간 도과 후 구제신청=각하 확인 사례",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44425","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["중간관리자와구두SNS합의","보험설계사총무전환","실질근로자성"],
"legal_focus":["사용자적격","근로자성판단","해고서면통지"],
"industry_context":"finance","exclusion_flags":["procedure_dominant"],
"include_for_queries":["중간관리자경유임금지급=실질사용자적격","보험설계사→총무전환근로자성인정"],
"exclude_for_queries":[],
"summary_short":"중간관리자 경유 계약이나 회사가 실질 사용자+근로자성 인정",
"holding_summary":"중간관리자구두SNS합의이나임금지급주체=회사=실질사용자+보험설계사→총무전환후근로자성인정+서면통지위반=해고부당",
"retrieval_note":"중간관리자를 통한 채용이라도 임금 지급 주체 회사=실질 사용자 적격, 업무 성격 변화에 따른 근로자성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44567","issue_type_primary":"procedure","issue_type_secondary":[],
"employment_stage":"unknown","disposition_type":["other"],
"fact_markers":["시설장원장위촉계약","인사회계포괄적권한","근로자성부정"],
"legal_focus":["근로자성판단","구제신청적격"],
"industry_context":"service","exclusion_flags":["procedure_dominant","unrelated_to_dismissal"],
"include_for_queries":["시설장원장위촉계약포괄적권한근로자성부정각하"],
"exclude_for_queries":[],
"summary_short":"시설장(원장) 위촉계약+포괄적 권한=근로자성 부정=각하",
"holding_summary":"시설장원장위촉계약+인사회계전반포괄적권한=실질근로자성부정=구제신청각하",
"retrieval_note":"시설 운영 권한을 포괄적으로 위임받은 시설장(원장)은 근기법상 근로자성 부정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44743","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전보후퇴직","직책수당미지급","구제이익존재"],
"legal_focus":["구제이익","전보후퇴직","직책수당"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["전보발령일~퇴직일직책수당미지급구제이익존재","전보후퇴직해도직책수당청구구제이익"],
"exclude_for_queries":[],
"summary_short":"전보→퇴직 기간 직책수당 미지급=구제이익 존재",
"holding_summary":"전보발령일~퇴직일직책수당미지급=임금상당액청구가능=구제이익존재=본안판단",
"retrieval_note":"근로관계 종료 후에도 전보 기간 직책수당 미지급액이 있으면 구제이익 존재",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44855","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["다른사업장노무제공금지","사용자직접임금지급","기본급위주"],
"legal_focus":["근로자성판단","전속성","사용종속관계"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["다른사업장노무금지+직접임금지급+기본급위주=근로자성인정"],
"exclude_for_queries":[],
"summary_short":"타 사업장 금지+직접임금지급+기본급 위주=근로자성 인정",
"holding_summary":"다른사업장노무제공금지+사용자직접임금지급+기본급대부분=근기법상근로자성인정",
"retrieval_note":"근로자성 판단 3요소(전속성+직접임금+기본급구조) 충족 시 근로자 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── transfer_validity ──

{"case_id":"id_44139","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],
"employment_stage":"regular","disposition_type":["transfer","no_formal_disposition"],
"fact_markers":["성희롱신고","분리조치","1차전보","2차직위해제","객지근무수당감소"],
"legal_focus":["성희롱분리조치업무상필요성","전보3요소","직위해제"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["성희롱분리조치=TV업무상필요성인정","성희롱피해자분리전보정당","성희롱가해자직위해제정당"],
"exclude_for_queries":[],
"summary_short":"성희롱 신고에 따른 분리조치 전보+직위해제 모두 정당",
"holding_summary":"성희롱신고=분리조치불가피=1차전보(TV정당)+2차직위해제업무상필요성인정+객지수당감소=감수범위=TV정당",
"retrieval_note":"성희롱 발생 시 피해자-가해자 분리 전보=업무상 필요성 인정. 객지근무수당 15만원 감소=감수 범위 내",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44249","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["DKD업무해외이관","주요담당업무소멸","업무재배치"],
"legal_focus":["업무상필요성","주요업무소멸"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["주요담당업무소멸=업무재배치불가피=TV정당","DKD업무해외이관=업무재배치=TV정당"],
"exclude_for_queries":[],
"summary_short":"주요 업무 해외이관으로 소멸=업무재배치 불가피=TV 정당",
"holding_summary":"DKD업무해외이관결정=근로자주요담당업무소멸=업무재배치불가피=TV업무상필요성인정=TV정당",
"retrieval_note":"담당 업무 자체가 해외 이관으로 소멸된 경우 업무 재배치 TV의 업무상 필요성 당연 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44287","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["직제개편TF팀폐지","부서장자리소멸","직책수당미지급","협의미준수"],
"legal_focus":["업무상필요성","직책수당생활상불이익여부","협의절차당연무효아님"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["직제개편부서폐지부서장자리소멸=TV업무상필요성","직책수당미지급=생활상불이익아님TV정당"],
"exclude_for_queries":[],
"summary_short":"직제개편 TF팀 폐지=TV 필요성, 직책수당 미지급=불이익 아님=TV 정당",
"holding_summary":"직제개편TF팀폐지=2부서장중1명부서원발령불가피=업무상필요성+직책수당미지급=인사발령결과=생활상불이익아님+협의미준수=당연무효아님=TV정당",
"retrieval_note":"직제개편으로 부서장 자리 소멸 시 TV 업무상 필요성 자동 인정. 직책수당 미지급은 전보 결과이지 별도 불이익이 아님",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44303","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["수평→수직조직변경","파트장신설","구제신청대상인정"],
"legal_focus":["전직구제신청대상여부","업무상필요성","생활상불이익"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["수직조직전환파트장신설=전직해당구제신청대상","조직변경전기차대응=업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"수직조직 전환+파트장 신설=전직 해당+TV 정당",
"holding_summary":"수평→수직조직변경+파트장신설+지휘결재변화=전직해당=구제신청대상+경영악화대응조직변경=업무상필요성+임금장소변화없음=TV정당",
"retrieval_note":"조직 구조 변경(수평→수직)으로 지휘결재 관계가 달라지면 전직에 해당하여 구제신청 대상. 조직변경 자체가 업무상 필요성 충족",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44359","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["장기근무순환근무","안전관리목적","노조활동관련생활상불이익주장"],
"legal_focus":["순환근무업무상필요성","생활상불이익","부당노동행위"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["장기근무자순환근무안전관리=TV업무상필요성","노조활동관련생활상불이익통상감수범위=TV정당"],
"exclude_for_queries":[],
"summary_short":"장기근무자 순환+안전관리=업무상필요성, TV 정당+부당노동행위 불인정",
"holding_summary":"장기근무자순환근무+안전관리확보=업무상필요성+노조활동관련생활상불이익통상감수범위=TV정당+부당노동행위불인정",
"retrieval_note":"장기근무자 순환근무와 안전관리 목적의 TV=업무상 필요성 충분. 노조 활동 관련 생활상 불이익 주장도 감수 범위 내",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44383","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로계약서업무변경가능규정","코로나19이용객감소","예산배정문제"],
"legal_focus":["업무상필요성","근로계약서규정","코로나특수상황"],
"industry_context":"service","exclusion_flags":[],
"include_for_queries":["근로계약서업무변경가능규정+코로나이용객감소=TV정당"],
"exclude_for_queries":[],
"summary_short":"근로계약서 업무변경 가능 규정+코로나 이용객 감소=TV 정당",
"holding_summary":"근로계약서무기계약직관리규정업무변경가능규정+코로나19이용객감소+예산배정문제=TV업무상필요성=TV정당",
"retrieval_note":"근로계약서에 업무변경 가능 규정 존재+코로나 경영상 사정=TV 업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4439","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["협의절차미준수","업무상필요성인정","생활상불이익감수범위"],
"legal_focus":["협의절차당연무효아님","전보3요소"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["협의절차미준수당연무효아님TV정당","업무상필요성+생활상불이익감수범위+협의미준수=TV정당"],
"exclude_for_queries":[],
"summary_short":"업무상필요성+생활상불이익 감수범위, 협의 미준수=당연무효 아님=TV 정당",
"holding_summary":"업무상필요성인정+생활상불이익통상감수범위+협의절차미준수만으로전보당연무효아님=TV정당",
"retrieval_note":"협의절차 미준수=당연무효 아님 법리 재확인(batch_055 id_413251, batch_057 id_41579, batch_059 id_43203에 이어 4회 누적)",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44399","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["임금피크제적용근로자","절대평가필요성","업무상필요성"],
"legal_focus":["임금피크제전보업무상필요성"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["임금피크제적용근로자절대평가전보=TV업무상필요성"],
"exclude_for_queries":[],
"summary_short":"임금피크제 적용 근로자 절대평가 위한 TV=업무상 필요성 인정=TV 정당",
"holding_summary":"노조의견제시+여러부문임금피크제근로자절대평가필요=업무상필요성=TV정당",
"retrieval_note":"임금피크제 적용 근로자에 대한 절대평가를 위한 전보=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44409","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["배치전환업무상필요성","생활상불이익감수범위","협의준수"],
"legal_focus":["전보3요소"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["TV3요소모두충족TV정당"],
"exclude_for_queries":[],
"summary_short":"배치전환 3요소 모두 충족=TV 정당",
"holding_summary":"배치전환업무상필요성인정+생활상불이익통상감수범위+협의절차준수=TV정당",
"retrieval_note":"TV 3요소(업무상필요성/생활상불이익/협의절차) 모두 충족=TV 정당 표준 사례",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44421","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["TV3요소정당","부당노동행위주장","불인정"],
"legal_focus":["전보3요소","부당노동행위"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["TV정당+부당노동행위불인정"],
"exclude_for_queries":[],
"summary_short":"TV 정당 + 부당노동행위 불인정",
"holding_summary":"TV업무상필요성+생활상불이익감수범위+협의준수=TV정당+부당노동행위볼객관적사정부족=불인정",
"retrieval_note":"TV 정당성 인정 후 부당노동행위 주장도 함께 배척",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44477","issue_type_primary":"transfer_validity","issue_type_secondary":["union_activity"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["대인사고","고정기사→예비기사","징벌해당","배치전환정당","부당노동행위불인정"],
"legal_focus":["배치전환징벌여부","전보정당성","부당노동행위"],
"industry_context":"transport","exclusion_flags":[],
"include_for_queries":["고정기사예비기사배치전환=징벌해당이나정당","대인사고배치전환징벌해당=업무상필요성정당"],
"exclude_for_queries":[],
"summary_short":"고정→예비기사 배치전환=징벌 해당이나 정당, 부당노동행위 불인정",
"holding_summary":"대인사고=고정기사→예비기사배치전환=근기법23조1항징벌해당+업무상필요성인정+생활상불이익감수범위+협의미준수=당연무효아님=배치전환정당+부당노동행위불인정",
"retrieval_note":"배치전환이 징벌(근기법23조1항)에 해당하더라도 업무상 필요성+생활상불이익감수범위=정당. 협의미준수=당연무효아님 법리 적용",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44493","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로계약근무지특정","광주영업→김해생산팀","업무성격변화","생활상불이익현저"],
"legal_focus":["근로계약근무지변경동의","생활상불이익현저"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["근로계약근무지특정광주영업→김해생산팀=생활상불이익현저=TV부당"],
"exclude_for_queries":[],
"summary_short":"근로계약 광주 영업지역 특정→김해 생산팀 전보=생활상 불이익 현저=TV 부당",
"holding_summary":"근로계약서광주지역영업업무특정+전보로김해본사생산팀업무변경=근로계약내용변경+생활상불이익현저=TV부당",
"retrieval_note":"근로계약상 특정 지역/업무로 고용된 경우 다른 지역+다른 직무 TV=근로계약 내용 변경+생활상 불이익 현저=TV 부당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44505","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["내부사정업무상필요성","생활상불이익없음"],
"legal_focus":["업무상필요성","생활상불이익"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["내부사정업무상필요성+생활상불이익없음=TV정당"],
"exclude_for_queries":[],
"summary_short":"내부 사정에 따른 인사발령=업무상 필요성+생활상 불이익 없음=TV 정당",
"holding_summary":"사용자내부사정업무상필요성인정+특별한생활상불이익없음=TV정당",
"retrieval_note":"업무상 필요성과 생활상 불이익 부재 확인으로 TV 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44575","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["잦은사고발생","안전조치강화","업무상필요성"],
"legal_focus":["안전관리TV업무상필요성","생활상불이익감수범위"],
"industry_context":"transport","exclusion_flags":[],
"include_for_queries":["잦은사고안전조치강화전보=TV업무상필요성"],
"exclude_for_queries":[],
"summary_short":"잦은 사고=안전조치 강화 전보=업무상 필요성=TV 정당",
"holding_summary":"잦은사고발생=안전조치강화예방전보=업무상필요성+생활상불이익감수범위=TV정당",
"retrieval_note":"안전 관리 강화(반복 사고 방지)를 위한 전보=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44647","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["저성과자","기술부족","연구→생산부전보","협의준수","생활상불이익없음"],
"legal_focus":["저성과TV업무상필요성","협의절차","생활상불이익"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["저성과기술부족=연구→생산부전보=TV업무상필요성","저성과자부서전환TV=협의준수+생활상불이익없음=TV정당"],
"exclude_for_queries":[],
"summary_short":"저성과·기술 부족자 연구→생산부 전보=업무상 필요성+협의 준수=TV 정당",
"holding_summary":"지속적기술부족평가+경영효율성제고필요=업무상필요성+생산부전보협의준수+생활상불이익없음=TV정당",
"retrieval_note":"저성과·기술부족 근로자의 적합 부서 전보=업무상 필요성 인정. 사전 면담+대안 3가지 제시=협의절차 준수",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4465","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["직장질서유지","업무상필요성","생활상불이익감수범위"],
"legal_focus":["직장질서TV업무상필요성","생활상불이익"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["직장질서유지목적TV=업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"직장질서 유지 목적 전보=업무상 필요성=TV 정당",
"holding_summary":"직장질서유지차원TV=업무상필요성+생활상불이익통상감수범위=TV정당",
"retrieval_note":"직장 질서 유지를 위한 전보도 업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44713","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로자간폭행사건","법규정내부규정근거","불가피한조치","세척제피부발진"],
"legal_focus":["폭행사건TV업무상필요성","생활상불이익","협의절차당연무효아님"],
"industry_context":"healthcare","exclusion_flags":[],
"include_for_queries":["근로자간폭행사건=불가피한전보조치=TV업무상필요성","폭행사건후분리전보=TV정당"],
"exclude_for_queries":[],
"summary_short":"근로자 간 폭행 사건=불가피한 분리 조치=TV 정당",
"holding_summary":"근로자간폭행사건발생=근기법+내부규정근거불가피한분리조치=업무상필요성+세척제피부발진대처+야간→주간변경=생활상불이익감수범위+협의미준수=당연무효아님=TV정당",
"retrieval_note":"근로자 간 폭행 사건 후 분리를 위한 전보=법규정+내부규정 근거=업무상 필요성. 협의미준수=당연무효아님 법리 적용",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44839","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["전문인력신규채용","육아휴직자복직","업무상필요성","생활상불이익없음"],
"legal_focus":["신규채용+복직에따른TV업무상필요성"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["전문인력신규채용+육아복직=TV업무상필요성TV정당"],
"exclude_for_queries":[],
"summary_short":"전문인력 신규 채용+육아휴직자 복직=업무상 필요성=TV 정당",
"holding_summary":"전문인력신규채용+육아휴직자복직=업무재배치필요=TV업무상필요성+생활상불이익없음=TV정당",
"retrieval_note":"신규 채용과 육아휴직자 복직에 따른 자리 조정 TV=업무상 필요성 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44849","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["기획실장보직해임","건강검진센터발령","부분인용"],
"legal_focus":["경영진소통필요직위TV","업무상필요성근거불충분"],
"industry_context":"healthcare","exclusion_flags":[],
"include_for_queries":["경영진소통필요기획실장보직해임=TV정당","업무상필요성근거미제시건강검진센터발령=TV부당","TV부분인용근로자1정당근로자2부당"],
"exclude_for_queries":[],
"summary_short":"부분인용: 근로자1(기획실장보직해임=TV정당)+근로자2(건강검진센터발령=TV부당)",
"holding_summary":"근로자1기획실장=경영진소통필요광범한인사재량=TV정당/근로자2건강검진센터발령=업무상필요성근거불충분=TV부당=부분인용",
"retrieval_note":"경영진 소통 필요 직위(기획실장)는 인사권 재량 넓음=TV 정당. 반면 구체적 근거 없는 발령=TV 부당. 동일 사건 부분인용",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44857","issue_type_primary":"transfer_validity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로계약서근무지변경규정","팀임원건의","연봉증가","협의미준수"],
"legal_focus":["근로계약서규정","업무상필요성","생활상불이익","협의절차당연무효아님"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["근로계약서근무지변경규정+팀임원건의=TV업무상필요성","연봉증가+생활상불이익없음+협의미준수=당연무효아님=TV정당"],
"exclude_for_queries":[],
"summary_short":"근로계약서 근무지변경 규정+임원 건의=업무상 필요성, 협의 미준수=당연무효 아님=TV 정당",
"holding_summary":"근로계약서취업규칙근무지변경규정+팀장임원건의+인력부족요청=업무상필요성+전보후연봉증가+생활상불이익없음+협의미준수=당연무효아님=TV정당",
"retrieval_note":"근로계약서에 근무지 변경 규정 있고 임원이 전배 건의=업무상 필요성. 협의미준수=당연무효아님 법리 적용",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── disciplinary_severity ──

{"case_id":"id_4405","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["업무방해불인정","팀장욕설분란조장","전보불응","무단결근","양정적정"],
"legal_focus":["징계사유개별심사","양정적정성"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["징계사유일부불인정=나머지인정+양정적정=징계정당"],
"exclude_for_queries":[],
"summary_short":"징계사유 4가지 중 업무방해 제외 3가지 인정+양정 적정=징계 정당",
"holding_summary":"징계사유4가지중업무방해제외팀장욕설전보불응무단결근3가지인정+양정적정=징계정당",
"retrieval_note":"징계사유 일부 불인정이더라도 나머지 사유 충분+양정 적정=징계 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44057","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],
"employment_stage":"regular","disposition_type":["other","transfer"],
"fact_markers":["지시내용불특정","징계사유불인정","인사발령업무상필요성없음","활동비생활상불이익"],
"legal_focus":["징계사유특정","인사발령업무상필요성"],
"industry_context":"it","exclusion_flags":[],
"include_for_queries":["지시내용구체적특정불가=징계사유불인정=징계부당","인사발령업무상필요성없음+활동비생활상불이익=TV부당"],
"exclude_for_queries":[],
"summary_short":"징계사유 불인정(지시내용 불특정)+인사발령 TV 부당=모두 부당",
"holding_summary":"지시내용구체적특정불가=징계사유불인정+인사발령업무상필요성없음+활동비생활상불이익+전날통지협의미준수=징계및TV부당",
"retrieval_note":"징계사유인 '지시'는 내용이 특정되어야 함. 인사발령은 업무상 필요성+전날 통지=협의절차 미준수로 TV 부당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4407","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["인사명령거부","업무지시불이행","직무태만","무단결근","양정적정"],
"legal_focus":["징계사유","양정"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["인사명령거부+업무지시불이행+무단결근=징계사유인정+양정적정=징계정당"],
"exclude_for_queries":[],
"summary_short":"인사명령 거부+지시 불이행+무단결근=징계사유 인정+양정 적정=징계 정당",
"holding_summary":"인사명령거부+업무지시불이행+직무태만+무단결근=징계사유모두인정+양정적정=징계정당",
"retrieval_note":"복합적 복무위반(거부+불이행+태만+결근) 징계사유 모두 인정=징계 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44233","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["other"],
"fact_markers":["업무미숙수십차례경위서","반복동일사유","징계전력"],
"legal_focus":["반복적징계사유","누적징계"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["반복동일사유수십차례경위서=징계사유인정"],
"exclude_for_queries":[],
"summary_short":"반복 업무미숙 수십 차례 경위서=징계사유 인정=정당",
"holding_summary":"동일사유수십차례경위서+2차례징계전력에도개선없음=상시적업무개진의지없음=징계사유인정=징계정당",
"retrieval_note":"반복적 동일 업무미숙에도 불구하고 개선이 없는 경우=징계사유 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44657","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["other"],
"fact_markers":["시각장애인교육장소음","내부사정누출","시말서거부"],
"legal_focus":["징계사유","시말서거부"],
"industry_context":"education","exclusion_flags":[],
"include_for_queries":["소음발생+내부사정누출+시말서거부=징계사유인정=정당"],
"exclude_for_queries":[],
"summary_short":"소음 발생+내부사정 누출+시말서 거부=징계사유 인정=정당",
"holding_summary":"시각장애인교육장소음발생+내부사정외부누출+시말서거부=징계사유인정=징계정당",
"retrieval_note":"시말서 거부 자체도 징계사유의 일부로 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44821","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],
"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],
"fact_markers":["시용근로계약","본채용거부","합리적이유없음"],
"legal_focus":["시용기간본채용거부합리성","본채용거부부당해고"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["시용근로계약본채용거부합리적이유없음=부당"],
"exclude_for_queries":[],
"summary_short":"시용근로계약 본채용 거부 합리적 이유 없음=부당해고",
"holding_summary":"3개월시용근로계약+본채용거부합리적이유인정안됨=부당해고",
"retrieval_note":"시용(수습)기간 후 본채용 거부는 합리적 이유가 있어야 함. 이유 불충분=부당해고",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── no_dismissal ──

{"case_id":"id_44189","issue_type_primary":"no_dismissal","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["no_formal_disposition"],
"fact_markers":["권고사직통지","일방적의사표시아님"],
"legal_focus":["권고사직해고여부","해고의사표시"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["권고사직통지=사용자일방적의사표시아님=해고아님"],
"exclude_for_queries":[],
"summary_short":"권고사직 통지=사용자 일방적 의사표시 아님=해고 없음",
"holding_summary":"권고사직통지=사용자일방적의사에따른근로관계종료볼수없음=해고해당않음",
"retrieval_note":"권고사직 통지가 사용자 일방적 의사에 의한 것으로 볼 수 없어 해고 불인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44243","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["사직서미제출","박대표해고의사표시","해고통지서요구","폐업금전보상"],
"legal_focus":["해고의사표시","묵시적해고인정","서면통지위반","금전보상"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["관리위임자해고의사표시=묵시적인정=해고존재","사직서미제출+해고의사표시묵시인정=해고존재+서면통지위반"],
"exclude_for_queries":[],
"summary_short":"사직서 없음+관리위임자 해고 의사표시=해고 존재+서면통지 위반=부당",
"holding_summary":"사직서미제출+위임받은박대표해고발언+해고통지서요구시사용자무반응=묵시적해고인정+서면통지위반=부당+금전보상",
"retrieval_note":"노무관리 위임받은 자의 해고 의사표시+사용자의 묵시적 인정=해고 존재. 서면통지 의무 위반=절차적 부당해고",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44467","issue_type_primary":"no_dismissal","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["권고사직동의증거없음","권고사직처리지시"],
"legal_focus":["권고사직=해고여부","사직동의입증"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["권고사직처리지시+동의증거없음=해고존재"],
"exclude_for_queries":[],
"summary_short":"권고사직 처리 지시+동의 증거 없음=해고 존재",
"holding_summary":"사용자권고사직처리지시+근로자먼저요청또는동의증거없음=해고존재",
"retrieval_note":"권고사직이더라도 근로자의 자발적 동의 증거가 없으면 해고 존재 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44583","issue_type_primary":"no_dismissal","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["면담해고의사표시","문자메시지근로관계종료"],
"legal_focus":["해고의사표시방법","문자메시지해고"],
"industry_context":"service","exclusion_flags":[],
"include_for_queries":["면담+문자메시지근로관계종료=사용자해고의사표시=해고존재"],
"exclude_for_queries":[],
"summary_short":"면담+문자메시지 통한 근로관계 종료=해고 존재",
"holding_summary":"면담및직원문자메시지통한근로관계종료=사용자해고의사표시=해고존재",
"retrieval_note":"면담+문자메시지 방식의 근로관계 종료도 해고 의사표시에 해당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44607","issue_type_primary":"no_dismissal","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["no_formal_disposition"],
"fact_markers":["근로자스스로사직서제출"],
"legal_focus":["자발적사직여부","해고없음"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["근로자스스로사직서제출=자발적사직=해고없음"],
"exclude_for_queries":[],
"summary_short":"근로자 스스로 사직서 제출=자발적 사직=해고 없음",
"holding_summary":"근로자스스로사직서제출=근로관계자발적종료=해고없음",
"retrieval_note":"근로자가 먼저 사직서를 제출한 경우=자발적 사직=해고 부존재",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44881","issue_type_primary":"no_dismissal","issue_type_secondary":["contract_expiry"],
"employment_stage":"fixed_term","disposition_type":["contract_termination"],
"fact_markers":["기간만료통보","전보발령갱신의사표시내포","근로자거부","갱신불성립"],
"legal_focus":["기간만료통보철회여부","갱신의사표시","근로자거부효과"],
"industry_context":"unknown","exclusion_flags":["resignation_dispute"],
"include_for_queries":["전보발령=갱신의사내포이나근로자거부=갱신불성립=기간만료=해고없음"],
"exclude_for_queries":[],
"summary_short":"전보발령에 갱신 의사 내포이나 근로자 거부=갱신 불성립=기간만료=해고 없음",
"holding_summary":"기간만료통보후전보발령=갱신의사표시내포이나근로자출근거부=갱신거부=근로계약기간만료종료=해고없음",
"retrieval_note":"기간만료 통보 후 전보발령이 갱신 의사를 내포하더라도 근로자가 출근을 거부하면 갱신 불성립=기간만료 종료=해고 없음",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── union_activity ──

{"case_id":"id_4433","issue_type_primary":"union_activity","issue_type_secondary":["transfer_validity","procedure"],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["근로시간면제자지정","구제이익없음","근로시간면제한도소진","현업복귀요청","TV정당","부당노동행위불인정"],
"legal_focus":["근로시간면제자구제이익","전임자현업복귀TV업무상필요성","부당노동행위"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["근로시간면제자지정=구제이익없음각하","면제한도소진후노조요청현업복귀=TV업무상필요성인정+부당노동행위불인정"],
"exclude_for_queries":[],
"summary_short":"근로자1=근로시간면제자 지정=구제이익 없음/근로자2=면제한도 소진 후 현업복귀=TV 정당",
"holding_summary":"근로자1근로시간면제자지정=구제이익없음각하/근로자2면제한도소진노조복귀요청=업무상필요성+협의준수=TV정당+부당노동행위불인정",
"retrieval_note":"전임자(근로시간면제자)가 판정 전 면제자로 지정되면 구제이익 소멸. 면제한도 소진 후 노조 요청에 따른 현업복귀 전보=TV 정당",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44449","issue_type_primary":"union_activity","issue_type_secondary":["procedure"],
"employment_stage":"regular","disposition_type":["other"],
"fact_markers":["노조지부장사원서비스센터장직무부여","1회적행위","제척기간도과"],
"legal_focus":["지배개입부당노동행위","1회적행위제척기간","계속행위구별"],
"industry_context":"unknown","exclusion_flags":["procedure_dominant"],
"include_for_queries":["노조지부장직무부여=1회적행위=제척기간도과각하","지배개입부당노동행위1회적행위제척기간"],
"exclude_for_queries":[],
"summary_short":"노조 지부장 사원서비스센터장 직무 부여=1회적 행위=제척기간 도과=각하",
"holding_summary":"지부장선출과동시센터장직무부여=1회적행위=당일완성+이후직무수행임금지급=선행행위의결과=제척기간도과=각하",
"retrieval_note":"지배·개입 부당노동행위의 1회적 행위 여부: 지부장 선출 시 직무 부여=1회 완성. 이후 직무 수행·임금 지급은 부수적 결과=제척기간 기산은 최초 행위일",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_4451","issue_type_primary":"union_activity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["transfer"],
"fact_markers":["소수노조차별","공정대표의무","단체협약15%기준","15%이상조건"],
"legal_focus":["공정대표의무","소수노조차별","단체협약유불리"],
"industry_context":"unknown","exclusion_flags":[],
"include_for_queries":["단협조합원15%이상노조만사전합의=소수노조차별=공정대표의무위반","공정대표의무소수노조차별"],
"exclude_for_queries":[],
"summary_short":"단협 15% 이상 노조만 사전합의=소수노조 차별=공정대표 의무 위반",
"holding_summary":"단협17조3항조합원15%이상노조만사전합의대상=소수노조합리적이유없는차별=공정대표의무위반/단협17조4항3년이상근무우선전보=모든노조공통적용=차별없음=위반않음",
"retrieval_note":"공정대표의무: 조합원 비율에 따른 사전 합의 범위 제한=소수 노조 차별=위반. 반면 모든 노조에 균등 적용 조항=위반 아님",
"confidence":"high","review_status":"approved","tag_version":"v3"},

{"case_id":"id_44585","issue_type_primary":"union_activity","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["no_formal_disposition"],
"fact_markers":["원청사내하청","원청지배결정력","노조법상사용자지위"],
"legal_focus":["원청사용자지위","노조법상사용자","교섭대상"],
"industry_context":"manufacturing","exclusion_flags":[],
"include_for_queries":["원청상당한지배결정력=노조법상사용자지위인정","사내하청근로자교섭요구원청사용자지위"],
"exclude_for_queries":[],
"summary_short":"원청이 사내하청 근로자에 상당한 지배·결정력=노조법상 사용자 지위 인정",
"holding_summary":"원청사용자사내하청근로자작업내용환경상당한지배결정력=노조법상사용자지위인정=교섭의무",
"retrieval_note":"원청이 사내하청 근로자의 작업 내용·환경에 상당한 지배·결정력을 보유=노조법상 사용자 지위 인정",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── redundancy ──

{"case_id":"id_44069","issue_type_primary":"redundancy","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["dismissal"],
"fact_markers":["신규게임흥행실패","매출감소","신규채용공고","대표이사연봉인상","긴박성불충분"],
"legal_focus":["정리해고4요건","긴박한경영상필요성","신규채용공고"],
"industry_context":"it","exclusion_flags":[],
"include_for_queries":["신규채용공고+대표이사연봉인상=긴박한경영상필요성불충분=정리해고부당"],
"exclude_for_queries":[],
"summary_short":"신규채용 공고+대표이사 연봉 인상=긴박한 경영상 필요성 불충분=정리해고 부당",
"holding_summary":"경영악화인정이나신규채용공고+대표이사연봉인상=긴박한경영상필요성불충분=정리해고4요건미충족=부당",
"retrieval_note":"정리해고 시 신규채용 공고와 대표이사 연봉 인상은 긴박한 경영상 필요성을 부정하는 핵심 증거",
"confidence":"high","review_status":"approved","tag_version":"v3"},

# ── discrimination ──

{"case_id":"id_44617","issue_type_primary":"discrimination","issue_type_secondary":[],
"employment_stage":"regular","disposition_type":["no_formal_disposition"],
"fact_markers":["위험근무수당","두리발운전직제외","합리적이유없는차별"],
"legal_focus":["차별적처우금지","위험수당지급기준","합리적이유"],
"industry_context":"transport","exclusion_flags":[],
"include_for_queries":["위험근무수당지급대상제한=상시위험노출두리발운전직제외=차별인정"],
"exclude_for_queries":[],
"summary_short":"위험근무수당 지급대상에서 두리발운전직 제외=합리적 이유 없는 차별 인정",
"holding_summary":"위험근무수당지급대상도로교량관리처한정+상시위험노출두리발운전직제외=합리적이유없는차별=부당",
"retrieval_note":"위험에 상시 노출된 운전직을 위험근무수당 대상에서 합리적 이유 없이 제외=차별적 처우",
"confidence":"high","review_status":"approved","tag_version":"v3"},

]

with open(OUTPUT, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Written {len(records)} records")
