import json, pathlib, sys
sys.stdout.reconfigure(encoding='utf-8')

OUT = pathlib.Path("retagging/output/reviewed/transfer_batch_051_reviewed.jsonl")
OUT.parent.mkdir(parents=True, exist_ok=True)

records = [

{"case_id":"id_409149","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["금전보상신청","진정성없는복직명령","구제이익소멸주장","서면통지결여"],"legal_focus":["진정성없는복직명령=구제이익소멸불인정","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["진정성없는복직명령=구제이익소멸불인정","서면통지결여=부당해고","금전보상신청근로자협의없이일방적복직통보=진정성없음"],"exclude_for_queries":[],"summary_short":"금전보상신청 근로자에게 협의없이 일방적 복직통보+사직서 요구=진정성없음=구제이익소멸불인정+서면통지없음=부당해고","holding_summary":"금전보상신청근로자에게협의없이일방적복직통보+사직서요구연락확인=진정성없는복직명령=구제이익소멸불인정+해고사유시기서면통지없음=부당해고","retrieval_note":"진정성없는복직명령 패턴 + 서면통지결여 복합","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409151","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["서면통지결여","금전보상명령"],"legal_focus":["서면통지결여=부당해고","금전보상명령"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["서면통지결여=부당해고","금전보상명령수용"],"exclude_for_queries":[],"summary_short":"해고사유·시기 서면통지 없음=부당해고+금전보상명령","holding_summary":"해고사유및시기서면통지없음=부당해고+근로자금전보상원함=금전보상명령수용","retrieval_note":"서면통지결여 단순 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409167","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["demotion","transfer"],"fact_markers":["정년앞둔근로자","보직변경","배치전환","임금10-20%삭감","협의미준수"],"legal_focus":["보직변경=TV3요건충족=정당","배치전환=업무상필요성없음+생활상불이익+협의없음=부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["보직변경정당+배치전환부당=부분인용","정년앞둔근로자배치전환=업무상필요성없음"],"exclude_for_queries":[],"summary_short":"보직변경 정당+배치전환 부당(업무상필요성없음+임금10-20%삭감+협의없음)=부분인용","holding_summary":"정년앞둔직원보직해제=업무상필요성인정+보직수당미지급만=생활상불이익작음+면담협의=보직변경정당/교대팀인력충원됨=배치전환업무상필요성없음+임금10-20%삭감+협의없음=배치전환부당=부분인용","retrieval_note":"동일 사안에서 보직변경 정당 + 배치전환 부당 분리 판단","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409179","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["제척기간도과","인사발령2024.5.1.","구제신청2024.8.1."],"legal_focus":["인사발령제척기간3개월도과=각하"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["인사발령제척기간도과=각하"],"exclude_for_queries":[],"summary_short":"인사발령 2024.5.1. 효력 발생=구제신청 2024.8.1.=제척기간 3개월 도과=각하","holding_summary":"인사발령2024.5.1.사내게시판게시효력발생=구제신청2024.8.1.=제척기간3개월도과=각하","retrieval_note":"제척기간 도과 각하 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409181","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["내부감사지적","동일보직장기근무","상호보직변경","노조협의수차례"],"legal_focus":["내부감사지적동일보직장기근무=업무상필요성","상호보직변경임금변동없음=생활상불이익없음","노조수차례협의=협의준수"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["내부감사동일보직장기근무지적=업무상필요성인정=TV정당","TV3요건충족=정당"],"exclude_for_queries":[],"summary_short":"내부감사 동일보직 장기근무 지적+상호보직변경 임금변동없음+노조협의=TV 정당","holding_summary":"내부감사동일보직장기근무2차례지적=업무상필요성충분+상호보직변경임금근무지변동없음=생활상불이익없음+노조및근로자협의수차례=TV정당","retrieval_note":"내부감사 지적 근거 TV 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409221","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"unknown","disposition_type":["no_formal_disposition"],"fact_markers":["일용근로형태","아르바이트직급","작업물량결정","매일계약"],"legal_focus":["일용근로형태=근로관계단위종료=해고없음"],"industry_context":"unknown","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["일용근로형태=매일계약=근로관계종료=해고없음=기각"],"exclude_for_queries":[],"summary_short":"아르바이트직급+작업물량결정 일용근로형태=근로관계단위종료=해고없음=기각","holding_summary":"아르바이트직급+작업물량결정출근방식=현장특수성일용근로형태확인=매일일용근로계약=근로관계단위종료=해고없음=기각","retrieval_note":"일용근로 형태에서 해고 없음 기각 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409225","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["퇴사확인서서명","임금전액수령","강요주장"],"legal_focus":["퇴사확인서서명+당일임금전액수령=진정한사직=해고없음"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["퇴사확인서서명+당일임금전액수령=진정한사직=해고없음"],"exclude_for_queries":[],"summary_short":"퇴사확인서 자필서명+당일임금전액수령=강요입증부족=진정한사직=해고없음=기각","holding_summary":"퇴사일자명시확인서자필서명+당일임금전액수령=강요주장이나정신없는상태입증부족=진정한사직=해고없음=기각","retrieval_note":"퇴사확인서 서명 진정성 판단 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409259","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사문서위조혐의","기존업무수행어려움","총무파트인력충원필요"],"legal_focus":["사문서위조혐의=계약업무수행어려움=업무상필요성","임금근무지변동없음=생활상불이익없음"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사문서위조혐의=기존업무수행어려움=전직업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"사문서위조혐의로 계약업무 수행 어려움+총무파트 인력충원 필요=업무상필요성+임금변동없음=TV 정당","holding_summary":"사문서위조혐의로계약업무유사업무수행어려움+총무파트신규프로젝트인력충원필요=업무상필요성있음+임금근무지변동없음=생활상불이익없음=TV정당","retrieval_note":"비위혐의로 기존업무 수행 어려움 근거 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_40931","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["업무상필요성인정","생활상불이익통상감내가능","협의절차없어도당연무효아님"],"legal_focus":["TV3요건충족=정당인사명령","협의없어도당연무효사유아님"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["협의없어도당연무효아님=TV정당","TV3요건충족=정당"],"exclude_for_queries":[],"summary_short":"업무상필요성 인정+생활상불이익 통상감내가능+협의없어도 당연무효아님=TV 정당","holding_summary":"2019.8.1.인사발령=업무상필요성인정+생활상불이익통상감수가능+협의절차없어도당연무효사유아님=인사권범위정당인사명령","retrieval_note":"협의 없어도 당연 무효 아님 법리 확인","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409317","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["pay_cut","transfer"],"fact_markers":["직장내성희롱","공공기관","감봉1월","전직"],"legal_focus":["직장내성희롱=징계사유인정","공공기관높은도덕성=양정적정","전직정당"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["직장내성희롱=감봉1월정당","공공기관성희롱징계양정적정=TV정당"],"exclude_for_queries":[],"summary_short":"직장내 성희롱=징계사유 인정+공공기관 높은 도덕성 요구=감봉1월 양정 적정+전직 정당","holding_summary":"직장내성희롱인정=징계사유있음+공공기관소속높은도덕성요구+가장경미한징계=유사사례양정비교적정=감봉1월정당+전직정당","retrieval_note":"공공기관 직장내 성희롱 감봉 양정 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409327","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["산재상병근로자","수송기사","장거리운행","교통사고위험주장","객관적근거부족"],"legal_focus":["상병근로자전보=업무상필요성객관적근거부족=TV부당"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["산재상병근로자전보=업무상필요성객관적근거부족=TV부당"],"exclude_for_queries":[],"summary_short":"산재 상병 수송기사 전보=교통사고위험 주장이나 객관적 근거 부족=TV 부당","holding_summary":"상병상태수송기사장거리운행계속시대형교통사고위험주장이나객관적뒷받침근거부족=업무상필요성없음=TV부당","retrieval_note":"산재 상병 근로자 전보 업무상 필요성 객관적 근거 요구","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409331","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["사내강사제도운영안","취업규칙아님","교육수요감소","강사수당감소"],"legal_focus":["사내강사제도운영안=취업규칙아님","교육수요감소=업무상필요성","강사수당감소<업무상필요성=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["사내강사제도운영안취업규칙아님","교육수요감소업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"사내강사제도운영안=취업규칙 아님+교육수요 감소=업무상필요성 인정+강사수당 감소<업무상필요성=TV 정당","holding_summary":"사내강사제도운영안취업규칙으로볼수없음+교육수요감소업무상필요성인정+강사수당감소생활상불이익<업무상필요성=TV정당","retrieval_note":"사내규정의 취업규칙 해당 여부 + TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409349","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로자귀책동료불화","분리조치","희망근무지사전안내"],"legal_focus":["근로자귀책동료불화분리조치=업무상필요성","생활상불이익통상감수범위","희망근무지사전안내=협의준수"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로자귀책동료불화분리조치=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"근로자 귀책 동료불화 분리조치=업무상필요성 인정+생활상불이익 통상감수범위+희망근무지 사전안내=협의준수=TV 정당","holding_summary":"근로자귀책동료불화갈등방지분리조치=업무상필요성인정+생활상불이익통상감수범위+희망근무지전보가능성사전안내=협의준수=TV정당","retrieval_note":"근로자 귀책 동료불화 분리조치 TV 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409357","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["고보피보험자격상실신고","사전신규근로자채용","진정성없는복직명령"],"legal_focus":["면담후이틀고보상실신고=해고존재","진정성없는복직명령=구제이익소멸불인정","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["면담후이틀고보피보험자격상실신고=해고존재","진정성없는복직명령=구제이익소멸불인정","서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"면담 후 이틀만 고보 피보험자격 상실신고+사전 신규근로자 채용=해고 존재+진정성없는복직명령+서면통지없음=부당해고","holding_summary":"면담후이틀만고보피보험자격상실신고+신규근로자사전채용=해고존재+복직명령진정성없음=구제이익소멸불인정+서면통지없음=부당해고","retrieval_note":"고보 상실신고를 해고 존재의 간접증거로 활용","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409363","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["카카오톡해고메시지","남자답게정리발언","해고규정처리발언","서면통지결여"],"legal_focus":["카카오톡메시지=해고의사표시명확=해고존재","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["카카오톡메시지=해고존재","서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"카카오톡 '남자답게 정리+해고규정처리' 메시지=해고 존재+서면통지없음=부당해고","holding_summary":"카카오톡남자답게정리하자+근로계약제7조해고규정에따라처리했음메시지=해고의사표시명확=해고존재+서면통지없음=부당해고","retrieval_note":"카카오톡 메시지 해고 의사표시 인정 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409373","issue_type_primary":"redundancy","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["원아수급감","폐원결정","해고회피노력없음"],"legal_focus":["원아수감급적자=긴박한경영상필요성인정","해고회피노력없음=경영상해고부당"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["폐원=긴박한경영상필요성인정이나해고회피노력없음=경영상해고부당"],"exclude_for_queries":[],"summary_short":"원아수 급감 적자 폐원=긴박한경영상필요성 인정이나 해고회피노력없음=경영상해고 부당","holding_summary":"원아수급감으로적자폐원결정=긴박한경영상필요성인정+근무시간변경급여조정배치전환등해고회피노력없음=경영상해고부당","retrieval_note":"어린이집 폐원 경영상 해고 - 해고회피노력 부재로 부당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409379","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["demotion","transfer"],"fact_markers":["고용노동부진정서","정당한긴급안건","강등징계","전보"],"legal_focus":["고용노동부진정서=정당한권리행사=징계사유불인정","강등부당=원인전보도부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["고용노동부진정서=정당한권리행사=징계사유불인정=강등부당","강등원인전보=강등부당따라전보도부당"],"exclude_for_queries":[],"summary_short":"사용자 부당거부에 따른 고용노동부 진정서=정당한 권리행사=강등 징계사유 불인정=강등부당+원인전보도 부당","holding_summary":"사용자부당거부에따른고용노동부진정서제출=정당한긴급안건권리행사=징계사유불인정=강등부당+강등이주된원인인전보도부당","retrieval_note":"고용노동부 진정서 행사 = 정당한 권리행사 = 징계사유 불인정","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409381","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["서면통지결여","금전보상명령","금전보상액17129070원"],"legal_focus":["서면통지결여=부당해고","금전보상명령"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["서면통지결여=부당해고","금전보상명령수용"],"exclude_for_queries":[],"summary_short":"해고사유·시기 서면통지없음=부당해고+금전보상명령 17,129,070원","holding_summary":"해고사유및시기서면통지없음=부당해고+근로자금전보상원함+신뢰관계회복어려움=금전보상명령17,129,070원","retrieval_note":"서면통지결여 + 금전보상액 구체 산정 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409407","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],"fact_markers":["시용근로자","수습기간","본채용거부","팀원갈등","무례독단행동"],"legal_focus":["시용근로자본채용거부=팀갈등유발입증=정당"],"industry_context":"service","exclusion_flags":["unrelated_to_dismissal"],"include_for_queries":["시용근로자본채용거부=팀원전원무례독단진술=정당=기각"],"exclude_for_queries":[],"summary_short":"시용근로자 본채용거부=팀원 전원 무례·독단 갈등유발 진술+절차 적법=정당=기각","holding_summary":"근로계약서인사규정수습기간및직권면직규정=시용근로자인정+미화팀원전원무례독단행동팀갈등유발진술=본채용거부정당=기각","retrieval_note":"시용근로자 본채용 거부 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409423","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["진정성없는복직명령","손해배상소송","무보험탁송거부","안전권"],"legal_focus":["진정성없는복직명령=구제이익소멸불인정","무보험탁송거부=안전권=해고부당"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["진정성없는복직명령=구제이익소멸불인정","무보험탁송업무거부안전권=해고부당"],"exclude_for_queries":[],"summary_short":"금전보상신청 당일 복직명령+손해배상소송 제기=진정성없음+무보험탁송거부 안전권=해고 부당","holding_summary":"금전보상신청근로자에게당일복직명령+손해배상소송제기=진정성없는복직명령=구제이익소멸불인정+무보험탁송업무거부=안전권행사=해고부당","retrieval_note":"진정성없는 복직명령 + 안전권 거부 해고 복합 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409431","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["종전근무지추가인력불필요주장입증자료없음","생활상불이익있음"],"legal_focus":["업무상필요성입증자료없음=TV부당","생활상불이익있음=TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["종전근무지추가인력불필요주장입증자료없음=업무상필요성없음=TV부당"],"exclude_for_queries":[],"summary_short":"종전근무지 추가인력 불필요 주장 입증자료 없음+생활상불이익=TV 부당","holding_summary":"종전근무지추가인력불필요+근무태도문제있다는사용자주장입증자료없음=업무상필요성없음+전보생활상불이익있음=TV부당","retrieval_note":"사용자 업무상 필요성 주장 입증 실패로 TV 부당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_40945","issue_type_primary":"transfer_validity","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["영업사원징계사유인정","일본팀업무미숙","전직부당"],"legal_focus":["징계사유인정+절차적법","일본팀업무미숙=TV업무상필요성없음=부당"],"industry_context":"manufacturing","exclusion_flags":[],"include_for_queries":["징계사유인정이나담당직무미숙=TV업무상필요성없음=TV부당"],"exclude_for_queries":[],"summary_short":"영업업무 미대응·오제작=징계사유 인정+절차 적법이나 일본팀 업무 미숙=TV 부당","holding_summary":"영업업무미대응지연대응+자재코드오입력오제작=징계사유인정+절차하자없음이나인사발령된일본팀업무익숙하지않음=TV업무상필요성없음=TV부당","retrieval_note":"징계사유 인정 + 전직은 업무 미숙으로 TV 부당 분리 판단","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409461","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["no_formal_disposition"],"fact_markers":["인사평가결과전보통보","전보수용불가표명","자필사직서","퇴직서약서"],"legal_focus":["자필사직서+퇴직서약서=진정한사직=해고없음"],"industry_context":"unknown","exclusion_flags":["resignation_dispute"],"include_for_queries":["면담후자필사직서+퇴직서약서=진정한사직=해고없음=기각"],"exclude_for_queries":[],"summary_short":"인사평가+전보 수용불가 표명 후 자필사직서+퇴직서약서=진정한 사직=해고없음=기각","holding_summary":"인사평가및전보면담후전보수용불가표명+자필사직서+퇴직서약서제출=강요입증없음=진정한사직=해고없음=기각","retrieval_note":"전보 관련 면담 후 자필 사직서 = 진정한 사직 기각 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409471","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["pay_cut","demotion"],"fact_markers":["직무유기태업","인사권행사부분징계사유불인정","감봉3월양정과중","직책해제정당"],"legal_focus":["징계사유일부불인정","감봉3월=양정과중=부당","직책해제정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계사유일부불인정+감봉3월양정과중=부당","직책해제정당+감봉부당=부분인용"],"exclude_for_queries":[],"summary_short":"직무유기태업=징계사유 인정이나 인사권행사부분=불인정+감봉3월 양정과중=부당+직책해제 정당=부분인용","holding_summary":"직무유기태업=징계사유인정이나인사권행사조직질서문란부분=징계사유불인정+감봉3월징계재량범위초과=양정과중=부당+직책해제정당=부분인용","retrieval_note":"징계사유 일부 불인정 + 양정 과중 복합 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409479","issue_type_primary":"disciplinary_severity","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["pay_cut","transfer"],"fact_markers":["감봉정당","부서변경정당","징계사유=업무상필요성"],"legal_focus":["징계사유인정양정절차적법=감봉정당","징계사유비추어부서변경=업무상필요성+생활상불이익없음=전직정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["징계사유비추어부서변경업무상필요성인정=TV정당","감봉정당+전직정당"],"exclude_for_queries":[],"summary_short":"징계사유 인정·양정·절차 적법=감봉 정당+징계사유 비추어 부서변경 업무상필요성+생활상불이익없음=전직 정당","holding_summary":"징계사유인정양정절차적법=감봉정당+징계사유비추어부서변경업무상필요성인정+생활상불이익없음=전직정당","retrieval_note":"징계사유가 TV 업무상 필요성 근거가 되는 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409489","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["단체협약협의조항","협의조항이행여부","정상적경영권인사조치"],"legal_focus":["단체협약협의조항이행여부=인사권행사영향미칠정도아님=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["단체협약협의조항이행여부=인사권행사영향미칠정도아님=TV정당"],"exclude_for_queries":[],"summary_short":"단체협약 협의조항 이행여부=인사권 행사에 영향 미칠 정도 아님=정상적 경영권 인사조치=TV 정당","holding_summary":"단체협약협의조항이행여부가사용자인사권행사에영향미칠정도아님+사용자정상적경영권인사조치=TV정당","retrieval_note":"단협 협의조항이 인사권 제한 요건이 아님 법리 확인","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409557","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["육아휴직복귀","동일업무동일임금직무미배치","남녀고용평등법위반","임금삭감"],"legal_focus":["육아휴직복귀후동일업무또는동일임금직무배치의무","남녀고용평등법제19조제4항위반=TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["육아휴직복귀후동일업무미배치=남녀고용평등법위반=TV부당","순환근무업무상필요성없음=TV부당"],"exclude_for_queries":[],"summary_short":"육아휴직 복귀 후 동일업무·동일임금 직무 미배치=남녀고용평등법 제19조4항 위반+순환근무 업무상필요성없음=TV 부당","holding_summary":"육아휴직복귀후동일업무또는동일수준임금직무미배치=남녀고용평등법제19조제4항위반+순환근무업무상필요성인정어렵고임금삭감생활상불이익=TV부당","retrieval_note":"육아휴직 복귀 후 TV = 남녀고용평등법 위반 법리 적용","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409567","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["other"],"fact_markers":["역량개선기간연장","교육명령","구제신청대상여부","근기법제23조제1항"],"legal_focus":["역량개선기간연장교육명령=근기법제23조제1항해당아님=구제신청대상아님","TV정당"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["역량개선기간연장교육명령=구제신청대상아님=기각"],"exclude_for_queries":[],"summary_short":"역량개선기간 연장·교육명령=근기법 제23조제1항 해당 아님=구제신청 대상 아님+TV 정당=기각","holding_summary":"역량개선기간연장교육명령=근기법제23조제1항해고정직전직감봉그밖의징벌해당아님=구제신청대상아님+TV업무상필요성인정생활상불이익현저초과아님=TV정당=기각","retrieval_note":"인사조치의 구제신청 대상 해당 여부 판단 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409589","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["희망퇴직","도급계약축소폐지","조직개편","임금근무장소변동없음"],"legal_focus":["희망퇴직+도급계약축소폐지조직개편=업무상필요성","임금근무장소변동없음=생활상불이익없음=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["희망퇴직+도급계약축소폐지조직개편=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"희망퇴직 시행+도급계약 축소·폐지로 조직개편=업무상필요성+임금·장소 변동없음=TV 정당","holding_summary":"희망퇴직시행+도급계약축소폐지로조직개편필요=업무상필요성인정+임금근무장소근무시간변동없음=생활상불이익없음=TV정당","retrieval_note":"도급계약 축소·폐지 조직개편 근거 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409607","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["신입이업무분담","객관적평가아님","임금삭감많음","근로계약근로내용한정"],"legal_focus":["업무상필요성없음(신입이업무분담+객관적평가부족)","임금삭감생활상불이익큼","근로계약근로내용한정=TV부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약근로내용한정=다른업무배치전환TV부당","업무상필요성객관적평가부족=TV부당","임금삭감큼=생활상불이익=TV부당"],"exclude_for_queries":[],"summary_short":"신입이업무분담+객관적평가아님=업무상필요성없음+임금삭감많음+근로계약 근로내용한정=TV 부당","holding_summary":"신입이업무분담수행+코스관리팀부적합평가객관적이지않음=업무상필요성없음+임금삭감생활상불이익큼+근로계약근로내용한정=TV부당","retrieval_note":"근로계약 근로내용 한정 + 업무상 필요성 없음 복합 TV 부당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409621","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["6건민원","근로자이동요청","주간근무희망","근로계약서명시","임금삭감없음"],"legal_focus":["민원발생+근로자이동요청+근로계약서명시=업무상필요성","임금삭감없음근무환경개선=생활상불이익없음=TV정당"],"industry_context":"service","exclusion_flags":[],"include_for_queries":["근무태만민원+근로자이동요청+근로계약서명시=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"6건 민원+근로자 스스로 이동요청+근로계약서 명시=업무상필요성+임금삭감없음=TV 정당","holding_summary":"근무태만용모복장불량6건민원+근로자이동요청+주간근무희망+근로계약서업무장소직종변경명시=업무상필요성있음+임금삭감없음=생활상불이익없음=TV정당","retrieval_note":"근로자 스스로 이동 요청한 경우 TV 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409661","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer","demotion"],"fact_markers":["전직부당","보직해임","정직3월수반인사조치","정직취소따라보직해임취소"],"legal_focus":["전직=업무상필요성없음+생활상불이익+협의없음=부당","보직해임=정직3월수반=정직취소→보직해임취소"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["전직부당=업무상필요성없음+생활상불이익+협의없음","보직해임=정직수반=정직취소따라보직해임도취소"],"exclude_for_queries":[],"summary_short":"전직=업무상필요성없음+생활상불이익+협의없음=부당+보직해임=정직3월수반=정직취소따라보직해임도취소=부분인용","holding_summary":"전직=업무상필요성없음+생활상불이익있음+협의없음=TV부당+보직해임=정직3월당연수반인사조치=정직처분취소에따라보직해임도취소=부분인용","retrieval_note":"정직 수반 보직해임 = 정직 취소 시 보직해임도 취소 법리","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409671","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["도급계약주장","근로계약서존재","작업일보","5인이상","서면통지결여"],"legal_focus":["도급계약주장이나근로계약서+임금지급=근로자인정","5인이상근로기준법적용","서면통지결여=부당해고"],"industry_context":"construction","exclusion_flags":[],"include_for_queries":["도급계약주장이나근로계약서+임금지급=근로자인정","5인이상=근로기준법적용+서면통지결여=부당해고"],"exclude_for_queries":[],"summary_short":"도급계약 주장이나 근로계약서+임금지급=근로자 인정+5인이상=근기법적용+서면통지없음=부당해고","holding_summary":"도급계약주장이나근로계약서및작업일보존재+임금지급=근로기준법상근로자인정+상시5인이상=서면통지없음=부당해고","retrieval_note":"도급계약 주장 깨고 근로자성 인정 + 5인이상 적용 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409699","issue_type_primary":"procedure","issue_type_secondary":["transfer_validity"],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["원직노선폐업","원직복직객관적불가","구제이익없음"],"legal_focus":["원직노선폐업=원직복직객관적불가=구제이익없음=기각","설령있더라도TV정당"],"industry_context":"transport","exclusion_flags":["procedure_dominant"],"include_for_queries":["원직노선폐업=원직복직객관적불가=구제이익없음=기각"],"exclude_for_queries":[],"summary_short":"원직 노선 폐업=원직복직 객관적 불가=구제이익 없음=기각(설령있더라도 준공영제 환직거부 배치전환=TV 정당)","holding_summary":"원직노선폐업으로원직복직객관적불가=구제이익없음=기각+설령구제이익있더라도준공영제환직거부배치전환=TV정당","retrieval_note":"원직 폐업으로 구제이익 소멸 기각 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409701","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["스토킹예방지침","피해자보호조치","출퇴근시간증가미확인","임금감소없음"],"legal_focus":["스토킹피해자보호조치=업무상필요성인정","출퇴근시간증가미확인+임금감소없음=생활상불이익없음=TV정당"],"industry_context":"public","exclusion_flags":[],"include_for_queries":["스토킹피해자보호조치=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"스토킹 예방지침 피해자 보호조치=업무상필요성 인정+출퇴근시간증가 미확인·임금감소없음=TV 정당","holding_summary":"사내스토킹예방지침제8조피해자보호조치=TV업무상필요성인정+출퇴근시간증가미확인+임금감소없음=생활상불이익없음=TV정당","retrieval_note":"스토킹 피해자 보호조치 목적의 TV 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409743","issue_type_primary":"procedure","issue_type_secondary":["disciplinary_severity"],"employment_stage":"regular","disposition_type":["transfer","reprimand"],"fact_markers":["인사발령제척기간도과","연차신청반려","파견근무개시일무단결근","연락불응"],"legal_focus":["인사발령2024.2.28.=제척기간도과=각하","연차신청반려후무단결근=징계사유정당"],"industry_context":"unknown","exclusion_flags":["procedure_dominant"],"include_for_queries":["인사발령제척기간도과=각하","연차신청반려후무단출근거부=징계사유정당"],"exclude_for_queries":[],"summary_short":"인사발령 2024.2.28.=제척기간 도과=각하+연차반려 후 무단결근=징계사유 정당=기각","holding_summary":"인사발령2024.2.28.=제척기간도과=각하+연차신청반려후파견근무개시일무단결근이틀연락불응=징계사유인정=기각","retrieval_note":"제척기간 도과 각하 + 무단결근 징계 정당 복합","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409761","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["기간명시진단서미제출","장기업무미수행","새프로젝트인력필요","임금근무지변동없음"],"legal_focus":["진단서미제출+장기업무미수행+새프로젝트인력필요=업무상필요성","임금근무지변동없음=생활상불이익없음=TV정당"],"industry_context":"it","exclusion_flags":[],"include_for_queries":["장기병가진단서미제출+새프로젝트인력필요=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"기간명시 진단서 미제출+장기 업무미수행+새 프로젝트 인력 필요=업무상필요성+임금·근무지 변동없음=TV 정당","holding_summary":"기간명시진단서미제출+상당기간업무미수행+새프로젝트인력필요=업무상필요성인정+임금근무지변동없음=생활상불이익없음=TV정당","retrieval_note":"장기 병가 진단서 미제출 + 신규 프로젝트 투입 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409765","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["시회임원갈등","대기발령3개월이상해임위험","인근시회전보","통근시간차이작음","임금차액보전"],"legal_focus":["임원갈등+대기발령장기화시해임위험=인근시회전보업무상필요성인정","통근시간차이작음+임금차액보전=생활상불이익없음=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["임원갈등+대기발령장기화해임위험=인근시회전보업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"안양시회 임원갈등+대기발령 장기화 시 해임위험=인근시회 전보 업무상필요성+통근차이작음·임금보전=TV 정당","holding_summary":"안양시회임원갈등+대기발령3개월이상경과시해임위험=인근시회전보업무상필요성인정+통근시간차이작음+임금차액보전대책=생활상불이익없음=TV정당","retrieval_note":"임원갈등 회피 + 해임 위험 방지 목적 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409799","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["3년간경영난","채권은행기업구조조정협약","브랜드마케팅팀폐지","마케팅외주화"],"legal_focus":["3년경영난+채권은행협약+팀폐지외주화=업무상필요성인정","임금근무조건변동없음=생활상불이익없음=TV정당"],"industry_context":"retail","exclusion_flags":[],"include_for_queries":["경영난+팀폐지외주화=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"3년 경영난+채권은행 구조조정협약+브랜드마케팅팀 폐지 외주화=업무상필요성+임금·근무조건 변동없음=TV 정당","holding_summary":"3년간경영난영업손실+채권은행기업구조조정협약이자감면+브랜드마케팅팀폐지마케팅외주화=업무상필요성인정+임금근무조건변동없음=생활상불이익없음=TV정당","retrieval_note":"경영난 + 팀 폐지 외주화 근거 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409827","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["소속팀폐지","영업경험반영전보","기존인사전례비추이례적아님"],"legal_focus":["소속팀폐지+영업경험반영+이례적아님=업무상필요성인정=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["소속팀폐지+영업경험반영+인사전례비추=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"소속팀 폐지+영업경험 반영 전보+기존인사 전례 비추 이례적 아님=업무상필요성=TV 정당","holding_summary":"소속팀폐지+근로자영업경험반영전보+기존인사발령전례비추이례적아님=업무상필요성인정=TV정당","retrieval_note":"팀 폐지 + 경험 반영 전보 TV 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409829","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약근무지변경가능명시","조직개편총무부서폐지","복직시교과관총무공석"],"legal_focus":["근로계약근무지변경가능명시+총무부서폐지+복직시공석=업무상필요성인정=TV정당"],"industry_context":"education","exclusion_flags":[],"include_for_queries":["근로계약근무지변경가능명시+조직개편부서폐지+복직시공석=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"근로계약 근무지변경 가능 명시+조직개편 총무부서 폐지+복직시 교과관 총무 공석=업무상필요성=TV 정당","holding_summary":"근로계약서근무지변경가능명시+조직개편총무부서폐지+복직시교과관총무공석=업무상필요성인정=TV정당","retrieval_note":"근로계약 명시 + 조직개편 + 공석 결합 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409845","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"probation","disposition_type":["rejection_of_regular_employment"],"fact_markers":["시용근로자","본채용거부","주관적판단","객관적근거없음","해고통지서이유불충분"],"legal_focus":["시용근로자본채용거부=주관적판단+객관적근거없음=부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["시용근로자본채용거부=주관적판단객관적근거없음=부당해고"],"exclude_for_queries":[],"summary_short":"시용근로자 본채용거부=사용자 주관적 판단+객관적 근거자료 없음+해고통지서 구체적 이유 없음=부당","holding_summary":"시용근로관계인정+사용자해고사유주관적판단+객관적근거자료미제시+해고통지서구체실질이유없음=본채용거부부당","retrieval_note":"시용 본채용 거부 주관적 판단 = 부당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409861","issue_type_primary":"transfer_validity","issue_type_secondary":["no_dismissal"],"employment_stage":"regular","disposition_type":["transfer","disciplinary_dismissal"],"fact_markers":["서울본사강릉연구소전보","업무상필요성없음","생활상불이익현저","협의없음","무효전보명령거부=근무지이탈","해고사유불인정"],"legal_focus":["서울→강릉전보=TV3요건전부불충족=TV부당","무효전보명령거부=해고사유불인정=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["TV무효→근무지이탈해고=해고사유불인정=부당해고","서울→강릉전보=TV3요건전부불충족=TV부당"],"exclude_for_queries":[],"summary_short":"서울→강릉 전보=TV3요건 전부 불충족=TV 부당+무효전보 거부=근무지 이탈=해고사유 불인정=부당해고","holding_summary":"서울본사→강릉연구소전보=업무상필요성없음+생활상불이익현저+협의없음=TV부당+무효전보명령거부=근무지이탈=해고사유불인정=부당해고","retrieval_note":"TV 무효 → 명령 거부 해고 = 해고 사유 불인정 법리 중요","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409893","issue_type_primary":"disciplinary_severity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["suspension"],"fact_markers":["버스기사","신호위반","취업규칙위반","정직3일"],"legal_focus":["버스기사신호위반=취업규칙위반=징계사유","대형교통사고위험=엄격처리필요=정직3일양정적정"],"industry_context":"transport","exclusion_flags":[],"include_for_queries":["버스기사신호위반=대형교통사고위험=정직3일징계정당"],"exclude_for_queries":[],"summary_short":"버스기사 신호위반=취업규칙 위반·업무귀책+대형교통사고 위험=정직3일 양정 적정=징계 정당","holding_summary":"버스기사신호위반=취업규칙위반+업무귀책+대형교통사고위험성엄격처리필요=정직3일징계정당","retrieval_note":"운수업 신호위반 정직 양정 정당 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409897","issue_type_primary":"no_dismissal","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["근로관계파탄","경찰출동","진정성없는복직명령","대체근로자채용","구제이익소멸주장"],"legal_focus":["경찰출동근로관계파탄+대체근로자채용=진정성없는복직명령=구제이익소멸불인정","해고존재=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["경찰출동근로관계파탄+대체근로자채용=진정성없는복직명령=구제이익소멸불인정"],"exclude_for_queries":[],"summary_short":"경찰출동 근로관계 파탄+대체근로자 채용=진정성없는 복직명령=구제이익소멸 불인정+해고 존재=부당해고","holding_summary":"원장실고성욕설경찰출동근로관계파탄+복직명령후순차대체근로자채용=진정성없는복직명령=구제이익소멸불인정+해고존재=부당해고","retrieval_note":"근로관계 파탄 + 대체채용 = 진정성없는 복직명령 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409927","issue_type_primary":"contract_expiry","issue_type_secondary":[],"employment_stage":"renewal_stage","disposition_type":["nonrenewal"],"fact_markers":["기간제7회반복","위수탁계약기간따라체결","정년후재고용","별도평가없음"],"legal_focus":["기간제7회반복+정년후재고용=갱신기대권인정","합리적이유없는갱신거절=부당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["기간제7회반복+정년후재고용=갱신기대권인정","합리적이유없는갱신거절=부당"],"exclude_for_queries":[],"summary_short":"기간제 7회 반복+정년후 재고용=갱신기대권 인정+합리적 이유없는 갱신거절=부당","holding_summary":"기간제근로계약7회반복+별도평가없이위수탁계약기간따라체결+정년후재고용=갱신기대권인정+합리적이유없는갱신거절=부당","retrieval_note":"정년 후 재고용 기간제 갱신기대권 인정 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409937","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["임금피크제적용근로자","특정부서일률배치","연고지미반영","형평성위배"],"legal_focus":["임금피크제적용근로자만특정부서배치=형평성위배=업무상필요성없음=TV부당"],"industry_context":"finance","exclusion_flags":[],"include_for_queries":["임금피크제적용근로자만특정부서일률배치=형평성위배=TV부당"],"exclude_for_queries":[],"summary_short":"임금피크제 적용근로자만 대물보상센터 일률 배치+연고지 미반영=형평성 위배=업무상필요성 없음=TV 부당","holding_summary":"조직개편필요성있으나임금피크제적용근로자만대물보상센터각1명일률배치+인력규모업무량무관+연고지미반영=형평성위배업무상필요성없음=TV부당","retrieval_note":"임금피크제 적용 대상자만 특정 부서 배치 차별적 TV 부당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409955","issue_type_primary":"no_dismissal","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["dismissal"],"fact_markers":["권고사직합의사용자주장미확인","일방적근로관계종료","해고존재"],"legal_focus":["권고사직합의미확인=일방적근로관계종료=해고존재","서면통지결여=부당해고"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["권고사직합의사용자주장미확인=일방적근로관계종료=해고존재=부당해고"],"exclude_for_queries":[],"summary_short":"권고사직 합의 사용자 주장 미확인=일방적 근로관계 종료=해고 존재+서면통지없음=부당해고","holding_summary":"2024.12.말까지근로의사확인이나권고사직합의주장미확인+일방적근로관계종료=해고존재+서면통지없음=부당해고","retrieval_note":"권고사직 합의 미확인 = 해고 존재 인정 유형","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409963","issue_type_primary":"transfer_validity","issue_type_secondary":[],"employment_stage":"regular","disposition_type":["transfer"],"fact_markers":["근로계약서경영상필요시변경가능명시","조직개편","근무부서폐지","임금근무조건변동없음"],"legal_focus":["근로계약명시+조직개편근무부서폐지=업무상필요성인정","임금근무조건변동없음=생활상불이익없음=TV정당"],"industry_context":"unknown","exclusion_flags":[],"include_for_queries":["근로계약경영상필요시변경가능명시+조직개편부서폐지=업무상필요성인정=TV정당"],"exclude_for_queries":[],"summary_short":"근로계약 경영상 필요시 변경 가능 명시+조직개편 근무부서 폐지=업무상필요성+임금·근무조건 변동없음=TV 정당","holding_summary":"근로계약서경영상필요시업무내용근무장소변경가능명시+2024.8.1.조직개편근무부서폐지=업무상필요성인정+임금근무조건변동없음=생활상불이익없음=TV정당","retrieval_note":"근로계약 명시 + 조직개편 부서 폐지 TV 정당","confidence":"high","review_status":"done","tag_version":"v3"},

{"case_id":"id_409967","issue_type_primary":"transfer_validity","issue_type_secondary":["procedure"],"employment_stage":"regular","disposition_type":["transfer","demotion"],"fact_markers":["상담팀장해제","간호팀배치","인사발령징계해당여부","구제신청이익존재"],"legal_focus":["구제신청이익존재","인사발령이징계에해당하는지여부판단","TV정당성판단"],"industry_context":"healthcare","exclusion_flags":[],"include_for_queries":["인사발령이징계해당여부=구제신청이익판단"],"exclude_for_queries":[],"summary_short":"상담팀장 해제→간호팀 인사발령이 징계에 해당하는지 여부+구제신청 이익 존재=TV 정당성 판단=기각","holding_summary":"구제신청이익존재인정+상담팀장해제간호팀배치인사발령이징계에해당하는지여부판단=TV정당=기각","retrieval_note":"인사발령의 징계 해당 여부 + TV 정당 복합 판단 유형","confidence":"high","review_status":"done","tag_version":"v3"},

]

with open(OUT, 'w', encoding='utf-8') as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + '\n')

print(f"Written {len(records)} records")
